import { escapePowerShellString } from './powershell-utils';

export interface AzureResourceParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface AzureResourceTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: AzureResourceParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const azureResourceTasks: AzureResourceTask[] = [
  // ==================== Resource Management ====================
  {
    id: 'azure-create-resource-group',
    title: 'Create Resource Group',
    description: 'Create a new Azure Resource Group with optional tags and lock',
    category: 'Resource Management',
    parameters: [
      {
        name: 'resourceGroupName',
        label: 'Resource Group Name',
        type: 'text',
        required: true,
        placeholder: 'rg-production-eastus',
        helpText: 'Name for the new resource group'
      },
      {
        name: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        options: [
          { value: 'eastus', label: 'East US' },
          { value: 'westus', label: 'West US' },
          { value: 'centralus', label: 'Central US' },
          { value: 'northeurope', label: 'North Europe' },
          { value: 'westeurope', label: 'West Europe' }
        ],
        helpText: 'Azure region for the resource group'
      },
      {
        name: 'tags',
        label: 'Tags (Key=Value, one per line)',
        type: 'textarea',
        required: false,
        placeholder: 'Environment=Production\nCostCenter=IT',
        helpText: 'Optional tags in Key=Value format'
      }
    ],
    scriptTemplate: (params) => {
      const rgName = escapePowerShellString(params.resourceGroupName);
      const location = escapePowerShellString(params.location);
      
      let tagsBlock = '';
      if (params.tags) {
        const tagLines = params.tags.split('\n').filter((line: string) => line.trim());
        if (tagLines.length > 0) {
          const tagPairs = tagLines.map((line: string) => {
            const [key, value] = line.split('=').map(s => s.trim());
            return `    "${escapePowerShellString(key)}" = "${escapePowerShellString(value)}"`;
          }).join('\n');
          tagsBlock = `\n$Tags = @{\n${tagPairs}\n}`;
        }
      }

      return `# Create Azure Resource Group
# Generated by PSForge

Connect-AzAccount
${tagsBlock}

try {
    Write-Host "Creating Resource Group: ${rgName}" -ForegroundColor Cyan
    
    $RgParams = @{
        Name     = "${rgName}"
        Location = "${location}"
    }
    
    ${tagsBlock ? '$RgParams.Tag = $Tags' : ''}
    
    $ResourceGroup = New-AzResourceGroup @RgParams
    Write-Host "✓ Resource Group created successfully" -ForegroundColor Green
    
    $ResourceGroup | Select-Object ResourceGroupName, Location, ProvisioningState
    
} catch {
    Write-Error "Failed to create resource group: $_"
}`;
    }
  },

  {
    id: 'azure-tag-resources',
    title: 'Tag Resources at Scale',
    description: 'Add or update tags across resources in a Resource Group',
    category: 'Resource Management',
    parameters: [
      {
        name: 'resourceGroupName',
        label: 'Resource Group Name',
        type: 'text',
        required: true,
        placeholder: 'rg-production',
        helpText: 'Target resource group'
      },
      {
        name: 'tags',
        label: 'Tags to Apply (Key=Value, one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'Environment=Production\nManagedBy=PSForge',
        helpText: 'Tags to add/update on resources'
      }
    ],
    scriptTemplate: (params) => {
      const rgName = escapePowerShellString(params.resourceGroupName);
      
      const tagLines = params.tags.split('\n').filter((line: string) => line.trim());
      const tagPairs = tagLines.map((line: string) => {
        const [key, value] = line.split('=').map(s => s.trim());
        return `    "${escapePowerShellString(key)}" = "${escapePowerShellString(value)}"`;
      }).join('\n');

      return `# Tag Azure Resources at Scale
# Generated by PSForge

Connect-AzAccount

$NewTags = @{
${tagPairs}
}

try {
    Write-Host "Getting resources in Resource Group: ${rgName}" -ForegroundColor Cyan
    $Resources = Get-AzResource -ResourceGroupName "${rgName}"
    
    Write-Host "Found $($Resources.Count) resources to tag" -ForegroundColor Yellow
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($Resource in $Resources) {
        try {
            $CurrentTags = $Resource.Tags
            if ($null -eq $CurrentTags) { $CurrentTags = @{} }
            
            foreach ($Key in $NewTags.Keys) {
                $CurrentTags[$Key] = $NewTags[$Key]
            }
            
            Set-AzResource -ResourceId $Resource.ResourceId -Tag $CurrentTags -Force | Out-Null
            
            Write-Host "✓ Tagged: $($Resource.Name)" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed to tag $($Resource.Name): $_"
            $FailCount++
        }
    }
    
    Write-Host "`nTagging Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Tagging operation failed: $_"
}`;
    }
  },

  {
    id: 'azure-export-resource-inventory',
    title: 'Export Resource Inventory',
    description: 'Export comprehensive inventory of all Azure resources to CSV',
    category: 'Resource Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AzureInventory.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Azure Resource Inventory
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting Azure resource inventory..." -ForegroundColor Cyan
    
    $Resources = Get-AzResource
    Write-Host "Found $($Resources.Count) resources" -ForegroundColor Yellow
    
    $Inventory = $Resources | ForEach-Object {
        $TagsString = if ($_.Tags) {
            ($_.Tags.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join "; "
        } else {
            "No Tags"
        }
        
        [PSCustomObject]@{
            ResourceName      = $_.Name
            ResourceType      = $_.ResourceType
            ResourceGroup     = $_.ResourceGroupName
            Location          = $_.Location
            Tags              = $TagsString
            SubscriptionId    = $_.SubscriptionId
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Inventory exported to: ${exportPath}" -ForegroundColor Green
    Write-Host "  Total resources: $($Inventory.Count)" -ForegroundColor Cyan
    
    Write-Host "`nResources by Type:" -ForegroundColor Yellow
    $Inventory | Group-Object ResourceType | Sort-Object Count -Descending | Select-Object -First 10 | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export inventory: $_"
}`;
    }
  },

  // ==================== Virtual Machines ====================
  {
    id: 'azure-start-stop-vms',
    title: 'Start/Stop/Restart VMs',
    description: 'Perform power operations on Azure Virtual Machines',
    category: 'Virtual Machines',
    parameters: [
      {
        name: 'action',
        label: 'Action',
        type: 'select',
        required: true,
        options: [
          { value: 'Start', label: 'Start VMs' },
          { value: 'Stop', label: 'Stop VMs (Deallocate)' },
          { value: 'Restart', label: 'Restart VMs' }
        ],
        helpText: 'Power operation to perform'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-production',
        helpText: 'Resource group containing the VMs'
      },
      {
        name: 'vmNames',
        label: 'VM Names (one per line, or * for all)',
        type: 'textarea',
        required: true,
        placeholder: 'vm-web01\nvm-web02',
        helpText: 'List of VM names or * for all VMs'
      }
    ],
    scriptTemplate: (params) => {
      const action = params.action;
      const rgName = escapePowerShellString(params.resourceGroupName);
      const vmNamesInput = params.vmNames.trim();
      const targetAll = vmNamesInput === '*';

      return `# ${action} Azure Virtual Machines
# Generated by PSForge

Connect-AzAccount

try {
    ${targetAll ? `
    Write-Host "Getting all VMs in Resource Group: ${rgName}" -ForegroundColor Cyan
    $VMs = Get-AzVM -ResourceGroupName "${rgName}"
    ` : `
    $VmNames = @(
${vmNamesInput.split('\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join('\n')}
    )
    
    Write-Host "Target VMs: $($VmNames.Count)" -ForegroundColor Cyan
    $VMs = @()
    foreach ($VmName in $VmNames) {
        $VM = Get-AzVM -ResourceGroupName "${rgName}" -Name $VmName -ErrorAction SilentlyContinue
        if ($VM) {
            $VMs += $VM
        } else {
            Write-Warning "VM not found: $VmName"
        }
    }
    `}
    
    if ($VMs.Count -eq 0) {
        Write-Warning "No VMs found to process"
        exit
    }
    
    Write-Host "Found $($VMs.Count) VMs to ${action.toLowerCase()}" -ForegroundColor Yellow
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($VM in $VMs) {
        try {
            Write-Host "${action}ing: $($VM.Name)..." -ForegroundColor Cyan
            
            ${action === 'Start' ? `Start-AzVM -ResourceGroupName "${rgName}" -Name $VM.Name -NoWait | Out-Null` : ''}
            ${action === 'Stop' ? `Stop-AzVM -ResourceGroupName "${rgName}" -Name $VM.Name -Force -NoWait | Out-Null` : ''}
            ${action === 'Restart' ? `Restart-AzVM -ResourceGroupName "${rgName}" -Name $VM.Name -NoWait | Out-Null` : ''}
            
            Write-Host "✓ $($VM.Name) ${action.toLowerCase()} initiated" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed: $($VM.Name) - $_"
            $FailCount++
        }
    }
    
    Write-Host "`n${action} Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Operation failed: $_"
}`;
    }
  },

  {
    id: 'azure-export-vm-inventory',
    title: 'Export VM Inventory',
    description: 'Export comprehensive inventory of all Azure Virtual Machines to CSV',
    category: 'Virtual Machines',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\VMInventory.csv',
        helpText: 'Path where the CSV file will be saved'
      },
      {
        name: 'includeStatus',
        label: 'Include Power State',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Include current power state (adds processing time)'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const includeStatus = params.includeStatus !== false;

      return `# Export Azure VM Inventory
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting VM inventory..." -ForegroundColor Cyan
    
    $VMs = Get-AzVM
    Write-Host "Found $($VMs.Count) VMs" -ForegroundColor Yellow
    
    $Inventory = foreach ($VM in $VMs) {
        Write-Host "Processing: $($VM.Name)..." -ForegroundColor Gray
        
        ${includeStatus ? `
        $VMStatus = Get-AzVM -ResourceGroupName $VM.ResourceGroupName -Name $VM.Name -Status
        $PowerState = ($VMStatus.Statuses | Where-Object { $_.Code -like "PowerState/*" }).DisplayStatus
        ` : `
        $PowerState = "Not Collected"
        `}
        
        $PrivateIPs = @()
        foreach ($NicId in $VM.NetworkProfile.NetworkInterfaces.Id) {
            $Nic = Get-AzNetworkInterface -ResourceId $NicId
            $PrivateIPs += $Nic.IpConfigurations.PrivateIpAddress
        }
        
        [PSCustomObject]@{
            Name              = $VM.Name
            ResourceGroup     = $VM.ResourceGroupName
            Location          = $VM.Location
            VMSize            = $VM.HardwareProfile.VmSize
            OSType            = $VM.StorageProfile.OsDisk.OsType
            PowerState        = $PowerState
            PrivateIPs        = ($PrivateIPs -join ", ")
            ProvisioningState = $VM.ProvisioningState
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ VM inventory exported to: ${exportPath}" -ForegroundColor Green
    Write-Host "  Total VMs: $($Inventory.Count)" -ForegroundColor Cyan
    
    Write-Host "`nVMs by Status:" -ForegroundColor Yellow
    $Inventory | Group-Object PowerState | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export VM inventory: $_"
}`;
    }
  },

  {
    id: 'azure-resize-vm',
    title: 'Resize Virtual Machine',
    description: 'Change the size/SKU of an Azure Virtual Machine',
    category: 'Virtual Machines',
    parameters: [
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-production',
        helpText: 'Resource group name'
      },
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'vm-web01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'newSize',
        label: 'New VM Size',
        type: 'select',
        required: true,
        options: [
          { value: 'Standard_B2s', label: 'Standard_B2s (2 vCPU, 4 GB)' },
          { value: 'Standard_D2s_v3', label: 'Standard_D2s_v3 (2 vCPU, 8 GB)' },
          { value: 'Standard_D4s_v3', label: 'Standard_D4s_v3 (4 vCPU, 16 GB)' },
          { value: 'Standard_E4s_v3', label: 'Standard_E4s_v3 (4 vCPU, 32 GB)' }
        ],
        helpText: 'Target VM size'
      }
    ],
    scriptTemplate: (params) => {
      const rgName = escapePowerShellString(params.resourceGroupName);
      const vmName = escapePowerShellString(params.vmName);
      const newSize = escapePowerShellString(params.newSize);

      return `# Resize Azure Virtual Machine
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Resizing VM: ${vmName} to ${newSize}" -ForegroundColor Cyan
    
    $VM = Get-AzVM -ResourceGroupName "${rgName}" -Name "${vmName}"
    
    Write-Host "Current Size: $($VM.HardwareProfile.VmSize)" -ForegroundColor Yellow
    Write-Host "New Size: ${newSize}" -ForegroundColor Yellow
    
    $VM.HardwareProfile.VmSize = "${newSize}"
    
    Write-Host "Applying resize (VM will restart)..." -ForegroundColor Cyan
    Update-AzVM -VM $VM -ResourceGroupName "${rgName}"
    
    Write-Host "✓ VM resized successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to resize VM: $_"
}`;
    }
  },

  // ==================== Networking ====================
  {
    id: 'azure-create-vnet',
    title: 'Create Virtual Network',
    description: 'Create a new Azure Virtual Network with subnets',
    category: 'Networking',
    parameters: [
      {
        name: 'vnetName',
        label: 'VNet Name',
        type: 'text',
        required: true,
        placeholder: 'vnet-production',
        helpText: 'Virtual network name'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-network',
        helpText: 'Resource group name'
      },
      {
        name: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        options: [
          { value: 'eastus', label: 'East US' },
          { value: 'westus', label: 'West US' }
        ],
        helpText: 'Azure region'
      },
      {
        name: 'addressSpace',
        label: 'Address Space (CIDR)',
        type: 'text',
        required: true,
        placeholder: '10.0.0.0/16',
        helpText: 'VNet address space'
      },
      {
        name: 'subnets',
        label: 'Subnets (Name:CIDR, one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'subnet-web:10.0.1.0/24\nsubnet-app:10.0.2.0/24',
        helpText: 'Subnet definitions'
      }
    ],
    scriptTemplate: (params) => {
      const vnetName = escapePowerShellString(params.vnetName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const location = escapePowerShellString(params.location);
      const addressSpace = escapePowerShellString(params.addressSpace);
      
      const subnetLines = params.subnets.split('\n').filter((line: string) => line.trim());
      const subnetConfigs = subnetLines.map((line: string) => {
        const [name, cidr] = line.split(':').map(s => s.trim());
        return { name: escapePowerShellString(name), cidr: escapePowerShellString(cidr) };
      });

      return `# Create Azure Virtual Network
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating Virtual Network: ${vnetName}" -ForegroundColor Cyan
    
    $SubnetConfigs = @(
${subnetConfigs.map(subnet => `        New-AzVirtualNetworkSubnetConfig -Name "${subnet.name}" -AddressPrefix "${subnet.cidr}"`).join('\n')}
    )
    
    $VNetParams = @{
        Name              = "${vnetName}"
        ResourceGroupName = "${rgName}"
        Location          = "${location}"
        AddressPrefix     = "${addressSpace}"
        Subnet            = $SubnetConfigs
    }
    
    $VNet = New-AzVirtualNetwork @VNetParams
    
    Write-Host "✓ Virtual Network created successfully" -ForegroundColor Green
    
    Write-Host "`nVNet Details:" -ForegroundColor Cyan
    Write-Host "  Name: ${vnetName}"
    Write-Host "  Address Space: ${addressSpace}"
    Write-Host "  Subnets: $($VNet.Subnets.Count)"
    
    foreach ($Subnet in $VNet.Subnets) {
        Write-Host "    - $($Subnet.Name): $($Subnet.AddressPrefix)"
    }
    
} catch {
    Write-Error "Failed to create VNet: $_"
}`;
    }
  },

  {
    id: 'azure-create-nsg',
    title: 'Create Network Security Group',
    description: 'Create a Network Security Group with firewall rules',
    category: 'Networking',
    parameters: [
      {
        name: 'nsgName',
        label: 'NSG Name',
        type: 'text',
        required: true,
        placeholder: 'nsg-web-servers',
        helpText: 'Network Security Group name'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-network',
        helpText: 'Resource group name'
      },
      {
        name: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        options: [
          { value: 'eastus', label: 'East US' },
          { value: 'westus', label: 'West US' }
        ],
        helpText: 'Azure region'
      }
    ],
    scriptTemplate: (params) => {
      const nsgName = escapePowerShellString(params.nsgName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const location = escapePowerShellString(params.location);

      return `# Create Network Security Group
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating Network Security Group: ${nsgName}" -ForegroundColor Cyan
    
    $NSG = New-AzNetworkSecurityGroup -Name "${nsgName}" -ResourceGroupName "${rgName}" -Location "${location}"
    
    Write-Host "✓ NSG created successfully" -ForegroundColor Green
    
    Write-Host "`nNSG Details:" -ForegroundColor Cyan
    Write-Host "  Name: ${nsgName}"
    Write-Host "  Location: ${location}"
    Write-Host "  Resource ID: $($NSG.Id)"
    
} catch {
    Write-Error "Failed to create NSG: $_"
}`;
    }
  },

  // ==================== Storage ====================
  {
    id: 'azure-create-storage-account',
    title: 'Create Storage Account',
    description: 'Create a new Azure Storage Account',
    category: 'Storage',
    parameters: [
      {
        name: 'storageAccountName',
        label: 'Storage Account Name',
        type: 'text',
        required: true,
        placeholder: 'stproductiondata01',
        helpText: 'Unique name (3-24 lowercase letters/numbers)'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-storage',
        helpText: 'Resource group name'
      },
      {
        name: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        options: [
          { value: 'eastus', label: 'East US' },
          { value: 'westus', label: 'West US' }
        ],
        helpText: 'Azure region'
      },
      {
        name: 'skuName',
        label: 'Replication Type',
        type: 'select',
        required: true,
        options: [
          { value: 'Standard_LRS', label: 'Locally Redundant (LRS)' },
          { value: 'Standard_GRS', label: 'Geo-Redundant (GRS)' },
          { value: 'Standard_ZRS', label: 'Zone-Redundant (ZRS)' }
        ],
        defaultValue: 'Standard_LRS',
        helpText: 'Storage replication strategy'
      }
    ],
    scriptTemplate: (params) => {
      const storageName = escapePowerShellString(params.storageAccountName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const location = escapePowerShellString(params.location);
      const skuName = escapePowerShellString(params.skuName);

      return `# Create Azure Storage Account
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating Storage Account: ${storageName}" -ForegroundColor Cyan
    
    $StorageParams = @{
        ResourceGroupName      = "${rgName}"
        Name                   = "${storageName}"
        Location               = "${location}"
        SkuName                = "${skuName}"
        EnableHttpsTrafficOnly = $true
    }
    
    $StorageAccount = New-AzStorageAccount @StorageParams
    
    Write-Host "✓ Storage Account created successfully" -ForegroundColor Green
    
    Write-Host "`nStorage Account Details:" -ForegroundColor Cyan
    Write-Host "  Name: ${storageName}"
    Write-Host "  SKU: ${skuName}"
    Write-Host "  Status: $($StorageAccount.ProvisioningState)"
    
} catch {
    Write-Error "Failed to create storage account: $_"
}`;
    }
  },

  // ==================== RBAC ====================
  {
    id: 'azure-assign-rbac-role',
    title: 'Assign RBAC Role',
    description: 'Assign an Azure RBAC role to a user or group',
    category: 'Identity & Access (RBAC)',
    parameters: [
      {
        name: 'principalEmail',
        label: 'User/Group Email',
        type: 'text',
        required: true,
        placeholder: 'user@contoso.com',
        helpText: 'Email address of the principal'
      },
      {
        name: 'roleName',
        label: 'Role',
        type: 'select',
        required: true,
        options: [
          { value: 'Reader', label: 'Reader' },
          { value: 'Contributor', label: 'Contributor' },
          { value: 'Owner', label: 'Owner' },
          { value: 'Virtual Machine Contributor', label: 'Virtual Machine Contributor' }
        ],
        helpText: 'RBAC role to assign'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group (leave empty for subscription scope)',
        type: 'text',
        required: false,
        placeholder: 'rg-production',
        helpText: 'Optional: specific resource group scope'
      }
    ],
    scriptTemplate: (params) => {
      const principalEmail = escapePowerShellString(params.principalEmail);
      const roleName = escapePowerShellString(params.roleName);
      const rgName = params.resourceGroupName ? escapePowerShellString(params.resourceGroupName) : '';

      return `# Assign Azure RBAC Role
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Assigning RBAC Role: ${roleName}" -ForegroundColor Cyan
    
    ${rgName ? `
    $RG = Get-AzResourceGroup -Name "${rgName}"
    $Scope = $RG.ResourceId
    ` : `
    $Scope = "/subscriptions/$((Get-AzContext).Subscription.Id)"
    `}
    
    Write-Host "Looking up principal: ${principalEmail}" -ForegroundColor Cyan
    $Principal = Get-AzADUser -UserPrincipalName "${principalEmail}" -ErrorAction SilentlyContinue
    if (-not $Principal) {
        $Principal = Get-AzADGroup -DisplayName "${principalEmail}" -ErrorAction SilentlyContinue
    }
    if (-not $Principal) {
        throw "Principal not found: ${principalEmail}"
    }
    
    $Assignment = New-AzRoleAssignment -ObjectId $Principal.Id -RoleDefinitionName "${roleName}" -Scope $Scope
    
    Write-Host "✓ Role assigned successfully" -ForegroundColor Green
    
    Write-Host "`nAssignment Details:" -ForegroundColor Cyan
    Write-Host "  Principal: ${principalEmail}"
    Write-Host "  Role: ${roleName}"
    Write-Host "  Scope: $Scope"
    
} catch {
    Write-Error "Failed to assign role: $_"
}`;
    }
  },

  {
    id: 'azure-export-rbac-assignments',
    title: 'Export RBAC Assignments',
    description: 'Export all RBAC role assignments to CSV',
    category: 'Identity & Access (RBAC)',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\RBACAssignments.csv',
        helpText: 'Path where the CSV will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Azure RBAC Assignments
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting RBAC assignments..." -ForegroundColor Cyan
    
    $Assignments = Get-AzRoleAssignment
    
    Write-Host "Found $($Assignments.Count) assignments" -ForegroundColor Yellow
    
    $Report = $Assignments | ForEach-Object {
        [PSCustomObject]@{
            DisplayName = $_.DisplayName
            SignInName  = $_.SignInName
            RoleDefinitionName = $_.RoleDefinitionName
            Scope       = $_.Scope
            ObjectType  = $_.ObjectType
            ObjectId    = $_.ObjectId
        }
    }
    
    $Report | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ RBAC assignments exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host "`nAssignments by Role:" -ForegroundColor Yellow
    $Report | Group-Object RoleDefinitionName | Sort-Object Count -Descending | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export RBAC assignments: $_"
}`;
    }
  },

  // ==================== Cost Management ====================
  {
    id: 'azure-cost-report',
    title: 'Export Cost Data',
    description: 'Generate a cost report for Azure resources',
    category: 'Cost Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AzureCosts.csv',
        helpText: 'Path where the CSV will be saved'
      },
      {
        name: 'timeframe',
        label: 'Timeframe',
        type: 'select',
        required: true,
        options: [
          { value: 'MonthToDate', label: 'Month to Date' },
          { value: 'TheLastMonth', label: 'Last Month' }
        ],
        defaultValue: 'MonthToDate',
        helpText: 'Time period for cost data'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const timeframe = params.timeframe || 'MonthToDate';

      return `# Export Azure Cost Data
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting cost data for: ${timeframe}" -ForegroundColor Cyan
    
    $CostData = Get-AzConsumptionUsageDetail -Timeframe ${timeframe}
    
    Write-Host "Found $($CostData.Count) usage records" -ForegroundColor Yellow
    
    $CostsByRG = $CostData | Group-Object -Property InstanceLocation | ForEach-Object {
        $TotalCost = ($_.Group | Measure-Object -Property PretaxCost -Sum).Sum
        
        [PSCustomObject]@{
            ResourceGroup = $_.Name
            TotalCost     = [math]::Round($TotalCost, 2)
            Currency      = $_.Group[0].Currency
            RecordCount   = $_.Count
        }
    } | Sort-Object TotalCost -Descending
    
    $CostsByRG | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Cost data exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host "`nTop 10 Resource Groups by Cost:" -ForegroundColor Yellow
    $CostsByRG | Select-Object -First 10 | Format-Table ResourceGroup, TotalCost, Currency
    
    $GrandTotal = ($CostsByRG | Measure-Object -Property TotalCost -Sum).Sum
    Write-Host "`nGrand Total: $([math]::Round($GrandTotal, 2))" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export cost data: $_"
}`;
    }
  },

  // ==================== Policy & Governance ====================
  {
    id: 'azure-assign-policy',
    title: 'Assign Azure Policy',
    description: 'Assign a built-in Azure Policy to a resource group or subscription',
    category: 'Policy & Governance',
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'select',
        required: true,
        options: [
          { value: 'Allowed locations', label: 'Allowed locations' },
          { value: 'Require a tag on resources', label: 'Require a tag on resources' },
          { value: 'Allowed virtual machine size SKUs', label: 'Allowed virtual machine size SKUs' }
        ],
        helpText: 'Built-in policy to assign'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group (leave empty for subscription scope)',
        type: 'text',
        required: false,
        placeholder: 'rg-production',
        helpText: 'Optional: specific resource group scope'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const rgName = params.resourceGroupName ? escapePowerShellString(params.resourceGroupName) : '';

      return `# Assign Azure Policy
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Assigning Policy: ${policyName}" -ForegroundColor Cyan
    
    $PolicyDefinition = Get-AzPolicyDefinition | Where-Object { $_.Properties.DisplayName -eq "${policyName}" }
    
    if (-not $PolicyDefinition) {
        throw "Policy definition not found: ${policyName}"
    }
    
    ${rgName ? `
    $RG = Get-AzResourceGroup -Name "${rgName}"
    $Scope = $RG.ResourceId
    ` : `
    $Scope = "/subscriptions/$((Get-AzContext).Subscription.Id)"
    `}
    
    $Assignment = New-AzPolicyAssignment -Name "${policyName}-assignment" -PolicyDefinition $PolicyDefinition -Scope $Scope
    
    Write-Host "✓ Policy assigned successfully" -ForegroundColor Green
    
    Write-Host "`nPolicy Assignment Details:" -ForegroundColor Cyan
    Write-Host "  Policy: ${policyName}"
    Write-Host "  Scope: $Scope"
    Write-Host "  Assignment ID: $($Assignment.ResourceId)"
    
} catch {
    Write-Error "Failed to assign policy: $_"
}`;
    }
  },

  // ==================== Monitoring ====================
  {
    id: 'azure-enable-diagnostics',
    title: 'Enable Diagnostic Settings',
    description: 'Enable diagnostic settings on Azure resources',
    category: 'Monitoring & Logging',
    parameters: [
      {
        name: 'resourceId',
        label: 'Resource ID',
        type: 'text',
        required: true,
        placeholder: '/subscriptions/.../resourceGroups/.../providers/...',
        helpText: 'Full Azure resource ID'
      },
      {
        name: 'workspaceName',
        label: 'Log Analytics Workspace Name',
        type: 'text',
        required: true,
        placeholder: 'law-production',
        helpText: 'Log Analytics workspace name'
      },
      {
        name: 'workspaceResourceGroup',
        label: 'Workspace Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-monitoring',
        helpText: 'Resource group containing the workspace'
      }
    ],
    scriptTemplate: (params) => {
      const resourceId = escapePowerShellString(params.resourceId);
      const workspaceName = escapePowerShellString(params.workspaceName);
      const workspaceRG = escapePowerShellString(params.workspaceResourceGroup);

      return `# Enable Diagnostic Settings
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Enabling diagnostic settings..." -ForegroundColor Cyan
    
    $Workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName "${workspaceRG}" -Name "${workspaceName}"
    
    if (-not $Workspace) {
        throw "Log Analytics workspace not found: ${workspaceName}"
    }
    
    $Metrics = @()
    $Logs = @()
    
    $Categories = Get-AzDiagnosticSettingCategory -ResourceId "${resourceId}"
    
    foreach ($Category in $Categories) {
        if ($Category.CategoryType -eq "Logs") {
            $Logs += New-AzDiagnosticSettingLogSettingsObject -Enabled $true -Category $Category.Name
        }
        if ($Category.CategoryType -eq "Metrics") {
            $Metrics += New-AzDiagnosticSettingMetricSettingsObject -Enabled $true -Category $Category.Name
        }
    }
    
    New-AzDiagnosticSetting -Name "PSForge-Diagnostics" -ResourceId "${resourceId}" -WorkspaceId $Workspace.ResourceId -Log $Logs -Metric $Metrics
    
    Write-Host "✓ Diagnostic settings enabled successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to enable diagnostic settings: $_"
}`;
    }
  }
];

export const azureResourceCategories = [
  'Resource Management',
  'Virtual Machines',
  'Networking',
  'Storage',
  'Identity & Access (RBAC)',
  'Cost Management',
  'Policy & Governance',
  'Monitoring & Logging'
];
