import { escapePowerShellString } from './powershell-utils';

export interface AzureResourceParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface AzureResourceTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: AzureResourceParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const azureResourceTasks: AzureResourceTask[] = [
  // ==================== Resource Management ====================
  {
    id: 'azure-create-resource-group',
    title: 'Create Resource Group',
    description: 'Create a new Azure Resource Group with optional tags and lock',
    category: 'Resource Management',
    parameters: [
      {
        name: 'resourceGroupName',
        label: 'Resource Group Name',
        type: 'text',
        required: true,
        placeholder: 'rg-production-eastus',
        helpText: 'Name for the new resource group'
      },
      {
        name: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        options: [
          { value: 'eastus', label: 'East US' },
          { value: 'westus', label: 'West US' },
          { value: 'centralus', label: 'Central US' },
          { value: 'northeurope', label: 'North Europe' },
          { value: 'westeurope', label: 'West Europe' }
        ],
        helpText: 'Azure region for the resource group'
      },
      {
        name: 'tags',
        label: 'Tags (Key=Value, one per line)',
        type: 'textarea',
        required: false,
        placeholder: 'Environment=Production\nCostCenter=IT',
        helpText: 'Optional tags in Key=Value format'
      }
    ],
    scriptTemplate: (params) => {
      const rgName = escapePowerShellString(params.resourceGroupName);
      const location = escapePowerShellString(params.location);
      
      let tagsBlock = '';
      if (params.tags) {
        const tagLines = params.tags.split('\n').filter((line: string) => line.trim());
        if (tagLines.length > 0) {
          const tagPairs = tagLines.map((line: string) => {
            const [key, value] = line.split('=').map(s => s.trim());
            return `    "${escapePowerShellString(key)}" = "${escapePowerShellString(value)}"`;
          }).join('\n');
          tagsBlock = `\n$Tags = @{\n${tagPairs}\n}`;
        }
      }

      return `# Create Azure Resource Group
# Generated by PSForge

Connect-AzAccount
${tagsBlock}

try {
    Write-Host "Creating Resource Group: ${rgName}" -ForegroundColor Cyan
    
    $RgParams = @{
        Name     = "${rgName}"
        Location = "${location}"
    }
    
    ${tagsBlock ? '$RgParams.Tag = $Tags' : ''}
    
    $ResourceGroup = New-AzResourceGroup @RgParams
    Write-Host "✓ Resource Group created successfully" -ForegroundColor Green
    
    $ResourceGroup | Select-Object ResourceGroupName, Location, ProvisioningState
    
} catch {
    Write-Error "Failed to create resource group: $_"
}`;
    }
  },

  {
    id: 'azure-tag-resources',
    title: 'Tag Resources at Scale',
    description: 'Add or update tags across resources in a Resource Group',
    category: 'Resource Management',
    parameters: [
      {
        name: 'resourceGroupName',
        label: 'Resource Group Name',
        type: 'text',
        required: true,
        placeholder: 'rg-production',
        helpText: 'Target resource group'
      },
      {
        name: 'tags',
        label: 'Tags to Apply (Key=Value, one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'Environment=Production\nManagedBy=PSForge',
        helpText: 'Tags to add/update on resources'
      }
    ],
    scriptTemplate: (params) => {
      const rgName = escapePowerShellString(params.resourceGroupName);
      
      const tagLines = params.tags.split('\n').filter((line: string) => line.trim());
      const tagPairs = tagLines.map((line: string) => {
        const [key, value] = line.split('=').map(s => s.trim());
        return `    "${escapePowerShellString(key)}" = "${escapePowerShellString(value)}"`;
      }).join('\n');

      return `# Tag Azure Resources at Scale
# Generated by PSForge

Connect-AzAccount

$NewTags = @{
${tagPairs}
}

try {
    Write-Host "Getting resources in Resource Group: ${rgName}" -ForegroundColor Cyan
    $Resources = Get-AzResource -ResourceGroupName "${rgName}"
    
    Write-Host "Found $($Resources.Count) resources to tag" -ForegroundColor Yellow
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($Resource in $Resources) {
        try {
            $CurrentTags = $Resource.Tags
            if ($null -eq $CurrentTags) { $CurrentTags = @{} }
            
            foreach ($Key in $NewTags.Keys) {
                $CurrentTags[$Key] = $NewTags[$Key]
            }
            
            Set-AzResource -ResourceId $Resource.ResourceId -Tag $CurrentTags -Force | Out-Null
            
            Write-Host "✓ Tagged: $($Resource.Name)" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed to tag $($Resource.Name): $_"
            $FailCount++
        }
    }
    
    Write-Host \"\`nTagging Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Tagging operation failed: $_"
}`;
    }
  },

  {
    id: 'azure-export-resource-inventory',
    title: 'Export Resource Inventory',
    description: 'Export comprehensive inventory of all Azure resources to CSV',
    category: 'Resource Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AzureInventory.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Azure Resource Inventory
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting Azure resource inventory..." -ForegroundColor Cyan
    
    $Resources = Get-AzResource
    Write-Host "Found $($Resources.Count) resources" -ForegroundColor Yellow
    
    $Inventory = $Resources | ForEach-Object {
        $TagsString = if ($_.Tags) {
            ($_.Tags.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join "; "
        } else {
            "No Tags"
        }
        
        [PSCustomObject]@{
            ResourceName      = $_.Name
            ResourceType      = $_.ResourceType
            ResourceGroup     = $_.ResourceGroupName
            Location          = $_.Location
            Tags              = $TagsString
            SubscriptionId    = $_.SubscriptionId
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Inventory exported to: ${exportPath}" -ForegroundColor Green
    Write-Host "  Total resources: $($Inventory.Count)" -ForegroundColor Cyan
    
    Write-Host \"\`nResources by Type:" -ForegroundColor Yellow
    $Inventory | Group-Object ResourceType | Sort-Object Count -Descending | Select-Object -First 10 | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export inventory: $_"
}`;
    }
  },

  // ==================== Virtual Machines ====================
  {
    id: 'azure-start-stop-vms',
    title: 'Start/Stop/Restart VMs',
    description: 'Perform power operations on Azure Virtual Machines',
    category: 'Virtual Machines',
    parameters: [
      {
        name: 'action',
        label: 'Action',
        type: 'select',
        required: true,
        options: [
          { value: 'Start', label: 'Start VMs' },
          { value: 'Stop', label: 'Stop VMs (Deallocate)' },
          { value: 'Restart', label: 'Restart VMs' }
        ],
        helpText: 'Power operation to perform'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-production',
        helpText: 'Resource group containing the VMs'
      },
      {
        name: 'vmNames',
        label: 'VM Names (one per line, or * for all)',
        type: 'textarea',
        required: true,
        placeholder: 'vm-web01\nvm-web02',
        helpText: 'List of VM names or * for all VMs'
      }
    ],
    scriptTemplate: (params) => {
      const action = params.action;
      const rgName = escapePowerShellString(params.resourceGroupName);
      const vmNamesInput = params.vmNames.trim();
      const targetAll = vmNamesInput === '*';

      return `# ${action} Azure Virtual Machines
# Generated by PSForge

Connect-AzAccount

try {
    ${targetAll ? `
    Write-Host "Getting all VMs in Resource Group: ${rgName}" -ForegroundColor Cyan
    $VMs = Get-AzVM -ResourceGroupName "${rgName}"
    ` : `
    $VmNames = @(
${vmNamesInput.split('\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join('\n')}
    )
    
    Write-Host "Target VMs: $($VmNames.Count)" -ForegroundColor Cyan
    $VMs = @()
    foreach ($VmName in $VmNames) {
        $VM = Get-AzVM -ResourceGroupName "${rgName}" -Name $VmName -ErrorAction SilentlyContinue
        if ($VM) {
            $VMs += $VM
        } else {
            Write-Warning "VM not found: $VmName"
        }
    }
    `}
    
    if ($VMs.Count -eq 0) {
        Write-Warning "No VMs found to process"
        exit
    }
    
    Write-Host "Found $($VMs.Count) VMs to ${action.toLowerCase()}" -ForegroundColor Yellow
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($VM in $VMs) {
        try {
            Write-Host "${action}ing: $($VM.Name)..." -ForegroundColor Cyan
            
            ${action === 'Start' ? `Start-AzVM -ResourceGroupName "${rgName}" -Name $VM.Name -NoWait | Out-Null` : ''}
            ${action === 'Stop' ? `Stop-AzVM -ResourceGroupName "${rgName}" -Name $VM.Name -Force -NoWait | Out-Null` : ''}
            ${action === 'Restart' ? `Restart-AzVM -ResourceGroupName "${rgName}" -Name $VM.Name -NoWait | Out-Null` : ''}
            
            Write-Host "✓ $($VM.Name) ${action.toLowerCase()} initiated" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed: $($VM.Name) - $_"
            $FailCount++
        }
    }
    
    Write-Host \"\`n${action} Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Operation failed: $_"
}`;
    }
  },

  {
    id: 'azure-export-vm-inventory',
    title: 'Export VM Inventory',
    description: 'Export comprehensive inventory of all Azure Virtual Machines to CSV',
    category: 'Virtual Machines',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\VMInventory.csv',
        helpText: 'Path where the CSV file will be saved'
      },
      {
        name: 'includeStatus',
        label: 'Include Power State',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Include current power state (adds processing time)'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const includeStatus = params.includeStatus !== false;

      return `# Export Azure VM Inventory
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting VM inventory..." -ForegroundColor Cyan
    
    $VMs = Get-AzVM
    Write-Host "Found $($VMs.Count) VMs" -ForegroundColor Yellow
    
    $Inventory = foreach ($VM in $VMs) {
        Write-Host "Processing: $($VM.Name)..." -ForegroundColor Gray
        
        ${includeStatus ? `
        $VMStatus = Get-AzVM -ResourceGroupName $VM.ResourceGroupName -Name $VM.Name -Status
        $PowerState = ($VMStatus.Statuses | Where-Object { $_.Code -like "PowerState/*" }).DisplayStatus
        ` : `
        $PowerState = "Not Collected"
        `}
        
        $PrivateIPs = @()
        foreach ($NicId in $VM.NetworkProfile.NetworkInterfaces.Id) {
            $Nic = Get-AzNetworkInterface -ResourceId $NicId
            $PrivateIPs += $Nic.IpConfigurations.PrivateIpAddress
        }
        
        [PSCustomObject]@{
            Name              = $VM.Name
            ResourceGroup     = $VM.ResourceGroupName
            Location          = $VM.Location
            VMSize            = $VM.HardwareProfile.VmSize
            OSType            = $VM.StorageProfile.OsDisk.OsType
            PowerState        = $PowerState
            PrivateIPs        = ($PrivateIPs -join ", ")
            ProvisioningState = $VM.ProvisioningState
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ VM inventory exported to: ${exportPath}" -ForegroundColor Green
    Write-Host "  Total VMs: $($Inventory.Count)" -ForegroundColor Cyan
    
    Write-Host \"\`nVMs by Status:" -ForegroundColor Yellow
    $Inventory | Group-Object PowerState | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export VM inventory: $_"
}`;
    }
  },

  {
    id: 'azure-resize-vm',
    title: 'Resize Virtual Machine',
    description: 'Change the size/SKU of an Azure Virtual Machine',
    category: 'Virtual Machines',
    parameters: [
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-production',
        helpText: 'Resource group name'
      },
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'vm-web01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'newSize',
        label: 'New VM Size',
        type: 'select',
        required: true,
        options: [
          { value: 'Standard_B2s', label: 'Standard_B2s (2 vCPU, 4 GB)' },
          { value: 'Standard_D2s_v3', label: 'Standard_D2s_v3 (2 vCPU, 8 GB)' },
          { value: 'Standard_D4s_v3', label: 'Standard_D4s_v3 (4 vCPU, 16 GB)' },
          { value: 'Standard_E4s_v3', label: 'Standard_E4s_v3 (4 vCPU, 32 GB)' }
        ],
        helpText: 'Target VM size'
      }
    ],
    scriptTemplate: (params) => {
      const rgName = escapePowerShellString(params.resourceGroupName);
      const vmName = escapePowerShellString(params.vmName);
      const newSize = escapePowerShellString(params.newSize);

      return `# Resize Azure Virtual Machine
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Resizing VM: ${vmName} to ${newSize}" -ForegroundColor Cyan
    
    $VM = Get-AzVM -ResourceGroupName "${rgName}" -Name "${vmName}"
    
    Write-Host "Current Size: $($VM.HardwareProfile.VmSize)" -ForegroundColor Yellow
    Write-Host "New Size: ${newSize}" -ForegroundColor Yellow
    
    $VM.HardwareProfile.VmSize = "${newSize}"
    
    Write-Host "Applying resize (VM will restart)..." -ForegroundColor Cyan
    Update-AzVM -VM $VM -ResourceGroupName "${rgName}"
    
    Write-Host "✓ VM resized successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to resize VM: $_"
}`;
    }
  },

  // ==================== Networking ====================
  {
    id: 'azure-create-vnet',
    title: 'Create Virtual Network',
    description: 'Create a new Azure Virtual Network with subnets',
    category: 'Networking',
    parameters: [
      {
        name: 'vnetName',
        label: 'VNet Name',
        type: 'text',
        required: true,
        placeholder: 'vnet-production',
        helpText: 'Virtual network name'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-network',
        helpText: 'Resource group name'
      },
      {
        name: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        options: [
          { value: 'eastus', label: 'East US' },
          { value: 'westus', label: 'West US' }
        ],
        helpText: 'Azure region'
      },
      {
        name: 'addressSpace',
        label: 'Address Space (CIDR)',
        type: 'text',
        required: true,
        placeholder: '10.0.0.0/16',
        helpText: 'VNet address space'
      },
      {
        name: 'subnets',
        label: 'Subnets (Name:CIDR, one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'subnet-web:10.0.1.0/24\nsubnet-app:10.0.2.0/24',
        helpText: 'Subnet definitions'
      }
    ],
    scriptTemplate: (params) => {
      const vnetName = escapePowerShellString(params.vnetName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const location = escapePowerShellString(params.location);
      const addressSpace = escapePowerShellString(params.addressSpace);
      
      const subnetLines = params.subnets.split('\n').filter((line: string) => line.trim());
      const subnetConfigs = subnetLines.map((line: string) => {
        const [name, cidr] = line.split(':').map(s => s.trim());
        return { name: escapePowerShellString(name), cidr: escapePowerShellString(cidr) };
      });

      return `# Create Azure Virtual Network
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating Virtual Network: ${vnetName}" -ForegroundColor Cyan
    
    $SubnetConfigs = @(
${subnetConfigs.map((subnet: any) => `        New-AzVirtualNetworkSubnetConfig -Name "${subnet.name}" -AddressPrefix "${subnet.cidr}"`).join('\n')}
    )
    
    $VNetParams = @{
        Name              = "${vnetName}"
        ResourceGroupName = "${rgName}"
        Location          = "${location}"
        AddressPrefix     = "${addressSpace}"
        Subnet            = $SubnetConfigs
    }
    
    $VNet = New-AzVirtualNetwork @VNetParams
    
    Write-Host "✓ Virtual Network created successfully" -ForegroundColor Green
    
    Write-Host \"\`nVNet Details:" -ForegroundColor Cyan
    Write-Host "  Name: ${vnetName}"
    Write-Host "  Address Space: ${addressSpace}"
    Write-Host "  Subnets: $($VNet.Subnets.Count)"
    
    foreach ($Subnet in $VNet.Subnets) {
        Write-Host "    - $($Subnet.Name): $($Subnet.AddressPrefix)"
    }
    
} catch {
    Write-Error "Failed to create VNet: $_"
}`;
    }
  },

  {
    id: 'azure-create-nsg',
    title: 'Create Network Security Group',
    description: 'Create a Network Security Group with firewall rules',
    category: 'Networking',
    parameters: [
      {
        name: 'nsgName',
        label: 'NSG Name',
        type: 'text',
        required: true,
        placeholder: 'nsg-web-servers',
        helpText: 'Network Security Group name'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-network',
        helpText: 'Resource group name'
      },
      {
        name: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        options: [
          { value: 'eastus', label: 'East US' },
          { value: 'westus', label: 'West US' }
        ],
        helpText: 'Azure region'
      }
    ],
    scriptTemplate: (params) => {
      const nsgName = escapePowerShellString(params.nsgName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const location = escapePowerShellString(params.location);

      return `# Create Network Security Group
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating Network Security Group: ${nsgName}" -ForegroundColor Cyan
    
    $NSG = New-AzNetworkSecurityGroup -Name "${nsgName}" -ResourceGroupName "${rgName}" -Location "${location}"
    
    Write-Host "✓ NSG created successfully" -ForegroundColor Green
    
    Write-Host \"\`nNSG Details:" -ForegroundColor Cyan
    Write-Host "  Name: ${nsgName}"
    Write-Host "  Location: ${location}"
    Write-Host "  Resource ID: $($NSG.Id)"
    
} catch {
    Write-Error "Failed to create NSG: $_"
}`;
    }
  },

  // ==================== Storage ====================
  {
    id: 'azure-create-storage-account',
    title: 'Create Storage Account',
    description: 'Create a new Azure Storage Account',
    category: 'Storage',
    parameters: [
      {
        name: 'storageAccountName',
        label: 'Storage Account Name',
        type: 'text',
        required: true,
        placeholder: 'stproductiondata01',
        helpText: 'Unique name (3-24 lowercase letters/numbers)'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-storage',
        helpText: 'Resource group name'
      },
      {
        name: 'location',
        label: 'Location',
        type: 'select',
        required: true,
        options: [
          { value: 'eastus', label: 'East US' },
          { value: 'westus', label: 'West US' }
        ],
        helpText: 'Azure region'
      },
      {
        name: 'skuName',
        label: 'Replication Type',
        type: 'select',
        required: true,
        options: [
          { value: 'Standard_LRS', label: 'Locally Redundant (LRS)' },
          { value: 'Standard_GRS', label: 'Geo-Redundant (GRS)' },
          { value: 'Standard_ZRS', label: 'Zone-Redundant (ZRS)' }
        ],
        defaultValue: 'Standard_LRS',
        helpText: 'Storage replication strategy'
      }
    ],
    scriptTemplate: (params) => {
      const storageName = escapePowerShellString(params.storageAccountName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const location = escapePowerShellString(params.location);
      const skuName = escapePowerShellString(params.skuName);

      return `# Create Azure Storage Account
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating Storage Account: ${storageName}" -ForegroundColor Cyan
    
    $StorageParams = @{
        ResourceGroupName      = "${rgName}"
        Name                   = "${storageName}"
        Location               = "${location}"
        SkuName                = "${skuName}"
        EnableHttpsTrafficOnly = $true
    }
    
    $StorageAccount = New-AzStorageAccount @StorageParams
    
    Write-Host "✓ Storage Account created successfully" -ForegroundColor Green
    
    Write-Host \"\`nStorage Account Details:" -ForegroundColor Cyan
    Write-Host "  Name: ${storageName}"
    Write-Host "  SKU: ${skuName}"
    Write-Host "  Status: $($StorageAccount.ProvisioningState)"
    
} catch {
    Write-Error "Failed to create storage account: $_"
}`;
    }
  },

  // ==================== RBAC ====================
  {
    id: 'azure-assign-rbac-role',
    title: 'Assign RBAC Role',
    description: 'Assign an Azure RBAC role to a user or group',
    category: 'Identity & Access (RBAC)',
    parameters: [
      {
        name: 'principalEmail',
        label: 'User/Group Email',
        type: 'text',
        required: true,
        placeholder: 'user@contoso.com',
        helpText: 'Email address of the principal'
      },
      {
        name: 'roleName',
        label: 'Role',
        type: 'select',
        required: true,
        options: [
          { value: 'Reader', label: 'Reader' },
          { value: 'Contributor', label: 'Contributor' },
          { value: 'Owner', label: 'Owner' },
          { value: 'Virtual Machine Contributor', label: 'Virtual Machine Contributor' }
        ],
        helpText: 'RBAC role to assign'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group (leave empty for subscription scope)',
        type: 'text',
        required: false,
        placeholder: 'rg-production',
        helpText: 'Optional: specific resource group scope'
      }
    ],
    scriptTemplate: (params) => {
      const principalEmail = escapePowerShellString(params.principalEmail);
      const roleName = escapePowerShellString(params.roleName);
      const rgName = params.resourceGroupName ? escapePowerShellString(params.resourceGroupName) : '';

      return `# Assign Azure RBAC Role
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Assigning RBAC Role: ${roleName}" -ForegroundColor Cyan
    
    ${rgName ? `
    $RG = Get-AzResourceGroup -Name "${rgName}"
    $Scope = $RG.ResourceId
    ` : `
    $Scope = "/subscriptions/$((Get-AzContext).Subscription.Id)"
    `}
    
    Write-Host "Looking up principal: ${principalEmail}" -ForegroundColor Cyan
    $Principal = Get-AzADUser -UserPrincipalName "${principalEmail}" -ErrorAction SilentlyContinue
    if (-not $Principal) {
        $Principal = Get-AzADGroup -DisplayName "${principalEmail}" -ErrorAction SilentlyContinue
    }
    if (-not $Principal) {
        throw "Principal not found: ${principalEmail}"
    }
    
    $Assignment = New-AzRoleAssignment -ObjectId $Principal.Id -RoleDefinitionName "${roleName}" -Scope $Scope
    
    Write-Host "✓ Role assigned successfully" -ForegroundColor Green
    
    Write-Host \"\`nAssignment Details:" -ForegroundColor Cyan
    Write-Host "  Principal: ${principalEmail}"
    Write-Host "  Role: ${roleName}"
    Write-Host "  Scope: $Scope"
    
} catch {
    Write-Error "Failed to assign role: $_"
}`;
    }
  },

  {
    id: 'azure-export-rbac-assignments',
    title: 'Export RBAC Assignments',
    description: 'Export all RBAC role assignments to CSV',
    category: 'Identity & Access (RBAC)',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\RBACAssignments.csv',
        helpText: 'Path where the CSV will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Azure RBAC Assignments
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting RBAC assignments..." -ForegroundColor Cyan
    
    $Assignments = Get-AzRoleAssignment
    
    Write-Host "Found $($Assignments.Count) assignments" -ForegroundColor Yellow
    
    $Report = $Assignments | ForEach-Object {
        [PSCustomObject]@{
            DisplayName = $_.DisplayName
            SignInName  = $_.SignInName
            RoleDefinitionName = $_.RoleDefinitionName
            Scope       = $_.Scope
            ObjectType  = $_.ObjectType
            ObjectId    = $_.ObjectId
        }
    }
    
    $Report | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ RBAC assignments exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host \"\`nAssignments by Role:" -ForegroundColor Yellow
    $Report | Group-Object RoleDefinitionName | Sort-Object Count -Descending | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export RBAC assignments: $_"
}`;
    }
  },

  // ==================== Cost Management ====================
  {
    id: 'azure-cost-report',
    title: 'Export Cost Data',
    description: 'Generate a cost report for Azure resources',
    category: 'Cost Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AzureCosts.csv',
        helpText: 'Path where the CSV will be saved'
      },
      {
        name: 'timeframe',
        label: 'Timeframe',
        type: 'select',
        required: true,
        options: [
          { value: 'MonthToDate', label: 'Month to Date' },
          { value: 'TheLastMonth', label: 'Last Month' }
        ],
        defaultValue: 'MonthToDate',
        helpText: 'Time period for cost data'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const timeframe = params.timeframe || 'MonthToDate';

      return `# Export Azure Cost Data
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting cost data for: ${timeframe}" -ForegroundColor Cyan
    
    $CostData = Get-AzConsumptionUsageDetail -Timeframe ${timeframe}
    
    Write-Host "Found $($CostData.Count) usage records" -ForegroundColor Yellow
    
    $CostsByRG = $CostData | Group-Object -Property InstanceLocation | ForEach-Object {
        $TotalCost = ($_.Group | Measure-Object -Property PretaxCost -Sum).Sum
        
        [PSCustomObject]@{
            ResourceGroup = $_.Name
            TotalCost     = [math]::Round($TotalCost, 2)
            Currency      = $_.Group[0].Currency
            RecordCount   = $_.Count
        }
    } | Sort-Object TotalCost -Descending
    
    $CostsByRG | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Cost data exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host \"\`nTop 10 Resource Groups by Cost:" -ForegroundColor Yellow
    $CostsByRG | Select-Object -First 10 | Format-Table ResourceGroup, TotalCost, Currency
    
    $GrandTotal = ($CostsByRG | Measure-Object -Property TotalCost -Sum).Sum
    Write-Host \"\`nGrand Total: $([math]::Round($GrandTotal, 2))" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export cost data: $_"
}`;
    }
  },

  // ==================== Policy & Governance ====================
  {
    id: 'azure-assign-policy',
    title: 'Assign Azure Policy',
    description: 'Assign a built-in Azure Policy to a resource group or subscription',
    category: 'Policy & Governance',
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'select',
        required: true,
        options: [
          { value: 'Allowed locations', label: 'Allowed locations' },
          { value: 'Require a tag on resources', label: 'Require a tag on resources' },
          { value: 'Allowed virtual machine size SKUs', label: 'Allowed virtual machine size SKUs' }
        ],
        helpText: 'Built-in policy to assign'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group (leave empty for subscription scope)',
        type: 'text',
        required: false,
        placeholder: 'rg-production',
        helpText: 'Optional: specific resource group scope'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const rgName = params.resourceGroupName ? escapePowerShellString(params.resourceGroupName) : '';

      return `# Assign Azure Policy
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Assigning Policy: ${policyName}" -ForegroundColor Cyan
    
    $PolicyDefinition = Get-AzPolicyDefinition | Where-Object { $_.Properties.DisplayName -eq "${policyName}" }
    
    if (-not $PolicyDefinition) {
        throw "Policy definition not found: ${policyName}"
    }
    
    ${rgName ? `
    $RG = Get-AzResourceGroup -Name "${rgName}"
    $Scope = $RG.ResourceId
    ` : `
    $Scope = "/subscriptions/$((Get-AzContext).Subscription.Id)"
    `}
    
    $Assignment = New-AzPolicyAssignment -Name "${policyName}-assignment" -PolicyDefinition $PolicyDefinition -Scope $Scope
    
    Write-Host "✓ Policy assigned successfully" -ForegroundColor Green
    
    Write-Host \"\`nPolicy Assignment Details:" -ForegroundColor Cyan
    Write-Host "  Policy: ${policyName}"
    Write-Host "  Scope: $Scope"
    Write-Host "  Assignment ID: $($Assignment.ResourceId)"
    
} catch {
    Write-Error "Failed to assign policy: $_"
}`;
    }
  },

  // ==================== Monitoring ====================
  {
    id: 'azure-enable-diagnostics',
    title: 'Enable Diagnostic Settings',
    description: 'Enable diagnostic settings on Azure resources',
    category: 'Monitoring & Logging',
    parameters: [
      {
        name: 'resourceId',
        label: 'Resource ID',
        type: 'text',
        required: true,
        placeholder: '/subscriptions/.../resourceGroups/.../providers/...',
        helpText: 'Full Azure resource ID'
      },
      {
        name: 'workspaceName',
        label: 'Log Analytics Workspace Name',
        type: 'text',
        required: true,
        placeholder: 'law-production',
        helpText: 'Log Analytics workspace name'
      },
      {
        name: 'workspaceResourceGroup',
        label: 'Workspace Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-monitoring',
        helpText: 'Resource group containing the workspace'
      }
    ],
    scriptTemplate: (params) => {
      const resourceId = escapePowerShellString(params.resourceId);
      const workspaceName = escapePowerShellString(params.workspaceName);
      const workspaceRG = escapePowerShellString(params.workspaceResourceGroup);

      return `# Enable Diagnostic Settings
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Enabling diagnostic settings..." -ForegroundColor Cyan
    
    $Workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName "${workspaceRG}" -Name "${workspaceName}"
    
    if (-not $Workspace) {
        throw "Log Analytics workspace not found: ${workspaceName}"
    }
    
    $Metrics = @()
    $Logs = @()
    
    $Categories = Get-AzDiagnosticSettingCategory -ResourceId "${resourceId}"
    
    foreach ($Category in $Categories) {
        if ($Category.CategoryType -eq "Logs") {
            $Logs += New-AzDiagnosticSettingLogSettingsObject -Enabled $true -Category $Category.Name
        }
        if ($Category.CategoryType -eq "Metrics") {
            $Metrics += New-AzDiagnosticSettingMetricSettingsObject -Enabled $true -Category $Category.Name
        }
    }
    
    New-AzDiagnosticSetting -Name "PSForge-Diagnostics" -ResourceId "${resourceId}" -WorkspaceId $Workspace.ResourceId -Log $Logs -Metric $Metrics
    
    Write-Host "✓ Diagnostic settings enabled successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to enable diagnostic settings: $_"
}`;
    }
  },

  // ==================== Additional Resource Management ====================
  {
    id: 'azure-apply-resource-lock',
    title: 'Apply Resource Lock',
    description: 'Apply CanNotDelete or ReadOnly lock to prevent accidental changes',
    category: 'Resource Management',
    parameters: [
      {
        name: 'resourceGroupName',
        label: 'Resource Group Name',
        type: 'text',
        required: true,
        placeholder: 'rg-production',
        helpText: 'Resource group to lock'
      },
      {
        name: 'lockType',
        label: 'Lock Type',
        type: 'select',
        required: true,
        options: [
          { value: 'CanNotDelete', label: 'Cannot Delete' },
          { value: 'ReadOnly', label: 'Read Only' }
        ],
        helpText: 'Type of resource lock'
      },
      {
        name: 'lockName',
        label: 'Lock Name',
        type: 'text',
        required: true,
        placeholder: 'production-lock',
        helpText: 'Name for the lock'
      }
    ],
    scriptTemplate: (params) => {
      const rgName = escapePowerShellString(params.resourceGroupName);
      const lockType = params.lockType;
      const lockName = escapePowerShellString(params.lockName);

      return `# Apply Resource Lock
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Applying ${lockType} lock to: ${rgName}" -ForegroundColor Cyan
    
    New-AzResourceLock -LockLevel ${lockType} -LockName "${lockName}" -ResourceGroupName "${rgName}" -Force
    
    Write-Host "✓ Lock applied successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to apply resource lock: $_"
}`;
    }
  },

  {
    id: 'azure-move-resources',
    title: 'Move Resources Between Resource Groups',
    description: 'Move Azure resources from one resource group to another',
    category: 'Resource Management',
    parameters: [
      {
        name: 'sourceResourceGroup',
        label: 'Source Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-source',
        helpText: 'Source resource group'
      },
      {
        name: 'targetResourceGroup',
        label: 'Target Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-target',
        helpText: 'Destination resource group'
      },
      {
        name: 'resourceNames',
        label: 'Resource Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'vm-web01\nstorage-account01',
        helpText: 'Names of resources to move'
      }
    ],
    scriptTemplate: (params) => {
      const sourceRG = escapePowerShellString(params.sourceResourceGroup);
      const targetRG = escapePowerShellString(params.targetResourceGroup);
      const resourceNames = params.resourceNames.split('\\n').filter((line: string) => line.trim()).map((name: string) => `"${escapePowerShellString(name.trim())}"`).join(', ');

      return `# Move Azure Resources
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Moving resources from ${sourceRG} to ${targetRG}" -ForegroundColor Cyan
    
    $ResourceNames = @(${resourceNames})
    $ResourcesToMove = @()
    
    foreach ($Name in $ResourceNames) {
        $Resource = Get-AzResource -ResourceGroupName "${sourceRG}" -Name $Name
        if ($Resource) {
            $ResourcesToMove += $Resource.ResourceId
        } else {
            Write-Warning "Resource not found: $Name"
        }
    }
    
    if ($ResourcesToMove.Count -gt 0) {
        Write-Host "Moving $($ResourcesToMove.Count) resources..." -ForegroundColor Yellow
        Move-AzResource -DestinationResourceGroupName "${targetRG}" -ResourceId $ResourcesToMove -Force
        Write-Host "✓ Resources moved successfully" -ForegroundColor Green
    }
    
} catch {
    Write-Error "Failed to move resources: $_"
}`;
    }
  },

  // ==================== Additional Networking ====================
  {
    id: 'azure-create-vpn-gateway',
    title: 'Create VPN Gateway',
    description: 'Create a site-to-site VPN gateway for hybrid connectivity',
    category: 'Networking',
    parameters: [
      {
        name: 'gatewayName',
        label: 'Gateway Name',
        type: 'text',
        required: true,
        placeholder: 'vpn-gateway',
        helpText: 'Name for the VPN gateway'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-network',
        helpText: 'Resource group for the gateway'
      },
      {
        name: 'vnetName',
        label: 'Virtual Network Name',
        type: 'text',
        required: true,
        placeholder: 'vnet-production',
        helpText: 'Virtual network containing the gateway subnet'
      }
    ],
    scriptTemplate: (params) => {
      const gatewayName = escapePowerShellString(params.gatewayName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const vnetName = escapePowerShellString(params.vnetName);

      return `# Create VPN Gateway
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating VPN Gateway: ${gatewayName}" -ForegroundColor Cyan
    
    $VNet = Get-AzVirtualNetwork -Name "${vnetName}" -ResourceGroupName "${rgName}"
    $GatewaySubnet = Get-AzVirtualNetworkSubnetConfig -Name "GatewaySubnet" -VirtualNetwork $VNet
    
    $PIP = New-AzPublicIpAddress -Name "${gatewayName}-pip" -ResourceGroupName "${rgName}" -Location $VNet.Location -AllocationMethod Dynamic
    
    $IPConfig = New-AzVirtualNetworkGatewayIpConfig -Name "GatewayConfig" -SubnetId $GatewaySubnet.Id -PublicIpAddressId $PIP.Id
    
    New-AzVirtualNetworkGateway -Name "${gatewayName}" -ResourceGroupName "${rgName}" -Location $VNet.Location -IpConfigurations $IPConfig -GatewayType Vpn -VpnType RouteBased -GatewaySku VpnGw1
    
    Write-Host "✓ VPN Gateway created (this may take 30-45 minutes)" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to create VPN gateway: $_"
}`;
    }
  },

  {
    id: 'azure-configure-dns-zone',
    title: 'Create DNS Zone with Records',
    description: 'Create an Azure DNS zone and add DNS records',
    category: 'Networking',
    parameters: [
      {
        name: 'zoneName',
        label: 'DNS Zone Name',
        type: 'text',
        required: true,
        placeholder: 'contoso.com',
        helpText: 'DNS zone domain name'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-dns',
        helpText: 'Resource group for DNS zone'
      }
    ],
    scriptTemplate: (params) => {
      const zoneName = escapePowerShellString(params.zoneName);
      const rgName = escapePowerShellString(params.resourceGroupName);

      return `# Create DNS Zone
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating DNS zone: ${zoneName}" -ForegroundColor Cyan
    
    $Zone = New-AzDnsZone -Name "${zoneName}" -ResourceGroupName "${rgName}"
    
    Write-Host "✓ DNS zone created" -ForegroundColor Green
    Write-Host ${'\`n'}"Name servers for ${zoneName}:" -ForegroundColor Yellow
    $Zone.NameServers | ForEach-Object { Write-Host "  $_" }
    
} catch {
    Write-Error "Failed to create DNS zone: $_"
}`;
    }
  },

  // ==================== Additional Cost Management ====================
  {
    id: 'azure-create-budget',
    title: 'Create Cost Budget with Alert',
    description: 'Set up cost budget with email alerts for Azure resources',
    category: 'Cost Management',
    parameters: [
      {
        name: 'budgetName',
        label: 'Budget Name',
        type: 'text',
        required: true,
        placeholder: 'monthly-budget',
        helpText: 'Name for the budget'
      },
      {
        name: 'amount',
        label: 'Budget Amount (USD)',
        type: 'number',
        required: true,
        defaultValue: 1000,
        helpText: 'Monthly budget amount'
      },
      {
        name: 'alertEmail',
        label: 'Alert Email Address',
        type: 'text',
        required: true,
        placeholder: 'admin@contoso.com',
        helpText: 'Email for budget alerts'
      }
    ],
    scriptTemplate: (params) => {
      const budgetName = escapePowerShellString(params.budgetName);
      const amount = params.amount || 1000;
      const email = escapePowerShellString(params.alertEmail);

      return `# Create Cost Budget
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating budget: ${budgetName}" -ForegroundColor Cyan
    
    $Context = Get-AzContext
    $SubscriptionId = $Context.Subscription.Id
    
    $StartDate = (Get-Date).ToString("yyyy-MM-01")
    $EndDate = (Get-Date).AddYears(10).ToString("yyyy-MM-01")
    
    $NotificationContact = @("${email}")
    
    $BudgetParams = @{
        Name = "${budgetName}"
        Amount = ${amount}
        Category = "Cost"
        TimeGrain = "Monthly"
        StartDate = $StartDate
        EndDate = $EndDate
        Notification = @{
            "Alert80" = @{
                Enabled = $true
                Operator = "GreaterThan"
                Threshold = 80
                ContactEmails = $NotificationContact
            }
            "Alert100" = @{
                Enabled = $true
                Operator = "GreaterThan"
                Threshold = 100
                ContactEmails = $NotificationContact
            }
        }
    }
    
    New-AzConsumptionBudget @BudgetParams
    
    Write-Host "✓ Budget created with alerts at 80% and 100%" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to create budget: $_"
}`;
    }
  },

  {
    id: 'azure-export-cost-analysis',
    title: 'Export Cost Analysis Report',
    description: 'Generate detailed cost analysis report for current month',
    category: 'Cost Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AzureCosts.csv',
        helpText: 'Path for the cost report CSV'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Cost Analysis
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting cost data..." -ForegroundColor Cyan
    
    $StartDate = (Get-Date).AddMonths(-1).ToString("yyyy-MM-dd")
    $EndDate = (Get-Date).ToString("yyyy-MM-dd")
    
    $Usage = Get-AzConsumptionUsageDetail -StartDate $StartDate -EndDate $EndDate
    
    $CostReport = $Usage | Select-Object -Property @{
        Name = "Date"
        Expression = { $_.UsageStart }
    }, @{
        Name = "ResourceGroup"
        Expression = { $_.InstanceName.Split('/')[4] }
    }, @{
        Name = "ResourceName"
        Expression = { $_.InstanceName.Split('/')[-1] }
    }, @{
        Name = "ResourceType"
        Expression = { $_.ConsumedService }
    }, @{
        Name = "Cost"
        Expression = { $_.PretaxCost }
    }, Currency
    
    $CostReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    $TotalCost = ($CostReport | Measure-Object -Property Cost -Sum).Sum
    Write-Host "✓ Cost report exported: ${exportPath}" -ForegroundColor Green
    Write-Host "Total cost: \$" -NoNewline -ForegroundColor Yellow
    Write-Host ([math]::Round($TotalCost, 2))
    
} catch {
    Write-Error "Failed to export cost analysis: $_"
}`;
    }
  },

  // ==================== Additional Policy & Governance ====================
  {
    id: 'azure-set-policy',
    title: 'Assign Azure Policy',
    description: 'Assign a built-in or custom policy to resource group or subscription',
    category: 'Policy & Governance',
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'text',
        required: true,
        placeholder: 'Require tag on resources',
        helpText: 'Display name of the policy'
      },
      {
        name: 'scope',
        label: 'Scope (subscription or resource group)',
        type: 'text',
        required: true,
        placeholder: '/subscriptions/{id} or rg-production',
        helpText: 'Assignment scope'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const scope = escapePowerShellString(params.scope);

      return `# Assign Azure Policy
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Assigning policy: ${policyName}" -ForegroundColor Cyan
    
    $PolicyDef = Get-AzPolicyDefinition | Where-Object { $_.Properties.DisplayName -eq "${policyName}" }
    
    if (-not $PolicyDef) {
        throw "Policy definition not found: ${policyName}"
    }
    
    if ("${scope}".StartsWith("/subscriptions")) {
        $ScopeId = "${scope}"
    } else {
        $RG = Get-AzResourceGroup -Name "${scope}"
        $ScopeId = $RG.ResourceId
    }
    
    New-AzPolicyAssignment -Name "PSForge-$($PolicyDef.Name)" -PolicyDefinition $PolicyDef -Scope $ScopeId
    
    Write-Host "✓ Policy assigned successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to assign policy: $_"
}`;
    }
  },

  {
    id: 'azure-audit-compliance',
    title: 'Audit Policy Compliance',
    description: 'Generate compliance report for assigned Azure policies',
    category: 'Policy & Governance',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\PolicyCompliance.csv',
        helpText: 'Path for the compliance report'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Audit Policy Compliance
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting compliance data..." -ForegroundColor Cyan
    
    $PolicyStates = Get-AzPolicyState
    
    $ComplianceReport = $PolicyStates | Select-Object -Property @{
        Name = "ResourceId"
        Expression = { $_.ResourceId }
    }, @{
        Name = "PolicyDefinitionName"
        Expression = { $_.PolicyDefinitionName }
    }, @{
        Name = "ComplianceState"
        Expression = { $_.ComplianceState }
    }, @{
        Name = "ResourceType"
        Expression = { $_.ResourceType }
    }, @{
        Name = "ResourceGroup"
        Expression = { $_.ResourceGroup }
    }
    
    $ComplianceReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    $Summary = $ComplianceReport | Group-Object ComplianceState | Select-Object Name, Count
    
    Write-Host "✓ Compliance report exported" -ForegroundColor Green
    Write-Host ${'\`n'}"Compliance Summary:" -ForegroundColor Yellow
    $Summary | Format-Table -AutoSize
    
} catch {
    Write-Error "Failed to audit compliance: $_"
}`;
    }
  },

  // ==================== Additional Storage ====================
  {
    id: 'azure-configure-blob-lifecycle',
    title: 'Configure Blob Lifecycle Management',
    description: 'Set up automated blob tier transitions and deletion policies',
    category: 'Storage',
    parameters: [
      {
        name: 'storageAccountName',
        label: 'Storage Account Name',
        type: 'text',
        required: true,
        placeholder: 'storageaccount01',
        helpText: 'Storage account name'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-storage',
        helpText: 'Resource group containing the storage account'
      },
      {
        name: 'daysToArchive',
        label: 'Days Before Archive',
        type: 'number',
        required: true,
        defaultValue: 90,
        helpText: 'Days before moving to archive tier'
      }
    ],
    scriptTemplate: (params) => {
      const storageAccount = escapePowerShellString(params.storageAccountName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const archiveDays = params.daysToArchive || 90;

      return `# Configure Blob Lifecycle
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Configuring lifecycle management for: ${storageAccount}" -ForegroundColor Cyan
    
    $Action = Add-AzStorageAccountManagementPolicyAction -BaseBlobAction TierToArchive -daysAfterModificationGreaterThan ${archiveDays}
    $Action = Add-AzStorageAccountManagementPolicyAction -InputObject $Action -BaseBlobAction Delete -daysAfterModificationGreaterThan 365
    
    $Filter = New-AzStorageAccountManagementPolicyFilter -PrefixMatch "logs/"
    
    $Rule = New-AzStorageAccountManagementPolicyRule -Name "ArchiveAndDelete" -Action $Action -Filter $Filter
    
    Set-AzStorageAccountManagementPolicy -ResourceGroupName "${rgName}" -AccountName "${storageAccount}" -Rule $Rule
    
    Write-Host "✓ Lifecycle policy configured" -ForegroundColor Green
    Write-Host "  - Archive after ${archiveDays} days" -ForegroundColor Yellow
    Write-Host "  - Delete after 365 days" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to configure lifecycle policy: $_"
}`;
    }
  },

  {
    id: 'azure-backup-storage-account',
    title: 'Configure Storage Account Backup',
    description: 'Enable blob versioning and soft delete for data protection',
    category: 'Storage',
    parameters: [
      {
        name: 'storageAccountName',
        label: 'Storage Account Name',
        type: 'text',
        required: true,
        placeholder: 'storageaccount01',
        helpText: 'Storage account to protect'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-storage',
        helpText: 'Resource group name'
      },
      {
        name: 'retentionDays',
        label: 'Soft Delete Retention (days)',
        type: 'number',
        required: true,
        defaultValue: 30,
        helpText: 'Days to retain deleted blobs'
      }
    ],
    scriptTemplate: (params) => {
      const storageAccount = escapePowerShellString(params.storageAccountName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const retentionDays = params.retentionDays || 30;

      return `# Configure Storage Backup
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Configuring backup for: ${storageAccount}" -ForegroundColor Cyan
    
    Enable-AzStorageBlobDeleteRetentionPolicy -ResourceGroupName "${rgName}" -StorageAccountName "${storageAccount}" -RetentionDays ${retentionDays}
    
    Enable-AzStorageBlobVersioning -ResourceGroupName "${rgName}" -StorageAccountName "${storageAccount}"
    
    Update-AzStorageBlobServiceProperty -ResourceGroupName "${rgName}" -StorageAccountName "${storageAccount}" -IsVersioningEnabled \$true -EnableChangeFeed \$true
    
    Write-Host "✓ Backup features configured:" -ForegroundColor Green
    Write-Host "  - Soft delete: ${retentionDays} days" -ForegroundColor Yellow
    Write-Host "  - Versioning: Enabled" -ForegroundColor Yellow
    Write-Host "  - Change feed: Enabled" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to configure backup: $_"
}`;
    }
  },

  // ==================== Additional Virtual Machines ====================
  {
    id: 'azure-change-vm-size',
    title: 'Resize Virtual Machine',
    description: 'Change VM size to scale compute resources',
    category: 'Virtual Machines',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'vm-web01',
        helpText: 'Virtual machine to resize'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-vms',
        helpText: 'Resource group containing the VM'
      },
      {
        name: 'newSize',
        label: 'New VM Size',
        type: 'select',
        required: true,
        options: [
          { value: 'Standard_B2s', label: 'Standard_B2s (2 vCPU, 4 GB RAM)' },
          { value: 'Standard_D2s_v3', label: 'Standard_D2s_v3 (2 vCPU, 8 GB RAM)' },
          { value: 'Standard_D4s_v3', label: 'Standard_D4s_v3 (4 vCPU, 16 GB RAM)' },
          { value: 'Standard_D8s_v3', label: 'Standard_D8s_v3 (8 vCPU, 32 GB RAM)' }
        ],
        helpText: 'Target VM size'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const newSize = params.newSize;

      return `# Resize Virtual Machine
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Resizing VM: ${vmName} to ${newSize}" -ForegroundColor Cyan
    
    $VM = Get-AzVM -ResourceGroupName "${rgName}" -Name "${vmName}"
    $CurrentSize = $VM.HardwareProfile.VmSize
    
    Write-Host "Current size: $CurrentSize" -ForegroundColor Yellow
    
    if ($CurrentSize -eq "${newSize}") {
        Write-Host "VM is already the target size" -ForegroundColor Yellow
        exit
    }
    
    $VM.HardwareProfile.VmSize = "${newSize}"
    
    Write-Host "Stopping VM..." -ForegroundColor Cyan
    Stop-AzVM -ResourceGroupName "${rgName}" -Name "${vmName}" -Force
    
    Write-Host "Resizing VM..." -ForegroundColor Cyan
    Update-AzVM -ResourceGroupName "${rgName}" -VM $VM
    
    Write-Host "Starting VM..." -ForegroundColor Cyan
    Start-AzVM -ResourceGroupName "${rgName}" -Name "${vmName}"
    
    Write-Host "✓ VM resized successfully to ${newSize}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to resize VM: $_"
}`;
    }
  },

  {
    id: 'azure-attach-managed-disk',
    title: 'Attach Managed Disk to VM',
    description: 'Attach an existing or new managed disk to a virtual machine',
    category: 'Virtual Machines',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'vm-web01',
        helpText: 'Target virtual machine'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-vms',
        helpText: 'Resource group name'
      },
      {
        name: 'diskName',
        label: 'Disk Name',
        type: 'text',
        required: true,
        placeholder: 'data-disk-01',
        helpText: 'Name for the managed disk'
      },
      {
        name: 'diskSizeGB',
        label: 'Disk Size (GB)',
        type: 'number',
        required: true,
        defaultValue: 128,
        helpText: 'Size of the disk in GB'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const diskName = escapePowerShellString(params.diskName);
      const diskSizeGB = params.diskSizeGB || 128;

      return `# Attach Managed Disk
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Attaching disk to VM: ${vmName}" -ForegroundColor Cyan
    
    $VM = Get-AzVM -ResourceGroupName "${rgName}" -Name "${vmName}"
    
    $DiskConfig = New-AzDiskConfig -Location $VM.Location -CreateOption Empty -DiskSizeGB ${diskSizeGB} -SkuName Premium_LRS
    
    $Disk = New-AzDisk -ResourceGroupName "${rgName}" -DiskName "${diskName}" -Disk $DiskConfig
    
    $VM = Add-AzVMDataDisk -VM $VM -Name "${diskName}" -CreateOption Attach -ManagedDiskId $Disk.Id -Lun ($VM.StorageProfile.DataDisks.Count)
    
    Update-AzVM -ResourceGroupName "${rgName}" -VM $VM
    
    Write-Host "✓ Disk attached successfully" -ForegroundColor Green
    Write-Host "  Disk: ${diskName} (${diskSizeGB} GB)" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to attach disk: $_"
}`;
    }
  },

  // ==================== Additional Identity & Access ====================
  {
    id: 'azure-assign-rbac-multiple',
    title: 'Bulk Assign RBAC Roles',
    description: 'Assign RBAC roles to multiple users from CSV',
    category: 'Identity & Access (RBAC)',
    parameters: [
      {
        name: 'csvPath',
        label: 'CSV File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Assignments\\rbac.csv',
        helpText: 'CSV with columns: Email, Role, Scope'
      }
    ],
    scriptTemplate: (params) => {
      const csvPath = escapePowerShellString(params.csvPath);

      return `# Bulk Assign RBAC Roles
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Processing RBAC assignments from CSV..." -ForegroundColor Cyan
    
    $Assignments = Import-Csv -Path "${csvPath}"
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($Assignment in $Assignments) {
        try {
            $User = Get-AzADUser -UserPrincipalName $Assignment.Email
            
            if (-not $User) {
                Write-Warning "User not found: $($Assignment.Email)"
                $FailCount++
                continue
            }
            
            New-AzRoleAssignment -ObjectId $User.Id -RoleDefinitionName $Assignment.Role -Scope $Assignment.Scope -ErrorAction Stop
            
            Write-Host "✓ $($Assignment.Email): $($Assignment.Role)" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed: $($Assignment.Email) - $_"
            $FailCount++
        }
    }
    
    Write-Host ${'\`n'}"Assignments Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to process RBAC assignments: $_"
}`;
    }
  },

  {
    id: 'azure-audit-rbac-assignments',
    title: 'Audit All RBAC Assignments',
    description: 'Export comprehensive report of all role assignments',
    category: 'Identity & Access (RBAC)',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\RBACAssignments.csv',
        helpText: 'Path for the RBAC report'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Audit RBAC Assignments
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Collecting RBAC assignments..." -ForegroundColor Cyan
    
    $Assignments = Get-AzRoleAssignment
    
    $Report = $Assignments | Select-Object -Property @{
        Name = "DisplayName"
        Expression = { $_.DisplayName }
    }, @{
        Name = "SignInName"
        Expression = { $_.SignInName }
    }, @{
        Name = "RoleDefinitionName"
        Expression = { $_.RoleDefinitionName }
    }, @{
        Name = "Scope"
        Expression = { $_.Scope }
    }, @{
        Name = "ObjectType"
        Expression = { $_.ObjectType }
    }
    
    $Report | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ RBAC audit exported: ${exportPath}" -ForegroundColor Green
    Write-Host ${'\`n'}"Total assignments: $($Report.Count)" -ForegroundColor Yellow
    
    $RoleSummary = $Report | Group-Object RoleDefinitionName | Sort-Object Count -Descending | Select-Object -First 5
    Write-Host ${'\`n'}"Top 5 Roles:" -ForegroundColor Yellow
    $RoleSummary | Format-Table Name, Count -AutoSize
    
} catch {
    Write-Error "Failed to audit RBAC: $_"
}`;
    }
  },

  // ==================== Additional Monitoring ====================
  {
    id: 'azure-create-action-group',
    title: 'Create Action Group for Alerts',
    description: 'Set up email and SMS notifications for Azure alerts',
    category: 'Monitoring & Logging',
    parameters: [
      {
        name: 'actionGroupName',
        label: 'Action Group Name',
        type: 'text',
        required: true,
        placeholder: 'IT-Alerts',
        helpText: 'Name for the action group'
      },
      {
        name: 'resourceGroupName',
        label: 'Resource Group',
        type: 'text',
        required: true,
        placeholder: 'rg-monitoring',
        helpText: 'Resource group for action group'
      },
      {
        name: 'emailAddress',
        label: 'Email Address',
        type: 'text',
        required: true,
        placeholder: 'alerts@contoso.com',
        helpText: 'Email for notifications'
      }
    ],
    scriptTemplate: (params) => {
      const actionGroupName = escapePowerShellString(params.actionGroupName);
      const rgName = escapePowerShellString(params.resourceGroupName);
      const email = escapePowerShellString(params.emailAddress);

      return `# Create Action Group
# Generated by PSForge

Connect-AzAccount

try {
    Write-Host "Creating action group: ${actionGroupName}" -ForegroundColor Cyan
    
    $EmailReceiver = New-AzActionGroupReceiver -Name "EmailAdmin" -EmailReceiver -EmailAddress "${email}"
    
    Set-AzActionGroup -ResourceGroupName "${rgName}" -Name "${actionGroupName}" -ShortName "ITAlerts" -Receiver $EmailReceiver
    
    Write-Host "✓ Action group created successfully" -ForegroundColor Green
    Write-Host "  Email notifications: ${email}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to create action group: $_"
}`;
    }
  }
];

export const azureResourceCategories = [
  'Resource Management',
  'Virtual Machines',
  'Networking',
  'Storage',
  'Identity & Access (RBAC)',
  'Cost Management',
  'Policy & Governance',
  'Monitoring & Logging'
];
