import { escapePowerShellString } from './powershell-utils';

export interface AzureAdTaskParameter {
  id: string;
  label: string;
  type: 'text' | 'email' | 'path' | 'number' | 'boolean' | 'select' | 'textarea';
  placeholder?: string;
  required: boolean;
  description?: string;
  options?: string[];
  defaultValue?: any;
}

export interface AzureAdTask {
  id: string;
  name: string;
  category: string;
  description: string;
  parameters: AzureAdTaskParameter[];
  validate?: (params: Record<string, any>) => string | null;
  scriptTemplate: (params: Record<string, any>) => string;
}

export const azureAdTasks: AzureAdTask[] = [
  // ========================================
  // User Lifecycle Management (7 tasks)
  // ========================================
  {
    id: 'create-azure-ad-user',
    name: 'Create New User Account',
    category: 'User Lifecycle',
    description: 'Create a new Azure AD user with license assignment and password settings',
    parameters: [
      { id: 'upn', label: 'User Principal Name', type: 'text', required: true, placeholder: 'john.doe@contoso.com' },
      { id: 'displayName', label: 'Display Name', type: 'text', required: true, placeholder: 'John Doe' },
      { id: 'usageLocation', label: 'Usage Location', type: 'text', required: true, placeholder: 'US', description: '2-letter country code' },
      { id: 'licenseSku', label: 'License SKU', type: 'text', required: false, placeholder: 'ENTERPRISEPACK', description: 'Optional: SKU part number for license assignment' },
      { id: 'password', label: 'Password', type: 'text', required: true, placeholder: 'P@ssw0rd123!', description: 'Strong password meeting Azure AD requirements' },
      { id: 'forcePasswordChange', label: 'Force Password Change at Next Sign-In', type: 'boolean', required: false, defaultValue: true },
      { id: 'jobTitle', label: 'Job Title', type: 'text', required: false, placeholder: 'Sales Manager' },
      { id: 'department', label: 'Department', type: 'text', required: false, placeholder: 'Sales' }
    ],
    scriptTemplate: (params) => {
      const upn = escapePowerShellString(params.upn);
      const displayName = escapePowerShellString(params.displayName);
      const usageLocation = escapePowerShellString(params.usageLocation);
      const licenseSku = params.licenseSku ? escapePowerShellString(params.licenseSku) : null;
      const password = escapePowerShellString(params.password);
      const forcePasswordChange = params.forcePasswordChange === 'true' || params.forcePasswordChange === true;
      const jobTitle = params.jobTitle ? escapePowerShellString(params.jobTitle) : null;
      const department = params.department ? escapePowerShellString(params.department) : null;

      return `# Create New Azure AD User
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.ReadWrite.All", "Directory.ReadWrite.All"

# Define user parameters
$UPN = "${upn}"
$DisplayName = "${displayName}"
$UsageLocation = "${usageLocation}"
$Password = "${password}"
$ForcePasswordChange = $${forcePasswordChange}
${licenseSku ? `$LicenseSku = "${licenseSku}"` : '# No license specified'}
${jobTitle ? `$JobTitle = "${jobTitle}"` : ''}
${department ? `$Department = "${department}"` : ''}

try {
    Write-Host "Creating user: $DisplayName ($UPN)" -ForegroundColor Cyan
    
    # Create password profile
    $PasswordProfile = @{
        Password = $Password
        ForceChangePasswordNextSignIn = $ForcePasswordChange
    }
    
    # Build user parameters
    $UserParams = @{
        UserPrincipalName = $UPN
        DisplayName = $DisplayName
        MailNickname = $UPN.Split('@')[0]
        AccountEnabled = $true
        PasswordProfile = $PasswordProfile
        UsageLocation = $UsageLocation
    }
    
    ${jobTitle ? `$UserParams.JobTitle = $JobTitle` : ''}
    ${department ? `$UserParams.Department = $Department` : ''}
    
    # Create the user
    $User = New-MgUser @UserParams
    Write-Host "✓ User created successfully!" -ForegroundColor Green
    Write-Host "  User ID: $($User.Id)" -ForegroundColor Gray
    
    ${licenseSku ? `
    # Assign license if specified
    if ($LicenseSku) {
        Write-Host "Assigning license: $LicenseSku" -ForegroundColor Cyan
        
        # Resolve SKU name to GUID
        $Sku = Get-MgSubscribedSku -All | Where-Object { $_.SkuPartNumber -eq $LicenseSku }
        if (-not $Sku) {
            Write-Error "License SKU not found: $LicenseSku. Run 'Get-MgSubscribedSku | Select SkuPartNumber, SkuId' to see available SKUs"
        } else {
            Set-MgUserLicense -UserId $User.Id -AddLicenses @{SkuId = $Sku.SkuId} -RemoveLicenses @()
            Write-Host "✓ License assigned: $LicenseSku" -ForegroundColor Green
        }
    }
    ` : ''}
    
    Write-Host "
User creation completed!" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to create user: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'bulk-create-users',
    name: 'Bulk Create Users from CSV',
    category: 'User Lifecycle',
    description: 'Create multiple users from a CSV file with optional license assignment',
    parameters: [
      { id: 'csvPath', label: 'CSV File Path', type: 'path', required: true, placeholder: 'C:\\Scripts\\users.csv', description: 'CSV with UPN, DisplayName, UsageLocation, LicenseSku, Password, JobTitle, Department columns' },
      { id: 'forcePasswordChange', label: 'Force Password Change at Next Sign-In', type: 'boolean', required: false, defaultValue: true },
      { id: 'testMode', label: 'Test Mode (Preview Only)', type: 'boolean', required: false, defaultValue: true }
    ],
    scriptTemplate: (params) => {
      const csvPath = escapePowerShellString(params.csvPath);
      const forcePasswordChange = params.forcePasswordChange === 'true' || params.forcePasswordChange === true;
      const testMode = params.testMode === 'true' || params.testMode === true;

      return `# Bulk Create Azure AD Users from CSV
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.ReadWrite.All", "Directory.ReadWrite.All"

$CsvPath = "${csvPath}"
$ForcePasswordChange = $${forcePasswordChange}
$TestMode = $${testMode}

# Validation
if (-not (Test-Path $CsvPath)) {
    Write-Error "CSV file not found: $CsvPath"
    exit 1
}

try {
    # Import CSV
    $Users = Import-Csv -Path $CsvPath
    Write-Host "Loaded $($Users.Count) users from CSV" -ForegroundColor Cyan
    
    if ($TestMode) {
        Write-Host "
=== TEST MODE - No changes will be made ===" -ForegroundColor Yellow
    }
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($User in $Users) {
        try {
            Write-Host "
Processing: $($User.DisplayName) ($($User.UPN))" -ForegroundColor Cyan
            
            if ($TestMode) {
                Write-Host "  [TEST] Would create user with:" -ForegroundColor Gray
                Write-Host "    UPN: $($User.UPN)" -ForegroundColor Gray
                Write-Host "    Display Name: $($User.DisplayName)" -ForegroundColor Gray
                Write-Host "    Usage Location: $($User.UsageLocation)" -ForegroundColor Gray
                if ($User.LicenseSku) {
                    Write-Host "    License: $($User.LicenseSku)" -ForegroundColor Gray
                }
                $SuccessCount++
            } else {
                # Create password profile
                $PasswordProfile = @{
                    Password = $User.Password
                    ForceChangePasswordNextSignIn = $ForcePasswordChange
                }
                
                # Build user parameters
                $UserParams = @{
                    UserPrincipalName = $User.UPN
                    DisplayName = $User.DisplayName
                    MailNickname = $User.UPN.Split('@')[0]
                    AccountEnabled = $true
                    PasswordProfile = $PasswordProfile
                    UsageLocation = $User.UsageLocation
                }
                
                if ($User.JobTitle) { $UserParams.JobTitle = $User.JobTitle }
                if ($User.Department) { $UserParams.Department = $User.Department }
                
                # Create user
                $NewUser = New-MgUser @UserParams
                Write-Host "  ✓ User created" -ForegroundColor Green
                
                # Assign license if specified
                if ($User.LicenseSku) {
                    $Sku = Get-MgSubscribedSku -All | Where-Object { $_.SkuPartNumber -eq $User.LicenseSku }
                    if ($Sku) {
                        Set-MgUserLicense -UserId $NewUser.Id -AddLicenses @{SkuId = $Sku.SkuId} -RemoveLicenses @()
                        Write-Host "  ✓ License assigned: $($User.LicenseSku)" -ForegroundColor Green
                    } else {
                        Write-Host "  ⚠ SKU not found: $($User.LicenseSku)" -ForegroundColor Yellow
                    }
                }
                
                $SuccessCount++
            }
        } catch {
            Write-Host "  ✗ Failed: $_" -ForegroundColor Red
            $FailCount++
        }
    }
    
    # Summary
    Write-Host "
=== Bulk User Creation Summary ===" -ForegroundColor Cyan
    Write-Host "Total Users: $($Users.Count)" -ForegroundColor White
    Write-Host "Successful: $SuccessCount" -ForegroundColor Green
    Write-Host "Failed: $FailCount" -ForegroundColor Red
    
} catch {
    Write-Error "Bulk user creation failed: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'assign-remove-licenses',
    name: 'Assign or Remove User Licenses',
    category: 'User Lifecycle',
    description: 'Assign or remove licenses for a single user or multiple users',
    parameters: [
      { id: 'upn', label: 'User Principal Name', type: 'text', required: true, placeholder: 'john.doe@contoso.com' },
      { id: 'operation', label: 'Operation', type: 'select', required: true, options: ['Assign', 'Remove'], defaultValue: 'Assign' },
      { id: 'licenseSku', label: 'License SKU', type: 'text', required: true, placeholder: 'ENTERPRISEPACK', description: 'SKU part number (run Get-MgSubscribedSku to list)' },
      { id: 'usageLocation', label: 'Usage Location', type: 'text', required: false, placeholder: 'US', description: 'Required for license assignment (2-letter country code)' }
    ],
    scriptTemplate: (params) => {
      const upn = escapePowerShellString(params.upn);
      const operation = params.operation || 'Assign';
      const licenseSku = escapePowerShellString(params.licenseSku);
      const usageLocation = params.usageLocation ? escapePowerShellString(params.usageLocation) : null;

      return `# ${operation} Azure AD User License
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.ReadWrite.All", "Organization.Read.All"

$UPN = "${upn}"
$LicenseSku = "${licenseSku}"
$Operation = "${operation}"
${usageLocation ? `$UsageLocation = "${usageLocation}"` : ''}

try {
    Write-Host "${operation}ing license: $LicenseSku for user: $UPN" -ForegroundColor Cyan
    
    # Get user
    $User = Get-MgUser -UserId $UPN -ErrorAction Stop
    
    # Resolve SKU name to GUID
    $Sku = Get-MgSubscribedSku -All | Where-Object { $_.SkuPartNumber -eq $LicenseSku }
    if (-not $Sku) {
        Write-Error "License SKU not found: $LicenseSku. Run 'Get-MgSubscribedSku | Select SkuPartNumber, SkuId' to see available SKUs"
        exit 1
    }
    
    if ($Operation -eq "Assign") {
        ${usageLocation ? `
        # Set usage location if specified
        if ($UsageLocation) {
            Update-MgUser -UserId $UPN -UsageLocation $UsageLocation
            Write-Host "✓ Usage location set: $UsageLocation" -ForegroundColor Green
        }
        ` : ''}
        
        # Assign license
        Set-MgUserLicense -UserId $UPN -AddLicenses @{SkuId = $Sku.SkuId} -RemoveLicenses @()
        Write-Host "✓ License assigned successfully: $LicenseSku" -ForegroundColor Green
    } else {
        # Remove license
        Set-MgUserLicense -UserId $UPN -AddLicenses @() -RemoveLicenses @($Sku.SkuId)
        Write-Host "✓ License removed successfully: $LicenseSku" -ForegroundColor Green
    }
    
} catch {
    Write-Error "Failed to $($Operation.ToLower()) license: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'update-user-attributes',
    name: 'Update User Attributes',
    category: 'User Lifecycle',
    description: 'Update user profile attributes like job title, department, manager, phone number',
    parameters: [
      { id: 'upn', label: 'User Principal Name', type: 'text', required: true, placeholder: 'john.doe@contoso.com' },
      { id: 'jobTitle', label: 'Job Title', type: 'text', required: false, placeholder: 'Senior Sales Manager' },
      { id: 'department', label: 'Department', type: 'text', required: false, placeholder: 'Sales' },
      { id: 'officeLocation', label: 'Office Location', type: 'text', required: false, placeholder: 'Building 1, Floor 3' },
      { id: 'mobilePhone', label: 'Mobile Phone', type: 'text', required: false, placeholder: '+1-555-123-4567' },
      { id: 'managerUpn', label: 'Manager UPN', type: 'text', required: false, placeholder: 'manager@contoso.com' }
    ],
    scriptTemplate: (params) => {
      const upn = escapePowerShellString(params.upn);
      const jobTitle = params.jobTitle ? escapePowerShellString(params.jobTitle) : null;
      const department = params.department ? escapePowerShellString(params.department) : null;
      const officeLocation = params.officeLocation ? escapePowerShellString(params.officeLocation) : null;
      const mobilePhone = params.mobilePhone ? escapePowerShellString(params.mobilePhone) : null;
      const managerUpn = params.managerUpn ? escapePowerShellString(params.managerUpn) : null;

      return `# Update Azure AD User Attributes
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.ReadWrite.All"

$UPN = "${upn}"
${jobTitle ? `$JobTitle = "${jobTitle}"` : ''}
${department ? `$Department = "${department}"` : ''}
${officeLocation ? `$OfficeLocation = "${officeLocation}"` : ''}
${mobilePhone ? `$MobilePhone = "${mobilePhone}"` : ''}
${managerUpn ? `$ManagerUPN = "${managerUpn}"` : ''}

try {
    Write-Host "Updating user attributes for: $UPN" -ForegroundColor Cyan
    
    # Build update parameters
    $UpdateParams = @{}
    ${jobTitle ? `$UpdateParams.JobTitle = $JobTitle` : ''}
    ${department ? `$UpdateParams.Department = $Department` : ''}
    ${officeLocation ? `$UpdateParams.OfficeLocation = $OfficeLocation` : ''}
    ${mobilePhone ? `$UpdateParams.MobilePhone = $MobilePhone` : ''}
    
    # Update user
    if ($UpdateParams.Count -gt 0) {
        Update-MgUser -UserId $UPN @UpdateParams
        Write-Host "✓ User attributes updated:" -ForegroundColor Green
        foreach ($Key in $UpdateParams.Keys) {
            Write-Host "  $Key : $($UpdateParams[$Key])" -ForegroundColor Gray
        }
    }
    
    ${managerUpn ? `
    # Update manager if specified
    if ($ManagerUPN) {
        $Manager = Get-MgUser -UserId $ManagerUPN -ErrorAction Stop
        $ManagerRef = @{
            "@odata.id" = "https://graph.microsoft.com/v1.0/users/$($Manager.Id)"
        }
        Set-MgUserManagerByRef -UserId $UPN -BodyParameter $ManagerRef
        Write-Host "✓ Manager updated: $ManagerUPN" -ForegroundColor Green
    }
    ` : ''}
    
    Write-Host "
User attributes updated successfully!" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to update user attributes: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'enable-disable-user',
    name: 'Enable or Disable User Account',
    category: 'User Lifecycle',
    description: 'Enable or disable user account with optional logging and confirmation',
    parameters: [
      { id: 'upn', label: 'User Principal Name', type: 'text', required: true, placeholder: 'john.doe@contoso.com' },
      { id: 'operation', label: 'Operation', type: 'select', required: true, options: ['Enable', 'Disable'], defaultValue: 'Disable' },
      { id: 'revokeTokens', label: 'Revoke Refresh Tokens (Disable Only)', type: 'boolean', required: false, defaultValue: true, description: 'Forces user to re-authenticate on all devices' }
    ],
    scriptTemplate: (params) => {
      const upn = escapePowerShellString(params.upn);
      const operation = params.operation || 'Disable';
      const revokeTokens = params.revokeTokens === 'true' || params.revokeTokens === true;

      return `# ${operation} Azure AD User Account
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.ReadWrite.All"

$UPN = "${upn}"
$Operation = "${operation}"
$RevokeTokens = $${revokeTokens}

try {
    Write-Host "${operation}ing user account: $UPN" -ForegroundColor Cyan
    
    # Get current user status
    $User = Get-MgUser -UserId $UPN -Property Id,DisplayName,AccountEnabled
    Write-Host "Current status: $($User.DisplayName) - Enabled: $($User.AccountEnabled)" -ForegroundColor Gray
    
    $NewStatus = if ($Operation -eq "Enable") { $true } else { $false }
    
    # Update account status
    Update-MgUser -UserId $UPN -AccountEnabled $NewStatus
    Write-Host "✓ Account ${operation}d successfully" -ForegroundColor Green
    
    # Revoke tokens if disabling and requested
    if ($Operation -eq "Disable" -and $RevokeTokens) {
        Write-Host "Revoking refresh tokens..." -ForegroundColor Cyan
        Revoke-MgUserSignInSession -UserId $UPN
        Write-Host "✓ Refresh tokens revoked - user must re-authenticate" -ForegroundColor Green
    }
    
    Write-Host "
Account ${operation} completed!" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to ${operation.ToLower()} account: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'reset-password',
    name: 'Reset User Password',
    category: 'User Lifecycle',
    description: 'Reset user password with optional token revocation for security',
    parameters: [
      { id: 'upn', label: 'User Principal Name', type: 'text', required: true, placeholder: 'john.doe@contoso.com' },
      { id: 'newPassword', label: 'New Password', type: 'text', required: true, placeholder: 'NewP@ssw0rd123!', description: 'Strong password meeting Azure AD requirements' },
      { id: 'forcePasswordChange', label: 'Force Password Change at Next Sign-In', type: 'boolean', required: false, defaultValue: true },
      { id: 'revokeTokens', label: 'Revoke Refresh Tokens', type: 'boolean', required: false, defaultValue: true, description: 'Recommended for security - forces user to re-authenticate' }
    ],
    scriptTemplate: (params) => {
      const upn = escapePowerShellString(params.upn);
      const newPassword = escapePowerShellString(params.newPassword);
      const forcePasswordChange = params.forcePasswordChange === 'true' || params.forcePasswordChange === true;
      const revokeTokens = params.revokeTokens === 'true' || params.revokeTokens === true;

      return `# Reset Azure AD User Password
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.ReadWrite.All"

$UPN = "${upn}"
$NewPassword = "${newPassword}"
$ForcePasswordChange = $${forcePasswordChange}
$RevokeTokens = $${revokeTokens}

try {
    Write-Host "Resetting password for: $UPN" -ForegroundColor Cyan
    
    # Get user
    $User = Get-MgUser -UserId $UPN -Property Id,DisplayName
    Write-Host "User: $($User.DisplayName)" -ForegroundColor Gray
    
    # Create password profile
    $PasswordProfile = @{
        Password = $NewPassword
        ForceChangePasswordNextSignIn = $ForcePasswordChange
    }
    
    # Update password
    Update-MgUser -UserId $UPN -PasswordProfile $PasswordProfile
    Write-Host "✓ Password reset successfully" -ForegroundColor Green
    
    if ($ForcePasswordChange) {
        Write-Host "  User will be required to change password at next sign-in" -ForegroundColor Gray
    }
    
    # Revoke tokens if requested
    if ($RevokeTokens) {
        Write-Host "Revoking refresh tokens..." -ForegroundColor Cyan
        Revoke-MgUserSignInSession -UserId $UPN
        Write-Host "✓ Refresh tokens revoked - user must re-authenticate on all devices" -ForegroundColor Green
    }
    
    Write-Host "
Password reset completed!" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to reset password: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'check-mfa-status',
    name: 'Check MFA Registration Status',
    category: 'User Lifecycle',
    description: 'Check MFA registration status and authentication methods for users',
    parameters: [
      { id: 'upn', label: 'User Principal Name (Optional)', type: 'text', required: false, placeholder: 'john.doe@contoso.com', description: 'Leave blank to check all users' },
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: false, placeholder: 'C:\\Reports\\MFA-Status.csv', description: 'Optional: Export results to CSV' }
    ],
    scriptTemplate: (params) => {
      const upn = params.upn ? escapePowerShellString(params.upn) : null;
      const exportPath = params.exportPath ? escapePowerShellString(params.exportPath) : null;

      return `# Check MFA Registration Status
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "UserAuthenticationMethod.Read.All", "User.Read.All"

${upn ? `$UPN = "${upn}"` : '# Checking all users'}
${exportPath ? `$ExportPath = "${exportPath}"` : ''}

try {
    $Results = @()
    
    ${upn ? `
    # Check single user
    Write-Host "Checking MFA status for: $UPN" -ForegroundColor Cyan
    $Users = @(Get-MgUser -UserId $UPN -Property Id,DisplayName,UserPrincipalName)
    ` : `
    # Check all users
    Write-Host "Retrieving all users..." -ForegroundColor Cyan
    $Users = Get-MgUser -All -Property Id,DisplayName,UserPrincipalName
    Write-Host "Found $($Users.Count) users" -ForegroundColor Gray
    `}
    
    foreach ($User in $Users) {
        Write-Host "Processing: $($User.DisplayName)" -ForegroundColor Cyan
        
        # Get authentication methods
        $AuthMethods = Get-MgUserAuthenticationMethod -UserId $User.Id
        
        $MethodCount = $AuthMethods.Count
        $Methods = ($AuthMethods | ForEach-Object { 
            $_.AdditionalProperties.'@odata.type'.Replace('#microsoft.graph.', '')
        }) -join ', '
        
        $MfaStatus = if ($MethodCount -gt 1) { "Registered" } else { "Not Registered" }
        
        $Result = [PSCustomObject]@{
            DisplayName = $User.DisplayName
            UserPrincipalName = $User.UserPrincipalName
            MFAStatus = $MfaStatus
            MethodCount = $MethodCount
            Methods = $Methods
        }
        
        $Results += $Result
        
        Write-Host "  Status: $MfaStatus - Methods: $Methods" -ForegroundColor $(if ($MfaStatus -eq "Registered") { "Green" } else { "Yellow" })
    }
    
    # Display summary
    Write-Host "
=== MFA Status Summary ===" -ForegroundColor Cyan
    $Registered = ($Results | Where-Object { $_.MFAStatus -eq "Registered" }).Count
    $NotRegistered = ($Results | Where-Object { $_.MFAStatus -eq "Not Registered" }).Count
    Write-Host "Total Users: $($Results.Count)" -ForegroundColor White
    Write-Host "MFA Registered: $Registered" -ForegroundColor Green
    Write-Host "Not Registered: $NotRegistered" -ForegroundColor Yellow
    
    ${exportPath ? `
    # Export to CSV if path specified
    if ($ExportPath) {
        $Results | Export-Csv -Path $ExportPath -NoTypeInformation
        Write-Host "
✓ Report exported to: $ExportPath" -ForegroundColor Green
    }
    ` : ''}
    
} catch {
    Write-Error "Failed to check MFA status: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  // ========================================
  // Groups & Access Management (6 tasks)
  // ========================================
  {
    id: 'create-azure-ad-group',
    name: 'Create Security or M365 Group',
    category: 'Groups & Access',
    description: 'Create a new security group or Microsoft 365 group with owners and members',
    parameters: [
      { id: 'displayName', label: 'Group Display Name', type: 'text', required: true, placeholder: 'Sales Team' },
      { id: 'groupType', label: 'Group Type', type: 'select', required: true, options: ['Security', 'Microsoft365'], defaultValue: 'Security' },
      { id: 'description', label: 'Description', type: 'text', required: false, placeholder: 'Sales department team group' },
      { id: 'ownerUpn', label: 'Owner UPN (Optional)', type: 'text', required: false, placeholder: 'owner@contoso.com' },
      { id: 'mailNickname', label: 'Mail Nickname', type: 'text', required: false, placeholder: 'sales-team', description: 'Required for M365 groups, auto-generated from display name if not provided' }
    ],
    scriptTemplate: (params) => {
      const displayName = escapePowerShellString(params.displayName);
      const groupType = params.groupType || 'Security';
      const description = params.description ? escapePowerShellString(params.description) : null;
      const ownerUpn = params.ownerUpn ? escapePowerShellString(params.ownerUpn) : null;
      const mailNickname = params.mailNickname ? escapePowerShellString(params.mailNickname) : null;

      return `# Create ${groupType} Group
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Group.ReadWrite.All", "User.Read.All"

$DisplayName = "${displayName}"
$GroupType = "${groupType}"
${description ? `$Description = "${description}"` : ''}
${ownerUpn ? `$OwnerUPN = "${ownerUpn}"` : ''}
${mailNickname ? `$MailNickname = "${mailNickname}"` : `$MailNickname = $DisplayName -replace '[^a-zA-Z0-9]', '-' | ForEach-Object { $_.ToLower() }`}

try {
    Write-Host "Creating $GroupType group: $DisplayName" -ForegroundColor Cyan
    
    # Build group parameters
    $GroupParams = @{
        DisplayName = $DisplayName
        MailEnabled = $($GroupType -eq "Microsoft365")
        MailNickname = $MailNickname
        SecurityEnabled = $true
    }
    
    if ($GroupType -eq "Microsoft365") {
        $GroupParams.GroupTypes = @("Unified")
    }
    
    ${description ? `$GroupParams.Description = $Description` : ''}
    
    # Create group
    $Group = New-MgGroup @GroupParams
    Write-Host "✓ Group created successfully!" -ForegroundColor Green
    Write-Host "  Group ID: $($Group.Id)" -ForegroundColor Gray
    Write-Host "  Type: $GroupType" -ForegroundColor Gray
    
    ${ownerUpn ? `
    # Add owner if specified
    if ($OwnerUPN) {
        Write-Host "Adding owner: $OwnerUPN" -ForegroundColor Cyan
        $Owner = Get-MgUser -UserId $OwnerUPN -ErrorAction Stop
        $OwnerRef = @{
            "@odata.id" = "https://graph.microsoft.com/v1.0/users/$($Owner.Id)"
        }
        New-MgGroupOwnerByRef -GroupId $Group.Id -BodyParameter $OwnerRef
        Write-Host "✓ Owner added" -ForegroundColor Green
    }
    ` : ''}
    
    Write-Host "
Group creation completed!" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to create group: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'bulk-add-remove-members',
    name: 'Bulk Add/Remove Group Members',
    category: 'Groups & Access',
    description: 'Add or remove multiple members from a group using a CSV file',
    parameters: [
      { id: 'groupName', label: 'Group Display Name or ID', type: 'text', required: true, placeholder: 'Sales Team' },
      { id: 'csvPath', label: 'CSV File Path', type: 'path', required: true, placeholder: 'C:\\Scripts\\members.csv', description: 'CSV with UPN column' },
      { id: 'operation', label: 'Operation', type: 'select', required: true, options: ['Add', 'Remove'], defaultValue: 'Add' },
      { id: 'testMode', label: 'Test Mode (Preview Only)', type: 'boolean', required: false, defaultValue: true }
    ],
    scriptTemplate: (params) => {
      const groupName = escapePowerShellString(params.groupName);
      const csvPath = escapePowerShellString(params.csvPath);
      const operation = params.operation || 'Add';
      const testMode = params.testMode === 'true' || params.testMode === true;

      return `# Bulk ${operation} Group Members
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Group.ReadWrite.All", "GroupMember.ReadWrite.All", "User.Read.All"

$GroupName = "${groupName}"
$CsvPath = "${csvPath}"
$Operation = "${operation}"
$TestMode = $${testMode}

# Validation
if (-not (Test-Path $CsvPath)) {
    Write-Error "CSV file not found: $CsvPath"
    exit 1
}

try {
    # Get group
    Write-Host "Finding group: $GroupName" -ForegroundColor Cyan
    $Group = Get-MgGroup -Filter "displayName eq '$GroupName'" -ErrorAction SilentlyContinue
    if (-not $Group) {
        # Try as Group ID
        $Group = Get-MgGroup -GroupId $GroupName -ErrorAction SilentlyContinue
    }
    if (-not $Group) {
        Write-Error "Group not found: $GroupName"
        exit 1
    }
    Write-Host "Found group: $($Group.DisplayName)" -ForegroundColor Green
    
    # Import CSV
    $Users = Import-Csv -Path $CsvPath
    Write-Host "Loaded $($Users.Count) users from CSV" -ForegroundColor Cyan
    
    if ($TestMode) {
        Write-Host "
=== TEST MODE - No changes will be made ===" -ForegroundColor Yellow
    }
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($User in $Users) {
        try {
            Write-Host "Processing: $($User.UPN)" -ForegroundColor Cyan
            
            if ($TestMode) {
                Write-Host "  [TEST] Would $($Operation.ToLower()) user: $($User.UPN)" -ForegroundColor Gray
                $SuccessCount++
            } else {
                # Get user
                $MgUser = Get-MgUser -UserId $User.UPN -ErrorAction Stop
                
                if ($Operation -eq "Add") {
                    $MemberRef = @{
                        "@odata.id" = "https://graph.microsoft.com/v1.0/users/$($MgUser.Id)"
                    }
                    New-MgGroupMemberByRef -GroupId $Group.Id -BodyParameter $MemberRef
                    Write-Host "  ✓ Member added" -ForegroundColor Green
                } else {
                    Remove-MgGroupMemberByRef -GroupId $Group.Id -DirectoryObjectId $MgUser.Id
                    Write-Host "  ✓ Member removed" -ForegroundColor Green
                }
                
                $SuccessCount++
            }
        } catch {
            Write-Host "  ✗ Failed: $_" -ForegroundColor Red
            $FailCount++
        }
    }
    
    # Summary
    Write-Host "
=== Bulk Group Membership Summary ===" -ForegroundColor Cyan
    Write-Host "Total Users: $($Users.Count)" -ForegroundColor White
    Write-Host "Successful: $SuccessCount" -ForegroundColor Green
    Write-Host "Failed: $FailCount" -ForegroundColor Red
    
} catch {
    Write-Error "Bulk group membership operation failed: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'assign-group-owners',
    name: 'Assign Group Owners',
    category: 'Groups & Access',
    description: 'Add one or more owners to an Azure AD group',
    parameters: [
      { id: 'groupName', label: 'Group Display Name or ID', type: 'text', required: true, placeholder: 'Sales Team' },
      { id: 'ownerUpn', label: 'Owner UPN', type: 'text', required: true, placeholder: 'owner@contoso.com' }
    ],
    scriptTemplate: (params) => {
      const groupName = escapePowerShellString(params.groupName);
      const ownerUpn = escapePowerShellString(params.ownerUpn);

      return `# Assign Group Owner
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Group.ReadWrite.All", "User.Read.All"

$GroupName = "${groupName}"
$OwnerUPN = "${ownerUpn}"

try {
    # Get group
    Write-Host "Finding group: $GroupName" -ForegroundColor Cyan
    $Group = Get-MgGroup -Filter "displayName eq '$GroupName'" -ErrorAction SilentlyContinue
    if (-not $Group) {
        # Try as Group ID
        $Group = Get-MgGroup -GroupId $GroupName -ErrorAction SilentlyContinue
    }
    if (-not $Group) {
        Write-Error "Group not found: $GroupName"
        exit 1
    }
    Write-Host "Found group: $($Group.DisplayName)" -ForegroundColor Green
    
    # Get user
    Write-Host "Finding user: $OwnerUPN" -ForegroundColor Cyan
    $Owner = Get-MgUser -UserId $OwnerUPN -ErrorAction Stop
    Write-Host "Found user: $($Owner.DisplayName)" -ForegroundColor Green
    
    # Add owner
    $OwnerRef = @{
        "@odata.id" = "https://graph.microsoft.com/v1.0/users/$($Owner.Id)"
    }
    New-MgGroupOwnerByRef -GroupId $Group.Id -BodyParameter $OwnerRef
    Write-Host "✓ Owner added successfully!" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to assign group owner: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'export-group-membership',
    name: 'Export Group Membership to CSV',
    category: 'Groups & Access',
    description: 'Export all members of a group to a CSV file',
    parameters: [
      { id: 'groupName', label: 'Group Display Name or ID', type: 'text', required: true, placeholder: 'Sales Team' },
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\group-members.csv' },
      { id: 'includeNested', label: 'Include Nested Groups', type: 'boolean', required: false, defaultValue: false, description: 'Expand nested group membership' }
    ],
    scriptTemplate: (params) => {
      const groupName = escapePowerShellString(params.groupName);
      const exportPath = escapePowerShellString(params.exportPath);
      const includeNested = params.includeNested === 'true' || params.includeNested === true;

      return `# Export Group Membership
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Group.Read.All", "GroupMember.Read.All", "User.Read.All"

$GroupName = "${groupName}"
$ExportPath = "${exportPath}"
$IncludeNested = $${includeNested}

try {
    # Get group
    Write-Host "Finding group: $GroupName" -ForegroundColor Cyan
    $Group = Get-MgGroup -Filter "displayName eq '$GroupName'" -ErrorAction SilentlyContinue
    if (-not $Group) {
        # Try as Group ID
        $Group = Get-MgGroup -GroupId $GroupName -ErrorAction SilentlyContinue
    }
    if (-not $Group) {
        Write-Error "Group not found: $GroupName"
        exit 1
    }
    Write-Host "Found group: $($Group.DisplayName)" -ForegroundColor Green
    
    # Get members
    Write-Host "Retrieving group members..." -ForegroundColor Cyan
    $Members = Get-MgGroupMember -GroupId $Group.Id -All
    Write-Host "Found $($Members.Count) members" -ForegroundColor Gray
    
    $Results = @()
    foreach ($Member in $Members) {
        # Get member details
        $MemberType = $Member.AdditionalProperties.'@odata.type'
        
        if ($MemberType -eq '#microsoft.graph.user') {
            $User = Get-MgUser -UserId $Member.Id -Property Id,DisplayName,UserPrincipalName,JobTitle,Department
            $Results += [PSCustomObject]@{
                DisplayName = $User.DisplayName
                UserPrincipalName = $User.UserPrincipalName
                JobTitle = $User.JobTitle
                Department = $User.Department
                Type = "User"
            }
        } elseif ($MemberType -eq '#microsoft.graph.group') {
            $NestedGroup = Get-MgGroup -GroupId $Member.Id
            $Results += [PSCustomObject]@{
                DisplayName = $NestedGroup.DisplayName
                UserPrincipalName = "N/A"
                JobTitle = "N/A"
                Department = "N/A"
                Type = "Group"
            }
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "✓ Group membership exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total members: $($Results.Count)" -ForegroundColor Gray
    
} catch {
    Write-Error "Failed to export group membership: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'create-dynamic-group',
    name: 'Create Dynamic Group with Membership Rule',
    category: 'Groups & Access',
    description: 'Create a dynamic security group with automatic membership based on user attributes',
    parameters: [
      { id: 'displayName', label: 'Group Display Name', type: 'text', required: true, placeholder: 'All Sales Users' },
      { id: 'description', label: 'Description', type: 'text', required: false, placeholder: 'All users in Sales department' },
      { id: 'membershipRule', label: 'Membership Rule', type: 'text', required: true, placeholder: '(user.department -eq "Sales")', description: 'Azure AD dynamic rule syntax' },
      { id: 'mailNickname', label: 'Mail Nickname', type: 'text', required: false, placeholder: 'all-sales-users' }
    ],
    scriptTemplate: (params) => {
      const displayName = escapePowerShellString(params.displayName);
      const description = params.description ? escapePowerShellString(params.description) : null;
      const membershipRule = escapePowerShellString(params.membershipRule);
      const mailNickname = params.mailNickname ? escapePowerShellString(params.mailNickname) : null;

      return `# Create Dynamic Group
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Group.ReadWrite.All"

$DisplayName = "${displayName}"
${description ? `$Description = "${description}"` : ''}
$MembershipRule = "${membershipRule}"
${mailNickname ? `$MailNickname = "${mailNickname}"` : `$MailNickname = $DisplayName -replace '[^a-zA-Z0-9]', '-' | ForEach-Object { $_.ToLower() }`}

try {
    Write-Host "Creating dynamic group: $DisplayName" -ForegroundColor Cyan
    Write-Host "Membership rule: $MembershipRule" -ForegroundColor Gray
    
    # Build group parameters
    $GroupParams = @{
        DisplayName = $DisplayName
        MailEnabled = $false
        MailNickname = $MailNickname
        SecurityEnabled = $true
        GroupTypes = @("DynamicMembership")
        MembershipRule = $MembershipRule
        MembershipRuleProcessingState = "On"
    }
    
    ${description ? `$GroupParams.Description = $Description` : ''}
    
    # Create dynamic group
    $Group = New-MgGroup @GroupParams
    Write-Host "✓ Dynamic group created successfully!" -ForegroundColor Green
    Write-Host "  Group ID: $($Group.Id)" -ForegroundColor Gray
    Write-Host "  Membership will be evaluated automatically" -ForegroundColor Gray
    
    Write-Host "
Dynamic group creation completed!" -ForegroundColor Green
    Write-Host "Note: It may take several minutes for dynamic membership to be processed." -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to create dynamic group: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'export-all-groups',
    name: 'Export All Groups Inventory',
    category: 'Groups & Access',
    description: 'Export all Azure AD groups to a CSV file with details',
    parameters: [
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\all-groups.csv' },
      { id: 'groupType', label: 'Filter by Type (Optional)', type: 'select', required: false, options: ['All', 'Security', 'Microsoft365', 'Dynamic'], defaultValue: 'All' }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const groupType = params.groupType || 'All';

      return `# Export All Groups Inventory
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Group.Read.All", "GroupMember.Read.All"

$ExportPath = "${exportPath}"
$GroupTypeFilter = "${groupType}"

try {
    Write-Host "Retrieving all groups..." -ForegroundColor Cyan
    $Groups = Get-MgGroup -All -Property Id,DisplayName,Description,GroupTypes,SecurityEnabled,MailEnabled,MembershipRule,CreatedDateTime
    Write-Host "Found $($Groups.Count) groups" -ForegroundColor Gray
    
    $Results = @()
    foreach ($Group in $Groups) {
        # Determine group type
        $Type = if ($Group.GroupTypes -contains "DynamicMembership") {
            "Dynamic"
        } elseif ($Group.GroupTypes -contains "Unified") {
            "Microsoft365"
        } elseif ($Group.SecurityEnabled) {
            "Security"
        } else {
            "Distribution"
        }
        
        # Apply filter if specified
        if ($GroupTypeFilter -ne "All" -and $Type -ne $GroupTypeFilter) {
            continue
        }
        
        # Get member count
        $MemberCount = (Get-MgGroupMember -GroupId $Group.Id -All).Count
        
        $Results += [PSCustomObject]@{
            DisplayName = $Group.DisplayName
            Type = $Type
            Description = $Group.Description
            MemberCount = $MemberCount
            SecurityEnabled = $Group.SecurityEnabled
            MailEnabled = $Group.MailEnabled
            MembershipRule = $Group.MembershipRule
            CreatedDateTime = $Group.CreatedDateTime
            GroupId = $Group.Id
        }
        
        Write-Host "  Processed: $($Group.DisplayName) ($Type)" -ForegroundColor Gray
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "✓ Groups inventory exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total groups: $($Results.Count)" -ForegroundColor Gray
    
} catch {
    Write-Error "Failed to export groups inventory: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  // ========================================
  // Reporting & Auditing (5 tasks)
  // ========================================
  {
    id: 'export-signin-logs',
    name: 'Export Sign-In Logs',
    category: 'Reporting & Auditing',
    description: 'Export Azure AD sign-in logs filtered by date range, user, or application',
    parameters: [
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\signin-logs.csv' },
      { id: 'daysBack', label: 'Days to Look Back', type: 'number', required: false, placeholder: '7', defaultValue: 7, description: 'Number of days of history to export' },
      { id: 'filterUser', label: 'Filter by UPN (Optional)', type: 'text', required: false, placeholder: 'john.doe@contoso.com' },
      { id: 'maxRecords', label: 'Max Records', type: 'number', required: false, placeholder: '1000', defaultValue: 1000 }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const daysBack = params.daysBack || 7;
      const filterUser = params.filterUser ? escapePowerShellString(params.filterUser) : null;
      const maxRecords = params.maxRecords || 1000;

      return `# Export Sign-In Logs
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "AuditLog.Read.All", "Directory.Read.All"

$ExportPath = "${exportPath}"
$DaysBack = ${daysBack}
${filterUser ? `$FilterUser = "${filterUser}"` : ''}
$MaxRecords = ${maxRecords}

try {
    Write-Host "Retrieving sign-in logs..." -ForegroundColor Cyan
    
    # Calculate date filter
    $StartDate = (Get-Date).AddDays(-$DaysBack).ToString('yyyy-MM-ddTHH:mm:ssZ')
    
    # Build filter
    $Filter = "createdDateTime ge $StartDate"
    ${filterUser ? `$Filter += " and userPrincipalName eq '$FilterUser'"` : ''}
    
    Write-Host "Filter: $Filter" -ForegroundColor Gray
    
    # Get sign-in logs
    $SignInLogs = Get-MgAuditLogSignIn -Filter $Filter -Top $MaxRecords
    Write-Host "Retrieved $($SignInLogs.Count) sign-in records" -ForegroundColor Gray
    
    # Process and format results
    $Results = $SignInLogs | ForEach-Object {
        [PSCustomObject]@{
            CreatedDateTime = $_.CreatedDateTime
            UserPrincipalName = $_.UserPrincipalName
            UserDisplayName = $_.UserDisplayName
            AppDisplayName = $_.AppDisplayName
            IpAddress = $_.IpAddress
            Location = "$($_.Location.City), $($_.Location.State), $($_.Location.CountryOrRegion)"
            Status = if ($_.Status.ErrorCode -eq 0) { "Success" } else { "Failed" }
            ErrorCode = $_.Status.ErrorCode
            FailureReason = $_.Status.FailureReason
            DeviceDetail = $_.DeviceDetail.DisplayName
            Browser = $_.DeviceDetail.Browser
            OperatingSystem = $_.DeviceDetail.OperatingSystem
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "✓ Sign-in logs exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total records: $($Results.Count)" -ForegroundColor Gray
    
} catch {
    Write-Error "Failed to export sign-in logs: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'export-audit-logs',
    name: 'Export Audit Logs',
    category: 'Reporting & Auditing',
    description: 'Export Azure AD audit logs for user changes, group modifications, and administrative actions',
    parameters: [
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\audit-logs.csv' },
      { id: 'daysBack', label: 'Days to Look Back', type: 'number', required: false, placeholder: '7', defaultValue: 7 },
      { id: 'category', label: 'Filter by Category (Optional)', type: 'select', required: false, options: ['All', 'UserManagement', 'GroupManagement', 'ApplicationManagement', 'RoleManagement'], defaultValue: 'All' },
      { id: 'maxRecords', label: 'Max Records', type: 'number', required: false, placeholder: '1000', defaultValue: 1000 }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const daysBack = params.daysBack || 7;
      const category = params.category || 'All';
      const maxRecords = params.maxRecords || 1000;

      return `# Export Audit Logs
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "AuditLog.Read.All", "Directory.Read.All"

$ExportPath = "${exportPath}"
$DaysBack = ${daysBack}
$Category = "${category}"
$MaxRecords = ${maxRecords}

try {
    Write-Host "Retrieving audit logs..." -ForegroundColor Cyan
    
    # Calculate date filter
    $StartDate = (Get-Date).AddDays(-$DaysBack).ToString('yyyy-MM-ddTHH:mm:ssZ')
    
    # Build filter
    $Filter = "activityDateTime ge $StartDate"
    if ($Category -ne "All") {
        $Filter += " and category eq '$Category'"
    }
    
    Write-Host "Filter: $Filter" -ForegroundColor Gray
    
    # Get audit logs
    $AuditLogs = Get-MgAuditLogDirectoryAudit -Filter $Filter -Top $MaxRecords
    Write-Host "Retrieved $($AuditLogs.Count) audit records" -ForegroundColor Gray
    
    # Process and format results
    $Results = $AuditLogs | ForEach-Object {
        [PSCustomObject]@{
            ActivityDateTime = $_.ActivityDateTime
            ActivityDisplayName = $_.ActivityDisplayName
            Category = $_.Category
            Result = $_.Result
            InitiatedBy = if ($_.InitiatedBy.User) { $_.InitiatedBy.User.UserPrincipalName } else { $_.InitiatedBy.App.DisplayName }
            TargetResources = ($_.TargetResources | ForEach-Object { $_.DisplayName }) -join ', '
            OperationType = $_.OperationType
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "✓ Audit logs exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total records: $($Results.Count)" -ForegroundColor Gray
    
} catch {
    Write-Error "Failed to export audit logs: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'inactive-accounts-report',
    name: 'Inactive Accounts Report',
    category: 'Reporting & Auditing',
    description: 'Generate a report of user accounts with no sign-in activity for X days, with optional disable action',
    parameters: [
      { id: 'inactiveDays', label: 'Inactive Days Threshold', type: 'number', required: true, placeholder: '90', defaultValue: 90 },
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\inactive-accounts.csv' },
      { id: 'disableAccounts', label: 'Disable Inactive Accounts', type: 'boolean', required: false, defaultValue: false, description: 'WARNING: This will disable accounts!' },
      { id: 'testMode', label: 'Test Mode (Preview Only)', type: 'boolean', required: false, defaultValue: true }
    ],
    scriptTemplate: (params) => {
      const inactiveDays = params.inactiveDays || 90;
      const exportPath = escapePowerShellString(params.exportPath);
      const disableAccounts = params.disableAccounts === 'true' || params.disableAccounts === true;
      const testMode = params.testMode === 'true' || params.testMode === true;

      return `# Inactive Accounts Report
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.Read.All", "User.ReadWrite.All", "AuditLog.Read.All"

$InactiveDays = ${inactiveDays}
$ExportPath = "${exportPath}"
$DisableAccounts = $${disableAccounts}
$TestMode = $${testMode}

try {
    Write-Host "Finding inactive accounts (no sign-in for $InactiveDays days)..." -ForegroundColor Cyan
    
    if ($TestMode -and $DisableAccounts) {
        Write-Host "
=== TEST MODE - No accounts will be disabled ===" -ForegroundColor Yellow
    }
    
    # Get all users
    $Users = Get-MgUser -All -Property Id,DisplayName,UserPrincipalName,AccountEnabled,SignInActivity,CreatedDateTime
    Write-Host "Retrieved $($Users.Count) users" -ForegroundColor Gray
    
    $InactiveThreshold = (Get-Date).AddDays(-$InactiveDays)
    $Results = @()
    $DisabledCount = 0
    
    foreach ($User in $Users) {
        $LastSignIn = $User.SignInActivity.LastSignInDateTime
        
        # Check if user is inactive
        if ($LastSignIn) {
            $LastSignInDate = [DateTime]$LastSignIn
            $IsInactive = $LastSignInDate -lt $InactiveThreshold
        } else {
            # Never signed in - check account age
            $AccountAge = (Get-Date) - [DateTime]$User.CreatedDateTime
            $IsInactive = $AccountAge.Days -gt $InactiveDays
            $LastSignInDate = $null
        }
        
        if ($IsInactive) {
            $DaysSinceSignIn = if ($LastSignInDate) { 
                ((Get-Date) - $LastSignInDate).Days 
            } else { 
                "Never" 
            }
            
            $Results += [PSCustomObject]@{
                DisplayName = $User.DisplayName
                UserPrincipalName = $User.UserPrincipalName
                LastSignInDateTime = $LastSignIn
                DaysSinceSignIn = $DaysSinceSignIn
                AccountEnabled = $User.AccountEnabled
                CreatedDateTime = $User.CreatedDateTime
            }
            
            # Disable account if requested
            if ($DisableAccounts -and $User.AccountEnabled) {
                if ($TestMode) {
                    Write-Host "  [TEST] Would disable: $($User.DisplayName)" -ForegroundColor Gray
                } else {
                    Update-MgUser -UserId $User.Id -AccountEnabled $false
                    Write-Host "  ✓ Disabled: $($User.DisplayName)" -ForegroundColor Yellow
                    $DisabledCount++
                }
            }
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "
✓ Inactive accounts report exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total inactive accounts: $($Results.Count)" -ForegroundColor Gray
    if ($DisableAccounts -and -not $TestMode) {
        Write-Host "  Accounts disabled: $DisabledCount" -ForegroundColor Yellow
    }
    
} catch {
    Write-Error "Failed to generate inactive accounts report: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'license-usage-report',
    name: 'License Usage Report',
    category: 'Reporting & Auditing',
    description: 'Generate a report showing assigned vs available licenses for all SKUs',
    parameters: [
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\license-usage.csv' }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# License Usage Report
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Organization.Read.All", "Directory.Read.All"

$ExportPath = "${exportPath}"

try {
    Write-Host "Retrieving license information..." -ForegroundColor Cyan
    
    # Get all subscribed SKUs
    $SKUs = Get-MgSubscribedSku -All
    Write-Host "Found $($SKUs.Count) license SKUs" -ForegroundColor Gray
    
    $Results = @()
    foreach ($SKU in $SKUs) {
        $Enabled = $SKU.PrepaidUnits.Enabled
        $Consumed = $SKU.ConsumedUnits
        $Available = $Enabled - $Consumed
        $PercentUsed = if ($Enabled -gt 0) { [Math]::Round(($Consumed / $Enabled) * 100, 2) } else { 0 }
        
        $Results += [PSCustomObject]@{
            SkuPartNumber = $SKU.SkuPartNumber
            SkuId = $SKU.SkuId
            ProductName = $SKU.SkuPartNumber
            TotalLicenses = $Enabled
            AssignedLicenses = $Consumed
            AvailableLicenses = $Available
            PercentUsed = "$PercentUsed%"
            Warning = if ($Available -le 5 -and $Available -gt 0) { "Low" } elseif ($Available -le 0) { "Critical" } else { "" }
        }
        
        $StatusColor = if ($Available -le 0) { "Red" } elseif ($Available -le 5) { "Yellow" } else { "Green" }
        Write-Host "  $($SKU.SkuPartNumber): $Consumed / $Enabled ($PercentUsed% used)" -ForegroundColor $StatusColor
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "
✓ License usage report exported to: $ExportPath" -ForegroundColor Green
    
    # Summary
    $LowLicenses = ($Results | Where-Object { $_.Warning -eq "Low" }).Count
    $CriticalLicenses = ($Results | Where-Object { $_.Warning -eq "Critical" }).Count
    if ($LowLicenses -gt 0 -or $CriticalLicenses -gt 0) {
        Write-Host "
⚠ WARNING:" -ForegroundColor Yellow
        if ($CriticalLicenses -gt 0) {
            Write-Host "  $CriticalLicenses license types have NO available licenses!" -ForegroundColor Red
        }
        if ($LowLicenses -gt 0) {
            Write-Host "  $LowLicenses license types have low availability (≤5 licenses)" -ForegroundColor Yellow
        }
    }
    
} catch {
    Write-Error "Failed to generate license usage report: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'mfa-compliance-report',
    name: 'MFA Compliance Report',
    category: 'Reporting & Auditing',
    description: 'Generate comprehensive MFA registration and compliance report for all users',
    parameters: [
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\mfa-compliance.csv' },
      { id: 'includeGuests', label: 'Include Guest Users', type: 'boolean', required: false, defaultValue: false }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const includeGuests = params.includeGuests === 'true' || params.includeGuests === true;

      return `# MFA Compliance Report
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "UserAuthenticationMethod.Read.All", "User.Read.All"

$ExportPath = "${exportPath}"
$IncludeGuests = $${includeGuests}

try {
    Write-Host "Generating MFA compliance report..." -ForegroundColor Cyan
    
    # Get all users
    $Filter = if ($IncludeGuests) { "" } else { "userType eq 'Member'" }
    if ($Filter) {
        $Users = Get-MgUser -All -Filter $Filter -Property Id,DisplayName,UserPrincipalName,UserType,AccountEnabled
    } else {
        $Users = Get-MgUser -All -Property Id,DisplayName,UserPrincipalName,UserType,AccountEnabled
    }
    Write-Host "Found $($Users.Count) users" -ForegroundColor Gray
    
    $Results = @()
    $CompliantCount = 0
    $NonCompliantCount = 0
    
    foreach ($User in $Users) {
        Write-Host "  Processing: $($User.DisplayName)" -ForegroundColor Gray
        
        # Get authentication methods
        $AuthMethods = Get-MgUserAuthenticationMethod -UserId $User.Id
        
        $MethodsList = ($AuthMethods | ForEach-Object { 
            $_.AdditionalProperties.'@odata.type'.Replace('#microsoft.graph.', '')
        })
        
        $HasMFA = $MethodsList.Count -gt 1
        $MFAMethods = $MethodsList -join ', '
        
        if ($HasMFA) {
            $CompliantCount++
            $ComplianceStatus = "Compliant"
        } else {
            $NonCompliantCount++
            $ComplianceStatus = "Non-Compliant"
        }
        
        $Results += [PSCustomObject]@{
            DisplayName = $User.DisplayName
            UserPrincipalName = $User.UserPrincipalName
            UserType = $User.UserType
            AccountEnabled = $User.AccountEnabled
            ComplianceStatus = $ComplianceStatus
            MFAMethodCount = $MethodsList.Count
            MFAMethods = $MFAMethods
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "
✓ MFA compliance report exported to: $ExportPath" -ForegroundColor Green
    
    # Summary
    $ComplianceRate = [Math]::Round(($CompliantCount / $Users.Count) * 100, 2)
    Write-Host "
=== MFA Compliance Summary ===" -ForegroundColor Cyan
    Write-Host "Total Users: $($Users.Count)" -ForegroundColor White
    Write-Host "Compliant (MFA Enabled): $CompliantCount" -ForegroundColor Green
    Write-Host "Non-Compliant (No MFA): $NonCompliantCount" -ForegroundColor Red
    Write-Host "Compliance Rate: $ComplianceRate%" -ForegroundColor $(if ($ComplianceRate -ge 80) { "Green" } elseif ($ComplianceRate -ge 50) { "Yellow" } else { "Red" })
    
} catch {
    Write-Error "Failed to generate MFA compliance report: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  // ========================================
  // Device & Identity Management (4 tasks)
  // ========================================
  {
    id: 'list-devices',
    name: 'List All Devices',
    category: 'Device Management',
    description: 'List all devices registered in Azure AD with filtering options',
    parameters: [
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\devices.csv' },
      { id: 'filterType', label: 'Filter by Join Type', type: 'select', required: false, options: ['All', 'AzureADJoined', 'AzureADRegistered', 'HybridAzureADJoined'], defaultValue: 'All' },
      { id: 'filterOS', label: 'Filter by OS (Optional)', type: 'select', required: false, options: ['All', 'Windows', 'iOS', 'Android', 'macOS'], defaultValue: 'All' }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      const filterType = params.filterType || 'All';
      const filterOS = params.filterOS || 'All';

      return `# List All Devices
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Device.Read.All"

$ExportPath = "${exportPath}"
$FilterType = "${filterType}"
$FilterOS = "${filterOS}"

try {
    Write-Host "Retrieving devices from Azure AD..." -ForegroundColor Cyan
    
    # Get all devices
    $Devices = Get-MgDevice -All -Property Id,DisplayName,OperatingSystem,OperatingSystemVersion,TrustType,ApproximateLastSignInDateTime,IsCompliant,IsManaged,ProfileType
    Write-Host "Retrieved $($Devices.Count) devices" -ForegroundColor Gray
    
    $Results = @()
    foreach ($Device in $Devices) {
        # Determine join type
        $JoinType = switch ($Device.TrustType) {
            "AzureAd" { "AzureADJoined" }
            "ServerAd" { "HybridAzureADJoined" }
            "Workplace" { "AzureADRegistered" }
            default { $Device.TrustType }
        }
        
        # Apply filters
        if ($FilterType -ne "All" -and $JoinType -ne $FilterType) {
            continue
        }
        if ($FilterOS -ne "All" -and $Device.OperatingSystem -notlike "*$FilterOS*") {
            continue
        }
        
        $DaysSinceSignIn = if ($Device.ApproximateLastSignInDateTime) {
            ((Get-Date) - [DateTime]$Device.ApproximateLastSignInDateTime).Days
        } else {
            "Never"
        }
        
        $Results += [PSCustomObject]@{
            DisplayName = $Device.DisplayName
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OperatingSystemVersion
            JoinType = $JoinType
            LastSignIn = $Device.ApproximateLastSignInDateTime
            DaysSinceSignIn = $DaysSinceSignIn
            IsCompliant = $Device.IsCompliant
            IsManaged = $Device.IsManaged
            DeviceId = $Device.Id
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "✓ Devices exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total devices: $($Results.Count)" -ForegroundColor Gray
    
    # Summary by join type
    $ByType = $Results | Group-Object -Property JoinType
    Write-Host "
Devices by Join Type:" -ForegroundColor Cyan
    foreach ($Type in $ByType) {
        Write-Host "  $($Type.Name): $($Type.Count)" -ForegroundColor Gray
    }
    
} catch {
    Write-Error "Failed to list devices: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'disable-stale-devices',
    name: 'Disable Stale Devices',
    category: 'Device Management',
    description: 'Disable or delete devices with no activity for X days',
    parameters: [
      { id: 'inactiveDays', label: 'Inactive Days Threshold', type: 'number', required: true, placeholder: '90', defaultValue: 90 },
      { id: 'action', label: 'Action', type: 'select', required: true, options: ['Disable', 'Delete'], defaultValue: 'Disable' },
      { id: 'exportPath', label: 'Export Report CSV Path', type: 'path', required: false, placeholder: 'C:\\Reports\\stale-devices.csv' },
      { id: 'testMode', label: 'Test Mode (Preview Only)', type: 'boolean', required: false, defaultValue: true }
    ],
    scriptTemplate: (params) => {
      const inactiveDays = params.inactiveDays || 90;
      const action = params.action || 'Disable';
      const exportPath = params.exportPath ? escapePowerShellString(params.exportPath) : null;
      const testMode = params.testMode === 'true' || params.testMode === true;

      return `# Disable Stale Devices
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Device.ReadWrite.All"

$InactiveDays = ${inactiveDays}
$Action = "${action}"
${exportPath ? `$ExportPath = "${exportPath}"` : ''}
$TestMode = $${testMode}

try {
    Write-Host "Finding stale devices (no activity for $InactiveDays days)..." -ForegroundColor Cyan
    
    if ($TestMode) {
        Write-Host "
=== TEST MODE - No devices will be modified ===" -ForegroundColor Yellow
    }
    
    # Get all devices
    $Devices = Get-MgDevice -All -Property Id,DisplayName,ApproximateLastSignInDateTime,AccountEnabled,OperatingSystem,TrustType
    Write-Host "Retrieved $($Devices.Count) devices" -ForegroundColor Gray
    
    $InactiveThreshold = (Get-Date).AddDays(-$InactiveDays)
    $Results = @()
    $ActionedCount = 0
    
    foreach ($Device in $Devices) {
        $LastSignIn = $Device.ApproximateLastSignInDateTime
        
        if ($LastSignIn) {
            $LastSignInDate = [DateTime]$LastSignIn
            $IsStale = $LastSignInDate -lt $InactiveThreshold
            $DaysSinceSignIn = ((Get-Date) - $LastSignInDate).Days
        } else {
            # Never signed in - consider stale
            $IsStale = $true
            $DaysSinceSignIn = "Never"
        }
        
        if ($IsStale) {
            $Results += [PSCustomObject]@{
                DisplayName = $Device.DisplayName
                OperatingSystem = $Device.OperatingSystem
                LastSignIn = $LastSignIn
                DaysSinceSignIn = $DaysSinceSignIn
                AccountEnabled = $Device.AccountEnabled
                DeviceId = $Device.Id
                Action = if ($TestMode) { "Would $Action" } else { $Action }
            }
            
            # Perform action
            if (-not $TestMode) {
                if ($Action -eq "Disable") {
                    Update-MgDevice -DeviceId $Device.Id -AccountEnabled $false
                    Write-Host "  ✓ Disabled: $($Device.DisplayName)" -ForegroundColor Yellow
                } elseif ($Action -eq "Delete") {
                    Remove-MgDevice -DeviceId $Device.Id
                    Write-Host "  ✓ Deleted: $($Device.DisplayName)" -ForegroundColor Red
                }
                $ActionedCount++
            } else {
                Write-Host "  [TEST] Would $($Action.ToLower()): $($Device.DisplayName) (Last sign-in: $DaysSinceSignIn days ago)" -ForegroundColor Gray
            }
        }
    }
    
    ${exportPath ? `
    # Export report if path specified
    if ($ExportPath) {
        $Results | Export-Csv -Path $ExportPath -NoTypeInformation
        Write-Host "
✓ Stale devices report exported to: $ExportPath" -ForegroundColor Green
    }
    ` : ''}
    
    Write-Host "
=== Stale Devices Summary ===" -ForegroundColor Cyan
    Write-Host "Total stale devices: $($Results.Count)" -ForegroundColor Gray
    if (-not $TestMode) {
        Write-Host "Devices $($Action.ToLower())d: $ActionedCount" -ForegroundColor Yellow
    }
    
} catch {
    Write-Error "Failed to process stale devices: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'export-device-compliance',
    name: 'Export Device Compliance Status',
    category: 'Device Management',
    description: 'Export compliance status for all managed devices',
    parameters: [
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\device-compliance.csv' }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Device Compliance Status
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Device.Read.All"

$ExportPath = "${exportPath}"

try {
    Write-Host "Retrieving device compliance information..." -ForegroundColor Cyan
    
    # Get all devices
    $Devices = Get-MgDevice -All -Property Id,DisplayName,OperatingSystem,OperatingSystemVersion,IsCompliant,IsManaged,ApproximateLastSignInDateTime,TrustType
    Write-Host "Retrieved $($Devices.Count) devices" -ForegroundColor Gray
    
    $Results = @()
    foreach ($Device in $Devices) {
        $JoinType = switch ($Device.TrustType) {
            "AzureAd" { "AzureADJoined" }
            "ServerAd" { "HybridAzureADJoined" }
            "Workplace" { "AzureADRegistered" }
            default { $Device.TrustType }
        }
        
        $ComplianceStatus = if ($Device.IsManaged) {
            if ($Device.IsCompliant) { "Compliant" }
            elseif ($null -eq $Device.IsCompliant) { "Unknown" }
            else { "Non-Compliant" }
        } else {
            "Not Managed"
        }
        
        $Results += [PSCustomObject]@{
            DisplayName = $Device.DisplayName
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OperatingSystemVersion
            JoinType = $JoinType
            IsManaged = $Device.IsManaged
            ComplianceStatus = $ComplianceStatus
            LastSignIn = $Device.ApproximateLastSignInDateTime
            DeviceId = $Device.Id
        }
        
        $StatusColor = switch ($ComplianceStatus) {
            "Compliant" { "Green" }
            "Non-Compliant" { "Red" }
            "Unknown" { "Yellow" }
            "Not Managed" { "Gray" }
        }
        Write-Host "  $($Device.DisplayName): $ComplianceStatus" -ForegroundColor $StatusColor
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "
✓ Device compliance report exported to: $ExportPath" -ForegroundColor Green
    
    # Summary
    $Compliant = ($Results | Where-Object { $_.ComplianceStatus -eq "Compliant" }).Count
    $NonCompliant = ($Results | Where-Object { $_.ComplianceStatus -eq "Non-Compliant" }).Count
    $NotManaged = ($Results | Where-Object { $_.ComplianceStatus -eq "Not Managed" }).Count
    
    Write-Host "
=== Compliance Summary ===" -ForegroundColor Cyan
    Write-Host "Total Devices: $($Results.Count)" -ForegroundColor White
    Write-Host "Compliant: $Compliant" -ForegroundColor Green
    Write-Host "Non-Compliant: $NonCompliant" -ForegroundColor Red
    Write-Host "Not Managed: $NotManaged" -ForegroundColor Gray
    
} catch {
    Write-Error "Failed to export device compliance: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'export-device-inventory',
    name: 'Export Device Inventory by Model/Owner/OS',
    category: 'Device Management',
    description: 'Detailed device inventory report with hardware and owner information',
    parameters: [
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\device-inventory.csv' }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Device Inventory
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "Device.Read.All", "User.Read.All"

$ExportPath = "${exportPath}"

try {
    Write-Host "Generating device inventory..." -ForegroundColor Cyan
    
    # Get all devices
    $Devices = Get-MgDevice -All -Property Id,DisplayName,OperatingSystem,OperatingSystemVersion,Model,Manufacturer,ApproximateLastSignInDateTime,TrustType,ProfileType,RegisteredOwners
    Write-Host "Retrieved $($Devices.Count) devices" -ForegroundColor Gray
    
    $Results = @()
    foreach ($Device in $Devices) {
        Write-Host "  Processing: $($Device.DisplayName)" -ForegroundColor Gray
        
        # Get registered owner
        $OwnerName = "N/A"
        $OwnerUPN = "N/A"
        try {
            $Owners = Get-MgDeviceRegisteredOwner -DeviceId $Device.Id
            if ($Owners) {
                $OwnerIds = $Owners.Id
                if ($OwnerIds) {
                    $Owner = Get-MgUser -UserId $OwnerIds[0] -ErrorAction SilentlyContinue
                    if ($Owner) {
                        $OwnerName = $Owner.DisplayName
                        $OwnerUPN = $Owner.UserPrincipalName
                    }
                }
            }
        } catch {
            # Owner not found or not accessible
        }
        
        $Results += [PSCustomObject]@{
            DisplayName = $Device.DisplayName
            Manufacturer = $Device.Manufacturer
            Model = $Device.Model
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OperatingSystemVersion
            OwnerName = $OwnerName
            OwnerUPN = $OwnerUPN
            TrustType = $Device.TrustType
            LastSignIn = $Device.ApproximateLastSignInDateTime
            DeviceId = $Device.Id
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "✓ Device inventory exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total devices: $($Results.Count)" -ForegroundColor Gray
    
    # Summary by OS
    $ByOS = $Results | Group-Object -Property OperatingSystem | Sort-Object Count -Descending
    Write-Host "
Devices by Operating System:" -ForegroundColor Cyan
    foreach ($OS in $ByOS) {
        Write-Host "  $($OS.Name): $($OS.Count)" -ForegroundColor Gray
    }
    
} catch {
    Write-Error "Failed to export device inventory: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  // ========================================
  // Maintenance & Governance (3 tasks)
  // ========================================
  {
    id: 'review-remove-guest-users',
    name: 'Review and Remove Guest Users',
    category: 'Maintenance & Governance',
    description: 'Find and optionally remove inactive or expired guest user accounts',
    parameters: [
      { id: 'inactiveDays', label: 'Inactive Days Threshold', type: 'number', required: true, placeholder: '90', defaultValue: 90 },
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\inactive-guests.csv' },
      { id: 'removeGuests', label: 'Remove Inactive Guests', type: 'boolean', required: false, defaultValue: false, description: 'WARNING: This will delete guest accounts!' },
      { id: 'testMode', label: 'Test Mode (Preview Only)', type: 'boolean', required: false, defaultValue: true }
    ],
    scriptTemplate: (params) => {
      const inactiveDays = params.inactiveDays || 90;
      const exportPath = escapePowerShellString(params.exportPath);
      const removeGuests = params.removeGuests === 'true' || params.removeGuests === true;
      const testMode = params.testMode === 'true' || params.testMode === true;

      return `# Review and Remove Guest Users
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.Read.All", "User.ReadWrite.All", "AuditLog.Read.All"

$InactiveDays = ${inactiveDays}
$ExportPath = "${exportPath}"
$RemoveGuests = $${removeGuests}
$TestMode = $${testMode}

try {
    Write-Host "Finding inactive guest users..." -ForegroundColor Cyan
    
    if ($TestMode -and $RemoveGuests) {
        Write-Host "
=== TEST MODE - No guests will be removed ===" -ForegroundColor Yellow
    }
    
    # Get all guest users
    $Guests = Get-MgUser -All -Filter "userType eq 'Guest'" -Property Id,DisplayName,UserPrincipalName,SignInActivity,CreatedDateTime,ExternalUserState
    Write-Host "Found $($Guests.Count) guest users" -ForegroundColor Gray
    
    $InactiveThreshold = (Get-Date).AddDays(-$InactiveDays)
    $Results = @()
    $RemovedCount = 0
    
    foreach ($Guest in $Guests) {
        $LastSignIn = $Guest.SignInActivity.LastSignInDateTime
        
        if ($LastSignIn) {
            $LastSignInDate = [DateTime]$LastSignIn
            $IsInactive = $LastSignInDate -lt $InactiveThreshold
            $DaysSinceSignIn = ((Get-Date) - $LastSignInDate).Days
        } else {
            $AccountAge = (Get-Date) - [DateTime]$Guest.CreatedDateTime
            $IsInactive = $AccountAge.Days -gt $InactiveDays
            $DaysSinceSignIn = "Never"
        }
        
        if ($IsInactive) {
            $Results += [PSCustomObject]@{
                DisplayName = $Guest.DisplayName
                UserPrincipalName = $Guest.UserPrincipalName
                LastSignIn = $LastSignIn
                DaysSinceSignIn = $DaysSinceSignIn
                InviteStatus = $Guest.ExternalUserState
                CreatedDateTime = $Guest.CreatedDateTime
                UserId = $Guest.Id
            }
            
            # Remove guest if requested
            if ($RemoveGuests) {
                if ($TestMode) {
                    Write-Host "  [TEST] Would remove: $($Guest.DisplayName)" -ForegroundColor Gray
                } else {
                    Remove-MgUser -UserId $Guest.Id
                    Write-Host "  ✓ Removed: $($Guest.DisplayName)" -ForegroundColor Red
                    $RemovedCount++
                }
            }
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "
✓ Inactive guests report exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total inactive guests: $($Results.Count)" -ForegroundColor Gray
    if ($RemoveGuests -and -not $TestMode) {
        Write-Host "  Guests removed: $RemovedCount" -ForegroundColor Red
    }
    
} catch {
    Write-Error "Failed to review guest users: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'bulk-invite-guests',
    name: 'Bulk Invite Guest Users',
    category: 'Maintenance & Governance',
    description: 'Send guest invitations to multiple external users from a CSV file',
    parameters: [
      { id: 'csvPath', label: 'CSV File Path', type: 'path', required: true, placeholder: 'C:\\Scripts\\guests.csv', description: 'CSV with Email, DisplayName columns' },
      { id: 'inviteMessage', label: 'Custom Invitation Message (Optional)', type: 'textarea', required: false, placeholder: 'You have been invited to collaborate with our organization.' },
      { id: 'redirectUrl', label: 'Redirect URL', type: 'text', required: false, placeholder: 'https://myapps.microsoft.com', defaultValue: 'https://myapps.microsoft.com' },
      { id: 'testMode', label: 'Test Mode (Preview Only)', type: 'boolean', required: false, defaultValue: true }
    ],
    scriptTemplate: (params) => {
      const csvPath = escapePowerShellString(params.csvPath);
      const inviteMessage = params.inviteMessage ? escapePowerShellString(params.inviteMessage) : null;
      const redirectUrl = params.redirectUrl ? escapePowerShellString(params.redirectUrl) : 'https://myapps.microsoft.com';
      const testMode = params.testMode === 'true' || params.testMode === true;

      return `# Bulk Invite Guest Users
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.Invite.All", "User.ReadWrite.All"

$CsvPath = "${csvPath}"
${inviteMessage ? `$InviteMessage = "${inviteMessage}"` : '$InviteMessage = "You have been invited to collaborate with our organization."'}
$RedirectUrl = "${redirectUrl}"
$TestMode = $${testMode}

# Validation
if (-not (Test-Path $CsvPath)) {
    Write-Error "CSV file not found: $CsvPath"
    exit 1
}

try {
    # Import CSV
    $Guests = Import-Csv -Path $CsvPath
    Write-Host "Loaded $($Guests.Count) guests from CSV" -ForegroundColor Cyan
    
    if ($TestMode) {
        Write-Host "
=== TEST MODE - No invitations will be sent ===" -ForegroundColor Yellow
    }
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($Guest in $Guests) {
        try {
            Write-Host "Processing: $($Guest.DisplayName) <$($Guest.Email)>" -ForegroundColor Cyan
            
            if ($TestMode) {
                Write-Host "  [TEST] Would invite: $($Guest.Email)" -ForegroundColor Gray
                $SuccessCount++
            } else {
                # Create invitation
                $InviteParams = @{
                    InvitedUserEmailAddress = $Guest.Email
                    InvitedUserDisplayName = $Guest.DisplayName
                    InviteRedirectUrl = $RedirectUrl
                    SendInvitationMessage = $true
                    InvitedUserMessageInfo = @{
                        CustomizedMessageBody = $InviteMessage
                    }
                }
                
                $Invitation = New-MgInvitation @InviteParams
                Write-Host "  ✓ Invitation sent to: $($Guest.Email)" -ForegroundColor Green
                Write-Host "    Invitation ID: $($Invitation.Id)" -ForegroundColor Gray
                $SuccessCount++
            }
        } catch {
            Write-Host "  ✗ Failed: $_" -ForegroundColor Red
            $FailCount++
        }
    }
    
    # Summary
    Write-Host "
=== Bulk Guest Invitation Summary ===" -ForegroundColor Cyan
    Write-Host "Total Guests: $($Guests.Count)" -ForegroundColor White
    Write-Host "Successful: $SuccessCount" -ForegroundColor Green
    Write-Host "Failed: $FailCount" -ForegroundColor Red
    
} catch {
    Write-Error "Bulk guest invitation failed: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {
    id: 'remove-unlicensed-accounts',
    name: 'Remove Unlicensed Accounts',
    category: 'Maintenance & Governance',
    description: 'Find and optionally disable/delete user accounts with no assigned licenses',
    parameters: [
      { id: 'action', label: 'Action', type: 'select', required: true, options: ['Report', 'Disable', 'Delete'], defaultValue: 'Report' },
      { id: 'exportPath', label: 'Export CSV Path', type: 'path', required: true, placeholder: 'C:\\Reports\\unlicensed-accounts.csv' },
      { id: 'excludeGuests', label: 'Exclude Guest Users', type: 'boolean', required: false, defaultValue: true },
      { id: 'testMode', label: 'Test Mode (Preview Only)', type: 'boolean', required: false, defaultValue: true }
    ],
    scriptTemplate: (params) => {
      const action = params.action || 'Report';
      const exportPath = escapePowerShellString(params.exportPath);
      const excludeGuests = params.excludeGuests === 'true' || params.excludeGuests === true;
      const testMode = params.testMode === 'true' || params.testMode === true;

      return `# Remove Unlicensed Accounts
# Generated by PSForge

# Connect to Microsoft Graph
Connect-MgGraph -Scopes "User.Read.All", "User.ReadWrite.All"

$Action = "${action}"
$ExportPath = "${exportPath}"
$ExcludeGuests = $${excludeGuests}
$TestMode = $${testMode}

try {
    Write-Host "Finding unlicensed user accounts..." -ForegroundColor Cyan
    
    if ($TestMode -and $Action -ne "Report") {
        Write-Host "
=== TEST MODE - No accounts will be modified ===" -ForegroundColor Yellow
    }
    
    # Get all users
    $Filter = if ($ExcludeGuests) { "userType eq 'Member'" } else { "" }
    if ($Filter) {
        $Users = Get-MgUser -All -Filter $Filter -Property Id,DisplayName,UserPrincipalName,UserType,AccountEnabled,AssignedLicenses,CreatedDateTime
    } else {
        $Users = Get-MgUser -All -Property Id,DisplayName,UserPrincipalName,UserType,AccountEnabled,AssignedLicenses,CreatedDateTime
    }
    Write-Host "Retrieved $($Users.Count) users" -ForegroundColor Gray
    
    $Results = @()
    $ActionedCount = 0
    
    foreach ($User in $Users) {
        $HasLicenses = $User.AssignedLicenses.Count -gt 0
        
        if (-not $HasLicenses) {
            $Results += [PSCustomObject]@{
                DisplayName = $User.DisplayName
                UserPrincipalName = $User.UserPrincipalName
                UserType = $User.UserType
                AccountEnabled = $User.AccountEnabled
                CreatedDateTime = $User.CreatedDateTime
                Action = if ($TestMode -and $Action -ne "Report") { "Would $Action" } else { $Action }
            }
            
            # Perform action
            if ($Action -ne "Report" -and -not $TestMode) {
                if ($Action -eq "Disable") {
                    Update-MgUser -UserId $User.Id -AccountEnabled $false
                    Write-Host "  ✓ Disabled: $($User.DisplayName)" -ForegroundColor Yellow
                } elseif ($Action -eq "Delete") {
                    Remove-MgUser -UserId $User.Id
                    Write-Host "  ✓ Deleted: $($User.DisplayName)" -ForegroundColor Red
                }
                $ActionedCount++
            } elseif ($Action -ne "Report") {
                Write-Host "  [TEST] Would $($Action.ToLower()): $($User.DisplayName)" -ForegroundColor Gray
            }
        }
    }
    
    # Export to CSV
    $Results | Export-Csv -Path $ExportPath -NoTypeInformation
    Write-Host "
✓ Unlicensed accounts report exported to: $ExportPath" -ForegroundColor Green
    Write-Host "  Total unlicensed accounts: $($Results.Count)" -ForegroundColor Gray
    if ($Action -ne "Report" -and -not $TestMode) {
        Write-Host "  Accounts $($Action.ToLower())d: $ActionedCount" -ForegroundColor Yellow
    }
    
} catch {
    Write-Error "Failed to process unlicensed accounts: $_"
    exit 1
}

# Disconnect
Disconnect-MgGraph`;
    }
  },

  {id:'export-group-membership',name:'Export Group Membership Report',description:'List all groups and their members',category:'Reporting',parameters:[{id:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\Reports\\\\GroupMembership.csv'}],scriptTemplate:p=>{const exportPath=escapePowerShellString(p.exportPath);return `Connect-MgGraph -Scopes "Group.Read.All"\ntry{$Groups=Get-MgGroup -All;$Results=@();foreach($Group in $Groups){$Members=Get-MgGroupMember -GroupId $Group.Id -All;foreach($Member in $Members){$Results+=[PSCustomObject]@{GroupName=$Group.DisplayName;GroupId=$Group.Id;MemberName=(Get-MgUser -UserId $Member.Id -ErrorAction SilentlyContinue).DisplayName;MemberId=$Member.Id}}};$Results|Export-Csv "${exportPath}" -NoTypeInformation;Write-Host "✓ Group membership exported: $($Results.Count) records" -ForegroundColor Green}catch{Write-Error $_};Disconnect-MgGraph`;}},
  {id:'configure-password-policy',name:'Configure Password Policy',description:'Set password expiration days for domain',category:'Security & Compliance',parameters:[{id:'passwordExpiryDays',label:'Password Expiry (Days)',type:'number',required:true,defaultValue:90}],scriptTemplate:p=>{const expiryDays=p.passwordExpiryDays||90;return `Connect-MgGraph -Scopes "Domain.ReadWrite.All"\ntry{Write-Host "Configuring password expiry policy..." -ForegroundColor Cyan;$Domain=Get-MgDomain|Where-Object{$_.IsDefault}|Select-Object -First 1;$PolicyParams=@{PasswordValidityPeriodInDays=${expiryDays};PasswordNotificationWindowInDays=14};Update-MgDomain -DomainId $Domain.Id -BodyParameter $PolicyParams;Write-Host "✓ Password expiry set to ${expiryDays} days" -ForegroundColor Green;Write-Host "  Notification window: 14 days before expiry" -ForegroundColor Yellow}catch{Write-Error $_};Disconnect-MgGraph`;}},
  {id:'audit-admin-roles',name:'Audit Admin Role Assignments',description:'Export all users with administrative roles',category:'Security & Compliance',parameters:[{id:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\Reports\\\\AdminRoles.csv'}],scriptTemplate:p=>{const exportPath=escapePowerShellString(p.exportPath);return `Connect-MgGraph -Scopes "RoleManagement.Read.Directory"\ntry{Write-Host "Collecting admin role assignments..." -ForegroundColor Cyan;$Roles=Get-MgDirectoryRole -All;$Results=@();foreach($Role in $Roles){$Members=Get-MgDirectoryRoleMember -DirectoryRoleId $Role.Id -All;foreach($Member in $Members){$User=Get-MgUser -UserId $Member.Id -ErrorAction SilentlyContinue;$Results+=[PSCustomObject]@{RoleName=$Role.DisplayName;UserName=$User.DisplayName;UserPrincipalName=$User.UserPrincipalName;AccountEnabled=$User.AccountEnabled}}};$Results|Export-Csv "${exportPath}" -NoTypeInformation;Write-Host "✓ Admin roles exported: $($Results.Count) assignments" -ForegroundColor Green}catch{Write-Error $_};Disconnect-MgGraph`;}},
  {id:'remove-stale-devices',name:'Remove Stale Devices',description:'Find and remove devices inactive for specified days',category:'Maintenance & Governance',parameters:[{id:'inactiveDays',label:'Inactive Days',type:'number',required:true,defaultValue:90},{id:'testMode',label:'Test Mode (Report Only)',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>{const inactiveDays=p.inactiveDays||90;const testMode=p.testMode!==false;return `Connect-MgGraph -Scopes "Device.Read.All","Device.ReadWrite.All"\ntry{Write-Host "Finding stale devices (${inactiveDays}+ days)..." -ForegroundColor Cyan;$Cutoff=(Get-Date).AddDays(-${inactiveDays});$Devices=Get-MgDevice -All|Where-Object{$_.ApproximateLastSignInDateTime -lt $Cutoff};Write-Host "Found $($Devices.Count) stale devices" -ForegroundColor Yellow;foreach($Device in $Devices){if(${testMode}){Write-Host "  [TEST] Would remove: $($Device.DisplayName)" -ForegroundColor Gray}else{Remove-MgDevice -DeviceId $Device.Id;Write-Host "  ✓ Removed: $($Device.DisplayName)" -ForegroundColor Green}};Write-Host "✓ Stale device cleanup complete" -ForegroundColor Green}catch{Write-Error $_};Disconnect-MgGraph`;}},
  {id:'export-app-registrations',name:'Export App Registrations',description:'List all registered applications and their permissions',category:'Reporting',parameters:[{id:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\Reports\\\\AppRegistrations.csv'}],scriptTemplate:p=>{const exportPath=escapePowerShellString(p.exportPath);return `Connect-MgGraph -Scopes "Application.Read.All"\ntry{Write-Host "Collecting app registrations..." -ForegroundColor Cyan;$Apps=Get-MgApplication -All;$Results=$Apps|Select DisplayName,AppId,@{N='CreatedDateTime';E={$_.CreatedDateTime}},@{N='Owners';E={(Get-MgApplicationOwner -ApplicationId $_.Id -All).AdditionalProperties.userPrincipalName -join '; '}};$Results|Export-Csv "${exportPath}" -NoTypeInformation;Write-Host "✓ App registrations exported: $($Results.Count) apps" -ForegroundColor Green}catch{Write-Error $_};Disconnect-MgGraph`;}}
];
