import { escapePowerShellString } from './powershell-utils';

export interface HyperVParameter {
  title: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface HyperVTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: HyperVParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const hyperVTasks: HyperVTask[] = [
  // ==================== Host Configuration ====================
  {
    id: 'hyperv-install-role',
    title: 'Install Hyper-V Role',
    description: 'Install and configure the Hyper-V role on a Windows Server',
    category: 'Host Configuration',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'HV-HOST01',
        helpText: 'Name of the server to configure'
      },
      {
        name: 'includeManagementTools',
        label: 'Include Management Tools',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Install Hyper-V PowerShell and management tools'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const includeMgmtTools = params.includeManagementTools !== false;

      return `# Install Hyper-V Role
# Generated by PSForge

try {
    Write-Host "Installing Hyper-V role on: ${serverName}" -ForegroundColor Cyan
    
    $Features = @("Hyper-V")
    ${includeMgmtTools ? '$Features += "Hyper-V-PowerShell", "Hyper-V-Tools"' : ''}
    
    $Result = Install-WindowsFeature -Name $Features -ComputerName "${serverName}" -IncludeManagementTools
    
    if ($Result.Success) {
        Write-Host "✓ Hyper-V role installed successfully" -ForegroundColor Green
    }
    
    $Result | Select-Object Success, RestartNeeded, ExitCode | Format-List
    
} catch {
    Write-Error "Failed to install Hyper-V role: $_"
}`;
    }
  },

  {
    id: 'hyperv-create-vswitch',
    title: 'Create Virtual Switch',
    description: 'Create a Hyper-V virtual switch (External/Internal/Private)',
    category: 'Host Configuration',
    parameters: [
      {
        name: 'switchName',
        label: 'Switch Name',
        type: 'text',
        required: true,
        placeholder: 'vSwitch-External',
        helpText: 'Name for the virtual switch'
      },
      {
        name: 'switchType',
        label: 'Switch Type',
        type: 'select',
        required: true,
        options: [
          { value: 'External', label: 'External (Connects to physical network)' },
          { value: 'Internal', label: 'Internal (Host and VMs only)' },
          { value: 'Private', label: 'Private (VMs only)' }
        ],
        helpText: 'Type of virtual switch'
      },
      {
        name: 'netAdapterName',
        label: 'Network Adapter Name (for External)',
        type: 'text',
        required: false,
        placeholder: 'Ethernet',
        helpText: 'Required for External switch type'
      }
    ],
    scriptTemplate: (params) => {
      const switchName = escapePowerShellString(params.switchName);
      const switchType = params.switchType;
      const adapterName = params.netAdapterName ? escapePowerShellString(params.netAdapterName) : '';

      return `# Create Hyper-V Virtual Switch
# Generated by PSForge

try {
    Write-Host "Creating ${switchType} virtual switch: ${switchName}" -ForegroundColor Cyan
    
    ${switchType === 'External' ? `
    if (-not "${adapterName}") {
        throw "Network adapter name is required for External switch"
    }
    $NetAdapter = Get-NetAdapter -Name "${adapterName}" -ErrorAction Stop
    New-VMSwitch -Name "${switchName}" -NetAdapterName $NetAdapter.Name -AllowManagementOS $true
    ` : switchType === 'Internal' ? `
    New-VMSwitch -Name "${switchName}" -SwitchType Internal
    ` : `
    New-VMSwitch -Name "${switchName}" -SwitchType Private
    `}
    
    Write-Host "✓ Virtual switch created successfully" -ForegroundColor Green
    
    Get-VMSwitch -Name "${switchName}" | Select-Object Name, SwitchType, Id | Format-List
    
} catch {
    Write-Error "Failed to create virtual switch: $_"
}`;
    }
  },

  // ==================== VM Lifecycle ====================
  {
    id: 'hyperv-create-vm',
    title: 'Create Virtual Machine',
    description: 'Create a new Hyper-V virtual machine',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'Name for the virtual machine'
      },
      {
        name: 'generation',
        label: 'VM Generation',
        type: 'select',
        required: true,
        options: [
          { value: '1', label: 'Generation 1 (Legacy BIOS)' },
          { value: '2', label: 'Generation 2 (UEFI)' }
        ],
        defaultValue: '2',
        helpText: 'VM generation'
      },
      {
        name: 'memoryGB',
        label: 'Memory (GB)',
        type: 'number',
        required: true,
        defaultValue: 4,
        helpText: 'Amount of memory in GB'
      },
      {
        name: 'processorCount',
        label: 'Processor Count',
        type: 'number',
        required: true,
        defaultValue: 2,
        helpText: 'Number of virtual processors'
      },
      {
        name: 'vhdSizeGB',
        label: 'VHD Size (GB)',
        type: 'number',
        required: true,
        defaultValue: 60,
        helpText: 'Size of virtual hard disk in GB'
      },
      {
        name: 'switchName',
        label: 'Virtual Switch Name',
        type: 'text',
        required: true,
        placeholder: 'vSwitch-External',
        helpText: 'Virtual switch to connect to'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const generation = params.generation || '2';
      const memoryGB = params.memoryGB || 4;
      const cpuCount = params.processorCount || 2;
      const vhdSizeGB = params.vhdSizeGB || 60;
      const switchName = escapePowerShellString(params.switchName);

      return `# Create Hyper-V Virtual Machine
# Generated by PSForge

try {
    Write-Host "Creating Virtual Machine: ${vmName}" -ForegroundColor Cyan
    
    $HostSettings = Get-VMHost
    $VmPath = $HostSettings.VirtualMachinePath
    $VhdPath = $HostSettings.VirtualHardDiskPath
    
    $MemoryBytes = ${memoryGB}GB
    $VhdSizeBytes = ${vhdSizeGB}GB
    $VhdFilePath = Join-Path $VhdPath "${vmName}.vhdx"
    
    New-VM -Name "${vmName}" -Generation ${generation} -MemoryStartupBytes $MemoryBytes -Path $VmPath -NewVHDPath $VhdFilePath -NewVHDSizeBytes $VhdSizeBytes -SwitchName "${switchName}"
    
    Set-VMProcessor -VMName "${vmName}" -Count ${cpuCount}
    
    Write-Host "✓ Virtual Machine created successfully" -ForegroundColor Green
    
    Get-VM -Name "${vmName}" | Select-Object Name, Generation, State, ProcessorCount | Format-List
    
} catch {
    Write-Error "Failed to create VM: $_"
}`;
    }
  },

  {
    id: 'hyperv-start-stop-vm',
    title: 'Start/Stop VMs',
    description: 'Perform power operations on Hyper-V virtual machines',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'action',
        label: 'Action',
        type: 'select',
        required: true,
        options: [
          { value: 'Start', label: 'Start VMs' },
          { value: 'Stop', label: 'Stop VMs' },
          { value: 'Restart', label: 'Restart VMs' }
        ],
        helpText: 'Power operation to perform'
      },
      {
        name: 'vmNames',
        label: 'VM Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'VM-WEB01\nVM-DB01',
        helpText: 'List of VM names'
      }
    ],
    scriptTemplate: (params) => {
      const action = params.action;
      const vmNamesInput = params.vmNames.trim();

      return `# ${action} Hyper-V Virtual Machines
# Generated by PSForge

try {
    $VmNames = @(
${vmNamesInput.split('\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join('\n')}
    )
    
    Write-Host "Target VMs: $($VmNames.Count)" -ForegroundColor Cyan
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($VmName in $VmNames) {
        try {
            Write-Host "${action}ing: $VmName..." -ForegroundColor Cyan
            
            ${action === 'Start' ? 'Start-VM -Name $VmName' : ''}
            ${action === 'Stop' ? 'Stop-VM -Name $VmName -Force' : ''}
            ${action === 'Restart' ? 'Restart-VM -Name $VmName -Force' : ''}
            
            Write-Host "✓ $VmName ${action.toLowerCase()} completed" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed: $VmName - $_"
            $FailCount++
        }
    }
    
    Write-Host \"\`n${action} Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Operation failed: $_"
}`;
    }
  },

  {
    id: 'hyperv-export-vm',
    title: 'Export Virtual Machine',
    description: 'Export a Hyper-V VM for backup or migration',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'VM to export'
      },
      {
        name: 'exportPath',
        label: 'Export Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\VMExports',
        helpText: 'Destination folder'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Hyper-V Virtual Machine
# Generated by PSForge

try {
    Write-Host "Exporting VM: ${vmName}" -ForegroundColor Cyan
    
    if (-not (Test-Path "${exportPath}")) {
        New-Item -Path "${exportPath}" -ItemType Directory -Force | Out-Null
    }
    
    Export-VM -Name "${vmName}" -Path "${exportPath}"
    
    Write-Host "✓ VM exported successfully" -ForegroundColor Green
    
    $ExportFolder = Join-Path "${exportPath}" "${vmName}"
    Write-Host "  Location: $ExportFolder" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export VM: $_"
}`;
    }
  },

  // ==================== Storage ====================
  {
    id: 'hyperv-create-vhd',
    title: 'Create Virtual Hard Disk',
    description: 'Create a new VHDX file',
    category: 'Storage',
    parameters: [
      {
        name: 'vhdPath',
        label: 'VHD Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Hyper-V\\Disks\\Data01.vhdx',
        helpText: 'Full path for the new VHDX'
      },
      {
        name: 'sizeGB',
        label: 'Size (GB)',
        type: 'number',
        required: true,
        defaultValue: 60,
        helpText: 'Size in GB'
      },
      {
        name: 'diskType',
        label: 'Disk Type',
        type: 'select',
        required: true,
        options: [
          { value: 'Dynamic', label: 'Dynamic' },
          { value: 'Fixed', label: 'Fixed' }
        ],
        defaultValue: 'Dynamic',
        helpText: 'Disk allocation type'
      }
    ],
    scriptTemplate: (params) => {
      const vhdPath = escapePowerShellString(params.vhdPath);
      const sizeGB = params.sizeGB || 60;
      const diskType = params.diskType || 'Dynamic';

      return `# Create Virtual Hard Disk
# Generated by PSForge

try {
    Write-Host "Creating ${diskType} VHDX: ${vhdPath}" -ForegroundColor Cyan
    
    $SizeBytes = ${sizeGB}GB
    
    New-VHD -Path "${vhdPath}" -SizeBytes $SizeBytes -${diskType}
    
    Write-Host "✓ Virtual hard disk created successfully" -ForegroundColor Green
    
    Get-VHD -Path "${vhdPath}" | Select-Object Path, VhdType, Size | Format-List
    
} catch {
    Write-Error "Failed to create VHD: $_"
}`;
    }
  },

  {
    id: 'hyperv-resize-vhd',
    title: 'Resize Virtual Hard Disk',
    description: 'Expand a VHDX file',
    category: 'Storage',
    parameters: [
      {
        name: 'vhdPath',
        label: 'VHD Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Hyper-V\\Disks\\Data01.vhdx',
        helpText: 'Path to the VHDX file'
      },
      {
        name: 'newSizeGB',
        label: 'New Size (GB)',
        type: 'number',
        required: true,
        placeholder: '100',
        helpText: 'New size in GB'
      }
    ],
    scriptTemplate: (params) => {
      const vhdPath = escapePowerShellString(params.vhdPath);
      const newSizeGB = params.newSizeGB;

      return `# Resize Virtual Hard Disk
# Generated by PSForge

try {
    Write-Host "Resizing VHD: ${vhdPath}" -ForegroundColor Cyan
    
    $VHD = Get-VHD -Path "${vhdPath}"
    $CurrentSizeGB = [math]::Round($VHD.Size / 1GB, 2)
    
    Write-Host "Current Size: $CurrentSizeGB GB" -ForegroundColor Yellow
    Write-Host "New Size: ${newSizeGB} GB" -ForegroundColor Yellow
    
    $NewSizeBytes = ${newSizeGB}GB
    
    Resize-VHD -Path "${vhdPath}" -SizeBytes $NewSizeBytes
    
    Write-Host "✓ VHD resized successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to resize VHD: $_"
}`;
    }
  },

  // ==================== Checkpoints ====================
  {
    id: 'hyperv-create-checkpoint',
    title: 'Create VM Checkpoint',
    description: 'Create a checkpoint (snapshot) of a virtual machine',
    category: 'Checkpoints',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'VM to checkpoint'
      },
      {
        name: 'checkpointName',
        label: 'Checkpoint Name',
        type: 'text',
        required: false,
        placeholder: 'Before Windows Update',
        helpText: 'Optional checkpoint name'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const checkpointName = params.checkpointName ? escapePowerShellString(params.checkpointName) : '';

      return `# Create VM Checkpoint
# Generated by PSForge

try {
    Write-Host "Creating checkpoint for VM: ${vmName}" -ForegroundColor Cyan
    
    ${checkpointName ? `
    $CheckpointName = "${checkpointName}"
    ` : `
    $CheckpointName = "Checkpoint-$(Get-Date -Format 'yyyy-MM-dd-HHmmss')"
    `}
    
    Checkpoint-VM -Name "${vmName}" -SnapshotName $CheckpointName
    
    Write-Host "✓ Checkpoint created: $CheckpointName" -ForegroundColor Green
    
    Get-VMCheckpoint -VMName "${vmName}" | Select-Object Name, CreationTime | Format-Table
    
} catch {
    Write-Error "Failed to create checkpoint: $_"
}`;
    }
  },

  // ==================== Reporting ====================
  {
    id: 'hyperv-export-inventory',
    title: 'Export VM Inventory',
    description: 'Export inventory of all Hyper-V VMs to CSV',
    category: 'Reporting',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\HyperV-Inventory.csv',
        helpText: 'CSV file path'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Hyper-V VM Inventory
# Generated by PSForge

try {
    Write-Host "Collecting Hyper-V VM inventory..." -ForegroundColor Cyan
    
    $VMs = Get-VM
    Write-Host "Found $($VMs.Count) VMs" -ForegroundColor Yellow
    
    $Inventory = foreach ($VM in $VMs) {
        [PSCustomObject]@{
            Name              = $VM.Name
            State             = $VM.State
            Generation        = $VM.Generation
            ProcessorCount    = $VM.ProcessorCount
            MemoryGB          = [math]::Round($VM.MemoryStartup / 1GB, 2)
            DynamicMemory     = $VM.DynamicMemoryEnabled
            Path              = $VM.Path
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Inventory exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host \"\`nVMs by State:" -ForegroundColor Yellow
    $Inventory | Group-Object State | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export inventory: $_"
}`;
    }
  }
];

export const hyperVCategories = [
  'Host Configuration',
  'VM Lifecycle',
  'Storage',
  'Checkpoints',
  'Reporting'
];
