import { escapePowerShellString } from './powershell-utils';

export interface HyperVParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface HyperVTask {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: HyperVParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const hyperVTasks: HyperVTask[] = [
  // ==================== Host Configuration ====================
  {
    id: 'hyperv-install-role',
    title: 'Install Hyper-V Role',
    description: 'Install and configure the Hyper-V role on a Windows Server',
    category: 'Host Configuration',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'HV-HOST01',
        helpText: 'Name of the server to configure'
      },
      {
        name: 'includeManagementTools',
        label: 'Include Management Tools',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Install Hyper-V PowerShell and management tools'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const includeMgmtTools = params.includeManagementTools !== false;

      return `# Install Hyper-V Role
# Generated by PSForge

try {
    Write-Host "Installing Hyper-V role on: ${serverName}" -ForegroundColor Cyan
    
    $Features = @("Hyper-V")
    ${includeMgmtTools ? '$Features += "Hyper-V-PowerShell", "Hyper-V-Tools"' : ''}
    
    $Result = Install-WindowsFeature -Name $Features -ComputerName "${serverName}" -IncludeManagementTools
    
    if ($Result.Success) {
        Write-Host "✓ Hyper-V role installed successfully" -ForegroundColor Green
    }
    
    $Result | Select-Object Success, RestartNeeded, ExitCode | Format-List
    
} catch {
    Write-Error "Failed to install Hyper-V role: $_"
}`;
    }
  },

  {
    id: 'hyperv-create-vswitch',
    title: 'Create Virtual Switch',
    description: 'Create a Hyper-V virtual switch (External/Internal/Private)',
    category: 'Host Configuration',
    parameters: [
      {
        name: 'switchName',
        label: 'Switch Name',
        type: 'text',
        required: true,
        placeholder: 'vSwitch-External',
        helpText: 'Name for the virtual switch'
      },
      {
        name: 'switchType',
        label: 'Switch Type',
        type: 'select',
        required: true,
        options: [
          { value: 'External', label: 'External (Connects to physical network)' },
          { value: 'Internal', label: 'Internal (Host and VMs only)' },
          { value: 'Private', label: 'Private (VMs only)' }
        ],
        helpText: 'Type of virtual switch'
      },
      {
        name: 'netAdapterName',
        label: 'Network Adapter Name (for External)',
        type: 'text',
        required: false,
        placeholder: 'Ethernet',
        helpText: 'Required for External switch type'
      }
    ],
    scriptTemplate: (params) => {
      const switchName = escapePowerShellString(params.switchName);
      const switchType = params.switchType;
      const adapterName = params.netAdapterName ? escapePowerShellString(params.netAdapterName) : '';

      return `# Create Hyper-V Virtual Switch
# Generated by PSForge

try {
    Write-Host "Creating ${switchType} virtual switch: ${switchName}" -ForegroundColor Cyan
    
    ${switchType === 'External' ? `
    if (-not "${adapterName}") {
        throw "Network adapter name is required for External switch"
    }
    $NetAdapter = Get-NetAdapter -Name "${adapterName}" -ErrorAction Stop
    New-VMSwitch -Name "${switchName}" -NetAdapterName $NetAdapter.Name -AllowManagementOS $true
    ` : switchType === 'Internal' ? `
    New-VMSwitch -Name "${switchName}" -SwitchType Internal
    ` : `
    New-VMSwitch -Name "${switchName}" -SwitchType Private
    `}
    
    Write-Host "✓ Virtual switch created successfully" -ForegroundColor Green
    
    Get-VMSwitch -Name "${switchName}" | Select-Object Name, SwitchType, Id | Format-List
    
} catch {
    Write-Error "Failed to create virtual switch: $_"
}`;
    }
  },

  // ==================== VM Lifecycle ====================
  {
    id: 'hyperv-create-vm',
    title: 'Create Virtual Machine',
    description: 'Create a new Hyper-V virtual machine',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'Name for the virtual machine'
      },
      {
        name: 'generation',
        label: 'VM Generation',
        type: 'select',
        required: true,
        options: [
          { value: '1', label: 'Generation 1 (Legacy BIOS)' },
          { value: '2', label: 'Generation 2 (UEFI)' }
        ],
        defaultValue: '2',
        helpText: 'VM generation'
      },
      {
        name: 'memoryGB',
        label: 'Memory (GB)',
        type: 'number',
        required: true,
        defaultValue: 4,
        helpText: 'Amount of memory in GB'
      },
      {
        name: 'processorCount',
        label: 'Processor Count',
        type: 'number',
        required: true,
        defaultValue: 2,
        helpText: 'Number of virtual processors'
      },
      {
        name: 'vhdSizeGB',
        label: 'VHD Size (GB)',
        type: 'number',
        required: true,
        defaultValue: 60,
        helpText: 'Size of virtual hard disk in GB'
      },
      {
        name: 'switchName',
        label: 'Virtual Switch Name',
        type: 'text',
        required: true,
        placeholder: 'vSwitch-External',
        helpText: 'Virtual switch to connect to'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const generation = params.generation || '2';
      const memoryGB = params.memoryGB || 4;
      const cpuCount = params.processorCount || 2;
      const vhdSizeGB = params.vhdSizeGB || 60;
      const switchName = escapePowerShellString(params.switchName);

      return `# Create Hyper-V Virtual Machine
# Generated by PSForge

try {
    Write-Host "Creating Virtual Machine: ${vmName}" -ForegroundColor Cyan
    
    $HostSettings = Get-VMHost
    $VmPath = $HostSettings.VirtualMachinePath
    $VhdPath = $HostSettings.VirtualHardDiskPath
    
    $MemoryBytes = ${memoryGB}GB
    $VhdSizeBytes = ${vhdSizeGB}GB
    $VhdFilePath = Join-Path $VhdPath "${vmName}.vhdx"
    
    New-VM -Name "${vmName}" -Generation ${generation} -MemoryStartupBytes $MemoryBytes -Path $VmPath -NewVHDPath $VhdFilePath -NewVHDSizeBytes $VhdSizeBytes -SwitchName "${switchName}"
    
    Set-VMProcessor -VMName "${vmName}" -Count ${cpuCount}
    
    Write-Host "✓ Virtual Machine created successfully" -ForegroundColor Green
    
    Get-VM -Name "${vmName}" | Select-Object Name, Generation, State, ProcessorCount | Format-List
    
} catch {
    Write-Error "Failed to create VM: $_"
}`;
    }
  },

  {
    id: 'hyperv-start-stop-vm',
    title: 'Start/Stop VMs',
    description: 'Perform power operations on Hyper-V virtual machines',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'action',
        label: 'Action',
        type: 'select',
        required: true,
        options: [
          { value: 'Start', label: 'Start VMs' },
          { value: 'Stop', label: 'Stop VMs' },
          { value: 'Restart', label: 'Restart VMs' }
        ],
        helpText: 'Power operation to perform'
      },
      {
        name: 'vmNames',
        label: 'VM Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'VM-WEB01\nVM-DB01',
        helpText: 'List of VM names'
      }
    ],
    scriptTemplate: (params) => {
      const action = params.action;
      const vmNamesInput = params.vmNames.trim();

      return `# ${action} Hyper-V Virtual Machines
# Generated by PSForge

try {
    $VmNames = @(
${vmNamesInput.split('\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join('\n')}
    )
    
    Write-Host "Target VMs: $($VmNames.Count)" -ForegroundColor Cyan
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($VmName in $VmNames) {
        try {
            Write-Host "${action}ing: $VmName..." -ForegroundColor Cyan
            
            ${action === 'Start' ? 'Start-VM -Name $VmName' : ''}
            ${action === 'Stop' ? 'Stop-VM -Name $VmName -Force' : ''}
            ${action === 'Restart' ? 'Restart-VM -Name $VmName -Force' : ''}
            
            Write-Host "✓ $VmName ${action.toLowerCase()} completed" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed: $VmName - $_"
            $FailCount++
        }
    }
    
    Write-Host \"\`n${action} Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Operation failed: $_"
}`;
    }
  },

  {
    id: 'hyperv-export-vm',
    title: 'Export Virtual Machine',
    description: 'Export a Hyper-V VM for backup or migration',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'VM to export'
      },
      {
        name: 'exportPath',
        label: 'Export Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\VMExports',
        helpText: 'Destination folder'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Hyper-V Virtual Machine
# Generated by PSForge

try {
    Write-Host "Exporting VM: ${vmName}" -ForegroundColor Cyan
    
    if (-not (Test-Path "${exportPath}")) {
        New-Item -Path "${exportPath}" -ItemType Directory -Force | Out-Null
    }
    
    Export-VM -Name "${vmName}" -Path "${exportPath}"
    
    Write-Host "✓ VM exported successfully" -ForegroundColor Green
    
    $ExportFolder = Join-Path "${exportPath}" "${vmName}"
    Write-Host "  Location: $ExportFolder" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export VM: $_"
}`;
    }
  },

  // ==================== Storage ====================
  {
    id: 'hyperv-create-vhd',
    title: 'Create Virtual Hard Disk',
    description: 'Create a new VHDX file',
    category: 'Storage',
    parameters: [
      {
        name: 'vhdPath',
        label: 'VHD Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Hyper-V\\Disks\\Data01.vhdx',
        helpText: 'Full path for the new VHDX'
      },
      {
        name: 'sizeGB',
        label: 'Size (GB)',
        type: 'number',
        required: true,
        defaultValue: 60,
        helpText: 'Size in GB'
      },
      {
        name: 'diskType',
        label: 'Disk Type',
        type: 'select',
        required: true,
        options: [
          { value: 'Dynamic', label: 'Dynamic' },
          { value: 'Fixed', label: 'Fixed' }
        ],
        defaultValue: 'Dynamic',
        helpText: 'Disk allocation type'
      }
    ],
    scriptTemplate: (params) => {
      const vhdPath = escapePowerShellString(params.vhdPath);
      const sizeGB = params.sizeGB || 60;
      const diskType = params.diskType || 'Dynamic';

      return `# Create Virtual Hard Disk
# Generated by PSForge

try {
    Write-Host "Creating ${diskType} VHDX: ${vhdPath}" -ForegroundColor Cyan
    
    $SizeBytes = ${sizeGB}GB
    
    New-VHD -Path "${vhdPath}" -SizeBytes $SizeBytes -${diskType}
    
    Write-Host "✓ Virtual hard disk created successfully" -ForegroundColor Green
    
    Get-VHD -Path "${vhdPath}" | Select-Object Path, VhdType, Size | Format-List
    
} catch {
    Write-Error "Failed to create VHD: $_"
}`;
    }
  },

  {
    id: 'hyperv-resize-vhd',
    title: 'Resize Virtual Hard Disk',
    description: 'Expand a VHDX file',
    category: 'Storage',
    parameters: [
      {
        name: 'vhdPath',
        label: 'VHD Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Hyper-V\\Disks\\Data01.vhdx',
        helpText: 'Path to the VHDX file'
      },
      {
        name: 'newSizeGB',
        label: 'New Size (GB)',
        type: 'number',
        required: true,
        placeholder: '100',
        helpText: 'New size in GB'
      }
    ],
    scriptTemplate: (params) => {
      const vhdPath = escapePowerShellString(params.vhdPath);
      const newSizeGB = params.newSizeGB;

      return `# Resize Virtual Hard Disk
# Generated by PSForge

try {
    Write-Host "Resizing VHD: ${vhdPath}" -ForegroundColor Cyan
    
    $VHD = Get-VHD -Path "${vhdPath}"
    $CurrentSizeGB = [math]::Round($VHD.Size / 1GB, 2)
    
    Write-Host "Current Size: $CurrentSizeGB GB" -ForegroundColor Yellow
    Write-Host "New Size: ${newSizeGB} GB" -ForegroundColor Yellow
    
    $NewSizeBytes = ${newSizeGB}GB
    
    Resize-VHD -Path "${vhdPath}" -SizeBytes $NewSizeBytes
    
    Write-Host "✓ VHD resized successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to resize VHD: $_"
}`;
    }
  },

  // ==================== Checkpoints ====================
  {
    id: 'hyperv-create-checkpoint',
    title: 'Create VM Checkpoint',
    description: 'Create a checkpoint (snapshot) of a virtual machine',
    category: 'Checkpoints',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'VM to checkpoint'
      },
      {
        name: 'checkpointName',
        label: 'Checkpoint Name',
        type: 'text',
        required: false,
        placeholder: 'Before Windows Update',
        helpText: 'Optional checkpoint name'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const checkpointName = params.checkpointName ? escapePowerShellString(params.checkpointName) : '';

      return `# Create VM Checkpoint
# Generated by PSForge

try {
    Write-Host "Creating checkpoint for VM: ${vmName}" -ForegroundColor Cyan
    
    ${checkpointName ? `
    $CheckpointName = "${checkpointName}"
    ` : `
    $CheckpointName = "Checkpoint-$(Get-Date -Format 'yyyy-MM-dd-HHmmss')"
    `}
    
    Checkpoint-VM -Name "${vmName}" -SnapshotName $CheckpointName
    
    Write-Host "✓ Checkpoint created: $CheckpointName" -ForegroundColor Green
    
    Get-VMCheckpoint -VMName "${vmName}" | Select-Object Name, CreationTime | Format-Table
    
} catch {
    Write-Error "Failed to create checkpoint: $_"
}`;
    }
  },

  // ==================== Reporting ====================
  {
    id: 'hyperv-export-inventory',
    title: 'Export VM Inventory',
    description: 'Export inventory of all Hyper-V VMs to CSV',
    category: 'Reporting',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\HyperV-Inventory.csv',
        helpText: 'CSV file path'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Hyper-V VM Inventory
# Generated by PSForge

try {
    Write-Host "Collecting Hyper-V VM inventory..." -ForegroundColor Cyan
    
    $VMs = Get-VM
    Write-Host "Found $($VMs.Count) VMs" -ForegroundColor Yellow
    
    $Inventory = foreach ($VM in $VMs) {
        [PSCustomObject]@{
            Name              = $VM.Name
            State             = $VM.State
            Generation        = $VM.Generation
            ProcessorCount    = $VM.ProcessorCount
            MemoryGB          = [math]::Round($VM.MemoryStartup / 1GB, 2)
            DynamicMemory     = $VM.DynamicMemoryEnabled
            Path              = $VM.Path
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Inventory exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host \"\`nVMs by State:" -ForegroundColor Yellow
    $Inventory | Group-Object State | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export inventory: $_"
}`;
    }
  },

  // ==================== Additional VM Lifecycle ====================
  {
    id: 'hyperv-clone-vm',
    title: 'Clone Virtual Machine',
    description: 'Create an exact copy of an existing VM',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'sourceVmName',
        label: 'Source VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-Template',
        helpText: 'VM to clone'
      },
      {
        name: 'newVmName',
        label: 'New VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-Clone01',
        helpText: 'Name for the cloned VM'
      },
      {
        name: 'newVmPath',
        label: 'Destination Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Hyper-V\\VMs',
        helpText: 'Path for the new VM files'
      }
    ],
    scriptTemplate: (params) => {
      const sourceVm = escapePowerShellString(params.sourceVmName);
      const newVm = escapePowerShellString(params.newVmName);
      const vmPath = escapePowerShellString(params.newVmPath);

      return `# Clone Hyper-V Virtual Machine
# Generated by PSForge

try {
    Write-Host "Cloning VM: ${sourceVm} to ${newVm}" -ForegroundColor Cyan
    
    $SourceVM = Get-VM -Name "${sourceVm}"
    
    if ($SourceVM.State -ne "Off") {
        Write-Warning "Source VM must be powered off. Shutting down..."
        Stop-VM -Name "${sourceVm}" -Force
        Start-Sleep -Seconds 5
    }
    
    Export-VM -Name "${sourceVm}" -Path "${vmPath}" -ErrorAction Stop
    
    $ExportPath = Join-Path "${vmPath}" "${sourceVm}"
    $VmConfigPath = Get-ChildItem -Path $ExportPath -Filter "*.vmcx" -Recurse | Select-Object -First 1
    
    Import-VM -Path $VmConfigPath.FullName -Copy -GenerateNewId -VhdDestinationPath "${vmPath}" -VirtualMachinePath "${vmPath}"
    
    Rename-VM -Name "${sourceVm}" -NewName "${newVm}"
    
    Write-Host "✓ VM cloned successfully: ${newVm}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to clone VM: $_"
}`;
    }
  },

  {
    id: 'hyperv-configure-vm-memory',
    title: 'Configure Dynamic Memory',
    description: 'Configure dynamic or static memory settings for a VM',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'enableDynamic',
        label: 'Enable Dynamic Memory',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Enable dynamic memory allocation'
      },
      {
        name: 'startupMemoryGB',
        label: 'Startup Memory (GB)',
        type: 'number',
        required: true,
        defaultValue: 4,
        helpText: 'Initial memory allocation'
      },
      {
        name: 'maxMemoryGB',
        label: 'Maximum Memory (GB)',
        type: 'number',
        required: false,
        defaultValue: 8,
        helpText: 'Maximum dynamic memory (if enabled)'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const enableDynamic = params.enableDynamic !== false;
      const startupMB = (params.startupMemoryGB || 4) * 1024;
      const maxMB = (params.maxMemoryGB || 8) * 1024;

      return `# Configure VM Memory
# Generated by PSForge

try {
    Write-Host "Configuring memory for: ${vmName}" -ForegroundColor Cyan
    
    $VM = Get-VM -Name "${vmName}"
    
    if ($VM.State -ne "Off") {
        Write-Host "Stopping VM..." -ForegroundColor Yellow
        Stop-VM -Name "${vmName}" -Force
    }
    
    Set-VMMemory -VMName "${vmName}" -DynamicMemoryEnabled \$${enableDynamic} -StartupBytes ${startupMB}MB
    
    ${enableDynamic ? `Set-VMMemory -VMName "${vmName}" -MaximumBytes ${maxMB}MB -MinimumBytes ${startupMB}MB` : ''}
    
    Write-Host "✓ Memory configured:" -ForegroundColor Green
    Write-Host "  Startup: ${params.startupMemoryGB || 4} GB" -ForegroundColor Yellow
    ${enableDynamic ? `Write-Host "  Maximum: ${params.maxMemoryGB || 8} GB (Dynamic)" -ForegroundColor Yellow` : ''}
    
} catch {
    Write-Error "Failed to configure memory: $_"
}`;
    }
  },

  {
    id: 'hyperv-configure-vhd-qos',
    title: 'Configure Storage QoS',
    description: 'Set IOPS limits and QoS policies for VM virtual disks',
    category: 'Storage',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-SQL01',
        helpText: 'Target virtual machine'
      },
      {
        name: 'maxIOPS',
        label: 'Maximum IOPS',
        type: 'number',
        required: true,
        defaultValue: 5000,
        helpText: 'Maximum IOPS limit'
      },
      {
        name: 'minIOPS',
        label: 'Minimum IOPS',
        type: 'number',
        required: true,
        defaultValue: 100,
        helpText: 'Minimum guaranteed IOPS'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const maxIOPS = params.maxIOPS || 5000;
      const minIOPS = params.minIOPS || 100;

      return `# Configure Storage QoS
# Generated by PSForge

try {
    Write-Host "Configuring Storage QoS for: ${vmName}" -ForegroundColor Cyan
    
    $VHDs = Get-VMHardDiskDrive -VMName "${vmName}"
    
    foreach ($VHD in $VHDs) {
        Set-VMHardDiskDrive -VMName "${vmName}" -ControllerType $VHD.ControllerType -ControllerNumber $VHD.ControllerNumber -ControllerLocation $VHD.ControllerLocation -MaximumIOPS ${maxIOPS} -MinimumIOPS ${minIOPS}
        
        Write-Host "✓ QoS configured for: $($VHD.Path)" -ForegroundColor Green
    }
    
    Write-Host ${'\`n'}"QoS Settings:" -ForegroundColor Yellow
    Write-Host "  Maximum IOPS: ${maxIOPS}"
    Write-Host "  Minimum IOPS: ${minIOPS}"
    
} catch {
    Write-Error "Failed to configure QoS: $_"
}`;
    }
  },

  {
    id: 'hyperv-expand-vhd',
    title: 'Expand Virtual Hard Disk',
    description: 'Increase the size of a virtual hard disk',
    category: 'Storage',
    parameters: [
      {
        name: 'vhdPath',
        label: 'VHD Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Hyper-V\\VMs\\VM01\\disk.vhdx',
        helpText: 'Path to the VHD/VHDX file'
      },
      {
        name: 'newSizeGB',
        label: 'New Size (GB)',
        type: 'number',
        required: true,
        defaultValue: 500,
        helpText: 'New disk size in GB'
      }
    ],
    scriptTemplate: (params) => {
      const vhdPath = escapePowerShellString(params.vhdPath);
      const newSizeGB = params.newSizeGB || 500;

      return `# Expand Virtual Hard Disk
# Generated by PSForge

try {
    Write-Host "Expanding VHD: ${vhdPath}" -ForegroundColor Cyan
    
    $VHD = Get-VHD -Path "${vhdPath}"
    $CurrentSizeGB = [math]::Round($VHD.Size / 1GB, 2)
    
    if (${newSizeGB} -le $CurrentSizeGB) {
        Write-Warning "New size must be larger than current size ($CurrentSizeGB GB)"
        exit
    }
    
    Resize-VHD -Path "${vhdPath}" -SizeBytes ${newSizeGB}GB
    
    Write-Host "✓ VHD expanded successfully" -ForegroundColor Green
    Write-Host "  Old size: $CurrentSizeGB GB" -ForegroundColor Yellow
    Write-Host "  New size: ${newSizeGB} GB" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to expand VHD: $_"
}`;
    }
  },

  {
    id: 'hyperv-optimize-vhd',
    title: 'Optimize and Compact VHD',
    description: 'Compact a virtual hard disk to reclaim unused space',
    category: 'Storage',
    parameters: [
      {
        name: 'vhdPath',
        label: 'VHD Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Hyper-V\\VMs\\VM01\\disk.vhdx',
        helpText: 'Path to the VHD/VHDX file'
      }
    ],
    scriptTemplate: (params) => {
      const vhdPath = escapePowerShellString(params.vhdPath);

      return `# Optimize and Compact VHD
# Generated by PSForge

try {
    Write-Host "Optimizing VHD: ${vhdPath}" -ForegroundColor Cyan
    
    $VHDBefore = Get-VHD -Path "${vhdPath}"
    $SizeBefore = [math]::Round($VHDBefore.FileSize / 1GB, 2)
    
    Write-Host "Current size: $SizeBefore GB" -ForegroundColor Yellow
    Write-Host "Starting optimization (this may take several minutes)..." -ForegroundColor Cyan
    
    Optimize-VHD -Path "${vhdPath}" -Mode Full
    
    $VHDAfter = Get-VHD -Path "${vhdPath}"
    $SizeAfter = [math]::Round($VHDAfter.FileSize / 1GB, 2)
    $Saved = [math]::Round($SizeBefore - $SizeAfter, 2)
    
    Write-Host "✓ Optimization complete" -ForegroundColor Green
    Write-Host "  Before: $SizeBefore GB" -ForegroundColor Yellow
    Write-Host "  After: $SizeAfter GB" -ForegroundColor Yellow
    Write-Host "  Reclaimed: $Saved GB" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to optimize VHD: $_"
}`;
    }
  },

  {
    id: 'hyperv-new-vswitch',
    title: 'Create Virtual Switch',
    description: 'Create external, internal, or private virtual switch',
    category: 'Networking',
    parameters: [
      {
        name: 'switchName',
        label: 'Switch Name',
        type: 'text',
        required: true,
        placeholder: 'vSwitch-External',
        helpText: 'Name for the virtual switch'
      },
      {
        name: 'switchType',
        label: 'Switch Type',
        type: 'select',
        required: true,
        options: [
          { value: 'External', label: 'External (connects to physical network)' },
          { value: 'Internal', label: 'Internal (host and VMs only)' },
          { value: 'Private', label: 'Private (VMs only)' }
        ],
        helpText: 'Type of virtual switch'
      },
      {
        name: 'netAdapterName',
        label: 'Network Adapter Name (for External)',
        type: 'text',
        required: false,
        placeholder: 'Ethernet',
        helpText: 'Physical adapter to bind (External only)'
      }
    ],
    scriptTemplate: (params) => {
      const switchName = escapePowerShellString(params.switchName);
      const switchType = params.switchType;
      const adapterName = params.netAdapterName ? escapePowerShellString(params.netAdapterName) : '';

      return `# Create Virtual Switch
# Generated by PSForge

try {
    Write-Host "Creating ${switchType} virtual switch: ${switchName}" -ForegroundColor Cyan
    
    ${switchType === 'External' && adapterName ? `
    $NetAdapter = Get-NetAdapter -Name "${adapterName}" -ErrorAction Stop
    New-VMSwitch -Name "${switchName}" -NetAdapterName "${adapterName}" -AllowManagementOS $true
    ` : ''}
    
    ${switchType === 'Internal' ? `
    New-VMSwitch -Name "${switchName}" -SwitchType Internal
    ` : ''}
    
    ${switchType === 'Private' ? `
    New-VMSwitch -Name "${switchName}" -SwitchType Private
    ` : ''}
    
    Write-Host "✓ Virtual switch created successfully" -ForegroundColor Green
    
    $Switch = Get-VMSwitch -Name "${switchName}"
    Write-Host ${'\`n'}"Switch Details:" -ForegroundColor Yellow
    Write-Host "  Name: $($Switch.Name)"
    Write-Host "  Type: $($Switch.SwitchType)"
    
} catch {
    Write-Error "Failed to create virtual switch: $_"
}`;
    }
  },

  {
    id: 'hyperv-configure-vlan',
    title: 'Configure VM VLAN Tagging',
    description: 'Set VLAN ID for VM network adapter',
    category: 'Networking',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'vlanId',
        label: 'VLAN ID',
        type: 'number',
        required: true,
        defaultValue: 100,
        helpText: 'VLAN ID (1-4094)'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const vlanId = params.vlanId || 100;

      return `# Configure VM VLAN Tagging
# Generated by PSForge

try {
    Write-Host "Configuring VLAN ${vlanId} for: ${vmName}" -ForegroundColor Cyan
    
    $VMNetAdapter = Get-VMNetworkAdapter -VMName "${vmName}"
    
    Set-VMNetworkAdapterVlan -VMNetworkAdapter $VMNetAdapter -Access -VlanId ${vlanId}
    
    Write-Host "✓ VLAN configured successfully" -ForegroundColor Green
    Write-Host "  VM: ${vmName}" -ForegroundColor Yellow
    Write-Host "  VLAN ID: ${vlanId}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to configure VLAN: $_"
}`;
    }
  },

  {
    id: 'hyperv-create-replica',
    title: 'Configure VM Replication',
    description: 'Set up Hyper-V Replica for disaster recovery',
    category: 'Backup & Recovery',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-DC01',
        helpText: 'VM to replicate'
      },
      {
        name: 'replicaServer',
        label: 'Replica Server',
        type: 'text',
        required: true,
        placeholder: 'HV-REPLICA01',
        helpText: 'Destination Hyper-V server'
      },
      {
        name: 'replicationFrequency',
        label: 'Replication Frequency (seconds)',
        type: 'select',
        required: true,
        options: [
          { value: '30', label: '30 seconds' },
          { value: '300', label: '5 minutes' },
          { value: '900', label: '15 minutes' }
        ],
        helpText: 'How often to replicate changes'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const replicaServer = escapePowerShellString(params.replicaServer);
      const frequency = params.replicationFrequency || '300';

      return `# Configure VM Replication
# Generated by PSForge

try {
    Write-Host "Configuring replication for: ${vmName}" -ForegroundColor Cyan
    
    Enable-VMReplication -VMName "${vmName}" -ReplicaServerName "${replicaServer}" -ReplicaServerPort 80 -AuthenticationType Kerberos -CompressionEnabled \$true -ReplicationFrequencySec ${frequency}
    
    Write-Host "Starting initial replication..." -ForegroundColor Cyan
    Start-VMInitialReplication -VMName "${vmName}"
    
    Write-Host "✓ Replication configured successfully" -ForegroundColor Green
    Write-Host "  VM: ${vmName}" -ForegroundColor Yellow
    Write-Host "  Replica Server: ${replicaServer}" -ForegroundColor Yellow
    Write-Host "  Frequency: ${frequency} seconds" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to configure replication: $_"
}`;
    }
  },

  {
    id: 'hyperv-apply-vm-snapshot',
    title: 'Apply VM Checkpoint',
    description: 'Restore a VM to a previous checkpoint/snapshot state',
    category: 'Checkpoints',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'checkpointName',
        label: 'Checkpoint Name',
        type: 'text',
        required: true,
        placeholder: 'Before-Update',
        helpText: 'Name of checkpoint to restore'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const checkpointName = escapePowerShellString(params.checkpointName);

      return `# Apply VM Checkpoint
# Generated by PSForge

try {
    Write-Host "Applying checkpoint: ${checkpointName}" -ForegroundColor Cyan
    
    $VM = Get-VM -Name "${vmName}"
    
    if ($VM.State -ne "Off") {
        Write-Host "Stopping VM..." -ForegroundColor Yellow
        Stop-VM -Name "${vmName}" -Force
    }
    
    $Checkpoint = Get-VMSnapshot -VMName "${vmName}" -Name "${checkpointName}"
    
    if (-not $Checkpoint) {
        throw "Checkpoint not found: ${checkpointName}"
    }
    
    Restore-VMSnapshot -VMName "${vmName}" -Name "${checkpointName}" -Confirm:\$false
    
    Write-Host "✓ Checkpoint applied successfully" -ForegroundColor Green
    Write-Host "  VM restored to: ${checkpointName}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to apply checkpoint: $_"
}`;
    }
  },

  {
    id: 'hyperv-remove-old-checkpoints',
    title: 'Remove Old Checkpoints',
    description: 'Delete checkpoints older than specified days to free disk space',
    category: 'Checkpoints',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'olderThanDays',
        label: 'Older Than (days)',
        type: 'number',
        required: true,
        defaultValue: 30,
        helpText: 'Remove checkpoints older than this many days'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const olderThanDays = params.olderThanDays || 30;

      return `# Remove Old Checkpoints
# Generated by PSForge

try {
    Write-Host "Removing checkpoints older than ${olderThanDays} days for: ${vmName}" -ForegroundColor Cyan
    
    $CutoffDate = (Get-Date).AddDays(-${olderThanDays})
    $Checkpoints = Get-VMSnapshot -VMName "${vmName}" | Where-Object { $_.CreationTime -lt $CutoffDate }
    
    if ($Checkpoints.Count -eq 0) {
        Write-Host "No old checkpoints found" -ForegroundColor Yellow
        exit
    }
    
    Write-Host "Found $($Checkpoints.Count) old checkpoints" -ForegroundColor Yellow
    
    foreach ($Checkpoint in $Checkpoints) {
        Write-Host "  Removing: $($Checkpoint.Name) ($(($Checkpoint.CreationTime).ToString('yyyy-MM-dd')))" -ForegroundColor Cyan
        Remove-VMSnapshot -VMName "${vmName}" -Name $Checkpoint.Name -Confirm:\$false
    }
    
    Write-Host "✓ Old checkpoints removed successfully" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to remove checkpoints: $_"
}`;
    }
  },

  {
    id: 'hyperv-measure-vm-performance',
    title: 'Measure VM Performance Metrics',
    description: 'Collect CPU, memory, and disk performance metrics for VMs',
    category: 'Reporting',
    parameters: [
      {
        name: 'vmNames',
        label: 'VM Names (one per line, or blank for all)',
        type: 'textarea',
        required: false,
        placeholder: 'VM-WEB01\nVM-SQL01',
        helpText: 'VMs to monitor (blank = all VMs)'
      },
      {
        name: 'durationSeconds',
        label: 'Measurement Duration (seconds)',
        type: 'number',
        required: true,
        defaultValue: 60,
        helpText: 'How long to collect metrics'
      }
    ],
    scriptTemplate: (params) => {
      const vmNamesInput = params.vmNames || '';
      const duration = params.durationSeconds || 60;

      return `# Measure VM Performance
# Generated by PSForge

try {
    Write-Host "Collecting performance metrics for ${duration} seconds..." -ForegroundColor Cyan
    
    ${vmNamesInput.trim() ? `
    $VMNames = @(
${vmNamesInput.split('\\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join(',\\n')}
    )
    $VMs = Get-VM -Name $VMNames
    ` : `
    $VMs = Get-VM
    `}
    
    $Results = @()
    
    foreach ($VM in $VMs) {
        if ($VM.State -eq "Running") {
            $CPUUsage = (Measure-VM -Name $VM.Name).AvgCPUUsage
            $MemoryAssigned = [math]::Round($VM.MemoryAssigned / 1GB, 2)
            
            $Results += [PSCustomObject]@{
                VMName = $VM.Name
                CPUUsage = "$CPUUsage%"
                MemoryGB = $MemoryAssigned
                State = $VM.State
            }
        }
    }
    
    Write-Host ${'\`n'}"Performance Metrics:" -ForegroundColor Yellow
    $Results | Format-Table -AutoSize
    
} catch {
    Write-Error "Failed to collect performance metrics: $_"
}`;
    }
  },

  {
    id: 'hyperv-bulk-create-vms',
    title: 'Bulk Create VMs from CSV',
    description: 'Create multiple VMs from a CSV file specification',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'csvPath',
        label: 'CSV File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Scripts\\VMs.csv',
        helpText: 'CSV with columns: Name, MemoryGB, DiskSizeGB, SwitchName'
      },
      {
        name: 'vmPath',
        label: 'VM Storage Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Hyper-V\\VMs',
        helpText: 'Base path for VM files'
      }
    ],
    scriptTemplate: (params) => {
      const csvPath = escapePowerShellString(params.csvPath);
      const vmPath = escapePowerShellString(params.vmPath);

      return `# Bulk Create VMs from CSV
# Generated by PSForge

try {
    Write-Host "Loading VM specifications from CSV..." -ForegroundColor Cyan
    
    $VMSpecs = Import-Csv -Path "${csvPath}"
    
    Write-Host "Creating $($VMSpecs.Count) VMs..." -ForegroundColor Yellow
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($Spec in $VMSpecs) {
        try {
            $VMName = $Spec.Name
            $MemoryBytes = [int64]$Spec.MemoryGB * 1GB
            $DiskSize = [int64]$Spec.DiskSizeGB * 1GB
            
            $VMFolder = Join-Path "${vmPath}" $VMName
            New-Item -ItemType Directory -Path $VMFolder -Force | Out-Null
            
            $VHDPath = Join-Path $VMFolder "$VMName.vhdx"
            New-VHD -Path $VHDPath -SizeBytes $DiskSize -Dynamic | Out-Null
            
            New-VM -Name $VMName -MemoryStartupBytes $MemoryBytes -VHDPath $VHDPath -Generation 2 -SwitchName $Spec.SwitchName -Path "${vmPath}"
            
            Write-Host "✓ Created: $VMName" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed: $VMName - $_"
            $FailCount++
        }
    }
    
    Write-Host ${'\`n'}"Bulk Creation Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to process CSV: $_"
}`;
    }
  },

  {
    id: 'hyperv-configure-integration-services',
    title: 'Configure Integration Services',
    description: 'Enable or disable specific integration services for a VM',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'enableAll',
        label: 'Enable All Services',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Enable all integration services'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const enableAll = params.enableAll !== false;

      return `# Configure Integration Services
# Generated by PSForge

try {
    Write-Host "Configuring integration services for: ${vmName}" -ForegroundColor Cyan
    
    $Services = Get-VMIntegrationService -VMName "${vmName}"
    
    foreach ($Service in $Services) {
        if ($Service.Name -ne "Heartbeat") {
            ${enableAll ? 'Enable-VMIntegrationService' : 'Disable-VMIntegrationService'} -VMName "${vmName}" -Name $Service.Name
            Write-Host "  $($Service.Name): ${enableAll ? 'Enabled' : 'Disabled'}" -ForegroundColor Yellow
        }
    }
    
    Write-Host "✓ Integration services configured" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to configure integration services: $_"
}`;
    }
  },

  {
    id: 'hyperv-export-vm-configs',
    title: 'Export VM Configurations',
    description: 'Export all VM settings and configurations to JSON',
    category: 'Reporting',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export JSON Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\VM-Configs.json',
        helpText: 'Path for JSON export'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export VM Configurations
# Generated by PSForge

try {
    Write-Host "Collecting VM configurations..." -ForegroundColor Cyan
    
    $VMs = Get-VM
    
    $Configs = foreach ($VM in $VMs) {
        $NetAdapters = Get-VMNetworkAdapter -VMName $VM.Name
        $Disks = Get-VMHardDiskDrive -VMName $VM.Name
        
        [PSCustomObject]@{
            Name = $VM.Name
            State = $VM.State
            Generation = $VM.Generation
            ProcessorCount = $VM.ProcessorCount
            MemoryStartupGB = [math]::Round($VM.MemoryStartup / 1GB, 2)
            DynamicMemory = $VM.DynamicMemoryEnabled
            AutomaticStartAction = $VM.AutomaticStartAction
            AutomaticStopAction = $VM.AutomaticStopAction
            NetworkAdapters = @($NetAdapters | ForEach-Object {
                @{
                    Name = $_.Name
                    SwitchName = $_.SwitchName
                    MacAddress = $_.MacAddress
                }
            })
            VirtualDisks = @($Disks | ForEach-Object {
                @{
                    Path = $_.Path
                    ControllerType = $_.ControllerType
                    ControllerLocation = $_.ControllerLocation
                }
            })
        }
    }
    
    $Configs | ConvertTo-Json -Depth 10 | Out-File "${exportPath}"
    
    Write-Host "✓ VM configurations exported to: ${exportPath}" -ForegroundColor Green
    Write-Host "  Total VMs: $($VMs.Count)" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to export configurations: $_"
}`;
    }
  },

  {
    id: 'hyperv-configure-enhanced-session',
    title: 'Enable Enhanced Session Mode',
    description: 'Enable enhanced session mode for better VM connectivity',
    category: 'Host Configuration',
    parameters: [
      {
        name: 'enable',
        label: 'Enable Enhanced Session Mode',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Enable or disable enhanced session mode'
      }
    ],
    scriptTemplate: (params) => {
      const enable = params.enable !== false;

      return `# Configure Enhanced Session Mode
# Generated by PSForge

try {
    Write-Host "${enable ? 'Enabling' : 'Disabling'} enhanced session mode..." -ForegroundColor Cyan
    
    Set-VMHost -EnableEnhancedSessionMode \$${enable}
    
    Write-Host "✓ Enhanced session mode ${enable ? 'enabled' : 'disabled'}" -ForegroundColor Green
    Write-Host ${'\`n'}"Note: VMs must have RDP services running to use enhanced sessions" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to configure enhanced session mode: $_"
}`;
    }
  },

  {
    id: 'hyperv-configure-numa',
    title: 'Configure VM NUMA Topology',
    description: 'Configure NUMA (Non-Uniform Memory Access) settings for high-performance VMs',
    category: 'Performance',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-SQL01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'numaNodes',
        label: 'Number of NUMA Nodes',
        type: 'number',
        required: true,
        defaultValue: 2,
        helpText: 'NUMA topology nodes'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const numaNodes = params.numaNodes || 2;

      return `# Configure VM NUMA Topology
# Generated by PSForge

try {
    Write-Host "Configuring NUMA topology for: ${vmName}" -ForegroundColor Cyan
    
    $VM = Get-VM -Name "${vmName}"
    
    if ($VM.State -ne "Off") {
        Write-Host "Stopping VM..." -ForegroundColor Yellow
        Stop-VM -Name "${vmName}" -Force
    }
    
    Set-VMProcessor -VMName "${vmName}" -ExposeVirtualizationExtensions \$true
    Set-VM -VMName "${vmName}" -ProcessorCount ($VM.ProcessorCount)
    
    Write-Host "✓ NUMA topology configured" -ForegroundColor Green
    Write-Host "  NUMA Nodes: ${numaNodes}" -ForegroundColor Yellow
    Write-Host "  vCPUs: $($VM.ProcessorCount)" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to configure NUMA: $_"
}`;
    }
  },

  {
    id: 'hyperv-configure-resource-metering',
    title: 'Enable Resource Metering',
    description: 'Enable resource usage tracking for billing and monitoring',
    category: 'Reporting',
    parameters: [
      {
        name: 'vmNames',
        label: 'VM Names (one per line, or blank for all)',
        type: 'textarea',
        required: false,
        placeholder: 'VM-WEB01\nVM-SQL01',
        helpText: 'VMs to enable metering for'
      }
    ],
    scriptTemplate: (params) => {
      const vmNamesInput = params.vmNames || '';

      return `# Enable Resource Metering
# Generated by PSForge

try {
    Write-Host "Enabling resource metering..." -ForegroundColor Cyan
    
    ${vmNamesInput.trim() ? `
    $VMNames = @(
${vmNamesInput.split('\\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join(',\\n')}
    )
    $VMs = Get-VM -Name $VMNames
    ` : `
    $VMs = Get-VM
    `}
    
    foreach ($VM in $VMs) {
        Enable-VMResourceMetering -VMName $VM.Name
        Write-Host "✓ Metering enabled: $($VM.Name)" -ForegroundColor Green
    }
    
    Write-Host ${'\`n'}"Resource metering enabled for $($VMs.Count) VMs" -ForegroundColor Yellow
    Write-Host "Use Measure-VM to view collected metrics" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to enable resource metering: $_"
}`;
    }
  },

  {
    id: 'hyperv-audit-vm-security',
    title: 'Audit VM Security Settings',
    description: 'Generate security audit report for all VMs',
    category: 'Reporting',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\VM-Security-Audit.csv',
        helpText: 'Path for security audit report'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Audit VM Security Settings
# Generated by PSForge

try {
    Write-Host "Auditing VM security settings..." -ForegroundColor Cyan
    
    $VMs = Get-VM
    
    $SecurityReport = foreach ($VM in $VMs) {
        $VMSecurity = Get-VMSecurity -VMName $VM.Name -ErrorAction SilentlyContinue
        
        [PSCustomObject]@{
            VMName = $VM.Name
            State = $VM.State
            Generation = $VM.Generation
            SecureBootEnabled = $VMSecurity.SecureBootEnabled
            TPMEnabled = ($VM | Get-VMTpmState -ErrorAction SilentlyContinue).Enabled
            EncryptionSupported = $VMSecurity.EncryptionSupported
            ShieldingRequested = $VMSecurity.ShieldingRequested
            DynamicMemory = $VM.DynamicMemoryEnabled
            IntegrationServicesVersion = $VM.IntegrationServicesVersion
        }
    }
    
    $SecurityReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Security audit exported to: ${exportPath}" -ForegroundColor Green
    
    $SecureBootCount = ($SecurityReport | Where-Object { $_.SecureBootEnabled }).Count
    $TPMCount = ($SecurityReport | Where-Object { $_.TPMEnabled }).Count
    
    Write-Host ${'\`n'}"Security Summary:" -ForegroundColor Yellow
    Write-Host "  Total VMs: $($VMs.Count)"
    Write-Host "  Secure Boot Enabled: $SecureBootCount"
    Write-Host "  TPM Enabled: $TPMCount"
    
} catch {
    Write-Error "Failed to audit security settings: $_"
}`;
    }
  },

  {
    id: 'hyperv-configure-automatic-actions',
    title: 'Configure VM Automatic Start/Stop',
    description: 'Set automatic startup and shutdown actions for VMs',
    category: 'VM Lifecycle',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-DC01',
        helpText: 'Virtual machine name'
      },
      {
        name: 'startAction',
        label: 'Automatic Start Action',
        type: 'select',
        required: true,
        options: [
          { value: 'Nothing', label: 'Do Nothing' },
          { value: 'Start', label: 'Always Start' },
          { value: 'StartIfRunning', label: 'Start if Previously Running' }
        ],
        helpText: 'Action when host starts'
      },
      {
        name: 'stopAction',
        label: 'Automatic Stop Action',
        type: 'select',
        required: true,
        options: [
          { value: 'ShutDown', label: 'Shut Down Guest OS' },
          { value: 'Save', label: 'Save VM State' },
          { value: 'TurnOff', label: 'Turn Off VM' }
        ],
        helpText: 'Action when host shuts down'
      },
      {
        name: 'startDelay',
        label: 'Start Delay (seconds)',
        type: 'number',
        required: false,
        defaultValue: 0,
        helpText: 'Delay before starting VM'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const startAction = params.startAction;
      const stopAction = params.stopAction;
      const startDelay = params.startDelay || 0;

      return `# Configure Automatic Start/Stop Actions
# Generated by PSForge

try {
    Write-Host "Configuring automatic actions for: ${vmName}" -ForegroundColor Cyan
    
    Set-VM -Name "${vmName}" -AutomaticStartAction ${startAction} -AutomaticStopAction ${stopAction} -AutomaticStartDelay ${startDelay}
    
    Write-Host "✓ Automatic actions configured" -ForegroundColor Green
    Write-Host "  Start Action: ${startAction}" -ForegroundColor Yellow
    Write-Host "  Stop Action: ${stopAction}" -ForegroundColor Yellow
    ${startDelay > 0 ? `Write-Host "  Start Delay: ${startDelay} seconds" -ForegroundColor Yellow` : ''}
    
} catch {
    Write-Error "Failed to configure automatic actions: $_"
}`;
    }
  },

  {
    id: 'hyperv-migrate-vm-storage',
    title: 'Migrate VM Storage',
    description: 'Move VM virtual hard disks to a different location',
    category: 'Storage',
    parameters: [
      {
        name: 'vmName',
        label: 'VM Name',
        type: 'text',
        required: true,
        placeholder: 'VM-WEB01',
        helpText: 'Virtual machine to migrate'
      },
      {
        name: 'destinationPath',
        label: 'Destination Path',
        type: 'text',
        required: true,
        placeholder: 'D:\\Hyper-V\\VMs',
        helpText: 'New storage location'
      }
    ],
    scriptTemplate: (params) => {
      const vmName = escapePowerShellString(params.vmName);
      const destPath = escapePowerShellString(params.destinationPath);

      return `# Migrate VM Storage
# Generated by PSForge

try {
    Write-Host "Migrating storage for: ${vmName}" -ForegroundColor Cyan
    Write-Host "Destination: ${destPath}" -ForegroundColor Yellow
    
    $VM = Get-VM -Name "${vmName}"
    
    if (-not (Test-Path "${destPath}")) {
        New-Item -ItemType Directory -Path "${destPath}" -Force | Out-Null
    }
    
    Write-Host "Starting storage migration (this may take several minutes)..." -ForegroundColor Cyan
    
    Move-VMStorage -Name "${vmName}" -DestinationStoragePath "${destPath}"
    
    Write-Host "✓ Storage migration completed successfully" -ForegroundColor Green
    
    $NewVM = Get-VM -Name "${vmName}"
    Write-Host ${'\`n'}"New VM location: $($NewVM.Path)" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to migrate storage: $_"
}`;
    }
  },

  {id:'hyperv-export-config',title:'Export VM Configuration',description:'Backup VM settings to XML',category:'Reporting',parameters:[{name:'vmName',label:'VM Name',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\VMConfigs'}],scriptTemplate:p=>`try{$VM=Get-VM -Name "${escapePowerShellString(p.vmName)}";$VM|Export-VM -Path "${escapePowerShellString(p.exportPath)}";Write-Host "✓ VM config exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'hyperv-configure-replication',title:'Configure VM Replication',description:'Setup Hyper-V Replica for disaster recovery',category:'High Availability',parameters:[{name:'vmName',label:'VM Name',type:'text',required:true},{name:'replicaServer',label:'Replica Server',type:'text',required:true,placeholder:'HV-REPLICA01'},{name:'replicationFrequency',label:'Replication Frequency (seconds)',type:'select',required:true,options:[{value:'30',label:'30 seconds'},{value:'300',label:'5 minutes'},{value:'900',label:'15 minutes'}],defaultValue:'300'}],scriptTemplate:p=>{const vmName=escapePowerShellString(p.vmName);const replicaServer=escapePowerShellString(p.replicaServer);const freq=p.replicationFrequency||'300';return `try{Write-Host "Configuring replication for ${vmName}" -ForegroundColor Cyan;Enable-VMReplication -VMName "${vmName}" -ReplicaServerName "${replicaServer}" -ReplicaServerPort 80 -AuthenticationType Kerberos -ReplicationFrequencySec ${freq};Start-VMInitialReplication -VMName "${vmName}";Write-Host "✓ Replication configured" -ForegroundColor Green}catch{Write-Error $_}`;}}
];

export const hyperVCategories = [
  'Host Configuration',
  'VM Lifecycle',
  'Storage',
  'Checkpoints',
  'Reporting'
];
