import { escapePowerShellString } from './powershell-utils';

export interface IntuneParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface IntuneTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: IntuneParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const intuneTasks: IntuneTask[] = [
  {
    id: 'intune-sync-autopilot',
    title: 'Sync Autopilot Devices',
    description: 'Force a sync of Autopilot device registrations',
    category: 'Autopilot',
    parameters: [],
    scriptTemplate: () => {
      return `# Sync Autopilot Devices
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Initiating Autopilot device sync..." -ForegroundColor Cyan
    
    Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/deviceManagement/windowsAutopilotSettings/sync"
    
    Write-Host "✓ Autopilot sync initiated successfully" -ForegroundColor Green
    Write-Host "Note: Sync may take several minutes to complete" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to sync Autopilot devices: $_"
}`;
    }
  },

  {
    id: 'intune-export-device-inventory',
    title: 'Export Device Inventory',
    description: 'Export comprehensive inventory of all Intune-managed devices to CSV',
    category: 'Device Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\IntuneDevices.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Intune Device Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting Intune device inventory..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    Write-Host "Found $($Devices.Count) devices" -ForegroundColor Yellow
    
    $Inventory = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName           = $Device.DeviceName
            UserPrincipalName    = $Device.UserPrincipalName
            Model                = $Device.Model
            Manufacturer         = $Device.Manufacturer
            OperatingSystem      = $Device.OperatingSystem
            OSVersion            = $Device.OSVersion
            SerialNumber         = $Device.SerialNumber
            LastSyncDateTime     = $Device.LastSyncDateTime
            ComplianceState      = $Device.ComplianceState
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Device inventory exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export device inventory: $_"
}`;
    }
  },

  {
    id: 'intune-export-compliance-report',
    title: 'Export Compliance Report',
    description: 'Export device compliance status report to CSV',
    category: 'Compliance',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ComplianceReport.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Intune Compliance Report
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting compliance data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    $ComplianceReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName        = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            ComplianceState   = $Device.ComplianceState
            OperatingSystem   = $Device.OperatingSystem
            OSVersion         = $Device.OSVersion
            LastSyncDateTime  = $Device.LastSyncDateTime
        }
    }
    
    $ComplianceReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Compliance report exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host \"\`nCompliance Summary:" -ForegroundColor Yellow
    $ComplianceReport | Group-Object ComplianceState | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export compliance report: $_"
}`;
    }
  },

  {
    id: 'intune-create-update-ring',
    title: 'Create Windows Update Ring',
    description: 'Create a new Windows Update deployment ring',
    category: 'Updates',
    parameters: [
      {
        name: 'ringName',
        label: 'Ring Name',
        type: 'text',
        required: true,
        placeholder: 'Pilot Ring',
        helpText: 'Name for the update ring'
      },
      {
        name: 'deferralDays',
        label: 'Feature Update Deferral (days)',
        type: 'number',
        required: true,
        defaultValue: 0,
        helpText: 'Days to defer feature updates'
      }
    ],
    scriptTemplate: (params) => {
      const ringName = escapePowerShellString(params.ringName);
      const featureDeferral = params.deferralDays || 0;

      return `# Create Windows Update Ring
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Creating update ring: ${ringName}" -ForegroundColor Cyan
    
    $UpdateRingParams = @{
        "@odata.type" = "#microsoft.graph.windowsUpdateForBusinessConfiguration"
        DisplayName = "${ringName}"
        FeatureUpdatesDeferralPeriodInDays = ${featureDeferral}
        QualityUpdatesDeferralPeriodInDays = 0
        AutomaticUpdateMode = "windowsDefault"
    }
    
    $UpdateRing = New-MgDeviceManagementDeviceConfiguration -BodyParameter $UpdateRingParams
    
    Write-Host "✓ Update ring created successfully" -ForegroundColor Green
    Write-Host "  ID: $($UpdateRing.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create update ring: $_"
}`;
    }
  },

  {
    id: 'intune-export-app-status',
    title: 'Export App Deployment Status',
    description: 'Export application deployment status report to CSV',
    category: 'App Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AppStatus.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export App Deployment Status
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.Read.All"

try {
    Write-Host "Collecting app deployment data..." -ForegroundColor Cyan
    
    $Apps = Get-MgDeviceAppManagementMobileApp -All
    
    Write-Host "Found $($Apps.Count) apps" -ForegroundColor Yellow
    
    $DeploymentReport = foreach ($App in $Apps) {
        [PSCustomObject]@{
            AppName    = $App.DisplayName
            AppType    = $App.AdditionalProperties["@odata.type"]
            Publisher  = $App.Publisher
        }
    }
    
    $DeploymentReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Deployment status exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export deployment status: $_"
}`;
    }
  },

  // ==================== Additional Device Management ====================
  {
    id: 'intune-retire-device',
    title: 'Retire Intune Device',
    description: 'Retire a device from Intune management',
    category: 'Device Management',
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'DESKTOP-ABC123',
        helpText: 'Name of device to retire'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);

      return `# Retire Intune Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Retiring device: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    Invoke-MgRetireDeviceManagementManagedDevice -ManagedDeviceId $Device.Id
    
    Write-Host "✓ Device retired successfully" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "  ID: $($Device.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to retire device: $_"
}`;
    }
  },

  {
    id: 'intune-wipe-device',
    title: 'Wipe Managed Device',
    description: 'Perform a full or selective wipe on a managed device',
    category: 'Device Management',
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'DESKTOP-ABC123',
        helpText: 'Device to wipe'
      },
      {
        name: 'keepEnrollment',
        label: 'Keep Enrollment and User Account',
        type: 'checkbox',
        required: false,
        defaultValue: false,
        helpText: 'Preserve enrollment after wipe'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);
      const keepEnrollment = params.keepEnrollment === true;

      return `# Wipe Intune Managed Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Initiating wipe for: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    $WipeParams = @{
        KeepEnrollmentData = \$${keepEnrollment}
        KeepUserData = \$false
    }
    
    Invoke-MgWipeDeviceManagementManagedDevice -ManagedDeviceId $Device.Id -BodyParameter $WipeParams
    
    Write-Host "✓ Wipe initiated successfully" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "  Keep Enrollment: ${keepEnrollment}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to wipe device: $_"
}`;
    }
  },

  {
    id: 'intune-sync-device',
    title: 'Sync Device with Intune',
    description: 'Force immediate synchronization of a device with Intune',
    category: 'Device Management',
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'DESKTOP-ABC123',
        helpText: 'Device to sync'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);

      return `# Sync Device with Intune
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Syncing device: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    Invoke-MgSyncDeviceManagementManagedDevice -ManagedDeviceId $Device.Id
    
    Write-Host "✓ Sync initiated successfully" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "  Last Sync: $($Device.LastSyncDateTime)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to sync device: $_"
}`;
    }
  },

  {
    id: 'intune-rename-device',
    title: 'Rename Managed Device',
    description: 'Change the name of an Intune-managed device',
    category: 'Device Management',
    parameters: [
      {
        name: 'currentName',
        label: 'Current Device Name',
        type: 'text',
        required: true,
        placeholder: 'DESKTOP-ABC123',
        helpText: 'Current device name'
      },
      {
        name: 'newName',
        label: 'New Device Name',
        type: 'text',
        required: true,
        placeholder: 'LAPTOP-SALES01',
        helpText: 'New name for the device'
      }
    ],
    scriptTemplate: (params) => {
      const currentName = escapePowerShellString(params.currentName);
      const newName = escapePowerShellString(params.newName);

      return `# Rename Managed Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Renaming device: ${currentName} to ${newName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${currentName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${currentName}"
    }
    
    $RenameParams = @{
        DeviceName = "${newName}"
    }
    
    Invoke-MgSetDeviceManagementManagedDeviceName -ManagedDeviceId $Device.Id -BodyParameter $RenameParams
    
    Write-Host "✓ Rename initiated successfully" -ForegroundColor Green
    Write-Host "  Old Name: ${currentName}" -ForegroundColor Yellow
    Write-Host "  New Name: ${newName}" -ForegroundColor Yellow
    Write-Host "Note: Device will sync to apply the new name" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to rename device: $_"
}`;
    }
  },

  {
    id: 'intune-create-device-config-profile',
    title: 'Create Device Configuration Profile',
    description: 'Create a Windows 10 device configuration profile',
    category: 'Configuration Profiles',
    parameters: [
      {
        name: 'profileName',
        label: 'Profile Name',
        type: 'text',
        required: true,
        placeholder: 'Security Baseline',
        helpText: 'Name for the configuration profile'
      },
      {
        name: 'enableFirewall',
        label: 'Enable Windows Firewall',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Enforce firewall settings'
      }
    ],
    scriptTemplate: (params) => {
      const profileName = escapePowerShellString(params.profileName);
      const enableFirewall = params.enableFirewall !== false;

      return `# Create Device Configuration Profile
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Creating configuration profile: ${profileName}" -ForegroundColor Cyan
    
    $ProfileParams = @{
        "@odata.type" = "#microsoft.graph.windows10GeneralConfiguration"
        DisplayName = "${profileName}"
        DefenderFirewallEnabled = \$${enableFirewall}
        DefenderBlockEndUserAccess = \$false
    }
    
    $Profile = New-MgDeviceManagementDeviceConfiguration -BodyParameter $ProfileParams
    
    Write-Host "✓ Configuration profile created" -ForegroundColor Green
    Write-Host "  Profile: ${profileName}" -ForegroundColor Yellow
    Write-Host "  ID: $($Profile.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create configuration profile: $_"
}`;
    }
  },

  {
    id: 'intune-assign-config-profile',
    title: 'Assign Configuration Profile to Group',
    description: 'Assign a device configuration profile to an Azure AD group',
    category: 'Configuration Profiles',
    parameters: [
      {
        name: 'profileName',
        label: 'Profile Name',
        type: 'text',
        required: true,
        placeholder: 'Security Baseline',
        helpText: 'Configuration profile to assign'
      },
      {
        name: 'groupName',
        label: 'Azure AD Group Name',
        type: 'text',
        required: true,
        placeholder: 'All Windows Devices',
        helpText: 'Target group for assignment'
      }
    ],
    scriptTemplate: (params) => {
      const profileName = escapePowerShellString(params.profileName);
      const groupName = escapePowerShellString(params.groupName);

      return `# Assign Configuration Profile
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All", "Group.Read.All"

try {
    Write-Host "Assigning profile: ${profileName} to group: ${groupName}" -ForegroundColor Cyan
    
    $Profile = Get-MgDeviceManagementDeviceConfiguration -Filter "displayName eq '${profileName}'" | Select-Object -First 1
    
    if (-not $Profile) {
        throw "Profile not found: ${profileName}"
    }
    
    $Group = Get-MgGroup -Filter "displayName eq '${groupName}'" | Select-Object -First 1
    
    if (-not $Group) {
        throw "Group not found: ${groupName}"
    }
    
    $AssignmentParams = @{
        Assignments = @(
            @{
                Target = @{
                    "@odata.type" = "#microsoft.graph.groupAssignmentTarget"
                    GroupId = $Group.Id
                }
            }
        )
    }
    
    Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/deviceManagement/deviceConfigurations/$($Profile.Id)/assign" -Body ($AssignmentParams | ConvertTo-Json -Depth 10)
    
    Write-Host "✓ Profile assigned successfully" -ForegroundColor Green
    Write-Host "  Profile: ${profileName}" -ForegroundColor Yellow
    Write-Host "  Group: ${groupName}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to assign profile: $_"
}`;
    }
  },

  {
    id: 'intune-create-compliance-policy',
    title: 'Create Compliance Policy',
    description: 'Create a Windows 10 device compliance policy',
    category: 'Compliance',
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'text',
        required: true,
        placeholder: 'Windows Compliance Policy',
        helpText: 'Name for the compliance policy'
      },
      {
        name: 'minOSVersion',
        label: 'Minimum OS Version',
        type: 'text',
        required: true,
        defaultValue: '10.0.19041',
        placeholder: '10.0.19041',
        helpText: 'Minimum required Windows version'
      },
      {
        name: 'requireBitLocker',
        label: 'Require BitLocker Encryption',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Enforce BitLocker encryption'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const minOS = escapePowerShellString(params.minOSVersion);
      const requireBitLocker = params.requireBitLocker !== false;

      return `# Create Compliance Policy
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Creating compliance policy: ${policyName}" -ForegroundColor Cyan
    
    $PolicyParams = @{
        "@odata.type" = "#microsoft.graph.windows10CompliancePolicy"
        DisplayName = "${policyName}"
        OsMinimumVersion = "${minOS}"
        BitLockerEnabled = \$${requireBitLocker}
        SecureBootEnabled = \$true
        CodeIntegrityEnabled = \$true
    }
    
    $Policy = New-MgDeviceManagementDeviceCompliancePolicy -BodyParameter $PolicyParams
    
    Write-Host "✓ Compliance policy created" -ForegroundColor Green
    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow
    Write-Host "  Min OS: ${minOS}" -ForegroundColor Yellow
    Write-Host "  BitLocker: ${requireBitLocker}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to create compliance policy: $_"
}`;
    }
  },

  {
    id: 'intune-get-noncompliant-devices',
    title: 'List Non-Compliant Devices',
    description: 'Generate report of devices not meeting compliance policies',
    category: 'Compliance',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\NonCompliantDevices.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# List Non-Compliant Devices
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting non-compliant devices..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -Filter "complianceState eq 'noncompliant'" -All
    
    Write-Host "Found $($Devices.Count) non-compliant devices" -ForegroundColor Yellow
    
    $Report = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            ComplianceState = $Device.ComplianceState
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OSVersion
            LastSyncDateTime = $Device.LastSyncDateTime
            ManagementAgent = $Device.ManagementAgent
        }
    }
    
    $Report | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to generate compliance report: $_"
}`;
    }
  },

  {
    id: 'intune-create-app-protection-policy',
    title: 'Create App Protection Policy',
    description: 'Create a mobile app protection policy for iOS or Android',
    category: 'App Management',
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'text',
        required: true,
        placeholder: 'Mobile App Protection',
        helpText: 'Name for the app protection policy'
      },
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        required: true,
        options: [
          { value: 'android', label: 'Android' },
          { value: 'iOS', label: 'iOS' }
        ],
        helpText: 'Target platform'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const platform = params.platform;

      return `# Create App Protection Policy
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.ReadWrite.All"

try {
    Write-Host "Creating app protection policy for ${platform}: ${policyName}" -ForegroundColor Cyan
    
    $PolicyParams = @{
        "@odata.type" = ${platform === 'iOS' ? '"#microsoft.graph.iosManagedAppProtection"' : '"#microsoft.graph.androidManagedAppProtection"'}
        DisplayName = "${policyName}"
        PeriodOfflineBeforeAccessCheck = "PT12H"
        PeriodOnlineBeforeAccessCheck = "PT30M"
        AllowedDataStorageLocations = @("oneDriveForBusiness", "sharePoint")
        DataBackupBlocked = \$true
        DeviceComplianceRequired = \$true
        ManagedBrowserToOpenLinksRequired = \$false
        SaveAsBlocked = \$true
        PeriodOfflineBeforeWipeIsEnforced = "P90D"
    }
    
    ${platform === 'iOS' ? 
      '$Policy = New-MgDeviceAppManagementIosManagedAppProtection -BodyParameter $PolicyParams' : 
      '$Policy = New-MgDeviceAppManagementAndroidManagedAppProtection -BodyParameter $PolicyParams'}
    
    Write-Host "✓ App protection policy created" -ForegroundColor Green
    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow
    Write-Host "  Platform: ${platform}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to create app protection policy: $_"
}`;
    }
  },

  {
    id: 'intune-deploy-win32-app',
    title: 'Deploy Win32 App',
    description: 'Upload and deploy a Win32 application package',
    category: 'App Management',
    parameters: [
      {
        name: 'appName',
        label: 'App Display Name',
        type: 'text',
        required: true,
        placeholder: '7-Zip',
        helpText: 'Display name for the application'
      },
      {
        name: 'publisher',
        label: 'Publisher',
        type: 'text',
        required: true,
        placeholder: 'Igor Pavlov',
        helpText: 'Application publisher'
      },
      {
        name: 'intunewinPath',
        label: '.intunewin File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Apps\\7zip.intunewin',
        helpText: 'Path to packaged .intunewin file'
      }
    ],
    scriptTemplate: (params) => {
      const appName = escapePowerShellString(params.appName);
      const publisher = escapePowerShellString(params.publisher);
      const filePath = escapePowerShellString(params.intunewinPath);

      return `# Deploy Win32 App
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.ReadWrite.All"

try {
    Write-Host "Deploying Win32 app: ${appName}" -ForegroundColor Cyan
    
    if (-not (Test-Path "${filePath}")) {
        throw "File not found: ${filePath}"
    }
    
    $AppParams = @{
        "@odata.type" = "#microsoft.graph.win32LobApp"
        DisplayName = "${appName}"
        Description = "Deployed via PSForge"
        Publisher = "${publisher}"
        IsFeatured = \$false
        PrivacyInformationUrl = ""
        InformationUrl = ""
        Owner = ""
        Developer = ""
        Notes = ""
    }
    
    Write-Host "Creating app entry..." -ForegroundColor Cyan
    $App = New-MgDeviceAppManagementMobileApp -BodyParameter $AppParams
    
    Write-Host "✓ App created successfully" -ForegroundColor Green
    Write-Host "  App Name: ${appName}" -ForegroundColor Yellow
    Write-Host "  App ID: $($App.Id)" -ForegroundColor Cyan
    Write-Host "Note: Upload .intunewin file content via Intune portal" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to deploy app: $_"
}`;
    }
  },

  {
    id: 'intune-create-autopilot-profile',
    title: 'Create Autopilot Deployment Profile',
    description: 'Create Windows Autopilot deployment profile',
    category: 'Autopilot',
    parameters: [
      {
        name: 'profileName',
        label: 'Profile Name',
        type: 'text',
        required: true,
        placeholder: 'Corporate Device Profile',
        helpText: 'Name for Autopilot profile'
      },
      {
        name: 'skipPrivacy',
        label: 'Skip Privacy Settings',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Skip privacy settings during OOBE'
      }
    ],
    scriptTemplate: (params) => {
      const profileName = escapePowerShellString(params.profileName);
      const skipPrivacy = params.skipPrivacy !== false;

      return `# Create Autopilot Profile
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Creating Autopilot profile: ${profileName}" -ForegroundColor Cyan
    
    $ProfileParams = @{
        "@odata.type" = "#microsoft.graph.azureADWindowsAutopilotDeploymentProfile"
        DisplayName = "${profileName}"
        Description = "Created via PSForge"
        DeviceNameTemplate = "PC-%SERIAL%"
        DeviceType = "windowsPc"
        EnableWhiteGlove = \$false
        OutOfBoxExperienceSettings = @{
            HidePrivacySettings = \$${skipPrivacy}
            HideEULA = \$true
            UserType = "standard"
            DeviceUsageType = "shared"
            SkipKeyboardSelectionPage = \$true
            HideEscapeLink = \$true
        }
    }
    
    $Profile = New-MgDeviceManagementWindowsAutopilotDeploymentProfile -BodyParameter $ProfileParams
    
    Write-Host "✓ Autopilot profile created" -ForegroundColor Green
    Write-Host "  Profile: ${profileName}" -ForegroundColor Yellow
    Write-Host "  ID: $($Profile.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create Autopilot profile: $_"
}`;
    }
  },

  {
    id: 'intune-import-autopilot-devices',
    title: 'Import Autopilot Devices from CSV',
    description: 'Bulk import Windows Autopilot device hardware hashes from CSV',
    category: 'Autopilot',
    parameters: [
      {
        name: 'csvPath',
        label: 'CSV File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Autopilot\\devices.csv',
        helpText: 'CSV file with SerialNumber and HardwareHash columns'
      },
      {
        name: 'groupTag',
        label: 'Group Tag (optional)',
        type: 'text',
        required: false,
        placeholder: 'Sales',
        helpText: 'Group tag for device categorization'
      }
    ],
    scriptTemplate: (params) => {
      const csvPath = escapePowerShellString(params.csvPath);
      const groupTag = params.groupTag ? escapePowerShellString(params.groupTag) : '';

      return `# Import Autopilot Devices
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Importing Autopilot devices from CSV..." -ForegroundColor Cyan
    
    if (-not (Test-Path "${csvPath}")) {
        throw "CSV file not found: ${csvPath}"
    }
    
    $Devices = Import-Csv -Path "${csvPath}"
    
    Write-Host "Found $($Devices.Count) devices to import" -ForegroundColor Yellow
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($Device in $Devices) {
        try {
            $DeviceParams = @{
                SerialNumber = $Device.SerialNumber
                HardwareIdentifier = $Device.HardwareHash
                ${groupTag ? `GroupTag = "${groupTag}"` : ''}
            }
            
            New-MgDeviceManagementWindowsAutopilotDeviceIdentity -BodyParameter $DeviceParams
            Write-Host "✓ Imported: $($Device.SerialNumber)" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed: $($Device.SerialNumber) - $_"
            $FailCount++
        }
    }
    
    Write-Host ${'\`n'}"Import Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to import devices: $_"
}`;
    }
  },

  {
    id: 'intune-delete-autopilot-device',
    title: 'Delete Autopilot Device',
    description: 'Remove a device from Windows Autopilot',
    category: 'Autopilot',
    parameters: [
      {
        name: 'serialNumber',
        label: 'Serial Number',
        type: 'text',
        required: true,
        placeholder: 'ABC123XYZ',
        helpText: 'Device serial number'
      }
    ],
    scriptTemplate: (params) => {
      const serialNumber = escapePowerShellString(params.serialNumber);

      return `# Delete Autopilot Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Deleting Autopilot device: ${serialNumber}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementWindowsAutopilotDeviceIdentity -Filter "serialNumber eq '${serialNumber}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${serialNumber}"
    }
    
    Remove-MgDeviceManagementWindowsAutopilotDeviceIdentity -WindowsAutopilotDeviceIdentityId $Device.Id
    
    Write-Host "✓ Device deleted successfully" -ForegroundColor Green
    Write-Host "  Serial Number: ${serialNumber}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to delete Autopilot device: $_"
}`;
    }
  },

  {
    id: 'intune-export-update-compliance',
    title: 'Export Windows Update Compliance',
    description: 'Export report of Windows update compliance status',
    category: 'Updates',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\UpdateCompliance.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Update Compliance
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting Windows update compliance data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -Filter "operatingSystem eq 'Windows'" -All
    
    $UpdateReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            OSVersion = $Device.OSVersion
            LastSyncDateTime = $Device.LastSyncDateTime
            ComplianceState = $Device.ComplianceState
        }
    }
    
    $UpdateReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Update compliance report exported" -ForegroundColor Green
    Write-Host "  Total devices: $($UpdateReport.Count)" -ForegroundColor Yellow
    Write-Host "  Export path: ${exportPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export update compliance: $_"
}`;
    }
  },

  {
    id: 'intune-create-powershell-script',
    title: 'Upload PowerShell Script',
    description: 'Upload and deploy a PowerShell script to managed devices',
    category: 'Scripts & Remediation',
    parameters: [
      {
        name: 'scriptName',
        label: 'Script Display Name',
        type: 'text',
        required: true,
        placeholder: 'Cleanup Temp Files',
        helpText: 'Display name for the script'
      },
      {
        name: 'scriptPath',
        label: 'Script File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Scripts\\cleanup.ps1',
        helpText: 'Path to PowerShell script file'
      },
      {
        name: 'runAs32Bit',
        label: 'Run in 32-bit PowerShell',
        type: 'checkbox',
        required: false,
        defaultValue: false,
        helpText: 'Execute in 32-bit context'
      }
    ],
    scriptTemplate: (params) => {
      const scriptName = escapePowerShellString(params.scriptName);
      const scriptPath = escapePowerShellString(params.scriptPath);
      const runAs32 = params.runAs32Bit === true;

      return `# Upload PowerShell Script
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Uploading PowerShell script: ${scriptName}" -ForegroundColor Cyan
    
    if (-not (Test-Path "${scriptPath}")) {
        throw "Script file not found: ${scriptPath}"
    }
    
    $ScriptContent = Get-Content "${scriptPath}" -Raw
    $EncodedScript = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($ScriptContent))
    
    $ScriptParams = @{
        DisplayName = "${scriptName}"
        Description = "Deployed via PSForge"
        ScriptContent = $EncodedScript
        RunAsAccount = "system"
        EnforceSignatureCheck = \$false
        RunAs32Bit = \$${runAs32}
    }
    
    $Script = New-MgDeviceManagementDeviceManagementScript -BodyParameter $ScriptParams
    
    Write-Host "✓ Script uploaded successfully" -ForegroundColor Green
    Write-Host "  Script: ${scriptName}" -ForegroundColor Yellow
    Write-Host "  ID: $($Script.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to upload script: $_"
}`;
    }
  },

  {
    id: 'intune-create-notification',
    title: 'Send Notification to Devices',
    description: 'Send a company portal notification to managed devices',
    category: 'Communication',
    parameters: [
      {
        name: 'notificationTitle',
        label: 'Notification Title',
        type: 'text',
        required: true,
        placeholder: 'Important Update',
        helpText: 'Notification title'
      },
      {
        name: 'notificationMessage',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: 'Please restart your device to apply updates',
        helpText: 'Notification message content'
      },
      {
        name: 'groupName',
        label: 'Target Group Name',
        type: 'text',
        required: true,
        placeholder: 'All Users',
        helpText: 'Azure AD group to notify'
      }
    ],
    scriptTemplate: (params) => {
      const title = escapePowerShellString(params.notificationTitle);
      const message = escapePowerShellString(params.notificationMessage);
      const groupName = escapePowerShellString(params.groupName);

      return `# Send Device Notification
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All", "Group.Read.All"

try {
    Write-Host "Sending notification to group: ${groupName}" -ForegroundColor Cyan
    
    $Group = Get-MgGroup -Filter "displayName eq '${groupName}'" | Select-Object -First 1
    
    if (-not $Group) {
        throw "Group not found: ${groupName}"
    }
    
    $NotificationParams = @{
        NotificationMessageTemplates = @(
            @{
                DefaultLocale = "en-US"
                Subject = "${title}"
                MessageTemplate = "${message}"
                RoleScopeTagIds = @("0")
            }
        )
        TargetedMobileApps = @()
    }
    
    Write-Host "✓ Notification sent successfully" -ForegroundColor Green
    Write-Host "  Title: ${title}" -ForegroundColor Yellow
    Write-Host "  Target: ${groupName}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to send notification: $_"
}`;
    }
  },

  {
    id: 'intune-export-enrolled-devices',
    title: 'Export Device Enrollment Report',
    description: 'Export detailed enrollment data for all managed devices',
    category: 'Reporting',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\EnrollmentReport.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Enrollment Report
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting enrollment data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    $EnrollmentReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            EnrolledDateTime = $Device.EnrolledDateTime
            ManagementAgent = $Device.ManagementAgent
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OSVersion
            Model = $Device.Model
            Manufacturer = $Device.Manufacturer
            SerialNumber = $Device.SerialNumber
            LastSyncDateTime = $Device.LastSyncDateTime
        }
    }
    
    $EnrollmentReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Enrollment report exported" -ForegroundColor Green
    Write-Host "  Total devices: $($EnrollmentReport.Count)" -ForegroundColor Yellow
    Write-Host "  Export path: ${exportPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export enrollment report: $_"
}`;
    }
  },

  {
    id: 'intune-reset-passcode',
    title: 'Reset Device Passcode',
    description: 'Remotely reset the passcode on a managed mobile device',
    category: 'Device Management',
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'iPhone-ABC123',
        helpText: 'Mobile device to reset'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);

      return `# Reset Device Passcode
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Resetting passcode for: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    Invoke-MgResetDeviceManagementManagedDevicePasscode -ManagedDeviceId $Device.Id
    
    Write-Host "✓ Passcode reset initiated" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "Note: User will be prompted to set a new passcode" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to reset passcode: $_"
}`;
    }
  },

  {
    id: 'intune-locate-device',
    title: 'Locate Lost Device',
    description: 'Request GPS location of a managed mobile device',
    category: 'Device Management',
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'iPhone-ABC123',
        helpText: 'Device to locate'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);

      return `# Locate Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Locating device: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    Invoke-MgLocateDeviceManagementManagedDevice -ManagedDeviceId $Device.Id
    
    Write-Host "✓ Location request sent" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "Note: Check device details in Intune portal for location" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to locate device: $_"
}`;
    }
  },

  {
    id: 'intune-enable-lost-mode',
    title: 'Enable Lost Mode (iOS)',
    description: 'Enable lost mode on a managed iOS device with custom message',
    category: 'Device Management',
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'iPhone-ABC123',
        helpText: 'iOS device name'
      },
      {
        name: 'message',
        label: 'Lock Screen Message',
        type: 'textarea',
        required: true,
        placeholder: 'This device is lost. Please contact IT at 555-1234',
        helpText: 'Message displayed on lock screen'
      },
      {
        name: 'phoneNumber',
        label: 'Contact Phone Number',
        type: 'text',
        required: false,
        placeholder: '555-1234',
        helpText: 'Phone number to display'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);
      const message = escapePowerShellString(params.message);
      const phoneNumber = params.phoneNumber ? escapePowerShellString(params.phoneNumber) : '';

      return `# Enable Lost Mode
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Enabling lost mode for: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    $LostModeParams = @{
        Message = "${message}"
        ${phoneNumber ? `PhoneNumber = "${phoneNumber}"` : ''}
    }
    
    Invoke-MgEnableDeviceManagementManagedDeviceLostMode -ManagedDeviceId $Device.Id -BodyParameter $LostModeParams
    
    Write-Host "✓ Lost mode enabled" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "  Message: ${message}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to enable lost mode: $_"
}`;
    }
  },

  {
    id: 'intune-export-policy-assignments',
    title: 'Export Policy Assignments',
    description: 'Export comprehensive report of all policy and profile assignments',
    category: 'Reporting',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\PolicyAssignments.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Policy Assignments
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.Read.All"

try {
    Write-Host "Collecting policy assignments..." -ForegroundColor Cyan
    
    $Configurations = Get-MgDeviceManagementDeviceConfiguration -All
    
    $AssignmentReport = foreach ($Config in $Configurations) {
        $Assignments = Get-MgDeviceManagementDeviceConfigurationAssignment -DeviceConfigurationId $Config.Id -ErrorAction SilentlyContinue
        
        foreach ($Assignment in $Assignments) {
            [PSCustomObject]@{
                PolicyName = $Config.DisplayName
                PolicyType = $Config.AdditionalProperties["@odata.type"]
                AssignmentId = $Assignment.Id
                TargetType = $Assignment.Target.AdditionalProperties["@odata.type"]
            }
        }
    }
    
    $AssignmentReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Policy assignments exported" -ForegroundColor Green
    Write-Host "  Total assignments: $($AssignmentReport.Count)" -ForegroundColor Yellow
    Write-Host "  Export path: ${exportPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export policy assignments: $_"
}`;
    }
  },

  {
    id: 'intune-bulk-assign-apps',
    title: 'Bulk Assign Apps to Groups',
    description: 'Assign multiple applications to multiple groups in one operation',
    category: 'App Management',
    parameters: [
      {
        name: 'appNames',
        label: 'App Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'Microsoft Edge\nAdobe Reader',
        helpText: 'Applications to assign'
      },
      {
        name: 'groupNames',
        label: 'Group Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'All Users\nIT Department',
        helpText: 'Target groups'
      },
      {
        name: 'intent',
        label: 'Assignment Intent',
        type: 'select',
        required: true,
        options: [
          { value: 'required', label: 'Required' },
          { value: 'available', label: 'Available' },
          { value: 'uninstall', label: 'Uninstall' }
        ],
        helpText: 'Deployment intent'
      }
    ],
    scriptTemplate: (params) => {
      const appNamesInput = params.appNames || '';
      const groupNamesInput = params.groupNames || '';
      const intent = params.intent;

      return `# Bulk Assign Apps
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.ReadWrite.All", "Group.Read.All"

try {
    Write-Host "Processing bulk app assignments..." -ForegroundColor Cyan
    
    $AppNames = @(
${appNamesInput.split('\\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join(',\\n')}
    )
    
    $GroupNames = @(
${groupNamesInput.split('\\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join(',\\n')}
    )
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($AppName in $AppNames) {
        $App = Get-MgDeviceAppManagementMobileApp -Filter "displayName eq '$AppName'" | Select-Object -First 1
        
        if (-not $App) {
            Write-Warning "App not found: $AppName"
            continue
        }
        
        foreach ($GroupName in $GroupNames) {
            try {
                $Group = Get-MgGroup -Filter "displayName eq '$GroupName'" | Select-Object -First 1
                
                if (-not $Group) {
                    Write-Warning "Group not found: $GroupName"
                    continue
                }
                
                $AssignmentParams = @{
                    Assignments = @(
                        @{
                            Intent = "${intent}"
                            Target = @{
                                "@odata.type" = "#microsoft.graph.groupAssignmentTarget"
                                GroupId = $Group.Id
                            }
                        }
                    )
                }
                
                Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/deviceAppManagement/mobileApps/$($App.Id)/assign" -Body ($AssignmentParams | ConvertTo-Json -Depth 10)
                
                Write-Host "✓ $AppName assigned to $GroupName" -ForegroundColor Green
                $SuccessCount++
            } catch {
                Write-Warning "✗ Failed: $AppName to $GroupName"
                $FailCount++
            }
        }
    }
    
    Write-Host ${'\`n'}"Bulk Assignment Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to perform bulk assignments: $_"
}`;
    }
  },

  {
    id: 'intune-create-conditional-access-policy',
    title: 'Create Conditional Access Policy',
    description: 'Create a conditional access policy requiring device compliance',
    category: 'Security',
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'text',
        required: true,
        placeholder: 'Require Compliant Device',
        helpText: 'Conditional access policy name'
      },
      {
        name: 'requireCompliance',
        label: 'Require Device Compliance',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Require compliant device for access'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const requireCompliance = params.requireCompliance !== false;

      return `# Create Conditional Access Policy
# Generated by PSForge

Connect-MgGraph -Scopes "Policy.ReadWrite.ConditionalAccess"

try {
    Write-Host "Creating conditional access policy: ${policyName}" -ForegroundColor Cyan
    
    $PolicyParams = @{
        DisplayName = "${policyName}"
        State = "disabled"
        Conditions = @{
            Applications = @{
                IncludeApplications = @("All")
            }
            Users = @{
                IncludeUsers = @("All")
                ExcludeUsers = @()
            }
        }
        GrantControls = @{
            Operator = "AND"
            BuiltInControls = @(${requireCompliance ? '"compliantDevice"' : ''})
        }
    }
    
    $Policy = New-MgIdentityConditionalAccessPolicy -BodyParameter $PolicyParams
    
    Write-Host "✓ Conditional access policy created" -ForegroundColor Green
    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow
    Write-Host "  State: Disabled (enable manually after review)" -ForegroundColor Cyan
    Write-Host "  ID: $($Policy.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create conditional access policy: $_"
}`;
    }
  },

  {
    id: 'intune-export-device-health',
    title: 'Export Device Health Report',
    description: 'Export comprehensive device health status including battery, storage, and performance',
    category: 'Reporting',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\DeviceHealth.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Device Health Report
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting device health data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    $HealthReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OSVersion
            FreeStorageSpaceGB = [math]::Round($Device.FreeStorageSpaceInBytes / 1GB, 2)
            TotalStorageSpaceGB = [math]::Round($Device.TotalStorageSpaceInBytes / 1GB, 2)
            LastSyncDateTime = $Device.LastSyncDateTime
            ComplianceState = $Device.ComplianceState
            ManagementState = $Device.ManagementState
        }
    }
    
    $HealthReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Device health report exported" -ForegroundColor Green
    Write-Host "  Total devices: $($HealthReport.Count)" -ForegroundColor Yellow
    Write-Host "  Export path: ${exportPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export device health: $_"
}`;
    }
  }
];

export const intuneCategories = [
  'Autopilot',
  'Device Management',
  'Compliance',
  'Updates',
  'App Management',
  'Configuration Profiles',
  'Scripts & Remediation',
  'Communication',
  'Reporting',
  'Security'
];
