import { escapePowerShellString } from './powershell-utils';

export interface IntuneParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface IntuneTask {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: IntuneParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const intuneTasks: IntuneTask[] = [
  {
    id: 'intune-sync-autopilot',
    title: 'Sync Autopilot Devices',
    description: 'Force a sync of Autopilot device registrations',
    category: 'Autopilot',
    instructions: `**How This Task Works:**
This script forces immediate synchronization of Windows Autopilot device registrations with Microsoft Intune for rapid deployment readiness.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Global Administrator or Intune Administrator role
- DeviceManagementServiceConfig.ReadWrite.All permission

**What You Need to Provide:**
- No parameters required (manual authentication)

**What the Script Does:**
1. Connects to Microsoft Graph with required permissions
2. Initiates POST request to Autopilot sync endpoint
3. Triggers synchronization of device hardware hashes
4. Reports sync initiation status

**Important Notes:**
- Sync may take 5-15 minutes to complete
- Essential after uploading new device hardware IDs
- Forces update of device registration status
- Required when Autopilot devices not appearing in portal
- Run after bulk device imports via CSVs
- Does not restart existing device deployments
- Check sync status in Intune portal after 15 minutes`,
    parameters: [],
    scriptTemplate: () => {
      return `# Sync Autopilot Devices
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Initiating Autopilot device sync..." -ForegroundColor Cyan
    
    Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/deviceManagement/windowsAutopilotSettings/sync"
    
    Write-Host "✓ Autopilot sync initiated successfully" -ForegroundColor Green
    Write-Host "Note: Sync may take several minutes to complete" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to sync Autopilot devices: $_"
}`;
    }
  },

  {
    id: 'intune-export-device-inventory',
    title: 'Export Device Inventory',
    description: 'Export comprehensive inventory of all Intune-managed devices to CSV',
    category: 'Device Management',
    instructions: `**How This Task Works:**
This script generates comprehensive device inventory reports from Intune for asset management, compliance tracking, and lifecycle planning.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Reader role
- DeviceManagementManagedDevices.Read.All permission

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph with read permissions
2. Retrieves all Intune-managed devices (all pages)
3. Extracts device details: name, user, model, manufacturer
4. Captures OS version, serial number, compliance state
5. Includes last sync timestamp for health tracking
6. Exports comprehensive CSV report

**Important Notes:**
- Retrieves all devices regardless of count (may take time)
- Essential for asset management and auditing
- CSV includes compliance state for risk assessment
- LastSyncDateTime identifies stale/offline devices
- Use for hardware refresh planning
- Filter in Excel for specific models/users
- Run monthly for trending analysis`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\IntuneDevices.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Intune Device Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting Intune device inventory..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    Write-Host "Found $($Devices.Count) devices" -ForegroundColor Yellow
    
    $Inventory = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName           = $Device.DeviceName
            UserPrincipalName    = $Device.UserPrincipalName
            Model                = $Device.Model
            Manufacturer         = $Device.Manufacturer
            OperatingSystem      = $Device.OperatingSystem
            OSVersion            = $Device.OSVersion
            SerialNumber         = $Device.SerialNumber
            LastSyncDateTime     = $Device.LastSyncDateTime
            ComplianceState      = $Device.ComplianceState
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Device inventory exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export device inventory: $_"
}`;
    }
  },

  {
    id: 'intune-export-compliance-report',
    title: 'Export Compliance Report',
    description: 'Export device compliance status report to CSV',
    category: 'Compliance',
    instructions: `**How This Task Works:**
This script generates focused compliance reports showing which devices meet organizational security and configuration requirements.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Compliance Administrator role
- DeviceManagementManagedDevices.Read.All permission

**What You Need to Provide:**
- CSV export file path for compliance report

**What the Script Does:**
1. Connects to Microsoft Graph with read permissions
2. Retrieves all managed devices with compliance data
3. Filters and extracts compliance-specific fields
4. Includes device name, user, OS, and compliance state
5. Captures last compliance check timestamp
6. Exports focused compliance CSV report

**Important Notes:**
- Essential for security audits and compliance reporting
- ComplianceState shows Compliant/NonCompliant/Unknown
- Use to identify devices requiring remediation
- Run before audit reviews and compliance meetings
- Non-compliant devices may have blocked access
- Track compliance trends over time
- Coordinate with conditional access policies`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ComplianceReport.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Intune Compliance Report
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting compliance data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    $ComplianceReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName        = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            ComplianceState   = $Device.ComplianceState
            OperatingSystem   = $Device.OperatingSystem
            OSVersion         = $Device.OSVersion
            LastSyncDateTime  = $Device.LastSyncDateTime
        }
    }
    
    $ComplianceReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Compliance report exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host \"\`nCompliance Summary:" -ForegroundColor Yellow
    $ComplianceReport | Group-Object ComplianceState | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export compliance report: $_"
}`;
    }
  },

  {
    id: 'intune-create-update-ring',
    title: 'Create Windows Update Ring',
    description: 'Create a new Windows Update deployment ring',
    category: 'Updates',
    instructions: `**How This Task Works:**
This script creates Windows Update rings for controlled, phased deployment of feature and quality updates across device groups.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementConfiguration.ReadWrite.All permission

**What You Need to Provide:**
- Update ring name (e.g., Pilot Ring, Production Ring)
- Feature update deferral period in days

**What the Script Does:**
1. Connects to Microsoft Graph with configuration permissions
2. Creates Windows Update for Business configuration policy
3. Sets feature update deferral period as specified
4. Configures quality update deferral to 0 days (immediate)
5. Sets automatic update mode to Windows default
6. Returns created update ring ID for assignment

**Important Notes:**
- Essential for phased Windows 11/10 update deployment
- Feature deferral typical values: 0 (pilot), 7-30 (production)
- Quality updates deployed immediately by default
- Must assign ring to device groups after creation
- Coordinate with maintenance windows
- Use multiple rings for staged deployments
- Monitor update ring compliance in Intune portal`,
    parameters: [
      {
        name: 'ringName',
        label: 'Ring Name',
        type: 'text',
        required: true,
        placeholder: 'Pilot Ring',
        helpText: 'Name for the update ring'
      },
      {
        name: 'deferralDays',
        label: 'Feature Update Deferral (days)',
        type: 'number',
        required: true,
        defaultValue: 0,
        helpText: 'Days to defer feature updates'
      }
    ],
    scriptTemplate: (params) => {
      const ringName = escapePowerShellString(params.ringName);
      const featureDeferral = params.deferralDays || 0;

      return `# Create Windows Update Ring
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Creating update ring: ${ringName}" -ForegroundColor Cyan
    
    $UpdateRingParams = @{
        "@odata.type" = "#microsoft.graph.windowsUpdateForBusinessConfiguration"
        DisplayName = "${ringName}"
        FeatureUpdatesDeferralPeriodInDays = ${featureDeferral}
        QualityUpdatesDeferralPeriodInDays = 0
        AutomaticUpdateMode = "windowsDefault"
    }
    
    $UpdateRing = New-MgDeviceManagementDeviceConfiguration -BodyParameter $UpdateRingParams
    
    Write-Host "✓ Update ring created successfully" -ForegroundColor Green
    Write-Host "  ID: $($UpdateRing.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create update ring: $_"
}`;
    }
  },

  {
    id: 'intune-export-app-status',
    title: 'Export App Inventory',
    description: 'Export application inventory (name, type, publisher) to CSV',
    category: 'App Management',
    instructions: `**How This Task Works:**
This script generates application inventory reports from Intune showing all managed apps with basic metadata for app catalog management.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Reader role
- DeviceManagementApps.Read.All permission

**What You Need to Provide:**
- CSV export file path for app inventory report

**What the Script Does:**
1. Connects to Microsoft Graph with app read permissions
2. Retrieves all managed mobile applications
3. Extracts basic app metadata: name, type, publisher
4. Exports app inventory to CSV (does NOT include deployment/assignment status)
5. Reports total app count

**Important Notes:**
- Provides app catalog inventory ONLY (name, type, publisher)
- Does NOT include deployment status, assignments, or install success/failure
- Shows all app types: Win32, Store, Web, iOS, Android
- Essential for app portfolio visibility and governance
- Use to identify duplicate or unused apps
- @odata.type indicates app platform/deployment method
- To get deployment status, use separate Graph API queries for assignments
- Run monthly for app catalog tracking`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AppStatus.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export App Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.Read.All"

try {
    Write-Host "Collecting app inventory data..." -ForegroundColor Cyan
    
    $Apps = Get-MgDeviceAppManagementMobileApp -All
    
    Write-Host "Found $($Apps.Count) apps" -ForegroundColor Yellow
    
    $InventoryReport = foreach ($App in $Apps) {
        [PSCustomObject]@{
            AppName    = $App.DisplayName
            AppType    = $App.AdditionalProperties["@odata.type"]
            Publisher  = $App.Publisher
        }
    }
    
    $InventoryReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ App inventory exported to: ${exportPath}" -ForegroundColor Green
    Write-Host "Note: For deployment/assignment status, use additional Graph API queries" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to export app inventory: $_"
}`;
    }
  },

  // ==================== Additional Device Management ====================
  {
    id: 'intune-retire-device',
    title: 'Retire Intune Device',
    description: 'Retire a device from Intune management',
    category: 'Device Management',
    instructions: `**How This Task Works:**
This script gracefully retires devices from Intune management, removing company data while preserving personal data for BYOD scenarios.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementManagedDevices.ReadWrite.All permission

**What You Need to Provide:**
- Device name to retire

**What the Script Does:**
1. Connects to Microsoft Graph with device write permissions
2. Searches for device by exact name match
3. Validates device exists in Intune
4. Initiates retire action via Graph API
5. Reports retirement status with device ID

**Important Notes:**
- Retire removes company data, keeps personal data (BYOD-friendly)
- Use for employee offboarding or device repurposing
- Device can re-enroll after retirement
- Different from Wipe (which removes ALL data)
- Retirement may take 5-15 minutes to complete
- Check device status in portal to confirm
- Essential for BYOD lifecycle management
- Preserves user productivity while protecting company data`,
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'DESKTOP-ABC123',
        helpText: 'Name of device to retire'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);

      return `# Retire Intune Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Retiring device: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    Invoke-MgRetireDeviceManagementManagedDevice -ManagedDeviceId $Device.Id
    
    Write-Host "✓ Device retired successfully" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "  ID: $($Device.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to retire device: $_"
}`;
    }
  },

  {
    id: 'intune-wipe-device',
    title: 'Wipe Managed Device',
    description: 'Perform a full or selective wipe on a managed device',
    category: 'Device Management',
    instructions: `**How This Task Works:**
This script initiates complete device wipes (factory reset) for lost devices or repurposed hardware while optionally preserving enrollment.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementManagedDevices.ReadWrite.All permission

**What You Need to Provide:**
- Device name to wipe
- Whether to keep enrollment data (checkbox)

**What the Script Does:**
1. Connects to Microsoft Graph with device write permissions
2. Searches for device by exact name match
3. Validates device exists in Intune
4. Initiates full wipe with specified enrollment option
5. Reports wipe status with device details

**Important Notes:**
- Wipe removes ALL data (factory reset) - extremely destructive
- Different from Retire (which keeps personal data)
- Use for lost devices, security breaches, or hardware repurposing
- Keep Enrollment option allows faster re-provisioning
- Wipe cannot be canceled once initiated
- Device will revert to out-of-box state
- User data is completely erased
- Essential for security incident response`,
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'DESKTOP-ABC123',
        helpText: 'Device to wipe'
      },
      {
        name: 'keepEnrollment',
        label: 'Keep Enrollment and User Account',
        type: 'checkbox',
        required: false,
        defaultValue: false,
        helpText: 'Preserve enrollment after wipe'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);
      const keepEnrollment = params.keepEnrollment === true;

      return `# Wipe Intune Managed Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Initiating wipe for: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    $WipeParams = @{
        KeepEnrollmentData = \$${keepEnrollment}
        KeepUserData = \$false
    }
    
    Invoke-MgWipeDeviceManagementManagedDevice -ManagedDeviceId $Device.Id -BodyParameter $WipeParams
    
    Write-Host "✓ Wipe initiated successfully" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "  Keep Enrollment: ${keepEnrollment}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to wipe device: $_"
}`;
    }
  },

  {
    id: 'intune-sync-device',
    title: 'Sync Device with Intune',
    description: 'Force immediate synchronization of a device with Intune',
    category: 'Device Management',
    instructions: `**How This Task Works:**
This script forces immediate device check-in to apply pending policies, apps, and configuration updates without waiting for normal sync intervals.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementManagedDevices.ReadWrite.All permission

**What You Need to Provide:**
- Device name to sync

**What the Script Does:**
1. Connects to Microsoft Graph with device write permissions
2. Searches for device by exact name match
3. Validates device exists in Intune
4. Initiates immediate device sync
5. Reports last sync timestamp

**Important Notes:**
- Forces immediate policy/app/config application
- Use for troubleshooting or urgent deployments
- Normal sync interval is 8 hours for Windows, 24 hours for mobile
- Sync completes within 5-10 minutes typically
- Device must be online and connected
- Essential for validating policy changes
- Reduces waiting time for urgent updates
- Check Intune portal for sync completion status`,
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'DESKTOP-ABC123',
        helpText: 'Device to sync'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);

      return `# Sync Device with Intune
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Syncing device: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    Invoke-MgSyncDeviceManagementManagedDevice -ManagedDeviceId $Device.Id
    
    Write-Host "✓ Sync initiated successfully" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "  Last Sync: $($Device.LastSyncDateTime)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to sync device: $_"
}`;
    }
  },

  {
    id: 'intune-rename-device',
    title: 'Rename Managed Device',
    description: 'Change the name of an Intune-managed device',
    category: 'Device Management',
    instructions: `**How This Task Works:**
This script remotely renames Intune-managed devices for improved asset tracking and organizational clarity without requiring local access.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementManagedDevices.ReadWrite.All permission

**What You Need to Provide:**
- Current device name
- New device name

**What the Script Does:**
1. Connects to Microsoft Graph with device write permissions
2. Searches for device by current name
3. Validates device exists in Intune
4. Initiates remote rename action
5. Reports old and new names

**Important Notes:**
- Rename applies during next device sync
- Device must sync to complete rename (may take hours)
- Windows devices support rename; some mobile platforms may not
- Use standardized naming conventions (e.g., DEPT-USER-01)
- Improves asset management and troubleshooting
- Rename visible in Intune portal immediately
- Actual device hostname changes after sync
- Force sync after rename for faster application`,
    parameters: [
      {
        name: 'currentName',
        label: 'Current Device Name',
        type: 'text',
        required: true,
        placeholder: 'DESKTOP-ABC123',
        helpText: 'Current device name'
      },
      {
        name: 'newName',
        label: 'New Device Name',
        type: 'text',
        required: true,
        placeholder: 'LAPTOP-SALES01',
        helpText: 'New name for the device'
      }
    ],
    scriptTemplate: (params) => {
      const currentName = escapePowerShellString(params.currentName);
      const newName = escapePowerShellString(params.newName);

      return `# Rename Managed Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Renaming device: ${currentName} to ${newName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${currentName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${currentName}"
    }
    
    $RenameParams = @{
        DeviceName = "${newName}"
    }
    
    Invoke-MgSetDeviceManagementManagedDeviceName -ManagedDeviceId $Device.Id -BodyParameter $RenameParams
    
    Write-Host "✓ Rename initiated successfully" -ForegroundColor Green
    Write-Host "  Old Name: ${currentName}" -ForegroundColor Yellow
    Write-Host "  New Name: ${newName}" -ForegroundColor Yellow
    Write-Host "Note: Device will sync to apply the new name" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to rename device: $_"
}`;
    }
  },

  {
    id: 'intune-create-device-config-profile',
    title: 'Create Device Configuration Profile',
    description: 'Create a Windows 10 device configuration profile',
    category: 'Configuration Profiles',
    instructions: `**How This Task Works:**
This script creates Windows 10/11 configuration profiles to enforce security settings and device restrictions across managed devices.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementConfiguration.ReadWrite.All permission

**What You Need to Provide:**
- Profile name
- Whether to enable Windows Firewall (checkbox, default enabled)

**What the Script Does:**
1. Connects to Microsoft Graph with configuration permissions
2. Creates Windows 10 general configuration profile
3. Configures firewall enforcement settings
4. Sets defender policies (block end user access disabled)
5. Returns created profile ID for assignment

**Important Notes:**
- Profile not applied until assigned to groups
- Example shows firewall enforcement; extend for other settings
- Use for security baselines and device restrictions
- Test profiles with pilot groups first
- Monitor compliance after deployment
- Typical settings: BitLocker, Windows Update, security features
- Must assign profile after creation to take effect`,
    parameters: [
      {
        name: 'profileName',
        label: 'Profile Name',
        type: 'text',
        required: true,
        placeholder: 'Security Baseline',
        helpText: 'Name for the configuration profile'
      },
      {
        name: 'enableFirewall',
        label: 'Enable Windows Firewall',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Enforce firewall settings'
      }
    ],
    scriptTemplate: (params) => {
      const profileName = escapePowerShellString(params.profileName);
      const enableFirewall = params.enableFirewall !== false;

      return `# Create Device Configuration Profile
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Creating configuration profile: ${profileName}" -ForegroundColor Cyan
    
    $ProfileParams = @{
        "@odata.type" = "#microsoft.graph.windows10GeneralConfiguration"
        DisplayName = "${profileName}"
        DefenderFirewallEnabled = \$${enableFirewall}
        DefenderBlockEndUserAccess = \$false
    }
    
    $Profile = New-MgDeviceManagementDeviceConfiguration -BodyParameter $ProfileParams
    
    Write-Host "✓ Configuration profile created" -ForegroundColor Green
    Write-Host "  Profile: ${profileName}" -ForegroundColor Yellow
    Write-Host "  ID: $($Profile.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create configuration profile: $_"
}`;
    }
  },

  {
    id: 'intune-assign-config-profile',
    title: 'Assign Configuration Profile to Group',
    description: 'Assign a device configuration profile to an Azure AD group',
    category: 'Configuration Profiles',
    instructions: `**How This Task Works:**
This script assigns configuration profiles to Azure AD groups, controlling which devices receive specific security and management policies.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementConfiguration.ReadWrite.All and Group.Read.All permissions

**What You Need to Provide:**
- Configuration profile name to assign
- Azure AD group name for targeting

**What the Script Does:**
1. Connects to Microsoft Graph with configuration and group permissions
2. Searches for configuration profile by name
3. Searches for Azure AD group by name
4. Creates profile assignment targeting the group
5. Reports assignment success

**Important Notes:**
- Profile applies to all devices in target group
- Changes take effect during next device sync (8-24 hours)
- Use device groups, not user groups for device config
- Essential step after creating configuration profiles
- Test with pilot groups before broad deployment
- Monitor compliance in Intune portal
- Force device sync for immediate application
- Assignments cumulative if multiple groups targeted`,
    parameters: [
      {
        name: 'profileName',
        label: 'Profile Name',
        type: 'text',
        required: true,
        placeholder: 'Security Baseline',
        helpText: 'Configuration profile to assign'
      },
      {
        name: 'groupName',
        label: 'Azure AD Group Name',
        type: 'text',
        required: true,
        placeholder: 'All Windows Devices',
        helpText: 'Target group for assignment'
      }
    ],
    scriptTemplate: (params) => {
      const profileName = escapePowerShellString(params.profileName);
      const groupName = escapePowerShellString(params.groupName);

      return `# Assign Configuration Profile
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All", "Group.Read.All"

try {
    Write-Host "Assigning profile: ${profileName} to group: ${groupName}" -ForegroundColor Cyan
    
    $Profile = Get-MgDeviceManagementDeviceConfiguration -Filter "displayName eq '${profileName}'" | Select-Object -First 1
    
    if (-not $Profile) {
        throw "Profile not found: ${profileName}"
    }
    
    $Group = Get-MgGroup -Filter "displayName eq '${groupName}'" | Select-Object -First 1
    
    if (-not $Group) {
        throw "Group not found: ${groupName}"
    }
    
    $AssignmentParams = @{
        Assignments = @(
            @{
                Target = @{
                    "@odata.type" = "#microsoft.graph.groupAssignmentTarget"
                    GroupId = $Group.Id
                }
            }
        )
    }
    
    Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/deviceManagement/deviceConfigurations/$($Profile.Id)/assign" -Body ($AssignmentParams | ConvertTo-Json -Depth 10)
    
    Write-Host "✓ Profile assigned successfully" -ForegroundColor Green
    Write-Host "  Profile: ${profileName}" -ForegroundColor Yellow
    Write-Host "  Group: ${groupName}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to assign profile: $_"
}`;
    }
  },

  {
    id: 'intune-create-compliance-policy',
    title: 'Create Compliance Policy',
    description: 'Create a Windows 10 device compliance policy',
    category: 'Compliance',
    instructions: `**How This Task Works:**
This script creates Windows 10/11 compliance policies to enforce minimum security standards and control conditional access.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementConfiguration.ReadWrite.All permission

**What You Need to Provide:**
- Policy name
- Minimum OS version (e.g., 10.0.19041 for Windows 10 20H1)
- Whether to require BitLocker encryption (checkbox, default enabled)

**What the Script Does:**
1. Connects to Microsoft Graph with configuration permissions
2. Creates Windows 10 compliance policy
3. Sets minimum OS version requirement
4. Configures BitLocker, Secure Boot, and Code Integrity requirements
5. Returns created policy ID for assignment

**Important Notes:**
- Policy not enforced until assigned to groups
- Non-compliant devices flagged in Intune portal
- Essential for conditional access integration
- Typical requirements: OS version, encryption, firewall, antivirus
- Test with pilot groups before broad deployment
- Compliance checked during device sync intervals
- Combine with conditional access for access control
- Must assign policy after creation to take effect`,
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'text',
        required: true,
        placeholder: 'Windows Compliance Policy',
        helpText: 'Name for the compliance policy'
      },
      {
        name: 'minOSVersion',
        label: 'Minimum OS Version',
        type: 'text',
        required: true,
        defaultValue: '10.0.19041',
        placeholder: '10.0.19041',
        helpText: 'Minimum required Windows version'
      },
      {
        name: 'requireBitLocker',
        label: 'Require BitLocker Encryption',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Enforce BitLocker encryption'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const minOS = escapePowerShellString(params.minOSVersion);
      const requireBitLocker = params.requireBitLocker !== false;

      return `# Create Compliance Policy
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Creating compliance policy: ${policyName}" -ForegroundColor Cyan
    
    $PolicyParams = @{
        "@odata.type" = "#microsoft.graph.windows10CompliancePolicy"
        DisplayName = "${policyName}"
        OsMinimumVersion = "${minOS}"
        BitLockerEnabled = \$${requireBitLocker}
        SecureBootEnabled = \$true
        CodeIntegrityEnabled = \$true
    }
    
    $Policy = New-MgDeviceManagementDeviceCompliancePolicy -BodyParameter $PolicyParams
    
    Write-Host "✓ Compliance policy created" -ForegroundColor Green
    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow
    Write-Host "  Min OS: ${minOS}" -ForegroundColor Yellow
    Write-Host "  BitLocker: ${requireBitLocker}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to create compliance policy: $_"
}`;
    }
  },

  {
    id: 'intune-get-noncompliant-devices',
    title: 'List Non-Compliant Devices',
    description: 'Generate report of devices not meeting compliance policies',
    category: 'Compliance',
    instructions: `**How This Task Works:**
This script generates comprehensive reports of non-compliant devices for security remediation and conditional access troubleshooting.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Reader role
- DeviceManagementManagedDevices.Read.All permission

**What You Need to Provide:**
- CSV export file path for compliance report

**What the Script Does:**
1. Connects to Microsoft Graph with device read permissions
2. Filters devices by complianceState = 'noncompliant'
3. Extracts device name, user, OS details, and last sync time
4. Exports non-compliant devices to CSV
5. Reports total count of non-compliant devices

**Important Notes:**
- Essential for conditional access troubleshooting
- Identifies security risks requiring immediate attention
- Use to notify users of compliance issues
- Common issues: outdated OS, missing encryption, disabled firewall
- Run daily during compliance rollout
- Coordinate with helpdesk for user remediation
- Review reasons in Intune portal for specific violations
- Non-compliance may block access to corporate resources`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\NonCompliantDevices.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# List Non-Compliant Devices
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting non-compliant devices..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -Filter "complianceState eq 'noncompliant'" -All
    
    Write-Host "Found $($Devices.Count) non-compliant devices" -ForegroundColor Yellow
    
    $Report = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            ComplianceState = $Device.ComplianceState
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OSVersion
            LastSyncDateTime = $Device.LastSyncDateTime
            ManagementAgent = $Device.ManagementAgent
        }
    }
    
    $Report | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to generate compliance report: $_"
}`;
    }
  },

  {
    id: 'intune-create-app-protection-policy',
    title: 'Create App Protection Policy',
    description: 'Create a mobile app protection policy for iOS or Android',
    category: 'App Management',
    instructions: `**How This Task Works:**
This script creates mobile application management (MAM) policies to protect corporate data in mobile apps without requiring full device enrollment.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementApps.ReadWrite.All permission

**What You Need to Provide:**
- Policy name
- Platform (iOS or Android)

**What the Script Does:**
1. Connects to Microsoft Graph with app write permissions
2. Creates platform-specific app protection policy (iOS or Android)
3. Configures data protection settings (backup blocked, save-as blocked)
4. Sets access checks (offline 12h, online 30min)
5. Configures wipe after 90 days offline
6. Returns created policy ID for app assignment

**Important Notes:**
- Essential for BYOD scenarios (no device enrollment required)
- Protects corporate data in managed apps only
- Blocks data transfer to unmanaged apps
- Must assign policy to apps and users after creation
- Common managed apps: Outlook, Teams, OneDrive, SharePoint
- Test with pilot users before broad deployment
- Coordinate with app deployment strategy
- Works without full MDM enrollment`,
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'text',
        required: true,
        placeholder: 'Mobile App Protection',
        helpText: 'Name for the app protection policy'
      },
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        required: true,
        options: [
          { value: 'android', label: 'Android' },
          { value: 'iOS', label: 'iOS' }
        ],
        helpText: 'Target platform'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const platform = params.platform;

      return `# Create App Protection Policy
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.ReadWrite.All"

try {
    Write-Host "Creating app protection policy for ${platform}: ${policyName}" -ForegroundColor Cyan
    
    $PolicyParams = @{
        "@odata.type" = ${platform === 'iOS' ? '"#microsoft.graph.iosManagedAppProtection"' : '"#microsoft.graph.androidManagedAppProtection"'}
        DisplayName = "${policyName}"
        PeriodOfflineBeforeAccessCheck = "PT12H"
        PeriodOnlineBeforeAccessCheck = "PT30M"
        AllowedDataStorageLocations = @("oneDriveForBusiness", "sharePoint")
        DataBackupBlocked = \$true
        DeviceComplianceRequired = \$true
        ManagedBrowserToOpenLinksRequired = \$false
        SaveAsBlocked = \$true
        PeriodOfflineBeforeWipeIsEnforced = "P90D"
    }
    
    ${platform === 'iOS' ? 
      '$Policy = New-MgDeviceAppManagementIosManagedAppProtection -BodyParameter $PolicyParams' : 
      '$Policy = New-MgDeviceAppManagementAndroidManagedAppProtection -BodyParameter $PolicyParams'}
    
    Write-Host "✓ App protection policy created" -ForegroundColor Green
    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow
    Write-Host "  Platform: ${platform}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to create app protection policy: $_"
}`;
    }
  },

  {
    id: 'intune-deploy-win32-app',
    title: 'Deploy Win32 App',
    description: 'Upload and deploy a Win32 application package',
    category: 'App Management',
    instructions: `**How This Task Works:**
This script creates Win32 app entries in Intune for deploying traditional desktop applications (.exe/.msi) to managed devices.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementApps.ReadWrite.All permission
- App packaged as .intunewin file (using IntuneWinAppUtil.exe)

**What You Need to Provide:**
- App display name
- Publisher name
- Path to .intunewin packaged file

**What the Script Does:**
1. Connects to Microsoft Graph with app write permissions
2. Validates .intunewin file exists
3. Creates Win32 app entry in Intune
4. Returns app ID for manual content upload
5. Notes that file upload must be completed in portal

**Important Notes:**
- Must package app as .intunewin before running (use IntuneWinAppUtil.exe)
- Script creates app entry but content upload requires Intune portal
- Complete workflow: package → create entry → upload content → configure detection → assign
- Essential for deploying custom/legacy apps
- Use for apps not available in Microsoft Store
- Must configure install/uninstall commands in portal
- Must configure detection rules in portal after creation
- Assign to groups after upload completes`,
    parameters: [
      {
        name: 'appName',
        label: 'App Display Name',
        type: 'text',
        required: true,
        placeholder: '7-Zip',
        helpText: 'Display name for the application'
      },
      {
        name: 'publisher',
        label: 'Publisher',
        type: 'text',
        required: true,
        placeholder: 'Igor Pavlov',
        helpText: 'Application publisher'
      },
      {
        name: 'intunewinPath',
        label: '.intunewin File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Apps\\7zip.intunewin',
        helpText: 'Path to packaged .intunewin file'
      }
    ],
    scriptTemplate: (params) => {
      const appName = escapePowerShellString(params.appName);
      const publisher = escapePowerShellString(params.publisher);
      const filePath = escapePowerShellString(params.intunewinPath);

      return `# Deploy Win32 App
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.ReadWrite.All"

try {
    Write-Host "Deploying Win32 app: ${appName}" -ForegroundColor Cyan
    
    if (-not (Test-Path "${filePath}")) {
        throw "File not found: ${filePath}"
    }
    
    $AppParams = @{
        "@odata.type" = "#microsoft.graph.win32LobApp"
        DisplayName = "${appName}"
        Description = "Deployed via PSForge"
        Publisher = "${publisher}"
        IsFeatured = \$false
        PrivacyInformationUrl = ""
        InformationUrl = ""
        Owner = ""
        Developer = ""
        Notes = ""
    }
    
    Write-Host "Creating app entry..." -ForegroundColor Cyan
    $App = New-MgDeviceAppManagementMobileApp -BodyParameter $AppParams
    
    Write-Host "✓ App created successfully" -ForegroundColor Green
    Write-Host "  App Name: ${appName}" -ForegroundColor Yellow
    Write-Host "  App ID: $($App.Id)" -ForegroundColor Cyan
    Write-Host "Note: Upload .intunewin file content via Intune portal" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to deploy app: $_"
}`;
    }
  },

  {
    id: 'intune-create-autopilot-profile',
    title: 'Create Autopilot Deployment Profile',
    description: 'Create Windows Autopilot deployment profile',
    category: 'Autopilot',
    instructions: `**How This Task Works:**
This script creates Windows Autopilot deployment profiles to automate device provisioning and streamline out-of-box experience (OOBE).

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementServiceConfig.ReadWrite.All permission

**What You Need to Provide:**
- Profile name
- Whether to skip privacy settings during OOBE (checkbox, default enabled)

**What the Script Does:**
1. Connects to Microsoft Graph with service config permissions
2. Creates Azure AD Autopilot deployment profile
3. Configures device naming template (PC-%SERIAL%)
4. Sets OOBE settings (hide privacy, EULA, skip keyboard selection)
5. Configures shared device mode with standard users
6. Returns created profile ID for device assignment

**Important Notes:**
- Essential for zero-touch device deployment
- Streamlines OOBE for faster provisioning
- Must assign profile to Autopilot device groups
- Device name uses serial number automatically
- Combine with Autopilot device registration
- Test with pilot devices before production rollout
- Typical setup: register devices → create profile → assign profile → ship devices
- Users experience streamlined setup on first boot`,
    parameters: [
      {
        name: 'profileName',
        label: 'Profile Name',
        type: 'text',
        required: true,
        placeholder: 'Corporate Device Profile',
        helpText: 'Name for Autopilot profile'
      },
      {
        name: 'skipPrivacy',
        label: 'Skip Privacy Settings',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Skip privacy settings during OOBE'
      }
    ],
    scriptTemplate: (params) => {
      const profileName = escapePowerShellString(params.profileName);
      const skipPrivacy = params.skipPrivacy !== false;

      return `# Create Autopilot Profile
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Creating Autopilot profile: ${profileName}" -ForegroundColor Cyan
    
    $ProfileParams = @{
        "@odata.type" = "#microsoft.graph.azureADWindowsAutopilotDeploymentProfile"
        DisplayName = "${profileName}"
        Description = "Created via PSForge"
        DeviceNameTemplate = "PC-%SERIAL%"
        DeviceType = "windowsPc"
        EnableWhiteGlove = \$false
        OutOfBoxExperienceSettings = @{
            HidePrivacySettings = \$${skipPrivacy}
            HideEULA = \$true
            UserType = "standard"
            DeviceUsageType = "shared"
            SkipKeyboardSelectionPage = \$true
            HideEscapeLink = \$true
        }
    }
    
    $Profile = New-MgDeviceManagementWindowsAutopilotDeploymentProfile -BodyParameter $ProfileParams
    
    Write-Host "✓ Autopilot profile created" -ForegroundColor Green
    Write-Host "  Profile: ${profileName}" -ForegroundColor Yellow
    Write-Host "  ID: $($Profile.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create Autopilot profile: $_"
}`;
    }
  },

  {
    id: 'intune-import-autopilot-devices',
    title: 'Import Autopilot Devices from CSV',
    description: 'Bulk import Windows Autopilot device hardware hashes from CSV',
    category: 'Autopilot',
    instructions: `**How This Task Works:**
This script bulk imports Windows Autopilot device registrations from CSV files containing hardware hashes collected from devices.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementServiceConfig.ReadWrite.All permission
- CSV file with SerialNumber and HardwareHash columns

**What You Need to Provide:**
- CSV file path with device information
- Optional group tag for device categorization

**What the Script Does:**
1. Connects to Microsoft Graph with service config permissions
2. Validates CSV file exists
3. Imports device serial numbers and hardware hashes
4. Optionally applies group tag for categorization
5. Reports success/failure count for each device
6. Provides import summary

**Important Notes:**
- CSV must contain SerialNumber and HardwareHash columns
- Get hardware hash using Get-WindowsAutopilotInfo.ps1 on each device
- Essential for bulk Autopilot device registration
- Group tags enable automatic profile assignment
- Typical workflow: collect hashes → import CSV → assign profiles
- Import can take several minutes for large batches
- Verify imports in Autopilot device list after completion`,
    parameters: [
      {
        name: 'csvPath',
        label: 'CSV File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Autopilot\\devices.csv',
        helpText: 'CSV file with SerialNumber and HardwareHash columns'
      },
      {
        name: 'groupTag',
        label: 'Group Tag (optional)',
        type: 'text',
        required: false,
        placeholder: 'Sales',
        helpText: 'Group tag for device categorization'
      }
    ],
    scriptTemplate: (params) => {
      const csvPath = escapePowerShellString(params.csvPath);
      const groupTag = params.groupTag ? escapePowerShellString(params.groupTag) : '';

      return `# Import Autopilot Devices
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Importing Autopilot devices from CSV..." -ForegroundColor Cyan
    
    if (-not (Test-Path "${csvPath}")) {
        throw "CSV file not found: ${csvPath}"
    }
    
    $Devices = Import-Csv -Path "${csvPath}"
    
    Write-Host "Found $($Devices.Count) devices to import" -ForegroundColor Yellow
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($Device in $Devices) {
        try {
            $DeviceParams = @{
                SerialNumber = $Device.SerialNumber
                HardwareIdentifier = $Device.HardwareHash
                ${groupTag ? `GroupTag = "${groupTag}"` : ''}
            }
            
            New-MgDeviceManagementWindowsAutopilotDeviceIdentity -BodyParameter $DeviceParams
            Write-Host "✓ Imported: $($Device.SerialNumber)" -ForegroundColor Green
            $SuccessCount++
        } catch {
            Write-Warning "✗ Failed: $($Device.SerialNumber) - $_"
            $FailCount++
        }
    }
    
    Write-Host ${'\`n'}"Import Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to import devices: $_"
}`;
    }
  },

  {
    id: 'intune-delete-autopilot-device',
    title: 'Delete Autopilot Device',
    description: 'Remove a device from Windows Autopilot',
    category: 'Autopilot',
    instructions: `**How This Task Works:**
This script removes device registrations from Windows Autopilot for decommissioned or incorrectly registered devices.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementServiceConfig.ReadWrite.All permission

**What You Need to Provide:**
- Device serial number

**What the Script Does:**
1. Connects to Microsoft Graph with service config permissions
2. Searches for Autopilot device by serial number
3. Validates device exists in Autopilot
4. Removes device registration
5. Reports deletion success with serial number

**Important Notes:**
- Use for decommissioned hardware or incorrect registrations
- Device can be re-registered after deletion
- Does NOT delete from Intune (use retire/wipe separately)
- Only removes Autopilot registration, not device management
- Essential for device lifecycle management
- Verify deletion in Autopilot device list
- Re-registration requires collecting hardware hash again`,
    parameters: [
      {
        name: 'serialNumber',
        label: 'Serial Number',
        type: 'text',
        required: true,
        placeholder: 'ABC123XYZ',
        helpText: 'Device serial number'
      }
    ],
    scriptTemplate: (params) => {
      const serialNumber = escapePowerShellString(params.serialNumber);

      return `# Delete Autopilot Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Deleting Autopilot device: ${serialNumber}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementWindowsAutopilotDeviceIdentity -Filter "serialNumber eq '${serialNumber}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${serialNumber}"
    }
    
    Remove-MgDeviceManagementWindowsAutopilotDeviceIdentity -WindowsAutopilotDeviceIdentityId $Device.Id
    
    Write-Host "✓ Device deleted successfully" -ForegroundColor Green
    Write-Host "  Serial Number: ${serialNumber}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to delete Autopilot device: $_"
}`;
    }
  },

  {
    id: 'intune-export-update-compliance',
    title: 'Export Windows Update Compliance',
    description: 'Export report of Windows update compliance status',
    category: 'Updates',
    instructions: `**How This Task Works:**
This script generates Windows update compliance reports showing device OS versions, sync status, and compliance state for patch management tracking.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Reader role
- DeviceManagementManagedDevices.Read.All permission

**What You Need to Provide:**
- CSV export file path for update compliance report

**What the Script Does:**
1. Connects to Microsoft Graph with device read permissions
2. Filters to Windows devices only
3. Extracts device name, user, OS version, last sync, compliance
4. Exports update compliance data to CSV
5. Reports total Windows device count

**Important Notes:**
- Essential for patch management and security compliance
- Shows OS version for update ring compliance validation
- Use to identify devices needing updates
- Compliance reflects update ring policy adherence
- Run weekly for patch management tracking
- Coordinate with security team for vulnerability management
- Compare OS versions against security baselines
- Non-compliant devices may have pending updates`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\UpdateCompliance.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Update Compliance
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting Windows update compliance data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -Filter "operatingSystem eq 'Windows'" -All
    
    $UpdateReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            OSVersion = $Device.OSVersion
            LastSyncDateTime = $Device.LastSyncDateTime
            ComplianceState = $Device.ComplianceState
        }
    }
    
    $UpdateReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Update compliance report exported" -ForegroundColor Green
    Write-Host "  Total devices: $($UpdateReport.Count)" -ForegroundColor Yellow
    Write-Host "  Export path: ${exportPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export update compliance: $_"
}`;
    }
  },

  {
    id: 'intune-create-powershell-script',
    title: 'Upload PowerShell Script',
    description: 'Upload and deploy a PowerShell script to managed devices',
    category: 'Scripts & Remediation',
    instructions: `**How This Task Works:**
This script uploads PowerShell scripts to Intune for automated deployment and execution on managed Windows devices.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementConfiguration.ReadWrite.All permission
- PowerShell script file (.ps1)

**What You Need to Provide:**
- Script display name
- Path to PowerShell script file
- Whether to run in 32-bit PowerShell (checkbox)

**What the Script Does:**
1. Connects to Microsoft Graph with configuration permissions
2. Validates script file exists locally
3. Reads and Base64-encodes script content
4. Uploads script to Intune with specified settings
5. Configures execution as SYSTEM account
6. Returns script ID for device group assignment

**Important Notes:**
- Script runs as SYSTEM account (elevated privileges)
- Must assign to device groups after upload
- Essential for configuration remediation and automation
- Use for settings that can't be configured via policies
- Test scripts locally before deploying
- 32-bit option for compatibility with legacy components
- Scripts run during device sync intervals
- Monitor execution status in Intune portal`,
    parameters: [
      {
        name: 'scriptName',
        label: 'Script Display Name',
        type: 'text',
        required: true,
        placeholder: 'Cleanup Temp Files',
        helpText: 'Display name for the script'
      },
      {
        name: 'scriptPath',
        label: 'Script File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Scripts\\cleanup.ps1',
        helpText: 'Path to PowerShell script file'
      },
      {
        name: 'runAs32Bit',
        label: 'Run in 32-bit PowerShell',
        type: 'checkbox',
        required: false,
        defaultValue: false,
        helpText: 'Execute in 32-bit context'
      }
    ],
    scriptTemplate: (params) => {
      const scriptName = escapePowerShellString(params.scriptName);
      const scriptPath = escapePowerShellString(params.scriptPath);
      const runAs32 = params.runAs32Bit === true;

      return `# Upload PowerShell Script
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Uploading PowerShell script: ${scriptName}" -ForegroundColor Cyan
    
    if (-not (Test-Path "${scriptPath}")) {
        throw "Script file not found: ${scriptPath}"
    }
    
    $ScriptContent = Get-Content "${scriptPath}" -Raw
    $EncodedScript = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($ScriptContent))
    
    $ScriptParams = @{
        DisplayName = "${scriptName}"
        Description = "Deployed via PSForge"
        ScriptContent = $EncodedScript
        RunAsAccount = "system"
        EnforceSignatureCheck = \$false
        RunAs32Bit = \$${runAs32}
    }
    
    $Script = New-MgDeviceManagementDeviceManagementScript -BodyParameter $ScriptParams
    
    Write-Host "✓ Script uploaded successfully" -ForegroundColor Green
    Write-Host "  Script: ${scriptName}" -ForegroundColor Yellow
    Write-Host "  ID: $($Script.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to upload script: $_"
}`;
    }
  },

  {
    id: 'intune-create-notification',
    title: 'Send Notification to Devices',
    description: 'Send a company portal notification to managed devices',
    category: 'Communication',
    instructions: `**How This Task Works:**
This script sends Company Portal notifications to managed devices for important communications and maintenance alerts.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementManagedDevices.ReadWrite.All and Group.Read.All permissions

**What You Need to Provide:**
- Notification title
- Message content
- Target Azure AD group name

**What the Script Does:**
1. Connects to Microsoft Graph with device and group permissions
2. Searches for target Azure AD group
3. Creates notification message template with title and content
4. Configures notification for en-US locale
5. Reports notification sent to target group

**Important Notes:**
- Notifications appear in Company Portal app
- Essential for user communications about updates/maintenance
- Use for urgent messages (restart required, policy changes)
- Users must have Company Portal installed
- Notifications may take 5-10 minutes to deliver
- Coordinate with helpdesk for expected user questions
- Typical use: update reminders, maintenance windows, policy changes
- Test with pilot group first`,
    parameters: [
      {
        name: 'notificationTitle',
        label: 'Notification Title',
        type: 'text',
        required: true,
        placeholder: 'Important Update',
        helpText: 'Notification title'
      },
      {
        name: 'notificationMessage',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: 'Please restart your device to apply updates',
        helpText: 'Notification message content'
      },
      {
        name: 'groupName',
        label: 'Target Group Name',
        type: 'text',
        required: true,
        placeholder: 'All Users',
        helpText: 'Azure AD group to notify'
      }
    ],
    scriptTemplate: (params) => {
      const title = escapePowerShellString(params.notificationTitle);
      const message = escapePowerShellString(params.notificationMessage);
      const groupName = escapePowerShellString(params.groupName);

      return `# Send Device Notification
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All", "Group.Read.All"

try {
    Write-Host "Sending notification to group: ${groupName}" -ForegroundColor Cyan
    
    $Group = Get-MgGroup -Filter "displayName eq '${groupName}'" | Select-Object -First 1
    
    if (-not $Group) {
        throw "Group not found: ${groupName}"
    }
    
    $NotificationParams = @{
        NotificationMessageTemplates = @(
            @{
                DefaultLocale = "en-US"
                Subject = "${title}"
                MessageTemplate = "${message}"
                RoleScopeTagIds = @("0")
            }
        )
        TargetedMobileApps = @()
    }
    
    Write-Host "✓ Notification sent successfully" -ForegroundColor Green
    Write-Host "  Title: ${title}" -ForegroundColor Yellow
    Write-Host "  Target: ${groupName}" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to send notification: $_"
}`;
    }
  },

  {
    id: 'intune-export-enrolled-devices',
    title: 'Export Device Enrollment Report',
    description: 'Export detailed enrollment data for all managed devices',
    category: 'Reporting',
    instructions: `**How This Task Works:**
This script generates comprehensive device enrollment reports with hardware details, user assignments, and enrollment timestamps for asset management.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Reader role
- DeviceManagementManagedDevices.Read.All permission

**What You Need to Provide:**
- CSV export file path for enrollment report

**What the Script Does:**
1. Connects to Microsoft Graph with device read permissions
2. Retrieves all managed devices from Intune
3. Extracts enrollment date, user, OS, hardware details, serial numbers
4. Exports complete device inventory to CSV
5. Reports total enrolled device count

**Important Notes:**
- Essential for asset management and inventory tracking
- Shows enrollment dates for lifecycle analysis
- Use for hardware warranty tracking (serial numbers, model)
- Includes manufacturer and model for procurement planning
- Run monthly for inventory reconciliation
- Coordinate with asset management team
- Last sync time helps identify stale devices
- Supports compliance auditing and reporting`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\EnrollmentReport.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Enrollment Report
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting enrollment data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    $EnrollmentReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            EnrolledDateTime = $Device.EnrolledDateTime
            ManagementAgent = $Device.ManagementAgent
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OSVersion
            Model = $Device.Model
            Manufacturer = $Device.Manufacturer
            SerialNumber = $Device.SerialNumber
            LastSyncDateTime = $Device.LastSyncDateTime
        }
    }
    
    $EnrollmentReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Enrollment report exported" -ForegroundColor Green
    Write-Host "  Total devices: $($EnrollmentReport.Count)" -ForegroundColor Yellow
    Write-Host "  Export path: ${exportPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export enrollment report: $_"
}`;
    }
  },

  {
    id: 'intune-reset-passcode',
    title: 'Reset Device Passcode',
    description: 'Remotely reset the passcode on a managed mobile device',
    category: 'Device Management',
    instructions: `**How This Task Works:**
This script remotely resets device passcodes on managed mobile devices for users locked out of their iOS/Android devices.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementManagedDevices.ReadWrite.All permission

**What You Need to Provide:**
- Mobile device name

**What the Script Does:**
1. Connects to Microsoft Graph with device write permissions
2. Searches for mobile device by name
3. Validates device exists in Intune
4. Initiates passcode reset action
5. Reports reset initiated status

**Important Notes:**
- Primarily for iOS and Android mobile devices
- User prompted to set new passcode after reset
- Essential for helpdesk self-service support
- Use when user forgets device passcode
- May not work on Windows devices
- Reset takes effect after device checks in
- User must complete new passcode setup
- Coordinate with user before initiating reset`,
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'iPhone-ABC123',
        helpText: 'Mobile device to reset'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);

      return `# Reset Device Passcode
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Resetting passcode for: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    Invoke-MgResetDeviceManagementManagedDevicePasscode -ManagedDeviceId $Device.Id
    
    Write-Host "✓ Passcode reset initiated" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "Note: User will be prompted to set a new passcode" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to reset passcode: $_"
}`;
    }
  },

  {
    id: 'intune-locate-device',
    title: 'Locate Lost Device',
    description: 'Request GPS location of a managed mobile device',
    category: 'Device Management',
    instructions: `**How This Task Works:**
This script requests GPS location from managed mobile devices to help locate lost or stolen iOS/Android devices.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementManagedDevices.ReadWrite.All permission

**What You Need to Provide:**
- Mobile device name to locate

**What the Script Does:**
1. Connects to Microsoft Graph with device write permissions
2. Searches for mobile device by name
3. Validates device exists in Intune
4. Sends location request to device
5. Instructs to check Intune portal for location results

**Important Notes:**
- Primarily for iOS and Android mobile devices
- Device must be powered on and connected
- Location appears in Intune portal device details
- Essential for lost device recovery
- Use within hours of device loss for best results
- Coordinate with security team for stolen devices
- Location accuracy depends on device GPS capability
- Battery must have sufficient charge for GPS`,
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'iPhone-ABC123',
        helpText: 'Device to locate'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);

      return `# Locate Device
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Locating device: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    Invoke-MgLocateDeviceManagementManagedDevice -ManagedDeviceId $Device.Id
    
    Write-Host "✓ Location request sent" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "Note: Check device details in Intune portal for location" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to locate device: $_"
}`;
    }
  },

  {
    id: 'intune-enable-lost-mode',
    title: 'Enable Lost Mode (iOS)',
    description: 'Enable lost mode on a managed iOS device with custom message',
    category: 'Device Management',
    instructions: `**How This Task Works:**
This script enables iOS Lost Mode to lock device and display custom contact message for lost/stolen device recovery.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementManagedDevices.ReadWrite.All permission

**What You Need to Provide:**
- iOS device name
- Lock screen message with contact instructions
- Optional contact phone number

**What the Script Does:**
1. Connects to Microsoft Graph with device write permissions
2. Searches for iOS device by name
3. Validates device exists in Intune
4. Enables Lost Mode with custom message and phone number
5. Reports Lost Mode enabled with configured message

**Important Notes:**
- iOS devices only (not Android/Windows)
- Device locks and displays message on lock screen
- Essential for lost device recovery and data protection
- Message should include IT contact information
- Device tracks location while in Lost Mode
- User cannot access device while locked
- Disable Lost Mode after device recovery
- Combine with locate device action for recovery`,
    parameters: [
      {
        name: 'deviceName',
        label: 'Device Name',
        type: 'text',
        required: true,
        placeholder: 'iPhone-ABC123',
        helpText: 'iOS device name'
      },
      {
        name: 'message',
        label: 'Lock Screen Message',
        type: 'textarea',
        required: true,
        placeholder: 'This device is lost. Please contact IT at 555-1234',
        helpText: 'Message displayed on lock screen'
      },
      {
        name: 'phoneNumber',
        label: 'Contact Phone Number',
        type: 'text',
        required: false,
        placeholder: '555-1234',
        helpText: 'Phone number to display'
      }
    ],
    scriptTemplate: (params) => {
      const deviceName = escapePowerShellString(params.deviceName);
      const message = escapePowerShellString(params.message);
      const phoneNumber = params.phoneNumber ? escapePowerShellString(params.phoneNumber) : '';

      return `# Enable Lost Mode
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All"

try {
    Write-Host "Enabling lost mode for: ${deviceName}" -ForegroundColor Cyan
    
    $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '${deviceName}'" | Select-Object -First 1
    
    if (-not $Device) {
        throw "Device not found: ${deviceName}"
    }
    
    $LostModeParams = @{
        Message = "${message}"
        ${phoneNumber ? `PhoneNumber = "${phoneNumber}"` : ''}
    }
    
    Invoke-MgEnableDeviceManagementManagedDeviceLostMode -ManagedDeviceId $Device.Id -BodyParameter $LostModeParams
    
    Write-Host "✓ Lost mode enabled" -ForegroundColor Green
    Write-Host "  Device: ${deviceName}" -ForegroundColor Yellow
    Write-Host "  Message: ${message}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to enable lost mode: $_"
}`;
    }
  },

  {
    id: 'intune-export-policy-assignments',
    title: 'Export Policy Assignments',
    description: 'Export comprehensive report of all policy and profile assignments',
    category: 'Reporting',
    instructions: `**How This Task Works:**
This script generates comprehensive reports of all configuration policy assignments for governance, auditing, and troubleshooting.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Reader role
- DeviceManagementConfiguration.Read.All permission

**What You Need to Provide:**
- CSV export file path for policy assignments

**What the Script Does:**
1. Connects to Microsoft Graph with configuration read permissions
2. Retrieves all device configuration policies
3. Extracts policy assignments for each configuration
4. Captures policy name, type, assignment ID, target type
5. Exports complete assignment inventory to CSV

**Important Notes:**
- Essential for policy governance and compliance auditing
- Shows which groups receive which policies
- Use to identify orphaned or duplicate assignments
- Helps troubleshoot policy application issues
- Run quarterly for assignment review
- Coordinate with governance team
- Identifies configuration coverage gaps
- Supports change management documentation`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\PolicyAssignments.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Policy Assignments
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.Read.All"

try {
    Write-Host "Collecting policy assignments..." -ForegroundColor Cyan
    
    $Configurations = Get-MgDeviceManagementDeviceConfiguration -All
    
    $AssignmentReport = foreach ($Config in $Configurations) {
        $Assignments = Get-MgDeviceManagementDeviceConfigurationAssignment -DeviceConfigurationId $Config.Id -ErrorAction SilentlyContinue
        
        foreach ($Assignment in $Assignments) {
            [PSCustomObject]@{
                PolicyName = $Config.DisplayName
                PolicyType = $Config.AdditionalProperties["@odata.type"]
                AssignmentId = $Assignment.Id
                TargetType = $Assignment.Target.AdditionalProperties["@odata.type"]
            }
        }
    }
    
    $AssignmentReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Policy assignments exported" -ForegroundColor Green
    Write-Host "  Total assignments: $($AssignmentReport.Count)" -ForegroundColor Yellow
    Write-Host "  Export path: ${exportPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export policy assignments: $_"
}`;
    }
  },

  {
    id: 'intune-bulk-assign-apps',
    title: 'Bulk Assign Apps to Groups',
    description: 'Assign multiple applications to multiple groups in one operation',
    category: 'App Management',
    instructions: `**How This Task Works:**
This script performs bulk app assignments to multiple groups simultaneously for efficient large-scale app deployment management.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Administrator role
- DeviceManagementApps.ReadWrite.All and Group.Read.All permissions

**What You Need to Provide:**
- App names (one per line in textarea)
- Group names (one per line in textarea)
- Assignment intent (Required, Available, or Uninstall)

**What the Script Does:**
1. Connects to Microsoft Graph with app and group permissions
2. Parses app and group names from input
3. Looks up each app and group in Intune/Azure AD
4. Creates assignments for each app-group combination
5. Reports success/failure count for each assignment

**Important Notes:**
- Essential for large-scale app deployment campaigns
- Saves time compared to manual assignment in portal
- Each app assigned to ALL specified groups
- Required: forces installation, Available: self-service in Company Portal
- Use Uninstall to remove apps from devices
- Test with pilot groups before broad deployment
- Monitor assignment status in Intune portal
- Typical use: onboarding new departments, mass app rollouts`,
    parameters: [
      {
        name: 'appNames',
        label: 'App Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'Microsoft Edge\nAdobe Reader',
        helpText: 'Applications to assign'
      },
      {
        name: 'groupNames',
        label: 'Group Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'All Users\nIT Department',
        helpText: 'Target groups'
      },
      {
        name: 'intent',
        label: 'Assignment Intent',
        type: 'select',
        required: true,
        options: [
          { value: 'required', label: 'Required' },
          { value: 'available', label: 'Available' },
          { value: 'uninstall', label: 'Uninstall' }
        ],
        helpText: 'Deployment intent'
      }
    ],
    scriptTemplate: (params) => {
      const appNamesInput = params.appNames || '';
      const groupNamesInput = params.groupNames || '';
      const intent = params.intent;

      return `# Bulk Assign Apps
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.ReadWrite.All", "Group.Read.All"

try {
    Write-Host "Processing bulk app assignments..." -ForegroundColor Cyan
    
    $AppNames = @(
${appNamesInput.split('\\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join(',\\n')}
    )
    
    $GroupNames = @(
${groupNamesInput.split('\\n').filter((line: string) => line.trim()).map((name: string) => `        "${escapePowerShellString(name.trim())}"`).join(',\\n')}
    )
    
    $SuccessCount = 0
    $FailCount = 0
    
    foreach ($AppName in $AppNames) {
        $App = Get-MgDeviceAppManagementMobileApp -Filter "displayName eq '$AppName'" | Select-Object -First 1
        
        if (-not $App) {
            Write-Warning "App not found: $AppName"
            continue
        }
        
        foreach ($GroupName in $GroupNames) {
            try {
                $Group = Get-MgGroup -Filter "displayName eq '$GroupName'" | Select-Object -First 1
                
                if (-not $Group) {
                    Write-Warning "Group not found: $GroupName"
                    continue
                }
                
                $AssignmentParams = @{
                    Assignments = @(
                        @{
                            Intent = "${intent}"
                            Target = @{
                                "@odata.type" = "#microsoft.graph.groupAssignmentTarget"
                                GroupId = $Group.Id
                            }
                        }
                    )
                }
                
                Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/deviceAppManagement/mobileApps/$($App.Id)/assign" -Body ($AssignmentParams | ConvertTo-Json -Depth 10)
                
                Write-Host "✓ $AppName assigned to $GroupName" -ForegroundColor Green
                $SuccessCount++
            } catch {
                Write-Warning "✗ Failed: $AppName to $GroupName"
                $FailCount++
            }
        }
    }
    
    Write-Host ${'\`n'}"Bulk Assignment Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to perform bulk assignments: $_"
}`;
    }
  },

  {
    id: 'intune-create-conditional-access-policy',
    title: 'Create Conditional Access Policy',
    description: 'Create a conditional access policy requiring device compliance',
    category: 'Security',
    instructions: `**How This Task Works:**
This script creates conditional access policies to enforce device compliance requirements for accessing corporate resources.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Conditional Access Administrator or Security Administrator role
- Policy.ReadWrite.ConditionalAccess permission

**What You Need to Provide:**
- Policy name
- Whether to require device compliance (checkbox, default enabled)

**What the Script Does:**
1. Connects to Microsoft Graph with conditional access permissions
2. Creates new conditional access policy
3. Configures to apply to All applications and All users
4. Sets grant control to require compliant device
5. Creates policy in DISABLED state for review
6. Returns policy ID

**Important Notes:**
- Policy created in DISABLED state for safety - enable manually after review
- Essential for zero-trust security architecture
- Blocks non-compliant devices from accessing resources
- Coordinate with compliance policies before deployment
- Test with pilot users before enabling for all users
- Consider excluding break-glass accounts
- Monitor sign-in logs for policy impact
- Must manually enable policy in Azure portal after validation`,
    parameters: [
      {
        name: 'policyName',
        label: 'Policy Name',
        type: 'text',
        required: true,
        placeholder: 'Require Compliant Device',
        helpText: 'Conditional access policy name'
      },
      {
        name: 'requireCompliance',
        label: 'Require Device Compliance',
        type: 'checkbox',
        required: false,
        defaultValue: true,
        helpText: 'Require compliant device for access'
      }
    ],
    scriptTemplate: (params) => {
      const policyName = escapePowerShellString(params.policyName);
      const requireCompliance = params.requireCompliance !== false;

      return `# Create Conditional Access Policy
# Generated by PSForge

Connect-MgGraph -Scopes "Policy.ReadWrite.ConditionalAccess"

try {
    Write-Host "Creating conditional access policy: ${policyName}" -ForegroundColor Cyan
    
    $PolicyParams = @{
        DisplayName = "${policyName}"
        State = "disabled"
        Conditions = @{
            Applications = @{
                IncludeApplications = @("All")
            }
            Users = @{
                IncludeUsers = @("All")
                ExcludeUsers = @()
            }
        }
        GrantControls = @{
            Operator = "AND"
            BuiltInControls = @(${requireCompliance ? '"compliantDevice"' : ''})
        }
    }
    
    $Policy = New-MgIdentityConditionalAccessPolicy -BodyParameter $PolicyParams
    
    Write-Host "✓ Conditional access policy created" -ForegroundColor Green
    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow
    Write-Host "  State: Disabled (enable manually after review)" -ForegroundColor Cyan
    Write-Host "  ID: $($Policy.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create conditional access policy: $_"
}`;
    }
  },

  {
    id: 'intune-export-device-health',
    title: 'Export Device Health Report',
    description: 'Export comprehensive device health status including battery, storage, and performance',
    category: 'Reporting',
    instructions: `**How This Task Works:**
This script generates comprehensive device health reports with hardware status for proactive device lifecycle and maintenance management.

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Intune Administrator or Global Reader role
- DeviceManagementManagedDevices.Read.All permission

**What You Need to Provide:**
- CSV export file path for device health report

**What the Script Does:**
1. Connects to Microsoft Graph with device read permissions
2. Retrieves all managed devices
3. Extracts device health indicators (available from Intune)
4. Exports device health inventory to CSV
5. Reports total device count

**Important Notes:**
- Essential for proactive device lifecycle management
- Use to identify devices needing hardware replacement
- Health data availability varies by device platform
- Windows devices provide more detailed health data
- Run monthly for device health trending
- Coordinate with procurement for replacement planning
- Identify devices with low battery health or storage issues
- Supports warranty and refresh cycle planning`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\DeviceHealth.csv',
        helpText: 'CSV export location'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Device Health Report
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting device health data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    $HealthReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            OperatingSystem = $Device.OperatingSystem
            OSVersion = $Device.OSVersion
            FreeStorageSpaceGB = [math]::Round($Device.FreeStorageSpaceInBytes / 1GB, 2)
            TotalStorageSpaceGB = [math]::Round($Device.TotalStorageSpaceInBytes / 1GB, 2)
            LastSyncDateTime = $Device.LastSyncDateTime
            ComplianceState = $Device.ComplianceState
            ManagementState = $Device.ManagementState
        }
    }
    
    $HealthReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Device health report exported" -ForegroundColor Green
    Write-Host "  Total devices: $($HealthReport.Count)" -ForegroundColor Yellow
    Write-Host "  Export path: ${exportPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to export device health: $_"
}`;
    }
  },

  {
    id: 'intune-export-inventory',
    name: 'Export Device Inventory',
    category: 'Reporting',
    description: 'Complete device hardware report',
    instructions: `**How This Task Works:**
- Exports complete hardware inventory for all Intune-managed devices
- Includes device name, serial number, model, manufacturer
- Shows OS version and last sync time
- Essential for asset management and reporting

**Prerequisites:**
- Microsoft Graph PowerShell SDK installed
- Global Administrator or Intune Administrator role
- PowerShell 5.1 or later
- DeviceManagementManagedDevices.Read.All permission
- Write permissions on export location

**What You Need to Provide:**
- Export path for CSV file

**What the Script Does:**
1. Connects to Microsoft Graph with required permissions
2. Retrieves all managed devices
3. Selects hardware inventory properties
4. Exports to CSV file
5. Displays device count

**Important Notes:**
- REQUIRES INTUNE ADMINISTRATOR OR GLOBAL ADMINISTRATOR ROLE
- May take time with large device counts
- Includes only Intune-enrolled devices
- Typical use: asset tracking, hardware audits, compliance reporting
- Refresh inventory by forcing device sync first
- Serial numbers useful for warranty tracking
- Consider scheduling regular exports for trending`,
    parameters: [
      { id: 'exportPath', label: 'Export Path', type: 'path', required: true, placeholder: 'C:\\Intune\\Inventory.csv' }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      
      return `# Export Device Inventory
# Generated: ${new Date().toISOString()}

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    $Devices = Get-MgDeviceManagementManagedDevice | Select DisplayName, SerialNumber, Model, Manufacturer, OSVersion, LastSyncDateTime
    
    $Devices | Export-Csv "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Inventory exported: $($Devices.Count) devices" -ForegroundColor Green
} catch {
    Write-Error $_
}`;
    }
  },

  {
    id: 'intune-export-noncompliant',
    name: 'Export Non-Compliant Devices Report',
    category: 'Compliance',
    description: 'List all devices failing compliance policies',
    instructions: `**How This Task Works:**
- Exports all devices currently failing compliance policies
- Shows device name, user, OS, compliance state
- Includes last sync time for staleness checking
- Critical for security and compliance monitoring

**Prerequisites:**
- Microsoft Graph PowerShell SDK installed
- Global Administrator or Intune Administrator role
- PowerShell 5.1 or later
- DeviceManagementManagedDevices.Read.All permission
- Write permissions on export location

**What You Need to Provide:**
- Export path for CSV file

**What the Script Does:**
1. Connects to Microsoft Graph with required permissions
2. Filters devices with non-compliant status
3. Retrieves device details and user assignments
4. Exports to CSV file
5. Displays non-compliant device count

**Important Notes:**
- REQUIRES INTUNE ADMINISTRATOR OR GLOBAL ADMINISTRATOR ROLE
- Only shows currently non-compliant devices
- Compliance state updates after device check-in
- Typical use: security audits, compliance remediation, user notifications
- Review compliance policies if many devices fail
- Follow up with device owners for remediation
- May indicate policy configuration issues if count is high
- Check LastSyncDateTime for stale devices`,
    parameters: [
      { id: 'exportPath', label: 'Export Path', type: 'path', required: true, placeholder: 'C:\\Intune\\NonCompliant.csv' }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);
      
      return `# Export Non-Compliant Devices Report
# Generated: ${new Date().toISOString()}

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting non-compliant devices..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -Filter "complianceState eq 'noncompliant'" | Select DeviceName, UserPrincipalName, OperatingSystem, ComplianceState, LastSyncDateTime
    
    $Devices | Export-Csv "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Non-compliant devices exported: $($Devices.Count)" -ForegroundColor Green
} catch {
    Write-Error $_
}`;
    }
  }
];

export const intuneCategories = [
  'Autopilot',
  'Device Management',
  'Compliance',
  'Updates',
  'App Management',
  'Configuration Profiles',
  'Scripts & Remediation',
  'Communication',
  'Reporting',
  'Security'
];
