import { escapePowerShellString } from './powershell-utils';

export interface IntuneParameter {
  title: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface IntuneTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: IntuneParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const intuneTasks: IntuneTask[] = [
  {
    id: 'intune-sync-autopilot',
    title: 'Sync Autopilot Devices',
    description: 'Force a sync of Autopilot device registrations',
    category: 'Autopilot',
    parameters: [],
    scriptTemplate: () => {
      return `# Sync Autopilot Devices
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementServiceConfig.ReadWrite.All"

try {
    Write-Host "Initiating Autopilot device sync..." -ForegroundColor Cyan
    
    Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/deviceManagement/windowsAutopilotSettings/sync"
    
    Write-Host "✓ Autopilot sync initiated successfully" -ForegroundColor Green
    Write-Host "Note: Sync may take several minutes to complete" -ForegroundColor Yellow
    
} catch {
    Write-Error "Failed to sync Autopilot devices: $_"
}`;
    }
  },

  {
    id: 'intune-export-device-inventory',
    title: 'Export Device Inventory',
    description: 'Export comprehensive inventory of all Intune-managed devices to CSV',
    category: 'Device Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\IntuneDevices.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Intune Device Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting Intune device inventory..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    Write-Host "Found $($Devices.Count) devices" -ForegroundColor Yellow
    
    $Inventory = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName           = $Device.DeviceName
            UserPrincipalName    = $Device.UserPrincipalName
            Model                = $Device.Model
            Manufacturer         = $Device.Manufacturer
            OperatingSystem      = $Device.OperatingSystem
            OSVersion            = $Device.OSVersion
            SerialNumber         = $Device.SerialNumber
            LastSyncDateTime     = $Device.LastSyncDateTime
            ComplianceState      = $Device.ComplianceState
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Device inventory exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export device inventory: $_"
}`;
    }
  },

  {
    id: 'intune-export-compliance-report',
    title: 'Export Compliance Report',
    description: 'Export device compliance status report to CSV',
    category: 'Compliance',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ComplianceReport.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Intune Compliance Report
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All"

try {
    Write-Host "Collecting compliance data..." -ForegroundColor Cyan
    
    $Devices = Get-MgDeviceManagementManagedDevice -All
    
    $ComplianceReport = foreach ($Device in $Devices) {
        [PSCustomObject]@{
            DeviceName        = $Device.DeviceName
            UserPrincipalName = $Device.UserPrincipalName
            ComplianceState   = $Device.ComplianceState
            OperatingSystem   = $Device.OperatingSystem
            OSVersion         = $Device.OSVersion
            LastSyncDateTime  = $Device.LastSyncDateTime
        }
    }
    
    $ComplianceReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Compliance report exported to: ${exportPath}" -ForegroundColor Green
    
    Write-Host \"\`nCompliance Summary:" -ForegroundColor Yellow
    $ComplianceReport | Group-Object ComplianceState | Format-Table Name, Count
    
} catch {
    Write-Error "Failed to export compliance report: $_"
}`;
    }
  },

  {
    id: 'intune-create-update-ring',
    title: 'Create Windows Update Ring',
    description: 'Create a new Windows Update deployment ring',
    category: 'Updates',
    parameters: [
      {
        name: 'ringName',
        label: 'Ring Name',
        type: 'text',
        required: true,
        placeholder: 'Pilot Ring',
        helpText: 'Name for the update ring'
      },
      {
        name: 'deferralDays',
        label: 'Feature Update Deferral (days)',
        type: 'number',
        required: true,
        defaultValue: 0,
        helpText: 'Days to defer feature updates'
      }
    ],
    scriptTemplate: (params) => {
      const ringName = escapePowerShellString(params.ringName);
      const featureDeferral = params.deferralDays || 0;

      return `# Create Windows Update Ring
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

try {
    Write-Host "Creating update ring: ${ringName}" -ForegroundColor Cyan
    
    $UpdateRingParams = @{
        "@odata.type" = "#microsoft.graph.windowsUpdateForBusinessConfiguration"
        DisplayName = "${ringName}"
        FeatureUpdatesDeferralPeriodInDays = ${featureDeferral}
        QualityUpdatesDeferralPeriodInDays = 0
        AutomaticUpdateMode = "windowsDefault"
    }
    
    $UpdateRing = New-MgDeviceManagementDeviceConfiguration -BodyParameter $UpdateRingParams
    
    Write-Host "✓ Update ring created successfully" -ForegroundColor Green
    Write-Host "  ID: $($UpdateRing.Id)" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to create update ring: $_"
}`;
    }
  },

  {
    id: 'intune-export-app-status',
    title: 'Export App Deployment Status',
    description: 'Export application deployment status report to CSV',
    category: 'App Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AppStatus.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export App Deployment Status
# Generated by PSForge

Connect-MgGraph -Scopes "DeviceManagementApps.Read.All"

try {
    Write-Host "Collecting app deployment data..." -ForegroundColor Cyan
    
    $Apps = Get-MgDeviceAppManagementMobileApp -All
    
    Write-Host "Found $($Apps.Count) apps" -ForegroundColor Yellow
    
    $DeploymentReport = foreach ($App in $Apps) {
        [PSCustomObject]@{
            AppName    = $App.DisplayName
            AppType    = $App.AdditionalProperties["@odata.type"]
            Publisher  = $App.Publisher
        }
    }
    
    $DeploymentReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Deployment status exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export deployment status: $_"
}`;
    }
  }
];

export const intuneCategories = [
  'Autopilot',
  'Device Management',
  'Compliance',
  'Updates',
  'App Management'
];
