import { escapePowerShellString } from './powershell-utils';

export interface Office365Parameter {
  title: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface Office365Task {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: Office365Parameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const office365Tasks: Office365Task[] = [
  {
    id: 'o365-export-licenses',
    title: 'Export License Inventory',
    description: 'Export comprehensive report of Office 365 licenses to CSV',
    category: 'Licensing',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\O365Licenses.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Office 365 License Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "Organization.Read.All"

try {
    Write-Host "Collecting Office 365 licenses..." -ForegroundColor Cyan
    
    $Skus = Get-MgSubscribedSku
    
    $LicenseReport = foreach ($Sku in $Skus) {
        [PSCustomObject]@{
            SkuPartNumber    = $Sku.SkuPartNumber
            TotalLicenses    = $Sku.PrepaidUnits.Enabled
            AssignedLicenses = $Sku.ConsumedUnits
            AvailableLicenses = $Sku.PrepaidUnits.Enabled - $Sku.ConsumedUnits
        }
    }
    
    $LicenseReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ License inventory exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export licenses: $_"
}`;
    }
  },

  {
    id: 'o365-export-user-licenses',
    title: 'Export User License Assignments',
    description: 'Export detailed user license assignments to CSV',
    category: 'Licensing',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\UserLicenses.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export User License Assignments
# Generated by PSForge

Connect-MgGraph -Scopes "User.Read.All", "Organization.Read.All"

try {
    Write-Host "Collecting user license assignments..." -ForegroundColor Cyan
    
    $Users = Get-MgUser -All -Property DisplayName, UserPrincipalName, AssignedLicenses
    
    $LicenseReport = foreach ($User in $Users) {
        if ($User.AssignedLicenses.Count -gt 0) {
            [PSCustomObject]@{
                DisplayName       = $User.DisplayName
                UserPrincipalName = $User.UserPrincipalName
                LicenseCount      = $User.AssignedLicenses.Count
            }
        }
    }
    
    $LicenseReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ User licenses exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export user licenses: $_"
}`;
    }
  },

  {
    id: 'o365-export-service-health',
    title: 'Export Service Health Status',
    description: 'Export current Office 365 service health status to CSV',
    category: 'Health Monitoring',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ServiceHealth.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Service Health Status
# Generated by PSForge

Connect-MgGraph -Scopes "ServiceHealth.Read.All"

try {
    Write-Host "Collecting service health data..." -ForegroundColor Cyan
    
    $HealthStatus = Get-MgServiceAnnouncementHealthOverview
    
    $HealthReport = foreach ($Service in $HealthStatus) {
        [PSCustomObject]@{
            Service      = $Service.Service
            Status       = $Service.Status
        }
    }
    
    $HealthReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Service health exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export service health: $_"
}`;
    }
  },

  {
    id: 'o365-export-admin-roles',
    title: 'Export Admin Role Assignments',
    description: 'Export Office 365 admin role assignments to CSV',
    category: 'Administration',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AdminRoles.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Admin Role Assignments
# Generated by PSForge

Connect-MgGraph -Scopes "RoleManagement.Read.Directory"

try {
    Write-Host "Collecting admin role assignments..." -ForegroundColor Cyan
    
    $Roles = Get-MgDirectoryRole -All
    
    $RoleReport = foreach ($Role in $Roles) {
        $Members = Get-MgDirectoryRoleMember -DirectoryRoleId $Role.Id
        
        foreach ($Member in $Members) {
            [PSCustomObject]@{
                RoleName         = $Role.DisplayName
                MemberName       = $Member.AdditionalProperties.displayName
                MemberType       = $Member.AdditionalProperties."@odata.type"
            }
        }
    }
    
    $RoleReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Admin roles exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export admin roles: $_"
}`;
    }
  },

  {
    id: 'o365-export-domains',
    title: 'Export Tenant Domains',
    description: 'Export list of all domains in the Office 365 tenant to CSV',
    category: 'Tenant Configuration',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\Domains.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Tenant Domains
# Generated by PSForge

Connect-MgGraph -Scopes "Domain.Read.All"

try {
    Write-Host "Collecting tenant domains..." -ForegroundColor Cyan
    
    $Domains = Get-MgDomain
    
    $DomainReport = foreach ($Domain in $Domains) {
        [PSCustomObject]@{
            DomainName       = $Domain.Id
            IsDefault        = $Domain.IsDefault
            IsVerified       = $Domain.IsVerified
        }
    }
    
    $DomainReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Domains exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export domains: $_"
}`;
    }
  }
];

export const office365Categories = [
  'Licensing',
  'Health Monitoring',
  'Administration',
  'Tenant Configuration'
];
