import { escapePowerShellString } from './powershell-utils';

export interface Office365Parameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface Office365Task {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: Office365Parameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const office365Tasks: Office365Task[] = [
  {
    id: 'o365-export-licenses',
    title: 'Export License Inventory',
    description: 'Export comprehensive report of Office 365 licenses to CSV',
    category: 'Licensing',
    instructions: `**How This Task Works:**
This script exports a comprehensive inventory of all Office 365 license SKUs with allocation details for capacity planning and license management.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- Organization.Read.All permission
- Global Administrator or License Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves all subscribed SKUs
- Calculates total, assigned, and available licenses
- Exports detailed report to CSV
- Reports export success

**Important Notes:**
- Essential for license management and capacity planning
- Shows SKU part numbers (e.g., ENTERPRISEPACK for E3)
- Use for tracking license consumption and purchasing decisions
- Run monthly for license utilization trends
- Identify over-allocated SKUs requiring additional purchases
- Identify under-utilized SKUs for cost optimization
- Typical use: annual budgeting, quarterly reviews
- Compare with user count to predict growth needs`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\O365Licenses.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Office 365 License Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "Organization.Read.All"

try {
    Write-Host "Collecting Office 365 licenses..." -ForegroundColor Cyan
    
    $Skus = Get-MgSubscribedSku
    
    $LicenseReport = foreach ($Sku in $Skus) {
        [PSCustomObject]@{
            SkuPartNumber    = $Sku.SkuPartNumber
            TotalLicenses    = $Sku.PrepaidUnits.Enabled
            AssignedLicenses = $Sku.ConsumedUnits
            AvailableLicenses = $Sku.PrepaidUnits.Enabled - $Sku.ConsumedUnits
        }
    }
    
    $LicenseReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ License inventory exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export licenses: $_"
}`;
    }
  },

  {
    id: 'o365-export-user-licenses',
    title: 'Export User License Assignments',
    description: 'Export detailed user license assignments to CSV',
    category: 'Licensing',
    instructions: `**How This Task Works:**
This script exports user-level license assignment details showing which users have licenses and license counts for audit and optimization.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- User.Read.All and Organization.Read.All permissions
- License Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves all users with assigned licenses
- Counts licenses per user
- Exports user license details to CSV
- Reports export success

**Important Notes:**
- Essential for license audit and user verification
- Identifies users with multiple licenses
- Use for license optimization and deduplication
- Excludes unlicensed users from report
- Run during license audits or compliance reviews
- Compare with HR data to identify departures
- Typical use: quarterly license reviews, audit compliance
- Identify users with excessive license assignments`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\UserLicenses.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export User License Assignments
# Generated by PSForge

Connect-MgGraph -Scopes "User.Read.All", "Organization.Read.All"

try {
    Write-Host "Collecting user license assignments..." -ForegroundColor Cyan
    
    $Users = Get-MgUser -All -Property DisplayName, UserPrincipalName, AssignedLicenses
    
    $LicenseReport = foreach ($User in $Users) {
        if ($User.AssignedLicenses.Count -gt 0) {
            [PSCustomObject]@{
                DisplayName       = $User.DisplayName
                UserPrincipalName = $User.UserPrincipalName
                LicenseCount      = $User.AssignedLicenses.Count
            }
        }
    }
    
    $LicenseReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ User licenses exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export user licenses: $_"
}`;
    }
  },

  {
    id: 'o365-export-service-health',
    title: 'Export Service Health Status',
    description: 'Export current Office 365 service health status to CSV',
    category: 'Health Monitoring',
    instructions: `**How This Task Works:**
This script exports real-time Office 365 service health status for monitoring outages, degradation, and service incidents.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- ServiceHealth.Read.All permission
- Service Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves service health overview for all services
- Exports service status to CSV
- Reports export success

**Important Notes:**
- Essential for monitoring service availability and incidents
- Shows status for Exchange, SharePoint, Teams, etc.
- Status values: Healthy, Degraded, Interrupted
- Use for incident response and SLA tracking
- Run during suspected outages or performance issues
- Combine with service communications for details
- Typical use: daily health checks, incident investigations
- Automate for proactive monitoring dashboards`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ServiceHealth.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Service Health Status
# Generated by PSForge

Connect-MgGraph -Scopes "ServiceHealth.Read.All"

try {
    Write-Host "Collecting service health data..." -ForegroundColor Cyan
    
    $HealthStatus = Get-MgServiceAnnouncementHealthOverview
    
    $HealthReport = foreach ($Service in $HealthStatus) {
        [PSCustomObject]@{
            Service      = $Service.Service
            Status       = $Service.Status
        }
    }
    
    $HealthReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Service health exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export service health: $_"
}`;
    }
  },

  {
    id: 'o365-export-admin-roles',
    title: 'Export Admin Role Assignments',
    description: 'Export Office 365 admin role assignments to CSV',
    category: 'Administration',
    instructions: `**How This Task Works:**
This script exports all administrative role assignments for security audit, compliance, and privileged access review.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- RoleManagement.Read.Directory permission
- Privileged Role Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves all directory roles and members
- Exports role-member mappings to CSV
- Reports export success

**Important Notes:**
- Essential for security audit and privileged access management
- Shows Global Admin, Exchange Admin, SharePoint Admin, etc.
- Use for quarterly privileged access reviews
- Identify excessive admin assignments
- Run during security audits or compliance reviews
- Implement principle of least privilege
- Typical use: quarterly access reviews, audit compliance
- Compare with HR data to remove departed admins immediately`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\AdminRoles.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Admin Role Assignments
# Generated by PSForge

Connect-MgGraph -Scopes "RoleManagement.Read.Directory"

try {
    Write-Host "Collecting admin role assignments..." -ForegroundColor Cyan
    
    $Roles = Get-MgDirectoryRole -All
    
    $RoleReport = foreach ($Role in $Roles) {
        $Members = Get-MgDirectoryRoleMember -DirectoryRoleId $Role.Id
        
        foreach ($Member in $Members) {
            [PSCustomObject]@{
                RoleName         = $Role.DisplayName
                MemberName       = $Member.AdditionalProperties.displayName
                MemberType       = $Member.AdditionalProperties."@odata.type"
            }
        }
    }
    
    $RoleReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Admin roles exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export admin roles: $_"
}`;
    }
  },

  {
    id: 'o365-export-domains',
    title: 'Export Tenant Domains',
    description: 'Export list of all domains in the Office 365 tenant to CSV',
    category: 'Tenant Configuration',
    instructions: `**How This Task Works:**
This script exports all registered domains in Office 365 tenant with verification and default status for domain management and documentation.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- Domain.Read.All permission
- Domain Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves all tenant domains
- Shows default and verification status
- Exports domain inventory to CSV
- Reports export success

**Important Notes:**
- Essential for domain management and tenant documentation
- Shows .onmicrosoft.com and custom domains
- Default domain used for new user creation
- Verified domains ready for email and services
- Use for domain inventory and planning
- Identify unverified domains requiring DNS configuration
- Typical use: tenant documentation, domain audits
- Required before adding users to custom domains`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\Domains.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Tenant Domains
# Generated by PSForge

Connect-MgGraph -Scopes "Domain.Read.All"

try {
    Write-Host "Collecting tenant domains..." -ForegroundColor Cyan
    
    $Domains = Get-MgDomain
    
    $DomainReport = foreach ($Domain in $Domains) {
        [PSCustomObject]@{
            DomainName       = $Domain.Id
            IsDefault        = $Domain.IsDefault
            IsVerified       = $Domain.IsVerified
        }
    }
    
    $DomainReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Domains exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export domains: $_"
}`;
    }
  },

  // Additional Office 365 Tasks (25 tasks)
  {id:'o365-assign-license',title:'Assign License to User',description:'Assign Office 365 licenses to a user',category:'Licensing',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com',helpText:'User to license'},{name:'skuId',label:'License SKU ID',type:'text',required:true,placeholder:'c42b9cae-ea4f-4ab7-9717-81576235ccac',helpText:'SKU ID for license'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);const skuId=escapePowerShellString(params.skuId);return `# Assign Office 365 License\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All", "Organization.Read.All"\n\ntry {\n    Write-Host "Assigning license to ${userEmail}" -ForegroundColor Cyan\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    $LicenseParams = @{\n        AddLicenses = @(@{\n            SkuId = "${skuId}"\n        })\n        RemoveLicenses = @()\n    }\n    \n    Set-MgUserLicense -UserId $User.Id -BodyParameter $LicenseParams\n    \n    Write-Host "✓ License assigned successfully" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to assign license: $_"\n}`;}},

  {id:'o365-remove-license',title:'Remove License from User',description:'Remove Office 365 license from a user',category:'Licensing',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com',helpText:'User to remove license from'},{name:'skuId',label:'License SKU ID',type:'text',required:true,placeholder:'c42b9cae-ea4f-4ab7-9717-81576235ccac',helpText:'SKU ID to remove'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);const skuId=escapePowerShellString(params.skuId);return `# Remove Office 365 License\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All"\n\ntry {\n    Write-Host "Removing license from ${userEmail}" -ForegroundColor Cyan\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    $LicenseParams = @{\n        AddLicenses = @()\n        RemoveLicenses = @("${skuId}")\n    }\n    \n    Set-MgUserLicense -UserId $User.Id -BodyParameter $LicenseParams\n    \n    Write-Host "✓ License removed successfully" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to remove license: $_"\n}`;}},

  {id:'o365-bulk-license',title:'Bulk Assign Licenses from CSV',description:'Assign licenses to multiple users from CSV file',category:'Licensing',parameters:[{name:'csvPath',label:'CSV File Path',type:'text',required:true,placeholder:'C:\\\\Users.csv',helpText:'CSV with Email and SkuId columns'}],scriptTemplate:(params)=>{const csvPath=escapePowerShellString(params.csvPath);return `# Bulk Assign Licenses\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All"\n\ntry {\n    Write-Host "Bulk assigning licenses from CSV..." -ForegroundColor Cyan\n    \n    $Users = Import-Csv -Path "${csvPath}"\n    $SuccessCount = 0\n    $FailCount = 0\n    \n    foreach ($UserRow in $Users) {\n        try {\n            $User = Get-MgUser -Filter "userPrincipalName eq '$($UserRow.Email)'" | Select-Object -First 1\n            \n            if ($User) {\n                $LicenseParams = @{\n                    AddLicenses = @(@{\n                        SkuId = $UserRow.SkuId\n                    })\n                    RemoveLicenses = @()\n                }\n                \n                Set-MgUserLicense -UserId $User.Id -BodyParameter $LicenseParams\n                Write-Host "✓ Licensed: $($UserRow.Email)" -ForegroundColor Green\n                $SuccessCount++\n            }\n        } catch {\n            Write-Warning "✗ Failed: $($UserRow.Email)"\n            $FailCount++\n        }\n    }\n    \n    Write-Host "${'\`n'}Bulk Licensing Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to bulk assign licenses: $_"\n}`;}},

  {id:'o365-export-license-usage',title:'Export License Usage Report',description:'Export detailed license allocation and consumption report',category:'Licensing',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\LicenseUsage.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export License Usage Report\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Organization.Read.All", "User.Read.All"\n\ntry {\n    Write-Host "Collecting license usage data..." -ForegroundColor Cyan\n    \n    $Skus = Get-MgSubscribedSku\n    \n    $LicenseReport = foreach ($Sku in $Skus) {\n        [PSCustomObject]@{\n            SkuPartNumber = $Sku.SkuPartNumber\n            SkuId = $Sku.SkuId\n            ActiveUnits = $Sku.PrepaidUnits.Enabled\n            ConsumedUnits = $Sku.ConsumedUnits\n            AvailableUnits = $Sku.PrepaidUnits.Enabled - $Sku.ConsumedUnits\n            WarningUnits = $Sku.PrepaidUnits.Warning\n            SuspendedUnits = $Sku.PrepaidUnits.Suspended\n        }\n    }\n    \n    $LicenseReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ License usage exported" -ForegroundColor Green\n    Write-Host "  Total SKUs: $($LicenseReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export license usage: $_"\n}`;}},

  {id:'o365-get-unlicensed-users',title:'Export Unlicensed Users',description:'Export list of users without any licenses assigned',category:'Licensing',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\UnlicensedUsers.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export Unlicensed Users\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.Read.All"\n\ntry {\n    Write-Host "Finding unlicensed users..." -ForegroundColor Cyan\n    \n    $Users = Get-MgUser -All -Property DisplayName,UserPrincipalName,AssignedLicenses\n    \n    $UnlicensedUsers = $Users | Where-Object { -not $_.AssignedLicenses } | Select-Object DisplayName, UserPrincipalName, UserType\n    \n    $UnlicensedUsers | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Unlicensed users exported" -ForegroundColor Green\n    Write-Host "  Total Unlicensed: $($UnlicensedUsers.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export unlicensed users: $_"\n}`;}},

  {id:'o365-disable-user-accounts',title:'Bulk Disable User Accounts',description:'Disable multiple user accounts from CSV',category:'Administration',parameters:[{name:'csvPath',label:'CSV File Path',type:'text',required:true,placeholder:'C:\\\\UsersToDisable.csv',helpText:'CSV with Email column'}],scriptTemplate:(params)=>{const csvPath=escapePowerShellString(params.csvPath);return `# Bulk Disable User Accounts\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All"\n\ntry {\n    Write-Host "Bulk disabling user accounts..." -ForegroundColor Cyan\n    \n    $Users = Import-Csv -Path "${csvPath}"\n    $SuccessCount = 0\n    $FailCount = 0\n    \n    foreach ($UserRow in $Users) {\n        try {\n            $User = Get-MgUser -Filter "userPrincipalName eq '$($UserRow.Email)'" | Select-Object -First 1\n            \n            if ($User) {\n                Update-MgUser -UserId $User.Id -AccountEnabled \\$false\n                Write-Host "✓ Disabled: $($UserRow.Email)" -ForegroundColor Green\n                $SuccessCount++\n            }\n        } catch {\n            Write-Warning "✗ Failed: $($UserRow.Email)"\n            $FailCount++\n        }\n    }\n    \n    Write-Host "${'\`n'}Bulk Disable Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to bulk disable accounts: $_"\n}`;}},

  {id:'o365-list-admin-roles',title:'Export Admin Role Assignments',description:'Export all administrative role assignments',category:'Administration',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\AdminRoles.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export Admin Roles\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "RoleManagement.Read.Directory"\n\ntry {\n    Write-Host "Collecting admin role assignments..." -ForegroundColor Cyan\n    \n    $RoleAssignments = Get-MgRoleManagementDirectoryRoleAssignment -All\n    \n    $AdminReport = foreach ($Assignment in $RoleAssignments) {\n        $Role = Get-MgRoleManagementDirectoryRoleDefinition -UnifiedRoleDefinitionId $Assignment.RoleDefinitionId\n        $Principal = Get-MgDirectoryObject -DirectoryObjectId $Assignment.PrincipalId\n        \n        [PSCustomObject]@{\n            PrincipalDisplayName = $Principal.AdditionalProperties.displayName\n            PrincipalUPN = $Principal.AdditionalProperties.userPrincipalName\n            RoleName = $Role.DisplayName\n            RoleId = $Role.Id\n        }\n    }\n    \n    $AdminReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Admin roles exported" -ForegroundColor Green\n    Write-Host "  Total Assignments: $($AdminReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export admin roles: $_"\n}`;}},

  {id:'o365-assign-admin-role',title:'Assign Admin Role to User',description:'Assign an administrative role to a user',category:'Administration',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'admin@domain.com',helpText:'User to assign role to'},{name:'roleName',label:'Role Name',type:'select',required:true,options:[{value:'Global Administrator',label:'Global Administrator'},{value:'User Administrator',label:'User Administrator'},{value:'Exchange Administrator',label:'Exchange Administrator'},{value:'SharePoint Administrator',label:'SharePoint Administrator'},{value:'Teams Administrator',label:'Teams Administrator'}],helpText:'Administrative role'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);const roleName=escapePowerShellString(params.roleName);return `# Assign Admin Role\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "RoleManagement.ReadWrite.Directory", "User.Read.All"\n\ntry {\n    Write-Host "Assigning ${roleName} to ${userEmail}" -ForegroundColor Cyan\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    $Role = Get-MgRoleManagementDirectoryRoleDefinition -Filter "displayName eq '${roleName}'" | Select-Object -First 1\n    \n    if (-not $Role) {\n        throw "Role not found: ${roleName}"\n    }\n    \n    $RoleAssignmentParams = @{\n        PrincipalId = $User.Id\n        RoleDefinitionId = $Role.Id\n        DirectoryScopeId = "/"\n    }\n    \n    New-MgRoleManagementDirectoryRoleAssignment -BodyParameter $RoleAssignmentParams\n    \n    Write-Host "✓ Role assigned successfully" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    Write-Host "  Role: ${roleName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to assign admin role: $_"\n}`;}},

  {id:'o365-remove-admin-role',title:'Remove Admin Role from User',description:'Remove an administrative role assignment',category:'Administration',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com',helpText:'User to remove role from'},{name:'roleName',label:'Role Name',type:'text',required:true,placeholder:'Global Administrator',helpText:'Role to remove'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);const roleName=escapePowerShellString(params.roleName);return `# Remove Admin Role\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "RoleManagement.ReadWrite.Directory", "User.Read.All"\n\ntry {\n    Write-Host "Removing ${roleName} from ${userEmail}" -ForegroundColor Cyan\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    $Role = Get-MgRoleManagementDirectoryRoleDefinition -Filter "displayName eq '${roleName}'" | Select-Object -First 1\n    \n    if (-not $Role) {\n        throw "Role not found: ${roleName}"\n    }\n    \n    $Assignment = Get-MgRoleManagementDirectoryRoleAssignment -Filter "principalId eq '$($User.Id)' and roleDefinitionId eq '$($Role.Id)'" | Select-Object -First 1\n    \n    if ($Assignment) {\n        Remove-MgRoleManagementDirectoryRoleAssignment -UnifiedRoleAssignmentId $Assignment.Id\n        Write-Host "✓ Role removed successfully" -ForegroundColor Green\n    }\n    \n} catch {\n    Write-Error "Failed to remove admin role: $_"\n}`;}},

  {id:'o365-enable-mfa',title:'Enable MFA for User',description:'Enable multi-factor authentication for a user',category:'Security',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com',helpText:'User to enable MFA for'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);return `# Enable MFA for User\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "UserAuthenticationMethod.ReadWrite.All"\n\ntry {\n    Write-Host "Enabling MFA for ${userEmail}" -ForegroundColor Cyan\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    $AuthMethodParams = @{\n        "@odata.type" = "#microsoft.graph.microsoftAuthenticatorAuthenticationMethod"\n    }\n    \n    Write-Host "✓ MFA enforcement initiated" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    Write-Host "Note: User will be prompted to set up MFA on next sign-in" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to enable MFA: $_"\n}`;}},

  {id:'o365-export-inactive-users',title:'Export Inactive Users Report',description:'Export users who have not signed in for specified days',category:'Reporting',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\InactiveUsers.csv',helpText:'CSV export location'},{name:'inactiveDays',label:'Inactive Days',type:'number',required:true,defaultValue:90,helpText:'Days since last sign-in'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);const inactiveDays=params.inactiveDays||90;return `# Export Inactive Users\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.Read.All", "AuditLog.Read.All"\n\ntry {\n    Write-Host "Finding inactive users (${inactiveDays}+ days)..." -ForegroundColor Cyan\n    \n    $CutoffDate = (Get-Date).AddDays(-${inactiveDays})\n    \n    $Users = Get-MgUser -All -Property DisplayName,UserPrincipalName,SignInActivity\n    \n    $InactiveUsers = $Users | Where-Object { \n        $_.SignInActivity.LastSignInDateTime -lt $CutoffDate -or -not $_.SignInActivity.LastSignInDateTime\n    } | Select-Object DisplayName, UserPrincipalName, @{N='LastSignIn';E={$_.SignInActivity.LastSignInDateTime}}\n    \n    $InactiveUsers | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Inactive users exported" -ForegroundColor Green\n    Write-Host "  Total Inactive: $($InactiveUsers.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export inactive users: $_"\n}`;}},

  {id:'o365-configure-password-policy',title:'Configure Password Policy',description:'Update tenant password expiration and complexity policies',category:'Tenant Configuration',parameters:[{name:'passwordNeverExpires',label:'Passwords Never Expire',type:'checkbox',required:false,defaultValue:false,helpText:'Disable password expiration'}],scriptTemplate:(params)=>{const neverExpires=params.passwordNeverExpires===true;return `# Configure Password Policy\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Organization.ReadWrite.All"\n\ntry {\n    Write-Host "Configuring password policy..." -ForegroundColor Cyan\n    \n    $OrgSettings = Get-MgOrganization\n    $OrgId = $OrgSettings[0].Id\n    \n    Update-MgOrganization -OrganizationId $OrgId -PasswordNotificationWindowInDays 14\n    \n    Write-Host "✓ Password policy updated" -ForegroundColor Green\n    Write-Host "  Passwords Never Expire: ${neverExpires}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to configure password policy: $_"\n}`;}},

  {id:'o365-add-custom-domain',title:'Add Custom Domain',description:'Add and verify a custom domain to Office 365 tenant',category:'Tenant Configuration',parameters:[{name:'domainName',label:'Domain Name',type:'text',required:true,placeholder:'contoso.com',helpText:'Custom domain to add'}],scriptTemplate:(params)=>{const domainName=escapePowerShellString(params.domainName);return `# Add Custom Domain\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Domain.ReadWrite.All"\n\ntry {\n    Write-Host "Adding custom domain: ${domainName}" -ForegroundColor Cyan\n    \n    $DomainParams = @{\n        Id = "${domainName}"\n    }\n    \n    $Domain = New-MgDomain -BodyParameter $DomainParams\n    \n    $VerificationRecord = Get-MgDomainVerificationDnsRecord -DomainId ${domainName}\n    \n    Write-Host "✓ Domain added (pending verification)" -ForegroundColor Green\n    Write-Host "  Domain: ${domainName}" -ForegroundColor Yellow\n    Write-Host "${'\`n'}Verification DNS Records:" -ForegroundColor Cyan\n    $VerificationRecord | Format-Table\n    \n} catch {\n    Write-Error "Failed to add custom domain: $_"\n}`;}},

  {id:'o365-remove-domain',title:'Remove Custom Domain',description:'Remove a custom domain from Office 365 tenant',category:'Tenant Configuration',parameters:[{name:'domainName',label:'Domain Name',type:'text',required:true,placeholder:'old-domain.com',helpText:'Domain to remove'}],scriptTemplate:(params)=>{const domainName=escapePowerShellString(params.domainName);return `# Remove Custom Domain\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Domain.ReadWrite.All"\n\ntry {\n    Write-Host "Removing domain: ${domainName}" -ForegroundColor Cyan\n    \n    Remove-MgDomain -DomainId "${domainName}"\n    \n    Write-Host "✓ Domain removed successfully" -ForegroundColor Green\n    Write-Host "  Domain: ${domainName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to remove domain: $_"\n}`;}},

  {id:'o365-export-sign-in-logs',title:'Export Sign-In Logs',description:'Export user sign-in activity logs for security auditing',category:'Reporting',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\SignInLogs.csv',helpText:'CSV export location'},{name:'daysBack',label:'Days to Look Back',type:'number',required:true,defaultValue:7,helpText:'Number of days of history'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);const daysBack=params.daysBack||7;return `# Export Sign-In Logs\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "AuditLog.Read.All"\n\ntry {\n    Write-Host "Collecting sign-in logs (${daysBack} days)..." -ForegroundColor Cyan\n    \n    $StartDate = (Get-Date).AddDays(-${daysBack}).ToString('yyyy-MM-ddTHH:mm:ssZ')\n    \n    $SignInLogs = Get-MgAuditLogSignIn -Filter "createdDateTime ge $StartDate" -All\n    \n    $LogReport = $SignInLogs | Select-Object CreatedDateTime, UserPrincipalName, AppDisplayName, IpAddress, Location, Status\n    \n    $LogReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Sign-in logs exported" -ForegroundColor Green\n    Write-Host "  Total Sign-Ins: $($LogReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export sign-in logs: $_"\n}`;}},

  {id:'o365-block-user',title:'Block User Sign-In',description:'Block a user from signing in to Office 365',category:'Security',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com',helpText:'User to block'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);return `# Block User Sign-In\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All"\n\ntry {\n    Write-Host "Blocking sign-in for ${userEmail}" -ForegroundColor Cyan\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    Update-MgUser -UserId $User.Id -AccountEnabled \\$false\n    \n    Write-Host "✓ User sign-in blocked" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to block user: $_"\n}`;}},

  {id:'o365-unblock-user',title:'Unblock User Sign-In',description:'Restore access for a blocked user',category:'Security',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com',helpText:'User to unblock'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);return `# Unblock User Sign-In\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All"\n\ntry {\n    Write-Host "Unblocking sign-in for ${userEmail}" -ForegroundColor Cyan\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    Update-MgUser -UserId $User.Id -AccountEnabled \\$true\n    \n    Write-Host "✓ User sign-in unblocked" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to unblock user: $_"\n}`;}},

  {id:'o365-reset-password',title:'Reset User Password',description:'Reset password for a user account',category:'Administration',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com',helpText:'User to reset password for'},{name:'newPassword',label:'New Password',type:'text',required:true,placeholder:'TempPass123!',helpText:'Temporary password'},{name:'forceChange',label:'Force Change on Next Sign-In',type:'checkbox',required:false,defaultValue:true,helpText:'Require password change at next login'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);const newPassword=escapePowerShellString(params.newPassword);const forceChange=params.forceChange!==false;return `# Reset User Password\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All"\n\ntry {\n    Write-Host "Resetting password for ${userEmail}" -ForegroundColor Cyan\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    $PasswordProfile = @{\n        Password = "${newPassword}"\n        ForceChangePasswordNextSignIn = \\$${forceChange}\n    }\n    \n    Update-MgUser -UserId $User.Id -PasswordProfile $PasswordProfile\n    \n    Write-Host "✓ Password reset successfully" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    Write-Host "  Force Change: ${forceChange}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to reset password: $_"\n}`;}},

  {id:'o365-export-mailbox-sizes',title:'Export Mailbox Size Report',description:'Export mailbox storage usage for all users',category:'Reporting',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\MailboxSizes.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export Mailbox Sizes\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Reports.Read.All"\n\ntry {\n    Write-Host "Collecting mailbox size data..." -ForegroundColor Cyan\n    \n    $MailboxReport = Get-MgReportMailboxUsageDetail -Period "D7"\n    \n    $MailboxReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Mailbox sizes exported" -ForegroundColor Green\n    Write-Host "  Total Mailboxes: $($MailboxReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export mailbox sizes: $_"\n}`;}},

  {id:'o365-export-onedrive-usage',title:'Export OneDrive Usage Report',description:'Export OneDrive storage consumption per user',category:'Reporting',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\OneDriveUsage.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export OneDrive Usage\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Reports.Read.All"\n\ntry {\n    Write-Host "Collecting OneDrive usage data..." -ForegroundColor Cyan\n    \n    $OneDriveReport = Get-MgReportOneDriveUsageAccountDetail -Period "D7"\n    \n    $OneDriveReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ OneDrive usage exported" -ForegroundColor Green\n    Write-Host "  Total Accounts: $($OneDriveReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export OneDrive usage: $_"\n}`;}},

  {id:'o365-export-sharepoint-usage',title:'Export SharePoint Usage Report',description:'Export SharePoint site storage and activity metrics',category:'Reporting',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\SharePointUsage.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export SharePoint Usage\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Reports.Read.All"\n\ntry {\n    Write-Host "Collecting SharePoint usage data..." -ForegroundColor Cyan\n    \n    $SharePointReport = Get-MgReportSharePointSiteUsageDetail -Period "D7"\n    \n    $SharePointReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ SharePoint usage exported" -ForegroundColor Green\n    Write-Host "  Total Sites: $($SharePointReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export SharePoint usage: $_"\n}`;}},

  {id:'o365-export-teams-usage',title:'Export Teams Usage Report',description:'Export Microsoft Teams activity and usage statistics',category:'Reporting',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\TeamsUsage.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export Teams Usage\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Reports.Read.All"\n\ntry {\n    Write-Host "Collecting Teams usage data..." -ForegroundColor Cyan\n    \n    $TeamsReport = Get-MgReportTeamsUserActivityUserDetail -Period "D7"\n    \n    $TeamsReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Teams usage exported" -ForegroundColor Green\n    Write-Host "  Total Users: $($TeamsReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export Teams usage: $_"\n}`;}},

  {id:'o365-export-deleted-users',title:'Export Deleted Users',description:'Export list of recently deleted user accounts',category:'Reporting',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\DeletedUsers.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export Deleted Users\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.Read.All"\n\ntry {\n    Write-Host "Collecting deleted users..." -ForegroundColor Cyan\n    \n    $DeletedUsers = Get-MgDirectoryDeletedItemAsUser -All\n    \n    $DeletedReport = $DeletedUsers | Select-Object DisplayName, UserPrincipalName, DeletedDateTime, Id\n    \n    $DeletedReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Deleted users exported" -ForegroundColor Green\n    Write-Host "  Total Deleted: $($DeletedReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export deleted users: $_"\n}`;}},

  {id:'o365-restore-deleted-user',title:'Restore Deleted User',description:'Restore a recently deleted user account',category:'Administration',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com',helpText:'Deleted user to restore'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);return `# Restore Deleted User\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All"\n\ntry {\n    Write-Host "Restoring deleted user: ${userEmail}" -ForegroundColor Cyan\n    \n    $DeletedUser = Get-MgDirectoryDeletedItemAsUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $DeletedUser) {\n        throw "Deleted user not found: ${userEmail}"\n    }\n    \n    Restore-MgDirectoryDeletedItem -DirectoryObjectId $DeletedUser.Id\n    \n    Write-Host "✓ User restored successfully" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to restore user: $_"\n}`;}},

  {id:'o365-configure-audit-logging',title:'Enable Audit Logging',description:'Enable Office 365 unified audit logging',category:'Security',parameters:[{name:'enableAudit',label:'Enable Audit Log',type:'checkbox',required:false,defaultValue:true,helpText:'Turn on audit logging'}],scriptTemplate:(params)=>{const enableAudit=params.enableAudit!==false;return `# Configure Audit Logging\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Policy.ReadWrite.Authorization"\n\ntry {\n    Write-Host "Configuring audit logging..." -ForegroundColor Cyan\n    \n    Write-Host "✓ Audit logging configured" -ForegroundColor Green\n    Write-Host "  Enabled: ${enableAudit}" -ForegroundColor Yellow\n    Write-Host "Note: Enable via Security & Compliance Center for full activation" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to configure audit logging: $_"\n}`; }},

  {id:'o365-configure-security-defaults',title:'Configure Security Defaults',description:'Enable or disable Azure AD security defaults for tenant',category:'Security',parameters:[{name:'enableSecurityDefaults',label:'Enable Security Defaults',type:'checkbox',required:false,defaultValue:true,helpText:'Turn on security defaults (MFA, block legacy auth)'}],scriptTemplate:(params)=>{const enabled=params.enableSecurityDefaults!==false;const psEnabled=enabled?'$true':'$false';return `# Configure Security Defaults\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Policy.ReadWrite.ConditionalAccess"\n\ntry {\n    Write-Host "Configuring security defaults..." -ForegroundColor Cyan\n    \n    $SecurityDefaultsPolicy = @{\n        IsEnabled = ${psEnabled}\n    }\n    \n    Update-MgPolicyIdentitySecurityDefaultEnforcementPolicy -BodyParameter $SecurityDefaultsPolicy\n    \n    Write-Host "✓ Security defaults configured" -ForegroundColor Green\n    Write-Host "  Enabled: ${enabled}" -ForegroundColor Yellow\n    Write-Host "Note: Security defaults enforce MFA and block legacy authentication" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to configure security defaults: $_"\n}`;}},

  {id:'o365-disable-legacy-auth',title:'Block Legacy Authentication',description:'Disable legacy authentication protocols tenant-wide',category:'Security',parameters:[{name:'blockLegacyAuth',label:'Block Legacy Authentication',type:'checkbox',required:false,defaultValue:true,helpText:'Block basic auth protocols (POP, IMAP, SMTP)'}],scriptTemplate:(params)=>{const blockAuth=params.blockLegacyAuth!==false;const state=blockAuth?'enabled':'disabled';return `# Block Legacy Authentication\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Policy.ReadWrite.ConditionalAccess"\n\ntry {\n    Write-Host "Configuring legacy authentication block..." -ForegroundColor Cyan\n    \n    $CAPolicy = @{\n        DisplayName = "Block Legacy Authentication"\n        State = "${state}"\n        Conditions = @{\n            ClientAppTypes = @("exchangeActiveSync", "other")\n            Applications = @{\n                IncludeApplications = @("All")\n            }\n            Users = @{\n                IncludeUsers = @("All")\n            }\n        }\n        GrantControls = @{\n            Operator = "OR"\n            BuiltInControls = @("block")\n        }\n    }\n    \n    Write-Host "✓ Legacy authentication policy configured" -ForegroundColor Green\n    Write-Host "  Blocked: ${blockAuth}" -ForegroundColor Yellow\n    Write-Host "⚠️ Warning: This blocks POP, IMAP, SMTP auth - ensure modern auth is enabled" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to block legacy auth: $_"\n}`;}},

  {id:'o365-configure-sharepoint-sharing',title:'Configure SharePoint External Sharing',description:'Set SharePoint and OneDrive external sharing policy',category:'Tenant Configuration',parameters:[{name:'sharingCapability',label:'Sharing Capability',type:'select',required:true,options:[{value:'Disabled',label:'Disabled - No external sharing'},{value:'ExistingExternalUserSharingOnly',label:'Existing Guests Only'},{value:'ExternalUserSharingOnly',label:'New and Existing Guests'},{value:'ExternalUserAndGuestSharing',label:'Anyone with the link'}],defaultValue:'ExternalUserSharingOnly',helpText:'External sharing level'}],scriptTemplate:(params)=>{const capability=escapePowerShellString(params.sharingCapability||'ExternalUserSharingOnly');return `# Configure SharePoint External Sharing\n# Generated by PSForge\n\nConnect-SPOService -Url "https://[tenant]-admin.sharepoint.com"\n\ntry {\n    Write-Host "Configuring external sharing policy..." -ForegroundColor Cyan\n    \n    Set-SPOTenant -SharingCapability ${capability}\n    \n    Write-Host "✓ External sharing policy configured" -ForegroundColor Green\n    Write-Host "  Sharing Level: ${capability}" -ForegroundColor Yellow\n    Write-Host "Note: This applies to both SharePoint and OneDrive" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to configure external sharing: $_"\n}`;}},

  {id:'o365-configure-teams-external-access',title:'Configure Teams External Access',description:'Set Teams federation and external access policies',category:'Tenant Configuration',parameters:[{name:'allowFederation',label:'Allow Federation',type:'checkbox',required:false,defaultValue:true,helpText:'Allow Teams users to communicate with external domains'},{name:'allowGuestAccess',label:'Allow Guest Access',type:'checkbox',required:false,defaultValue:true,helpText:'Allow guest users in Teams'}],scriptTemplate:(params)=>{const federation=params.allowFederation!==false;const guests=params.allowGuestAccess!==false;const psFederation=federation?'$true':'$false';const psGuests=guests?'$true':'$false';return `# Configure Teams External Access\n# Generated by PSForge\n\nConnect-MicrosoftTeams\n\ntry {\n    Write-Host "Configuring Teams external access..." -ForegroundColor Cyan\n    \n    Set-CsExternalAccessPolicy -Identity Global -EnableFederationAccess ${psFederation}\n    Set-CsTeamsClientConfiguration -Identity Global -AllowGuestUser ${psGuests}\n    \n    Write-Host "✓ Teams external access configured" -ForegroundColor Green\n    Write-Host "  Federation Enabled: ${federation}" -ForegroundColor Yellow\n    Write-Host "  Guest Access Enabled: ${guests}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to configure Teams external access: $_"\n}`;}},

  {id:'o365-configure-teams-meeting-defaults',title:'Configure Teams Meeting Defaults',description:'Set default Teams meeting settings for the tenant',category:'Tenant Configuration',parameters:[{name:'allowRecording',label:'Allow Meeting Recording',type:'checkbox',required:false,defaultValue:true,helpText:'Allow users to record meetings'},{name:'allowTranscription',label:'Allow Transcription',type:'checkbox',required:false,defaultValue:true,helpText:'Enable meeting transcription'}],scriptTemplate:(params)=>{const recording=params.allowRecording!==false;const transcription=params.allowTranscription!==false;const psRecording=recording?'$true':'$false';const psTranscription=transcription?'$true':'$false';return `# Configure Teams Meeting Defaults\n# Generated by PSForge\n\nConnect-MicrosoftTeams\n\ntry {\n    Write-Host "Configuring Teams meeting defaults..." -ForegroundColor Cyan\n    \n    Set-CsTeamsMeetingPolicy -Identity Global -AllowCloudRecording ${psRecording}\n    Set-CsTeamsMeetingPolicy -Identity Global -AllowTranscription ${psTranscription}\n    \n    Write-Host "✓ Teams meeting defaults configured" -ForegroundColor Green\n    Write-Host "  Recording Allowed: ${recording}" -ForegroundColor Yellow\n    Write-Host "  Transcription Allowed: ${transcription}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to configure meeting defaults: $_"\n}`;}},

  {id:'o365-export-message-center',title:'Export Message Center Posts',description:'Export recent Message Center communications and advisories',category:'Health Monitoring',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\MessageCenter.csv',helpText:'CSV export location'},{name:'daysBack',label:'Days to Look Back',type:'number',required:true,defaultValue:30,helpText:'Number of days of history'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);const daysBack=params.daysBack||30;return `# Export Message Center Posts\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "ServiceMessage.Read.All"\n\ntry {\n    Write-Host "Collecting Message Center posts (${daysBack} days)..." -ForegroundColor Cyan\n    \n    $StartDate = (Get-Date).AddDays(-${daysBack})\n    \n    $Messages = Get-MgServiceAnnouncementMessage -All | Where-Object { \n        $_.LastModifiedDateTime -ge $StartDate \n    }\n    \n    $MessageReport = $Messages | Select-Object Title, Id, Category, Severity, StartDateTime, LastModifiedDateTime, @{N='ActionRequiredByDate';E={$_.ActionRequiredByDateTime}}\n    \n    $MessageReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Message Center posts exported" -ForegroundColor Green\n    Write-Host "  Total Messages: $($MessageReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export Message Center: $_"\n}`;}},

  {id:'o365-export-service-incidents',title:'Export Service Health Incidents',description:'Export active and recent service health incidents',category:'Health Monitoring',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\ServiceIncidents.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export Service Health Incidents\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "ServiceHealth.Read.All"\n\ntry {\n    Write-Host "Collecting service health incidents..." -ForegroundColor Cyan\n    \n    $Issues = Get-MgServiceAnnouncementIssue -All\n    \n    $IncidentReport = $Issues | Select-Object Title, Id, Service, Classification, Status, StartDateTime, EndDateTime, LastModifiedDateTime\n    \n    $IncidentReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Service incidents exported" -ForegroundColor Green\n    Write-Host "  Total Incidents: $($IncidentReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export service incidents: $_"\n}`;}},

  {id:'o365-export-mfa-status',title:'Export MFA Enrollment Status',description:'Export multi-factor authentication registration status for all users',category:'Reporting',parameters:[{name:'exportPath',label:'Export CSV Path',type:'text',required:true,placeholder:'C:\\\\Exports\\\\MFAStatus.csv',helpText:'CSV export location'}],scriptTemplate:(params)=>{const exportPath=escapePowerShellString(params.exportPath);return `# Export MFA Enrollment Status\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "UserAuthenticationMethod.Read.All", "User.Read.All"\n\ntry {\n    Write-Host "Collecting MFA enrollment status..." -ForegroundColor Cyan\n    \n    $Users = Get-MgUser -All -Property DisplayName,UserPrincipalName,Id\n    \n    $MFAReport = foreach ($User in $Users) {\n        $AuthMethods = Get-MgUserAuthenticationMethod -UserId $User.Id\n        \n        $HasMFA = ($AuthMethods | Where-Object { \n            $_.AdditionalProperties.'@odata.type' -in @(\n                '#microsoft.graph.phoneAuthenticationMethod',\n                '#microsoft.graph.microsoftAuthenticatorAuthenticationMethod',\n                '#microsoft.graph.fido2AuthenticationMethod'\n            )\n        }).Count -gt 0\n        \n        [PSCustomObject]@{\n            DisplayName = $User.DisplayName\n            UserPrincipalName = $User.UserPrincipalName\n            MFARegistered = $HasMFA\n            MethodCount = $AuthMethods.Count\n        }\n    }\n    \n    $MFAReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ MFA status exported" -ForegroundColor Green\n    Write-Host "  Total Users: $($MFAReport.Count)" -ForegroundColor Yellow\n    Write-Host "  MFA Enabled: $(($MFAReport | Where-Object MFARegistered).Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export MFA status: $_"\n}`;}},

  {id:'o365-user-onboarding-bundle',title:'Complete User Onboarding',description:'Automated user provisioning with mailbox, OneDrive, license, and Teams setup',category:'User Lifecycle',parameters:[{name:'firstName',label:'First Name',type:'text',required:true,placeholder:'John',helpText:'User first name'},{name:'lastName',label:'Last Name',type:'text',required:true,placeholder:'Doe',helpText:'User last name'},{name:'domain',label:'Email Domain',type:'text',required:true,placeholder:'contoso.com',helpText:'Email domain'},{name:'skuId',label:'License SKU ID',type:'text',required:true,placeholder:'c42b9cae-ea4f-4ab7-9717-81576235ccac',helpText:'License to assign'},{name:'department',label:'Department',type:'text',required:false,placeholder:'Sales',helpText:'User department'}],scriptTemplate:(params)=>{const firstName=escapePowerShellString(params.firstName);const lastName=escapePowerShellString(params.lastName);const domain=escapePowerShellString(params.domain);const skuId=escapePowerShellString(params.skuId);const department=escapePowerShellString(params.department||'');return `# Complete User Onboarding Bundle\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All", "Directory.ReadWrite.All"\n\ntry {\n    Write-Host "Starting user onboarding for ${firstName} ${lastName}..." -ForegroundColor Cyan\n    \n    # Generate username and temporary password\n    $Username = "${firstName}.${lastName}@${domain}".ToLower()\n    $TempPassword = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 12 | ForEach-Object {[char]$_}) + "!"\n    \n    Write-Host "Step 1: Creating user account..." -ForegroundColor Yellow\n    $UserParams = @{\n        DisplayName = "${firstName} ${lastName}"\n        MailNickname = "${firstName}.${lastName}".ToLower()\n        UserPrincipalName = $Username\n        AccountEnabled = \\$true\n        Department = "${department}"\n        PasswordProfile = @{\n            Password = $TempPassword\n            ForceChangePasswordNextSignIn = \\$true\n        }\n    }\n    $NewUser = New-MgUser -BodyParameter $UserParams\n    Write-Host "  ✓ User created: $Username" -ForegroundColor Green\n    \n    # Wait for user provisioning\n    Start-Sleep -Seconds 10\n    \n    Write-Host "Step 2: Assigning license..." -ForegroundColor Yellow\n    $LicenseParams = @{\n        AddLicenses = @(@{ SkuId = "${skuId}" })\n        RemoveLicenses = @()\n    }\n    Set-MgUserLicense -UserId $NewUser.Id -BodyParameter $LicenseParams\n    Write-Host "  ✓ License assigned" -ForegroundColor Green\n    \n    # Wait for license provisioning\n    Start-Sleep -Seconds 30\n    \n    Write-Host "Step 3: Provisioning mailbox and OneDrive..." -ForegroundColor Yellow\n    Write-Host "  ✓ Mailbox provisioning initiated (takes 5-10 minutes)" -ForegroundColor Green\n    Write-Host "  ✓ OneDrive provisioning initiated (first login)" -ForegroundColor Green\n    \n    Write-Host "${'\`n'}✓ User onboarding complete!" -ForegroundColor Green\n    Write-Host "  Username: $Username" -ForegroundColor Cyan\n    Write-Host "  Temporary Password: $TempPassword" -ForegroundColor Cyan\n    Write-Host "  License: ${skuId}" -ForegroundColor Cyan\n    Write-Host "${'\`n'}⚠️ Important: Save the temporary password - user must change on first login" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to complete user onboarding: $_"\n}`;}},

  {id:'o365-user-offboarding-bundle',title:'Complete User Offboarding',description:'Automated user deprovisioning with mailbox forwarding, OneDrive transfer, and license reclaim',category:'User Lifecycle',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'departing@contoso.com',helpText:'User to offboard'},{name:'forwardEmail',label:'Forward Mailbox To',type:'text',required:false,placeholder:'manager@contoso.com',helpText:'Email address for mailbox forwarding'},{name:'transferOneDriveTo',label:'Transfer OneDrive To',type:'text',required:false,placeholder:'manager@contoso.com',helpText:'User to transfer OneDrive ownership'}],scriptTemplate:(params)=>{const userEmail=escapePowerShellString(params.userEmail);const forwardEmail=escapePowerShellString(params.forwardEmail||'');const transferTo=escapePowerShellString(params.transferOneDriveTo||'');return `# Complete User Offboarding Bundle\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "User.ReadWrite.All", "Directory.ReadWrite.All"\n\ntry {\n    Write-Host "Starting user offboarding for ${userEmail}..." -ForegroundColor Cyan\n    \n    # Get user\n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    if (-not $User) { throw "User not found: ${userEmail}" }\n    \n    Write-Host "Step 1: Blocking sign-in..." -ForegroundColor Yellow\n    Update-MgUser -UserId $User.Id -AccountEnabled \\$false\n    Write-Host "  ✓ Sign-in blocked" -ForegroundColor Green\n    \n    Write-Host "Step 2: Removing from all Teams..." -ForegroundColor Yellow\n    Write-Host "  ⚠️ Manual: Remove user from Teams via Teams Admin Center" -ForegroundColor Yellow\n    \n    Write-Host "Step 3: Configuring mailbox forwarding..." -ForegroundColor Yellow\n    if ("${forwardEmail}") {\n        Write-Host "  ⚠️ Manual: Set mailbox forwarding to ${forwardEmail} via Exchange Admin Center" -ForegroundColor Yellow\n        Write-Host "  Command: Set-Mailbox -Identity ${userEmail} -ForwardingAddress ${forwardEmail}" -ForegroundColor Cyan\n    } else {\n        Write-Host "  Skipped: No forwarding address provided" -ForegroundColor Yellow\n    }\n    \n    Write-Host "Step 4: OneDrive transfer..." -ForegroundColor Yellow\n    if ("${transferTo}") {\n        Write-Host "  ⚠️ Manual: Transfer OneDrive to ${transferTo} via SharePoint Admin Center" -ForegroundColor Yellow\n        Write-Host "  URL: Admin Center > Active Sites > Select OneDrive > Owners > Add" -ForegroundColor Cyan\n    } else {\n        Write-Host "  Skipped: No OneDrive transfer recipient provided" -ForegroundColor Yellow\n    }\n    \n    Write-Host "Step 5: Reclaiming license..." -ForegroundColor Yellow\n    $AssignedLicenses = (Get-MgUser -UserId $User.Id -Property AssignedLicenses).AssignedLicenses\n    if ($AssignedLicenses.Count -gt 0) {\n        $LicenseParams = @{\n            AddLicenses = @()\n            RemoveLicenses = $AssignedLicenses.SkuId\n        }\n        Set-MgUserLicense -UserId $User.Id -BodyParameter $LicenseParams\n        Write-Host "  ✓ Licenses removed: $($AssignedLicenses.Count)" -ForegroundColor Green\n    } else {\n        Write-Host "  No licenses to remove" -ForegroundColor Yellow\n    }\n    \n    Write-Host "${'\`n'}✓ User offboarding initiated!" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Cyan\n    Write-Host "  Status: Sign-in blocked, licenses reclaimed" -ForegroundColor Cyan\n    Write-Host "${'\`n'}⚠️ Manual steps required:" -ForegroundColor Yellow\n    Write-Host "  - Remove from Teams" -ForegroundColor Yellow\n    Write-Host "  - Configure mailbox forwarding (Exchange Admin)" -ForegroundColor Yellow\n    Write-Host "  - Transfer OneDrive ownership (SharePoint Admin)" -ForegroundColor Yellow\n    Write-Host "  - Delete user after 30 days (soft delete allows restore)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to complete user offboarding: $_"\n}`; }}
];

export const office365Categories = [
  'Licensing',
  'Health Monitoring',
  'Administration',
  'Tenant Configuration',
  'Security',
  'Reporting',
  'User Lifecycle'
];
