import { escapePowerShellString } from './powershell-utils';

export interface OneDriveParameter {
  title: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface OneDriveTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: OneDriveParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const oneDriveTasks: OneDriveTask[] = [
  {
    id: 'onedrive-export-storage-report',
    title: 'Export Storage Usage Report',
    description: 'Export OneDrive storage usage for all users to CSV',
    category: 'Storage Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\OneDriveStorage.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export OneDrive Storage Usage
# Generated by PSForge

Connect-MgGraph -Scopes "Reports.Read.All"

try {
    Write-Host "Collecting OneDrive storage usage..." -ForegroundColor Cyan
    
    $StorageReport = Get-MgReportOneDriveUsageAccountDetail -Period D7
    
    $StorageReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Storage report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export storage report: $_"
}`;
    }
  },

  {
    id: 'onedrive-export-sharing-report',
    title: 'Export Sharing Activity Report',
    description: 'Export OneDrive sharing activity to CSV',
    category: 'Sharing & Permissions',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\OneDriveSharing.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export OneDrive Sharing Activity
# Generated by PSForge

Connect-MgGraph -Scopes "Reports.Read.All"

try {
    Write-Host "Collecting OneDrive sharing activity..." -ForegroundColor Cyan
    
    $SharingReport = Get-MgReportOneDriveActivityUserDetail -Period D7
    
    $SharingReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Sharing report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export sharing report: $_"
}`;
    }
  },

  {
    id: 'onedrive-list-external-shares',
    title: 'List Externally Shared Files',
    description: 'List all files shared externally from a user OneDrive',
    category: 'Sharing & Permissions',
    parameters: [
      {
        name: 'userPrincipalName',
        label: 'User Principal Name',
        type: 'text',
        required: true,
        placeholder: 'user@domain.com',
        helpText: 'User email address'
      }
    ],
    scriptTemplate: (params) => {
      const upn = escapePowerShellString(params.userPrincipalName);

      return `# List Externally Shared Files
# Generated by PSForge

Connect-MgGraph -Scopes "Sites.Read.All"

try {
    Write-Host "Finding externally shared files for: ${upn}" -ForegroundColor Cyan
    
    $User = Get-MgUser -UserId "${upn}"
    $Drive = Get-MgUserDrive -UserId $User.Id
    
    $SharedItems = Get-MgDriveSharedWithMe -DriveId $Drive.Id
    
    Write-Host "Found $($SharedItems.Count) shared items" -ForegroundColor Yellow
    
    $SharedItems | Select-Object Name, WebUrl | Format-Table
    
} catch {
    Write-Error "Failed to list shared files: $_"
}`;
    }
  },

  {
    id: 'onedrive-export-sync-health',
    title: 'Export OneDrive Sync Health',
    description: 'Export OneDrive sync client health status to CSV',
    category: 'Sync & Client',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\SyncHealth.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export OneDrive Sync Health
# Generated by PSForge

Connect-MgGraph -Scopes "Reports.Read.All"

try {
    Write-Host "Collecting OneDrive sync health data..." -ForegroundColor Cyan
    
    $SyncHealth = Get-MgReportOneDriveUsageAccountDetail -Period D7
    
    $SyncHealth | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Sync health exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export sync health: $_"
}`;
    }
  },

  {
    id: 'onedrive-export-user-inventory',
    title: 'Export OneDrive User Inventory',
    description: 'Export list of all OneDrive sites to CSV',
    category: 'Reporting',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\OneDriveSites.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export OneDrive User Inventory
# Generated by PSForge

try {
    Write-Host "Collecting OneDrive sites..." -ForegroundColor Cyan
    
    $Sites = Get-SPOSite -IncludePersonalSite $true -Limit All -Filter "Url -like '-my.sharepoint.com/personal/'"
    
    Write-Host "Found $($Sites.Count) OneDrive sites" -ForegroundColor Yellow
    
    $SiteReport = foreach ($Site in $Sites) {
        [PSCustomObject]@{
            Owner            = $Site.Owner
            Url              = $Site.Url
            StorageUsageMB   = $Site.StorageUsageCurrent
            StorageQuotaMB   = $Site.StorageQuota
        }
    }
    
    $SiteReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ OneDrive sites exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export OneDrive sites: $_"
}`;
    }
  }
];

export const oneDriveCategories = [
  'Storage Management',
  'Sharing & Permissions',
  'Sync & Client',
  'Reporting'
];
