import { escapePowerShellString } from './powershell-utils';

export interface OneDriveParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface OneDriveTask {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: OneDriveParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const oneDriveTasks: OneDriveTask[] = [
  {
    id: 'onedrive-export-storage-report',
    title: 'Export Storage Usage Report',
    description: 'Export OneDrive storage usage for all users to CSV',
    category: 'Storage Management',
    instructions: `**How This Task Works:**
This script exports comprehensive OneDrive storage usage statistics for all users to monitor consumption and plan capacity.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- Reports.Read.All permission
- Global Administrator or Reports Reader role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves 7-day OneDrive usage details
- Exports storage metrics to CSV
- Reports export success

**Important Notes:**
- Essential for capacity planning and storage management
- Shows storage used per user
- Use for identifying storage hogs and quota planning
- Run monthly for storage trend analysis
- Plan for storage growth (average 20-30% annually)
- Identify users exceeding quotas
- Typical use: capacity planning, cost optimization
- Compare with assigned quotas to prevent overruns`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\OneDriveStorage.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export OneDrive Storage Usage
# Generated by PSForge

Connect-MgGraph -Scopes "Reports.Read.All"

try {
    Write-Host "Collecting OneDrive storage usage..." -ForegroundColor Cyan
    
    $StorageReport = Get-MgReportOneDriveUsageAccountDetail -Period D7
    
    $StorageReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Storage report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export storage report: $_"
}`;
    }
  },

  {
    id: 'onedrive-export-sharing-report',
    title: 'Export Sharing Activity Report',
    description: 'Export OneDrive sharing activity to CSV',
    category: 'Sharing & Permissions',
    instructions: `**How This Task Works:**
This script exports OneDrive sharing and file activity metrics for security monitoring and collaboration analytics.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- Reports.Read.All permission
- Global Administrator or Reports Reader role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves 7-day OneDrive activity details
- Exports sharing activity to CSV
- Reports export success

**Important Notes:**
- Essential for security monitoring and compliance
- Shows file views, edits, shares, and syncs
- Use for identifying excessive external sharing
- Run weekly for security audits
- Monitor for data exfiltration patterns
- Identify inactive users for license optimization
- Typical use: security reviews, compliance reporting
- Compare sharing patterns against policies`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\OneDriveSharing.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export OneDrive Sharing Activity
# Generated by PSForge

Connect-MgGraph -Scopes "Reports.Read.All"

try {
    Write-Host "Collecting OneDrive sharing activity..." -ForegroundColor Cyan
    
    $SharingReport = Get-MgReportOneDriveActivityUserDetail -Period D7
    
    $SharingReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Sharing report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export sharing report: $_"
}`;
    }
  },

  {
    id: 'onedrive-list-external-shares',
    title: 'List Externally Shared Files',
    description: 'List all files shared externally from a user OneDrive',
    category: 'Sharing & Permissions',
    instructions: `**How This Task Works:**
This script lists all files shared externally from a specific user's OneDrive for security audit and compliance verification.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- Sites.Read.All permission
- SharePoint Administrator or Global Administrator role

**What You Need to Provide:**
- User principal name (email address)

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves user's OneDrive
- Lists all externally shared items
- Displays file names and URLs
- Reports total shared item count

**Important Notes:**
- Essential for security audits and data loss prevention
- Shows files accessible outside organization
- Use during offboarding to revoke external access
- Run quarterly for compliance reviews
- Identify sensitive data shared externally
- Use for GDPR/HIPAA compliance verification
- Typical use: security incidents, user departures
- Revoke sharing for departed employees immediately`,
    parameters: [
      {
        name: 'userPrincipalName',
        label: 'User Principal Name',
        type: 'text',
        required: true,
        placeholder: 'user@domain.com',
        helpText: 'User email address'
      }
    ],
    scriptTemplate: (params) => {
      const upn = escapePowerShellString(params.userPrincipalName);

      return `# List Externally Shared Files
# Generated by PSForge

Connect-MgGraph -Scopes "Sites.Read.All"

try {
    Write-Host "Finding externally shared files for: ${upn}" -ForegroundColor Cyan
    
    $User = Get-MgUser -UserId "${upn}"
    $Drive = Get-MgUserDrive -UserId $User.Id
    
    $SharedItems = Get-MgDriveSharedWithMe -DriveId $Drive.Id
    
    Write-Host "Found $($SharedItems.Count) shared items" -ForegroundColor Yellow
    
    $SharedItems | Select-Object Name, WebUrl | Format-Table
    
} catch {
    Write-Error "Failed to list shared files: $_"
}`;
    }
  },

  {
    id: 'onedrive-export-sync-health',
    title: 'Export OneDrive Sync Health',
    description: 'Export OneDrive sync client health status to CSV',
    category: 'Sync & Client',
    instructions: `**How This Task Works:**
This script exports OneDrive sync client health metrics to troubleshoot sync issues and monitor client performance.

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- Reports.Read.All permission
- Global Administrator or Reports Reader role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Connects to Microsoft Graph
- Retrieves 7-day OneDrive sync health data
- Exports sync metrics to CSV
- Reports export success

**Important Notes:**
- Essential for troubleshooting sync problems
- Shows sync errors, conflicts, and health status
- Use for identifying users with sync failures
- Run weekly for proactive support
- Common issues: quota exceeded, authentication failures
- Identify users needing Known Folder Move assistance
- Typical use: helpdesk troubleshooting, proactive monitoring
- Compare with support tickets to identify patterns`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\SyncHealth.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export OneDrive Sync Health
# Generated by PSForge

Connect-MgGraph -Scopes "Reports.Read.All"

try {
    Write-Host "Collecting OneDrive sync health data..." -ForegroundColor Cyan
    
    $SyncHealth = Get-MgReportOneDriveUsageAccountDetail -Period D7
    
    $SyncHealth | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Sync health exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export sync health: $_"
}`;
    }
  },

  {
    id: 'onedrive-export-user-inventory',
    title: 'Export OneDrive User Inventory',
    description: 'Export list of all OneDrive sites to CSV',
    category: 'Reporting',
    instructions: `**How This Task Works:**
This script exports complete inventory of all OneDrive sites with owner, storage usage, and quota details for tenant-wide management.

**Prerequisites:**
- SharePoint Online Management Shell installed
- SharePoint Administrator or Global Administrator role
- Connection to SharePoint admin center

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Retrieves all personal OneDrive sites
- Collects owner, URL, storage usage, and quota
- Exports comprehensive inventory to CSV
- Reports total OneDrive site count

**Important Notes:**
- Essential for tenant-wide OneDrive management
- Shows all provisioned OneDrive sites
- Use for capacity planning and license verification
- Run monthly for inventory updates
- Identify orphaned OneDrives from departed users
- Compare with active directory for discrepancies
- Typical use: annual audits, capacity planning
- Total storage cost calculation for budgeting`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\OneDriveSites.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export OneDrive User Inventory
# Generated by PSForge

try {
    Write-Host "Collecting OneDrive sites..." -ForegroundColor Cyan
    
    $Sites = Get-SPOSite -IncludePersonalSite $true -Limit All -Filter "Url -like '-my.sharepoint.com/personal/'"
    
    Write-Host "Found $($Sites.Count) OneDrive sites" -ForegroundColor Yellow
    
    $SiteReport = foreach ($Site in $Sites) {
        [PSCustomObject]@{
            Owner            = $Site.Owner
            Url              = $Site.Url
            StorageUsageMB   = $Site.StorageUsageCurrent
            StorageQuotaMB   = $Site.StorageQuota
        }
    }
    
    $SiteReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ OneDrive sites exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export OneDrive sites: $_"
}`;
    }
  },
  {id:'od-set-quota',title:'Set OneDrive Storage Quota',description:'Configure storage quota for a user OneDrive',category:'Storage Management',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com'},{name:'quotaGB',label:'Quota (GB)',type:'number',required:true,defaultValue:1024}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity (Get-SPOSite -IncludePersonalSite $true -Filter "Owner -eq '${escapePowerShellString(p.userEmail)}'").Url -StorageQuota $((${p.quotaGB})*1024);Write-Host "✓ Quota set to ${p.quotaGB}GB" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-block-download',title:'Block File Downloads',description:'Prevent file downloads from OneDrive',category:'Sharing & Permissions',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true,placeholder:'user@domain.com'}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity (Get-SPOSite -IncludePersonalSite $true -Filter "Owner -eq '${escapePowerShellString(p.userEmail)}'").Url -DisableCompanyWideSharingLinks Disabled -LimitedAccessFileType WebPreviewableFiles;Write-Host "✓ Downloads blocked" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-enable-versioning',title:'Enable File Versioning',description:'Turn on version history for OneDrive',category:'Storage Management',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true},{name:'versions',label:'Max Versions',type:'number',required:false,defaultValue:500}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity (Get-SPOSite -IncludePersonalSite $true -Filter "Owner -eq '${escapePowerShellString(p.userEmail)}'").Url -EnableVersioning $true -MajorVersionLimit ${p.versions};Write-Host "✓ Versioning enabled (${p.versions} versions)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-sharing-link-exp',title:'Set Sharing Link Expiration',description:'Configure expiration for sharing links',category:'Sharing & Permissions',parameters:[{name:'days',label:'Expiration Days',type:'number',required:true,defaultValue:30}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -RequireAnonymousLinksExpireInDays ${p.days};Write-Host "✓ Sharing links expire in ${p.days} days" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-disable-sync',title:'Disable OneDrive Sync',description:'Prevent syncing for specific OneDrive',category:'Sync & Client',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity (Get-SPOSite -IncludePersonalSite $true -Filter "Owner -eq '${escapePowerShellString(p.userEmail)}'").Url -DisableFlows $true;Write-Host "✓ Sync disabled" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-external-sharing',title:'Configure External Sharing',description:'Control external sharing settings',category:'Sharing & Permissions',parameters:[{name:'level',label:'Sharing Level',type:'select',required:true,options:[{value:'Disabled',label:'Disabled'},{value:'ExternalUserSharingOnly',label:'Existing Guests'},{value:'ExternalUserAndGuestSharing',label:'Anyone'}]}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -OneDriveSharingCapability ${p.level};Write-Host "✓ External sharing set to ${p.level}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-retention-policy',title:'Apply Retention Policy',description:'Set retention policy for OneDrive content',category:'Storage Management',parameters:[{name:'days',label:'Retention Days',type:'number',required:true,defaultValue:365}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -OrphanedPersonalSitesRetentionPeriod ${p.days};Write-Host "✓ Retention set to ${p.days} days" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-recycle-bin-quota',title:'Set Recycle Bin Quota',description:'Configure recycle bin storage percentage',category:'Storage Management',parameters:[{name:'percent',label:'Quota Percent',type:'number',required:true,defaultValue:50}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -RecycleBinRetentionPeriod ${p.percent};Write-Host "✓ Recycle bin quota set to ${p.percent}%" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-default-link-type',title:'Set Default Sharing Link',description:'Configure default link type for sharing',category:'Sharing & Permissions',parameters:[{name:'type',label:'Link Type',type:'select',required:true,options:[{value:'None',label:'None'},{value:'Direct',label:'Direct'},{value:'Internal',label:'Organization'},{value:'AnonymousAccess',label:'Anyone'}]}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -DefaultSharingLinkType ${p.type};Write-Host "✓ Default link type: ${p.type}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-notify-owner',title:'Enable Owner Notifications',description:'Notify owners of sharing activities',category:'Sharing & Permissions',parameters:[{name:'enable',label:'Enable Notifications',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -NotifyOwnersWhenItemsReshared \\$${p.enable!==false};Write-Host "✓ Owner notifications: ${p.enable!==false}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-pre-upload-scan',title:'Configure Pre-Upload Scanning',description:'Enable malware scanning before upload',category:'Storage Management',parameters:[{name:'enable',label:'Enable Scanning',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -DisallowInfectedFileDownload \\$${p.enable!==false};Write-Host "✓ Pre-upload scanning: ${p.enable!==false}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-sync-restrictions',title:'Configure Sync Restrictions',description:'Limit OneDrive sync to managed devices',category:'Sync & Client',parameters:[{name:'restrict',label:'Restrict to Managed Devices',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -AllowDownloadingNonWebViewableFiles \\$${!(p.restrict!==false)};Write-Host "✓ Sync restrictions applied" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-file-count-report',title:'Export File Count Report',description:'Report file counts per OneDrive',category:'Reporting',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\Reports\\\\FileCounts.csv'}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{$Sites=Get-SPOSite -IncludePersonalSite $true -Limit All -Filter "Url -like '-my.sharepoint.com/personal/'";$Sites|Select Owner,Url,@{N='FileCount';E={$_.ItemCount}}|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ File counts exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-shared-links-report',title:'Export Shared Links Report',description:'List all sharing links created',category:'Reporting',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\Reports\\\\SharedLinks.csv'}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{$Sites=Get-SPOSite -IncludePersonalSite $true -Limit All;$Links=@();foreach($Site in $Sites){$Links+=Get-SPOSiteFileVersionBatchDeleteJob -Identity $Site.Url};$Links|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Shared links exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-storage-trend',title:'Export Storage Trend Report',description:'Historical storage usage analysis',category:'Reporting',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'days',label:'Days Back',type:'number',required:false,defaultValue:30}],scriptTemplate:p=>`Connect-MgGraph -Scopes "Reports.Read.All"\ntry{$Report=Get-MgReportOneDriveUsageStorage -Period "D${p.days}";$Report|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Storage trend exported (${p.days} days)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-access-requests',title:'Enable Access Requests',description:'Allow users to request access',category:'Sharing & Permissions',parameters:[{name:'enable',label:'Enable Requests',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -PreventExternalUsersFromResharing \\$${!(p.enable!==false)};Write-Host "✓ Access requests: ${p.enable!==false}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-legacy-auth-block',title:'Block Legacy Authentication',description:'Disable legacy auth protocols',category:'Sync & Client',parameters:[{name:'block',label:'Block Legacy Auth',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -LegacyAuthProtocolsEnabled \\$${!(p.block!==false)};Write-Host "✓ Legacy auth blocked: ${p.block!==false}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-idle-timeout',title:'Set Idle Session Timeout',description:'Auto-logout inactive sessions',category:'Sync & Client',parameters:[{name:'minutes',label:'Timeout (minutes)',type:'number',required:true,defaultValue:60}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOBrowserIdleSignOut -Enabled $true -WarnAfter (New-TimeSpan -Minutes $((${p.minutes})-5)) -SignOutAfter (New-TimeSpan -Minutes ${p.minutes});Write-Host "✓ Idle timeout: ${p.minutes} min" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-unmanaged-device-policy',title:'Configure Unmanaged Device Policy',description:'Control access from unmanaged devices',category:'Sync & Client',parameters:[{name:'action',label:'Action',type:'select',required:true,options:[{value:'AllowFullAccess',label:'Allow Full'},{value:'AllowLimitedAccess',label:'Limited'},{value:'BlockAccess',label:'Block'}]}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -ConditionalAccessPolicy ${p.action};Write-Host "✓ Unmanaged device policy: ${p.action}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-bulk-delete-sites',title:'Bulk Delete OneDrive Sites',description:'Remove OneDrive sites from CSV list',category:'Storage Management',parameters:[{name:'csvPath',label:'CSV Path',type:'text',required:true,placeholder:'C:\\\\Sites.csv'}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{$Sites=Import-Csv "${escapePowerShellString(p.csvPath)}";foreach($Site in $Sites){Remove-SPOSite -Identity $Site.Url -Confirm:$false};Write-Host "✓ Deleted $($Sites.Count) sites" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-bulk-set-quota',title:'Bulk Set Storage Quotas',description:'Apply quotas to multiple OneDrives from CSV',category:'Storage Management',parameters:[{name:'csvPath',label:'CSV Path',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{$Users=Import-Csv "${escapePowerShellString(p.csvPath)}";foreach($User in $Users){Set-SPOSite -Identity (Get-SPOSite -IncludePersonalSite $true -Filter "Owner -eq '$($User.Email)'").Url -StorageQuota ($User.QuotaGB*1024)};Write-Host "✓ Set $($Users.Count) quotas" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-permission-inheritance',title:'Break Permission Inheritance',description:'Stop inheriting permissions from parent',category:'Sharing & Permissions',parameters:[{name:'userEmail',label:'User Email',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{$Site=Get-SPOSite -IncludePersonalSite $true -Filter "Owner -eq '${escapePowerShellString(p.userEmail)}'";Write-Host "✓ Permissions can be customized for $($Site.Url)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-activity-report',title:'Export Activity Report',description:'User activity metrics for OneDrive',category:'Reporting',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'days',label:'Days',type:'number',required:false,defaultValue:7}],scriptTemplate:p=>`Connect-MgGraph -Scopes "Reports.Read.All"\ntry{$Report=Get-MgReportOneDriveActivityUserDetail -Period "D${p.days}";$Report|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Activity report exported (${p.days} days)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-file-types-block',title:'Block Specific File Types',description:'Prevent upload of certain file extensions',category:'Storage Management',parameters:[{name:'extensions',label:'Blocked Extensions',type:'text',required:true,placeholder:'.exe,.bat,.cmd'}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -ExcludedFileExtensionsForSyncApp "${escapePowerShellString(p.extensions)}";Write-Host "✓ Blocked file types: ${p.extensions}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'od-restore-deleted',title:'Restore Deleted OneDrive',description:'Recover recently deleted OneDrive site',category:'Storage Management',parameters:[{name:'siteUrl',label:'Site URL',type:'text',required:true,placeholder:'https://tenant-my.sharepoint.com/personal/user_domain_com'}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Restore-SPODeletedSite -Identity "${escapePowerShellString(p.siteUrl)}";Write-Host "✓ OneDrive restored" -ForegroundColor Green}catch{Write-Error $_}`}
];

export const oneDriveCategories = [
  'Storage Management',
  'Sharing & Permissions',
  'Sync & Client',
  'Reporting'
];
