import { escapePowerShellString } from './powershell-utils';

export interface PowerPlatformParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface PowerPlatformTask {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: PowerPlatformParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const powerPlatformTasks: PowerPlatformTask[] = [
  {
    id: 'pp-export-environments',
    title: 'Export Environments List',
    description: 'Export list of all Power Platform environments to CSV',
    category: 'Environment Management',
    instructions: `**How This Task Works:**
This script exports comprehensive inventory of all Power Platform environments for governance, capacity planning, and license management.

**Prerequisites:**
- Power Apps PowerShell module installed
- Power Platform Administrator or Global Administrator role
- Authenticated to Power Platform

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Retrieves all Power Platform environments
- Collects environment type, location, and creation date
- Exports detailed inventory to CSV
- Reports total environment count

**Important Notes:**
- Essential for environment governance and compliance
- Shows production, trial, sandbox, and developer environments
- Use for capacity planning and cost management
- Run monthly for environment inventory updates
- Identify rogue trial environments for cleanup
- Track environment sprawl across organization
- Typical use: governance reviews, cost analysis
- Delete unused trial/sandbox environments to reduce costs`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\PowerPlatformEnvironments.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Power Platform Environments
# Generated by PSForge

try {
    Write-Host "Collecting Power Platform environments..." -ForegroundColor Cyan
    
    $Environments = Get-AdminPowerAppEnvironment
    
    Write-Host "Found $($Environments.Count) environments" -ForegroundColor Yellow
    
    $EnvReport = foreach ($Env in $Environments) {
        [PSCustomObject]@{
            DisplayName        = $Env.DisplayName
            EnvironmentName    = $Env.EnvironmentName
            EnvironmentType    = $Env.EnvironmentType
            Location           = $Env.Location
            CreatedTime        = $Env.CreatedTime
        }
    }
    
    $EnvReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Environments exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export environments: $_"
}`;
    }
  },

  {
    id: 'pp-export-apps',
    title: 'Export Power Apps Inventory',
    description: 'Export list of all Power Apps to CSV',
    category: 'Apps & Flows',
    instructions: `**How This Task Works:**
This script exports complete inventory of all Power Apps across tenant for app lifecycle management and governance.

**Prerequisites:**
- Power Apps PowerShell module installed
- Power Platform Administrator or Global Administrator role
- Authenticated to Power Platform

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Retrieves all Power Apps across environments
- Collects app name, owner, environment, and creation date
- Exports comprehensive app inventory to CSV
- Reports total app count

**Important Notes:**
- Essential for app lifecycle governance
- Shows canvas and model-driven apps
- Use for identifying orphaned apps after user departures
- Run quarterly for app inventory audits
- Identify duplicate apps for consolidation
- Track app ownership for support accountability
- Typical use: governance reviews, license optimization
- Delete unused apps to improve manageability`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\PowerApps.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Power Apps Inventory
# Generated by PSForge

try {
    Write-Host "Collecting Power Apps..." -ForegroundColor Cyan
    
    $Apps = Get-AdminPowerApp
    
    Write-Host "Found $($Apps.Count) apps" -ForegroundColor Yellow
    
    $AppReport = foreach ($App in $Apps) {
        [PSCustomObject]@{
            DisplayName      = $App.DisplayName
            AppName          = $App.AppName
            Owner            = $App.Owner.displayName
            EnvironmentName  = $App.EnvironmentName
            CreatedTime      = $App.CreatedTime
        }
    }
    
    $AppReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Power Apps exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export Power Apps: $_"
}`;
    }
  },

  {
    id: 'pp-export-flows',
    title: 'Export Power Automate Flows',
    description: 'Export list of all Power Automate flows to CSV',
    category: 'Apps & Flows',
    instructions: `**How This Task Works:**
This script exports inventory of all Power Automate flows for monitoring automation usage and governance.

**Prerequisites:**
- Power Apps PowerShell module installed
- Power Platform Administrator or Global Administrator role
- Authenticated to Power Platform

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Retrieves all Power Automate flows across environments
- Collects flow name, enabled status, owner, and creation date
- Exports flow inventory to CSV
- Reports total flow count

**Important Notes:**
- Essential for automation governance and monitoring
- Shows enabled/disabled flow status
- Use for identifying broken or orphaned flows
- Run monthly for flow health audits
- Identify flows with expired connections
- Track flow ownership for maintenance
- Typical use: governance reviews, troubleshooting
- Disable unused flows to reduce API consumption`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\PowerFlows.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Power Automate Flows
# Generated by PSForge

try {
    Write-Host "Collecting Power Automate flows..." -ForegroundColor Cyan
    
    $Flows = Get-AdminFlow
    
    Write-Host "Found $($Flows.Count) flows" -ForegroundColor Yellow
    
    $FlowReport = foreach ($Flow in $Flows) {
        [PSCustomObject]@{
            DisplayName      = $Flow.DisplayName
            FlowName         = $Flow.FlowName
            Enabled          = $Flow.Enabled
            Owner            = $Flow.CreatedBy.displayName
            EnvironmentName  = $Flow.EnvironmentName
            CreatedTime      = $Flow.CreatedTime
        }
    }
    
    $FlowReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Power Automate flows exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export flows: $_"
}`;
    }
  },

  {
    id: 'pp-export-connectors',
    title: 'Export Custom Connectors',
    description: 'Export list of custom connectors to CSV',
    category: 'Connectors',
    instructions: `**How This Task Works:**
This script exports inventory of custom connectors for API integration governance and documentation.

**Prerequisites:**
- Power Apps PowerShell module installed
- Power Platform Administrator or Global Administrator role
- Authenticated to Power Platform

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Retrieves all custom connectors across environments
- Collects connector name, environment, and creation date
- Exports connector inventory to CSV
- Reports total custom connector count

**Important Notes:**
- Essential for API integration governance
- Shows custom API connectors only (not built-in)
- Use for tracking external API dependencies
- Run quarterly for connector audits
- Identify unused connectors for cleanup
- Document connector purposes and owners
- Typical use: security reviews, API inventory
- Review for security vulnerabilities in custom APIs`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\Connectors.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Custom Connectors
# Generated by PSForge

try {
    Write-Host "Collecting custom connectors..." -ForegroundColor Cyan
    
    $Connectors = Get-AdminPowerAppConnector -ConnectorType Custom
    
    Write-Host "Found $($Connectors.Count) custom connectors" -ForegroundColor Yellow
    
    $ConnectorReport = foreach ($Connector in $Connectors) {
        [PSCustomObject]@{
            DisplayName      = $Connector.DisplayName
            ConnectorName    = $Connector.ConnectorName
            EnvironmentName  = $Connector.EnvironmentName
            CreatedTime      = $Connector.CreatedTime
        }
    }
    
    $ConnectorReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Custom connectors exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export connectors: $_"
}`;
    }
  },

  {
    id: 'pp-export-dlp-policies',
    title: 'Export DLP Policies',
    description: 'Export Data Loss Prevention policies to CSV',
    category: 'Governance',
    instructions: `**How This Task Works:**
This script exports Data Loss Prevention (DLP) policies for security compliance and connector governance documentation.

**Prerequisites:**
- Power Apps PowerShell module installed
- Power Platform Administrator or Global Administrator role
- Authenticated to Power Platform

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
- Retrieves all DLP policies across tenant
- Collects policy name, creator, and creation date
- Exports DLP policy inventory to CSV
- Reports total policy count

**Important Notes:**
- Essential for security compliance and data protection
- DLP policies control connector data sharing
- Use for regulatory compliance documentation
- Run quarterly for security audits
- Prevent data leakage between business/non-business connectors
- Typical policies: block consumer services in production
- Typical use: compliance reviews, security audits
- Ensure all environments covered by DLP policies`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\DLPPolicies.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export DLP Policies
# Generated by PSForge

try {
    Write-Host "Collecting DLP policies..." -ForegroundColor Cyan
    
    $Policies = Get-AdminDlpPolicy
    
    Write-Host "Found $($Policies.Count) DLP policies" -ForegroundColor Yellow
    
    $PolicyReport = foreach ($Policy in $Policies) {
        [PSCustomObject]@{
            DisplayName      = $Policy.DisplayName
            PolicyName       = $Policy.PolicyName
            CreatedBy        = $Policy.CreatedBy
            CreatedTime      = $Policy.CreatedTime
        }
    }
    
    $PolicyReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ DLP policies exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export DLP policies: $_"
}`;
    }
  },
  {id:'pp-create-env',title:'Create Environment',description:'Create new Power Platform environment',category:'Environment Management',parameters:[{name:'name',label:'Environment Name',type:'text',required:true},{name:'region',label:'Region',type:'select',required:true,options:[{value:'unitedstates',label:'US'},{value:'europe',label:'Europe'},{value:'asia',label:'Asia'}]}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{New-AdminPowerAppEnvironment -DisplayName "${escapePowerShellString(p.name)}" -LocationName ${p.region} -EnvironmentSku Production;Write-Host "✓ Environment created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-delete-env',title:'Delete Environment',description:'Remove Power Platform environment',category:'Environment Management',parameters:[{name:'envName',label:'Environment Name',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Remove-AdminPowerAppEnvironment -EnvironmentName "${escapePowerShellString(p.envName)}";Write-Host "✓ Environment deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-backup-env',title:'Backup Environment',description:'Create environment backup',category:'Environment Management',parameters:[{name:'envName',label:'Environment Name',type:'text',required:true},{name:'label',label:'Backup Label',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Backup-CdsEnvironment -EnvironmentName "${escapePowerShellString(p.envName)}" -BackupLabel "${escapePowerShellString(p.label)}";Write-Host "✓ Backup created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-restore-env',title:'Restore Environment',description:'Restore from backup',category:'Environment Management',parameters:[{name:'sourceEnv',label:'Source Environment',type:'text',required:true},{name:'targetEnv',label:'Target Environment',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Restore-CdsEnvironment -SourceEnvironmentName "${escapePowerShellString(p.sourceEnv)}" -TargetEnvironmentName "${escapePowerShellString(p.targetEnv)}";Write-Host "✓ Environment restored" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-copy-env',title:'Copy Environment',description:'Copy environment to another region',category:'Environment Management',parameters:[{name:'sourceEnv',label:'Source Environment',type:'text',required:true},{name:'targetName',label:'Target Name',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Copy-CdsEnvironment -SourceEnvironmentName "${escapePowerShellString(p.sourceEnv)}" -TargetEnvironmentDisplayName "${escapePowerShellString(p.targetName)}";Write-Host "✓ Environment copied" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-list-apps',title:'Export Apps List',description:'Export all Power Apps',category:'Apps & Flows',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\Apps.csv'}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Get-AdminPowerApp|Select DisplayName,AppName,Owner,CreatedTime|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Apps exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-delete-app',title:'Delete Power App',description:'Remove a Power App',category:'Apps & Flows',parameters:[{name:'appName',label:'App Name',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Remove-AdminPowerApp -AppName "${escapePowerShellString(p.appName)}";Write-Host "✓ App deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-share-app',title:'Share Power App',description:'Share app with user',category:'Apps & Flows',parameters:[{name:'appName',label:'App Name',type:'text',required:true},{name:'userEmail',label:'User Email',type:'text',required:true},{name:'role',label:'Role',type:'select',required:true,options:[{value:'CanView',label:'Viewer'},{value:'CanEdit',label:'Editor'}]}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Set-AdminPowerAppRoleAssignment -AppName "${escapePowerShellString(p.appName)}" -PrincipalType User -PrincipalObjectId "${escapePowerShellString(p.userEmail)}" -RoleName ${p.role};Write-Host "✓ App shared" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-list-flows',title:'Export Flows List',description:'Export all Power Automate flows',category:'Apps & Flows',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\Flows.csv'}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Get-AdminFlow|Select DisplayName,FlowName,CreatedTime,State|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Flows exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-disable-flow',title:'Disable Flow',description:'Turn off a Power Automate flow',category:'Apps & Flows',parameters:[{name:'flowName',label:'Flow Name',type:'text',required:true},{name:'envName',label:'Environment',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Disable-AdminFlow -EnvironmentName "${escapePowerShellString(p.envName)}" -FlowName "${escapePowerShellString(p.flowName)}";Write-Host "✓ Flow disabled" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-enable-flow',title:'Enable Flow',description:'Turn on a Power Automate flow',category:'Apps & Flows',parameters:[{name:'flowName',label:'Flow Name',type:'text',required:true},{name:'envName',label:'Environment',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Enable-AdminFlow -EnvironmentName "${escapePowerShellString(p.envName)}" -FlowName "${escapePowerShellString(p.flowName)}";Write-Host "✓ Flow enabled" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-delete-flow',title:'Delete Flow',description:'Remove a Power Automate flow',category:'Apps & Flows',parameters:[{name:'flowName',label:'Flow Name',type:'text',required:true},{name:'envName',label:'Environment',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Remove-AdminFlow -EnvironmentName "${escapePowerShellString(p.envName)}" -FlowName "${escapePowerShellString(p.flowName)}";Write-Host "✓ Flow deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-list-connectors',title:'Export Connectors',description:'List all custom connectors',category:'Connectors',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\\\Connectors.csv'}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Get-AdminPowerAppConnector -FilterNonCustomConnectors|Select DisplayName,ConnectorName,CreatedTime|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Connectors exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-delete-connector',title:'Delete Connector',description:'Remove custom connector',category:'Connectors',parameters:[{name:'connectorName',label:'Connector Name',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Remove-AdminPowerAppConnector -ConnectorName "${escapePowerShellString(p.connectorName)}";Write-Host "✓ Connector deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-block-connector',title:'Block Connector',description:'Block connector in DLP policy',category:'Governance',parameters:[{name:'policyName',label:'Policy Name',type:'text',required:true},{name:'connectorId',label:'Connector ID',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Add-ConnectorToBusinessDataGroup -PolicyName "${escapePowerShellString(p.policyName)}" -ConnectorName "${escapePowerShellString(p.connectorId)}" -GroupName Blocked;Write-Host "✓ Connector blocked" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-tenant-settings',title:'Configure Tenant Settings',description:'Update Power Platform tenant settings',category:'Governance',parameters:[{name:'disableTrials',label:'Disable Trials',type:'checkbox',required:false,defaultValue:false}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Set-TenantSettings -DisableTrialEnvironmentCreationByNonAdminUsers \\$${p.disableTrials===true};Write-Host "✓ Tenant settings updated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-export-users',title:'Export Environment Users',description:'List users with access to environments',category:'Governance',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{$Envs=Get-AdminPowerAppEnvironment;$Users=@();foreach($E in $Envs){$Users+=Get-AdminPowerAppEnvironmentRoleAssignment -EnvironmentName $E.EnvironmentName};$Users|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Users exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-set-env-security',title:'Set Environment Security',description:'Configure environment security roles',category:'Governance',parameters:[{name:'envName',label:'Environment',type:'text',required:true},{name:'userEmail',label:'User Email',type:'text',required:true},{name:'role',label:'Role',type:'select',required:true,options:[{value:'EnvironmentAdmin',label:'Admin'},{value:'EnvironmentMaker',label:'Maker'}]}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Set-AdminPowerAppEnvironmentRoleAssignment -EnvironmentName "${escapePowerShellString(p.envName)}" -PrincipalType User -PrincipalObjectId "${escapePowerShellString(p.userEmail)}" -RoleName ${p.role};Write-Host "✓ Security role assigned" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-capacity-report',title:'Export Capacity Report',description:'Report environment storage capacity',category:'Environment Management',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Get-AdminPowerAppEnvironment|Select DisplayName,@{N='CapacityMB';E={$_.Internal.properties.capacity.actualConsumption}}|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Capacity report exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-create-dlp',title:'Create DLP Policy',description:'Create data loss prevention policy',category:'Governance',parameters:[{name:'policyName',label:'Policy Name',type:'text',required:true},{name:'envFilter',label:'Environment Filter',type:'select',required:true,options:[{value:'All',label:'All'},{value:'Selected',label:'Selected'}]}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{New-DlpPolicy -DisplayName "${escapePowerShellString(p.policyName)}" -EnvironmentType ${p.envFilter};Write-Host "✓ DLP policy created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-delete-dlp',title:'Delete DLP Policy',description:'Remove DLP policy',category:'Governance',parameters:[{name:'policyName',label:'Policy Name',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Remove-DlpPolicy -PolicyName "${escapePowerShellString(p.policyName)}";Write-Host "✓ DLP policy deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-flow-run-history',title:'Export Flow Run History',description:'Get flow execution history',category:'Apps & Flows',parameters:[{name:'flowName',label:'Flow Name',type:'text',required:true},{name:'envName',label:'Environment',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Get-AdminFlowRunHistory -EnvironmentName "${escapePowerShellString(p.envName)}" -FlowName "${escapePowerShellString(p.flowName)}"|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Flow history exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-orphaned-resources',title:'Find Orphaned Resources',description:'List resources without owners',category:'Governance',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{$Apps=Get-AdminPowerApp|Where{-not $_.Owner};$Apps|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Orphaned resources: $($Apps.Count)" -ForegroundColor Yellow}catch{Write-Error $_}`},
  {id:'pp-usage-analytics',title:'Export Usage Analytics',description:'Get environment usage metrics',category:'Environment Management',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'days',label:'Days Back',type:'number',required:false,defaultValue:30}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{$StartDate=(Get-Date).AddDays(-${p.days});Get-AdminFlowRunHistory -Filter "startTime ge '$($StartDate.ToString('yyyy-MM-dd'))'"|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Analytics exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'pp-solution-export',title:'Export Solution',description:'Export managed/unmanaged solution',category:'Apps & Flows',parameters:[{name:'solutionName',label:'Solution Name',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'managed',label:'Export as Managed',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>`Add-PowerAppsAccount\ntry{Export-CdsSolution -SolutionName "${escapePowerShellString(p.solutionName)}" -SolutionOutputFile "${escapePowerShellString(p.exportPath)}" -Managed \\$${p.managed!==false};Write-Host "✓ Solution exported" -ForegroundColor Green}catch{Write-Error $_}`}
];

export const powerPlatformCategories = [
  'Environment Management',
  'Apps & Flows',
  'Connectors',
  'Governance'
];
