import { ScriptCommand } from "@shared/schema";
import { getCommandById } from "./powershell-commands";

export function generatePowerShellScript(scriptCommands: ScriptCommand[]): string {
  if (scriptCommands.length === 0) {
    return '';
  }

  const lines: string[] = [];
  
  lines.push('# PowerShell Script Generated by PowerShell Script Generator');
  lines.push(`# Generated on: ${new Date().toLocaleString()}`);
  lines.push('# Total Commands: ' + scriptCommands.length);
  lines.push('');

  scriptCommands.forEach((scriptCommand, index) => {
    const command = getCommandById(scriptCommand.commandId);
    if (!command) return;

    lines.push(`# Command ${index + 1}: ${command.name}`);
    if (command.description) {
      lines.push(`# ${command.description}`);
    }
    
    let commandLine = command.name;
    
    command.parameters.forEach(param => {
      const value = scriptCommand.parameters[param.id];
      
      if (value === undefined || value === null || value === '') {
        return;
      }

      if (param.type === 'switch' || param.type === 'boolean') {
        if (value === true) {
          commandLine += ` -${param.name}`;
        }
      } else if (param.type === 'array') {
        const arrayValue = Array.isArray(value) ? value : [value];
        const sanitizedArray = arrayValue
          .filter(v => v !== null && v !== undefined && String(v).trim() !== '');
        if (sanitizedArray.length > 0) {
          const formattedArray = sanitizedArray.map(v => `"${String(v).trim()}"`).join(',');
          commandLine += ` -${param.name} ${formattedArray}`;
        }
      } else if (param.type === 'int') {
        commandLine += ` -${param.name} ${value}`;
      } else {
        const needsQuotes = typeof value === 'string' && 
          (value.includes(' ') || value.includes('\\') || value.includes('/'));
        if (needsQuotes) {
          commandLine += ` -${param.name} "${value}"`;
        } else {
          commandLine += ` -${param.name} ${value}`;
        }
      }
    });
    
    lines.push(commandLine);
    
    if (index < scriptCommands.length - 1) {
      lines.push('');
    }
  });

  return lines.join('\n');
}

export function validatePowerShellScript(code: string): Array<{ line?: number; message: string; severity: string }> {
  const errors: Array<{ line?: number; message: string; severity: string }> = [];
  
  if (!code.trim()) {
    return errors;
  }

  const lines = code.split('\n');
  
  lines.forEach((line, index) => {
    const lineNumber = index + 1;
    const trimmedLine = line.trim();
    
    if (!trimmedLine || trimmedLine.startsWith('#')) {
      return;
    }

    if (trimmedLine.match(/[""]/g) && (trimmedLine.match(/[""]/g)?.length ?? 0) % 2 !== 0) {
      errors.push({
        line: lineNumber,
        message: 'Unmatched quotation marks detected',
        severity: 'error'
      });
    }

    if (trimmedLine.includes('\\\\')) {
      errors.push({
        line: lineNumber,
        message: 'Double backslashes detected - use single backslash in PowerShell paths',
        severity: 'warning'
      });
    }

    if (trimmedLine.match(/-\w+\s+-\w+/) && !trimmedLine.includes('"') && !trimmedLine.includes("'")) {
      const hasValue = trimmedLine.match(/-\w+\s+(?!-)/);
      if (!hasValue) {
        errors.push({
          line: lineNumber,
          message: 'Parameter appears to be missing a value',
          severity: 'warning'
        });
      }
    }

    if (trimmedLine.includes('C:') && !trimmedLine.includes('"') && !trimmedLine.includes("'")) {
      if (trimmedLine.match(/C:\S+\s/)) {
        errors.push({
          line: lineNumber,
          message: 'Path with spaces should be quoted',
          severity: 'info'
        });
      }
    }
  });

  return errors;
}
