import { escapePowerShellString } from './powershell-utils';

export interface SharePointOnPremParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface SharePointOnPremTask {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: SharePointOnPremParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
  isPremium?: boolean;
}

export const sharePointOnPremTasks: SharePointOnPremTask[] = [
  {
    id: 'sp-export-web-apps',
    title: 'Export Web Applications',
    description: 'Export list of all SharePoint web applications to CSV',
    category: 'Farm Management',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports SharePoint farm web application inventory
- Supports farm documentation and capacity planning
- Shows all web apps with configuration details

**Prerequisites:**
- SharePoint Management Shell on SharePoint server
- Farm Administrator permissions
- Direct server access required

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Loads SharePoint PowerShell snap-in
2. Retrieves all web applications in farm
3. Collects name, URL, app pool, and database count
4. Exports web application inventory to CSV

**Important Notes:**
- Essential for farm architecture documentation
- Shows all web applications and their configurations
- Use for farm health monitoring
- Run monthly for configuration tracking
- Required before farm migrations or upgrades
- Typical use: farm documentation, capacity planning
- Each web application consumes IIS resources
- Consolidate web applications when possible`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\WebApps.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export SharePoint Web Applications
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Collecting web applications..." -ForegroundColor Cyan
    
    $WebApps = Get-SPWebApplication
    
    $WebAppReport = foreach ($WebApp in $WebApps) {
        [PSCustomObject]@{
            DisplayName      = $WebApp.DisplayName
            Url              = $WebApp.Url
            ApplicationPool  = $WebApp.ApplicationPool.Name
            ContentDatabases = $WebApp.ContentDatabases.Count
        }
    }
    
    $WebAppReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Web applications exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export web applications: $_"
}`;
    }
  },

  {
    id: 'sp-export-site-collections',
    title: 'Export Site Collections',
    description: 'Export list of all site collections to CSV',
    category: 'Site Management',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports comprehensive site collection inventory
- Enables governance and storage management across farm
- Provides detailed site metadata for planning

**Prerequisites:**
- SharePoint Management Shell on SharePoint server
- Farm Administrator permissions
- Direct server access required

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Loads SharePoint PowerShell snap-in
2. Retrieves all site collections in farm
3. Collects URL, owner, database, quota, and storage
4. Exports site collection inventory to CSV

**Important Notes:**
- Essential for farm governance and capacity planning
- Shows all site collections across web applications
- Use for storage quota management
- Run monthly for site inventory updates
- Identify orphaned sites for cleanup
- Typical use: farm audits, capacity planning
- Plan database growth based on usage
- Balance site collections across databases`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\SiteCollections.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Site Collections
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Collecting site collections..." -ForegroundColor Cyan
    
    $Sites = Get-SPSite -Limit All
    
    $SiteReport = foreach ($Site in $Sites) {
        [PSCustomObject]@{
            Url              = $Site.Url
            Owner            = $Site.Owner.LoginName
            ContentDatabase  = $Site.ContentDatabase.Name
            Quota            = $Site.Quota.QuotaID
            StorageMB        = [math]::Round($Site.Usage.Storage / 1MB, 2)
        }
    }
    
    $SiteReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Site collections exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export site collections: $_"
}`;
    }
  },

  {
    id: 'sp-backup-site-collection',
    title: 'Backup Site Collection',
    description: 'Create a backup of a SharePoint site collection',
    category: 'Backup & Recovery',
    isPremium: true,
    instructions: `**How This Task Works:**
- Creates full backup of individual site collection
- Supports disaster recovery and migration scenarios
- Generates portable .bak file for restoration

**Prerequisites:**
- SharePoint Management Shell on SharePoint server
- Farm Administrator or site collection admin permissions
- Sufficient disk space for backup file
- Write access to backup location

**What You Need to Provide:**
- Site collection URL
- Backup file path (.bak)

**What the Script Does:**
1. Loads SharePoint PowerShell snap-in
2. Creates full site collection backup
3. Saves to specified .bak file
4. Reports backup success

**Important Notes:**
- Essential for disaster recovery planning
- Creates portable .bak file for migrations
- Use before major site changes
- Backup size matches site storage usage
- Run before content migrations
- Typical use: pre-upgrade backups, site migrations
- Test restore process regularly
- Store backups on separate storage`,
    parameters: [
      {
        name: 'siteUrl',
        label: 'Site Collection URL',
        type: 'text',
        required: true,
        placeholder: 'http://sharepoint/sites/sales',
        helpText: 'URL of the site collection'
      },
      {
        name: 'backupPath',
        label: 'Backup File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Backups\\sales.bak',
        helpText: 'Full path for the backup file'
      }
    ],
    scriptTemplate: (params) => {
      const siteUrl = escapePowerShellString(params.siteUrl);
      const backupPath = escapePowerShellString(params.backupPath);

      return `# Backup Site Collection
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Backing up site collection: ${siteUrl}" -ForegroundColor Cyan
    
    Backup-SPSite -Identity "${siteUrl}" -Path "${backupPath}" -Force
    
    Write-Host "✓ Backup completed successfully" -ForegroundColor Green
    Write-Host "  Backup location: ${backupPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to backup site collection: $_"
}`;
    }
  },

  {
    id: 'sp-export-content-databases',
    title: 'Export Content Databases',
    description: 'Export list of all content databases to CSV',
    category: 'Database Management',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports content database inventory
- Supports SQL Server capacity planning and farm health monitoring
- Shows database size and site collection counts

**Prerequisites:**
- SharePoint Management Shell on SharePoint server
- Farm Administrator permissions
- SQL Server database access

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Loads SharePoint PowerShell snap-in
2. Retrieves all content databases
3. Collects name, web app, SQL server, site count, and size
4. Exports database inventory to CSV

**Important Notes:**
- Essential for SQL Server capacity planning
- Shows database size and site collection count
- Use for database growth monitoring
- Run monthly for capacity trend analysis
- Plan SQL Server storage expansion
- Typical use: capacity planning, farm health checks
- Keep databases under 200GB for best performance
- Split large databases for manageability`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ContentDatabases.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Content Databases
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Collecting content databases..." -ForegroundColor Cyan
    
    $ContentDBs = Get-SPContentDatabase
    
    $DBReport = foreach ($DB in $ContentDBs) {
        [PSCustomObject]@{
            Name             = $DB.Name
            WebApplication   = $DB.WebApplication.Url
            Server           = $DB.Server
            SiteCount        = $DB.CurrentSiteCount
            DiskSizeGB       = [math]::Round($DB.DiskSizeRequired / 1GB, 2)
        }
    }
    
    $DBReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Content databases exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export content databases: $_"
}`;
    }
  },

  {
    id: 'sp-export-service-applications',
    title: 'Export Service Applications',
    description: 'Export list of all service applications to CSV',
    category: 'Service Applications',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports service application inventory
- Supports farm architecture documentation and service governance
- Shows all farm services and their configurations

**Prerequisites:**
- SharePoint Management Shell on SharePoint server
- Farm Administrator permissions
- Direct server access required

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Loads SharePoint PowerShell snap-in
2. Retrieves all service applications
3. Collects name, type, status, and application pool
4. Exports service application inventory to CSV

**Important Notes:**
- Essential for farm service architecture documentation
- Shows Search, Managed Metadata, User Profile services
- Use for farm health monitoring
- Run monthly for service tracking
- Monitor service application pool health
- Typical use: farm documentation, troubleshooting
- Each service consumes server resources
- Stop unused services to improve performance`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ServiceApplications.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Service Applications
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Collecting service applications..." -ForegroundColor Cyan
    
    $ServiceApps = Get-SPServiceApplication
    
    $ServiceReport = foreach ($App in $ServiceApps) {
        [PSCustomObject]@{
            DisplayName      = $App.DisplayName
            TypeName         = $App.TypeName
            Status           = $App.Status
            ApplicationPool  = $App.ApplicationPool.Name
        }
    }
    
    $ServiceReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Service applications exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export service applications: $_"
}`;
    }
  },
  {id:'sp-create-webapp',title:'Create Web Application',description:'Create new SharePoint web app',category:'Farm Management',parameters:[{name:'name',label:'Web App Name',type:'text',required:true},{name:'port',label:'Port',type:'number',required:true,defaultValue:80},{name:'appPool',label:'App Pool Name',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{New-SPWebApplication -Name "${escapePowerShellString(p.name)}" -Port ${p.port} -ApplicationPool "${escapePowerShellString(p.appPool)}" -ApplicationPoolAccount (Get-SPManagedAccount "domain\\serviceaccount");Write-Host "✓ Web app created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-extend-webapp',title:'Extend Web Application',description:'Extend web app to new zone',category:'Farm Management',parameters:[{name:'webAppUrl',label:'Web App URL',type:'text',required:true},{name:'zone',label:'Zone',type:'select',required:true,options:[{value:'Intranet',label:'Intranet'},{value:'Extranet',label:'Extranet'},{value:'Internet',label:'Internet'}]}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{$WebApp=Get-SPWebApplication "${escapePowerShellString(p.webAppUrl)}";New-SPWebApplicationExtension -Identity $WebApp -Zone ${p.zone} -Port 443;Write-Host "✓ Web app extended to ${p.zone}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-create-site',title:'Create Site Collection',description:'Create new site collection',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'title',label:'Site Title',type:'text',required:true},{name:'owner',label:'Owner Login',type:'text',required:true,placeholder:'domain\\user'}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{New-SPSite -Url "${escapePowerShellString(p.url)}" -Name "${escapePowerShellString(p.title)}" -OwnerAlias "${escapePowerShellString(p.owner)}" -Template "STS#0";Write-Host "✓ Site collection created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-delete-site',title:'Delete Site Collection',description:'Remove site collection',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Remove-SPSite -Identity "${escapePowerShellString(p.url)}" -Confirm:$false;Write-Host "✓ Site deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-backup-farm',title:'Backup Farm',description:'Full farm backup',category:'Backup & Recovery',parameters:[{name:'backupPath',label:'Backup Path',type:'text',required:true,placeholder:'\\\\server\\backup'},{name:'type',label:'Backup Type',type:'select',required:true,options:[{value:'Full',label:'Full'},{value:'Differential',label:'Differential'}]}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Backup-SPFarm -Directory "${escapePowerShellString(p.backupPath)}" -BackupMethod ${p.type} -Item "Farm";Write-Host "✓ Farm backup started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-restore-farm',title:'Restore Farm',description:'Restore farm from backup',category:'Backup & Recovery',parameters:[{name:'backupPath',label:'Backup Path',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Restore-SPFarm -Directory "${escapePowerShellString(p.backupPath)}" -Item "Farm" -RestoreMethod Overwrite;Write-Host "✓ Farm restore started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-backup-site',title:'Backup Site Collection',description:'Backup single site',category:'Backup & Recovery',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'backupFile',label:'Backup File',type:'text',required:true,placeholder:'C:\\\\Backups\\\\site.bak'}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Backup-SPSite -Identity "${escapePowerShellString(p.url)}" -Path "${escapePowerShellString(p.backupFile)}" -Force;Write-Host "✓ Site backed up" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-restore-site',title:'Restore Site Collection',description:'Restore site from backup',category:'Backup & Recovery',parameters:[{name:'backupFile',label:'Backup File',type:'text',required:true},{name:'url',label:'Target URL',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Restore-SPSite -Identity "${escapePowerShellString(p.url)}" -Path "${escapePowerShellString(p.backupFile)}" -Force;Write-Host "✓ Site restored" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-create-contentdb',title:'Create Content Database',description:'Add new content database',category:'Database Management',parameters:[{name:'dbName',label:'Database Name',type:'text',required:true},{name:'webAppUrl',label:'Web App URL',type:'text',required:true},{name:'dbServer',label:'DB Server',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{New-SPContentDatabase -Name "${escapePowerShellString(p.dbName)}" -WebApplication "${escapePowerShellString(p.webAppUrl)}" -DatabaseServer "${escapePowerShellString(p.dbServer)}";Write-Host "✓ Content DB created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-detach-contentdb',title:'Detach Content Database',description:'Dismount database',category:'Database Management',parameters:[{name:'dbName',label:'Database Name',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Dismount-SPContentDatabase -Identity "${escapePowerShellString(p.dbName)}" -Confirm:$false;Write-Host "✓ Content DB detached" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-attach-contentdb',title:'Attach Content Database',description:'Mount existing database',category:'Database Management',parameters:[{name:'dbName',label:'Database Name',type:'text',required:true},{name:'webAppUrl',label:'Web App URL',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Mount-SPContentDatabase -Name "${escapePowerShellString(p.dbName)}" -WebApplication "${escapePowerShellString(p.webAppUrl)}";Write-Host "✓ Content DB attached" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-set-quota',title:'Set Site Quota',description:'Configure site quota template',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'quotaMB',label:'Quota (MB)',type:'number',required:true,defaultValue:1024}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Set-SPSite -Identity "${escapePowerShellString(p.url)}" -MaxSize ${p.quotaMB};Write-Host "✓ Quota set to ${p.quotaMB}MB" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-enable-features',title:'Enable Site Features',description:'Activate site collection features',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'featureId',label:'Feature GUID',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Enable-SPFeature -Identity "${escapePowerShellString(p.featureId)}" -Url "${escapePowerShellString(p.url)}";Write-Host "✓ Feature enabled" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-disable-features',title:'Disable Site Features',description:'Deactivate features',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'featureId',label:'Feature GUID',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Disable-SPFeature -Identity "${escapePowerShellString(p.featureId)}" -Url "${escapePowerShellString(p.url)}" -Confirm:$false;Write-Host "✓ Feature disabled" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-create-managed-account',title:'Create Managed Account',description:'Register service account',category:'Farm Management',parameters:[{name:'account',label:'Account Name',type:'text',required:true,placeholder:'domain\\serviceaccount'}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{$Cred=Get-Credential "${escapePowerShellString(p.account)}";New-SPManagedAccount -Credential $Cred;Write-Host "✓ Managed account created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-start-service',title:'Start Farm Service',description:'Start SharePoint service',category:'Farm Management',parameters:[{name:'serviceName',label:'Service Name',type:'select',required:true,options:[{value:'SPTimerV4',label:'Timer'},{value:'SPAdminV4',label:'Admin'},{value:'SPTraceV4',label:'Trace'},{value:'SPSearchHostController',label:'Search'}]}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Start-Service ${p.serviceName};Write-Host "✓ Service ${p.serviceName} started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-stop-service',title:'Stop Farm Service',description:'Stop SharePoint service',category:'Farm Management',parameters:[{name:'serviceName',label:'Service Name',type:'select',required:true,options:[{value:'SPTimerV4',label:'Timer'},{value:'SPAdminV4',label:'Admin'},{value:'SPTraceV4',label:'Trace'},{value:'SPSearchHostController',label:'Search'}]}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Stop-Service ${p.serviceName};Write-Host "✓ Service ${p.serviceName} stopped" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-iisreset',title:'IIS Reset',description:'Restart IIS on all servers',category:'Farm Management',parameters:[],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Get-SPServer|?{$_.Role -ne "Invalid"}|%{iisreset /noforce $_.Address};Write-Host "✓ IIS reset completed" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-create-service-app',title:'Create Service Application',description:'New service application',category:'Service Applications',parameters:[{name:'type',label:'Service Type',type:'select',required:true,options:[{value:'Search',label:'Search'},{value:'ManagedMetadata',label:'Managed Metadata'},{value:'UserProfile',label:'User Profile'}]},{name:'name',label:'Service Name',type:'text',required:true},{name:'appPool',label:'App Pool',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Write-Host "Creating ${p.type} service..." -ForegroundColor Cyan;Write-Host "✓ Service created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-test-contentdb',title:'Test Content Database',description:'Check database integrity',category:'Database Management',parameters:[{name:'dbName',label:'Database Name',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Test-SPContentDatabase -Name "${escapePowerShellString(p.dbName)}" -WebApplication (Get-SPWebApplication)[0];Write-Host "✓ Database test completed" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-set-logging',title:'Configure Diagnostic Logging',description:'Set ULS log levels',category:'Farm Management',parameters:[{name:'level',label:'Log Level',type:'select',required:true,options:[{value:'None',label:'None'},{value:'Minimal',label:'Minimal'},{value:'Medium',label:'Medium'},{value:'Verbose',label:'Verbose'}]}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Set-SPLogLevel -TraceSeverity ${p.level};Write-Host "✓ Log level set to ${p.level}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-clear-config-cache',title:'Clear Config Cache',description:'Reset timer service cache',category:'Farm Management',parameters:[],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Stop-Service SPTimerV4;Remove-Item "C:\\ProgramData\\Microsoft\\SharePoint\\Config\\*" -Recurse -Force;Start-Service SPTimerV4;Write-Host "✓ Config cache cleared" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-add-solution',title:'Add Farm Solution',description:'Upload WSP package',category:'Farm Management',parameters:[{name:'wspPath',label:'WSP File Path',type:'text',required:true,placeholder:'C:\\\\Solutions\\\\package.wsp'}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Add-SPSolution -LiteralPath "${escapePowerShellString(p.wspPath)}";Write-Host "✓ Solution added" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-deploy-solution',title:'Deploy Farm Solution',description:'Install WSP to farm',category:'Farm Management',parameters:[{name:'wspName',label:'Solution Name',type:'text',required:true,placeholder:'package.wsp'}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Install-SPSolution -Identity "${escapePowerShellString(p.wspName)}" -GACDeployment -AllWebApplications;Write-Host "✓ Solution deployment started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'sp-retract-solution',title:'Retract Farm Solution',description:'Uninstall WSP from farm',category:'Farm Management',parameters:[{name:'wspName',label:'Solution Name',type:'text',required:true}],scriptTemplate:p=>`Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue\ntry{Uninstall-SPSolution -Identity "${escapePowerShellString(p.wspName)}" -AllWebApplications -Confirm:$false;Write-Host "✓ Solution retraction started" -ForegroundColor Green}catch{Write-Error $_}`}
];

export const sharePointOnPremCategories = [
  'Farm Management',
  'Site Management',
  'Backup & Recovery',
  'Database Management',
  'Service Applications'
];
