import { escapePowerShellString } from './powershell-utils';

export interface SharePointOnPremParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface SharePointOnPremTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: SharePointOnPremParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const sharePointOnPremTasks: SharePointOnPremTask[] = [
  {
    id: 'sp-export-web-apps',
    title: 'Export Web Applications',
    description: 'Export list of all SharePoint web applications to CSV',
    category: 'Farm Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\WebApps.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export SharePoint Web Applications
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Collecting web applications..." -ForegroundColor Cyan
    
    $WebApps = Get-SPWebApplication
    
    $WebAppReport = foreach ($WebApp in $WebApps) {
        [PSCustomObject]@{
            DisplayName      = $WebApp.DisplayName
            Url              = $WebApp.Url
            ApplicationPool  = $WebApp.ApplicationPool.Name
            ContentDatabases = $WebApp.ContentDatabases.Count
        }
    }
    
    $WebAppReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Web applications exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export web applications: $_"
}`;
    }
  },

  {
    id: 'sp-export-site-collections',
    title: 'Export Site Collections',
    description: 'Export list of all site collections to CSV',
    category: 'Site Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\SiteCollections.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Site Collections
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Collecting site collections..." -ForegroundColor Cyan
    
    $Sites = Get-SPSite -Limit All
    
    $SiteReport = foreach ($Site in $Sites) {
        [PSCustomObject]@{
            Url              = $Site.Url
            Owner            = $Site.Owner.LoginName
            ContentDatabase  = $Site.ContentDatabase.Name
            Quota            = $Site.Quota.QuotaID
            StorageMB        = [math]::Round($Site.Usage.Storage / 1MB, 2)
        }
    }
    
    $SiteReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Site collections exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export site collections: $_"
}`;
    }
  },

  {
    id: 'sp-backup-site-collection',
    title: 'Backup Site Collection',
    description: 'Create a backup of a SharePoint site collection',
    category: 'Backup & Recovery',
    parameters: [
      {
        name: 'siteUrl',
        label: 'Site Collection URL',
        type: 'text',
        required: true,
        placeholder: 'http://sharepoint/sites/sales',
        helpText: 'URL of the site collection'
      },
      {
        name: 'backupPath',
        label: 'Backup File Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Backups\\sales.bak',
        helpText: 'Full path for the backup file'
      }
    ],
    scriptTemplate: (params) => {
      const siteUrl = escapePowerShellString(params.siteUrl);
      const backupPath = escapePowerShellString(params.backupPath);

      return `# Backup Site Collection
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Backing up site collection: ${siteUrl}" -ForegroundColor Cyan
    
    Backup-SPSite -Identity "${siteUrl}" -Path "${backupPath}" -Force
    
    Write-Host "✓ Backup completed successfully" -ForegroundColor Green
    Write-Host "  Backup location: ${backupPath}" -ForegroundColor Cyan
    
} catch {
    Write-Error "Failed to backup site collection: $_"
}`;
    }
  },

  {
    id: 'sp-export-content-databases',
    title: 'Export Content Databases',
    description: 'Export list of all content databases to CSV',
    category: 'Database Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ContentDatabases.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Content Databases
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Collecting content databases..." -ForegroundColor Cyan
    
    $ContentDBs = Get-SPContentDatabase
    
    $DBReport = foreach ($DB in $ContentDBs) {
        [PSCustomObject]@{
            Name             = $DB.Name
            WebApplication   = $DB.WebApplication.Url
            Server           = $DB.Server
            SiteCount        = $DB.CurrentSiteCount
            DiskSizeGB       = [math]::Round($DB.DiskSizeRequired / 1GB, 2)
        }
    }
    
    $DBReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Content databases exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export content databases: $_"
}`;
    }
  },

  {
    id: 'sp-export-service-applications',
    title: 'Export Service Applications',
    description: 'Export list of all service applications to CSV',
    category: 'Service Applications',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ServiceApplications.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Service Applications
# Generated by PSForge

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

try {
    Write-Host "Collecting service applications..." -ForegroundColor Cyan
    
    $ServiceApps = Get-SPServiceApplication
    
    $ServiceReport = foreach ($App in $ServiceApps) {
        [PSCustomObject]@{
            DisplayName      = $App.DisplayName
            TypeName         = $App.TypeName
            Status           = $App.Status
            ApplicationPool  = $App.ApplicationPool.Name
        }
    }
    
    $ServiceReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Service applications exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export service applications: $_"
}`;
    }
  }
];

export const sharePointOnPremCategories = [
  'Farm Management',
  'Site Management',
  'Backup & Recovery',
  'Database Management',
  'Service Applications'
];
