import { escapePowerShellString } from './powershell-utils';

export interface SharePointOnlineParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface SharePointOnlineTask {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: SharePointOnlineParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const sharePointOnlineTasks: SharePointOnlineTask[] = [
  {
    id: 'spo-export-site-inventory',
    title: 'Export Site Collection Inventory',
    description: 'Export list of all SharePoint Online site collections to CSV',
    category: 'Site Management',
    instructions: `**How This Task Works:**
- Exports comprehensive inventory of all SharePoint Online site collections
- Enables governance, storage management, and compliance tracking
- Provides detailed site metadata for capacity planning

**Prerequisites:**
- SharePoint Online Management Shell installed
- SharePoint Administrator or Global Administrator role
- Connected to SharePoint Online admin center

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Retrieves all site collections in tenant
2. Collects title, URL, owner, storage usage, quota, and template
3. Exports detailed site inventory to CSV
4. Reports total site collection count

**Important Notes:**
- Essential for SharePoint governance and capacity planning
- Shows classic and modern sites
- Use for storage quota management and optimization
- Run monthly for site inventory updates
- Identify orphaned sites after employee departures
- Track storage consumption for cost forecasting
- Typical use: annual audits, capacity planning
- Delete unused sites to free up storage`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\SPOSites.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export SharePoint Online Site Inventory
# Generated by PSForge

try {
    Write-Host "Collecting SharePoint Online sites..." -ForegroundColor Cyan
    
    $Sites = Get-SPOSite -Limit All
    
    Write-Host "Found $($Sites.Count) sites" -ForegroundColor Yellow
    
    $SiteReport = foreach ($Site in $Sites) {
        [PSCustomObject]@{
            Title            = $Site.Title
            Url              = $Site.Url
            Owner            = $Site.Owner
            StorageUsageMB   = $Site.StorageUsageCurrent
            StorageQuotaMB   = $Site.StorageQuota
            Template         = $Site.Template
        }
    }
    
    $SiteReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Site inventory exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export site inventory: $_"
}`;
    }
  },

  {
    id: 'spo-export-permissions',
    title: 'Export Site Permissions',
    description: 'Export permissions for a specific SharePoint Online site to CSV',
    category: 'Permissions',
    instructions: `**How This Task Works:**
- Exports detailed site permission assignments
- Supports security audit and access review compliance
- Shows all groups and their member assignments

**Prerequisites:**
- PnP PowerShell module installed
- Site Collection Administrator or Global Administrator role
- Interactive authentication to SharePoint site

**What You Need to Provide:**
- SharePoint site URL
- CSV export file path

**What the Script Does:**
1. Connects to SharePoint site interactively
2. Retrieves all site groups and members
3. Exports group-user mappings to CSV
4. Reports permission structure

**Important Notes:**
- Essential for security audits and access reviews
- Shows all site groups and their members
- Use for quarterly access reviews
- Identify users with excessive permissions
- Run during security audits or employee departures
- Implement principle of least privilege
- Typical use: compliance reviews, security audits
- Revoke access for departed employees immediately`,
    parameters: [
      {
        name: 'siteUrl',
        label: 'Site URL',
        type: 'text',
        required: true,
        placeholder: 'https://contoso.sharepoint.com/sites/Sales',
        helpText: 'Full URL of the SharePoint site'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\SitePermissions.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const siteUrl = escapePowerShellString(params.siteUrl);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Site Permissions
# Generated by PSForge

Connect-PnPOnline -Url "${siteUrl}" -Interactive

try {
    Write-Host "Collecting permissions for: ${siteUrl}" -ForegroundColor Cyan
    
    $Permissions = Get-PnPSiteGroup | ForEach-Object {
        $GroupName = $_.Title
        $Users = Get-PnPGroupMember -Identity $GroupName
        
        foreach ($User in $Users) {
            [PSCustomObject]@{
                GroupName = $GroupName
                UserName  = $User.Title
                LoginName = $User.LoginName
            }
        }
    }
    
    $Permissions | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Permissions exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export permissions: $_"
}`;
    }
  },

  {
    id: 'spo-export-storage-report',
    title: 'Export Storage Report',
    description: 'Export storage usage report for all SharePoint Online sites to CSV',
    category: 'Storage',
    instructions: `**How This Task Works:**
- Exports storage consumption metrics with quota utilization
- Calculates percentage used for each site collection
- Enables capacity planning and cost optimization

**Prerequisites:**
- SharePoint Online Management Shell installed
- SharePoint Administrator or Global Administrator role
- Connected to SharePoint Online admin center

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Retrieves all site collections
2. Calculates storage used, quota, and percentage
3. Exports storage report to CSV
4. Shows quota utilization trends

**Important Notes:**
- Essential for capacity planning and cost management
- Identifies sites nearing quota limits
- Use for proactive quota management
- Run monthly for storage trend analysis
- Plan for storage growth before hitting limits
- Typical use: capacity planning, budget forecasting
- Increase quotas before users are blocked
- Archive or delete old content to reduce costs`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\StorageReport.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Storage Report
# Generated by PSForge

try {
    Write-Host "Collecting storage data..." -ForegroundColor Cyan
    
    $Sites = Get-SPOSite -Limit All
    
    $StorageReport = foreach ($Site in $Sites) {
        $PercentUsed = if ($Site.StorageQuota -gt 0) { 
            [math]::Round(($Site.StorageUsageCurrent / $Site.StorageQuota) * 100, 2) 
        } else { 0 }
        
        [PSCustomObject]@{
            SiteUrl          = $Site.Url
            StorageUsageMB   = $Site.StorageUsageCurrent
            StorageQuotaMB   = $Site.StorageQuota
            PercentUsed      = $PercentUsed
        }
    }
    
    $StorageReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Storage report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export storage report: $_"
}`;
    }
  },

  {
    id: 'spo-export-external-users',
    title: 'Export External Users',
    description: 'Export list of all external users with SharePoint access to CSV',
    category: 'Security',
    instructions: `**How This Task Works:**
- Exports all external guest users with SharePoint access
- Supports security compliance and external collaboration governance
- Identifies all guest accounts for access reviews

**Prerequisites:**
- SharePoint Online Management Shell installed
- SharePoint Administrator or Global Administrator role
- Connected to SharePoint Online admin center

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Retrieves all external users in tenant
2. Collects display name, email, accepted status, and creation date
3. Exports external user inventory to CSV
4. Reports total external user count

**Important Notes:**
- Essential for security compliance and guest access management
- Shows all external collaborators with SharePoint access
- Use for quarterly external access reviews
- Identify inactive external accounts for removal
- Required for GDPR and compliance audits
- Typical use: security reviews, compliance reporting
- Revoke access for ended partnerships immediately
- Monitor external access to sensitive content`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ExternalUsers.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export External Users
# Generated by PSForge

try {
    Write-Host "Collecting external users..." -ForegroundColor Cyan
    
    $ExternalUsers = Get-SPOExternalUser -PageSize 50
    
    Write-Host "Found $($ExternalUsers.Count) external users" -ForegroundColor Yellow
    
    $UserReport = foreach ($User in $ExternalUsers) {
        [PSCustomObject]@{
            DisplayName      = $User.DisplayName
            Email            = $User.Email
            AcceptedAs       = $User.AcceptedAs
            WhenCreated      = $User.WhenCreated
        }
    }
    
    $UserReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ External users exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export external users: $_"
}`;
    }
  },

  {
    id: 'spo-export-sharing-links',
    title: 'Export Sharing Links Report',
    description: 'Export all sharing links from a SharePoint site to CSV',
    category: 'Sharing',
    instructions: `**How This Task Works:**
- Exports all sharing links created for site documents
- Audits external sharing for data loss prevention compliance
- Identifies anonymous and organization-wide links

**Prerequisites:**
- PnP PowerShell module installed
- Site Collection Administrator or Global Administrator role
- Interactive authentication to SharePoint site

**What You Need to Provide:**
- SharePoint site URL
- CSV export file path

**What the Script Does:**
1. Connects to SharePoint site interactively
2. Scans all documents in default library
3. Retrieves sharing links for each file
4. Exports link inventory to CSV

**Important Notes:**
- Essential for security audits and DLP compliance
- Shows anonymous and organization-wide links
- Use for quarterly sharing audits
- Identify overshared sensitive content
- Typical use: security reviews, compliance audits
- Revoke unnecessary sharing links
- Block anonymous sharing for sensitive sites
- Monitor for data exfiltration risks`,
    parameters: [
      {
        name: 'siteUrl',
        label: 'Site URL',
        type: 'text',
        required: true,
        placeholder: 'https://contoso.sharepoint.com/sites/Sales',
        helpText: 'Full URL of the SharePoint site'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\SharingLinks.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const siteUrl = escapePowerShellString(params.siteUrl);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Sharing Links
# Generated by PSForge

Connect-PnPOnline -Url "${siteUrl}" -Interactive

try {
    Write-Host "Collecting sharing links..." -ForegroundColor Cyan
    
    $Files = Get-PnPListItem -List "Documents" -PageSize 500
    
    $SharingReport = foreach ($File in $Files) {
        $Links = Get-PnPFileSharingLink -Identity $File.Id -ErrorAction SilentlyContinue
        
        foreach ($Link in $Links) {
            [PSCustomObject]@{
                FileName     = $File["FileLeafRef"]
                LinkType     = $Link.ShareLinkType
                CreatedBy    = $Link.CreatedBy
                CreatedOn    = $Link.CreatedOn
            }
        }
    }
    
    $SharingReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Sharing links exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export sharing links: $_"
}`;
    }
  },
  {id:'spo-create-site',title:'Create Site Collection',description:'Create new SharePoint site collection',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true,placeholder:'https://tenant.sharepoint.com/sites/NewSite'},{name:'title',label:'Site Title',type:'text',required:true},{name:'owner',label:'Owner Email',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{New-SPOSite -Url "${escapePowerShellString(p.url)}" -Title "${escapePowerShellString(p.title)}" -Owner "${escapePowerShellString(p.owner)}" -StorageQuota 1024 -Template STS#3;Write-Host "✓ Site created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-delete-site',title:'Delete Site Collection',description:'Remove SharePoint site',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Remove-SPOSite -Identity "${escapePowerShellString(p.url)}" -Confirm:$false;Write-Host "✓ Site deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-restore-site',title:'Restore Deleted Site',description:'Recover site from recycle bin',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Restore-SPODeletedSite -Identity "${escapePowerShellString(p.url)}";Write-Host "✓ Site restored" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-set-quota',title:'Set Site Storage Quota',description:'Configure site storage limit',category:'Storage',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'quotaGB',label:'Quota (GB)',type:'number',required:true,defaultValue:25}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity "${escapePowerShellString(p.url)}" -StorageQuota $((${p.quotaGB})*1024);Write-Host "✓ Quota set to ${p.quotaGB}GB" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-add-admin',title:'Add Site Collection Admin',description:'Grant admin access to site',category:'Permissions',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'userEmail',label:'User Email',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOUser -Site "${escapePowerShellString(p.url)}" -LoginName "${escapePowerShellString(p.userEmail)}" -IsSiteCollectionAdmin $true;Write-Host "✓ Admin added" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-remove-admin',title:'Remove Site Collection Admin',description:'Revoke admin access',category:'Permissions',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'userEmail',label:'User Email',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOUser -Site "${escapePowerShellString(p.url)}" -LoginName "${escapePowerShellString(p.userEmail)}" -IsSiteCollectionAdmin $false;Write-Host "✓ Admin removed" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-disable-external-sharing',title:'Disable External Sharing',description:'Block external access to site',category:'Security',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity "${escapePowerShellString(p.url)}" -SharingCapability Disabled;Write-Host "✓ External sharing disabled" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-enable-versioning',title:'Enable Document Versioning',description:'Turn on version history',category:'Storage',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'versions',label:'Max Versions',type:'number',required:false,defaultValue:500}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Set-PnPList -Identity "Documents" -EnableVersioning $true -MajorVersions ${p.versions};Write-Host "✓ Versioning enabled (${p.versions} versions)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-export-users',title:'Export Site Users',description:'List all users with permissions',category:'Permissions',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Get-SPOUser -Site "${escapePowerShellString(p.url)}"|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Users exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-export-groups',title:'Export Site Groups',description:'List SharePoint groups',category:'Permissions',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Get-PnPGroup|Select Title,LoginName,Owner|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Groups exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-break-inheritance',title:'Break Permission Inheritance',description:'Stop inheriting parent permissions',category:'Permissions',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Set-PnPWeb -BreakRoleInheritance -CopyRoleAssignments;Write-Host "✓ Permission inheritance broken" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-hub-associate',title:'Associate Site to Hub',description:'Join site to hub site',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'hubUrl',label:'Hub Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Add-SPOHubSiteAssociation -Site "${escapePowerShellString(p.url)}" -HubSite "${escapePowerShellString(p.hubUrl)}";Write-Host "✓ Site associated to hub" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-hub-create',title:'Register Hub Site',description:'Convert site to hub',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'title',label:'Hub Title',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Register-SPOHubSite -Site "${escapePowerShellString(p.url)}" -Title "${escapePowerShellString(p.title)}";Write-Host "✓ Hub site registered" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-set-title',title:'Update Site Title',description:'Change site display name',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'title',label:'New Title',type:'text',required:true}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Set-PnPWeb -Title "${escapePowerShellString(p.title)}";Write-Host "✓ Site title updated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-lock-site',title:'Lock Site',description:'Prevent changes to site',category:'Security',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity "${escapePowerShellString(p.url)}" -LockState ReadOnly;Write-Host "✓ Site locked (read-only)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-unlock-site',title:'Unlock Site',description:'Re-enable site editing',category:'Security',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity "${escapePowerShellString(p.url)}" -LockState Unlock;Write-Host "✓ Site unlocked" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-modern-ui',title:'Enable Modern UI',description:'Switch to modern experience',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Set-PnPWeb -QuickLaunchEnabled $false;Enable-PnPFeature -Identity "E3540C7D-6BEA-403C-A224-1A12EAFEE4C4" -Scope Site;Write-Host "✓ Modern UI enabled" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-search-reindex',title:'Request Search Reindex',description:'Trigger full site reindex',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Request-PnPReIndexWeb;Write-Host "✓ Reindex requested" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-audit-permissions',title:'Export Permission Report',description:'Detailed permissions audit',category:'Permissions',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{$Perms=Get-PnPList|%{Get-PnPListItem -List $_.Title|%{Get-PnPProperty -ClientObject $_ -Property RoleAssignments}};$Perms|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Permissions exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-bulk-upload',title:'Bulk Upload Files',description:'Upload folder to library',category:'Storage',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'folderPath',label:'Local Folder',type:'text',required:true,placeholder:'C:\\\\Files'},{name:'library',label:'Library Name',type:'text',required:true,defaultValue:'Documents'}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Add-PnPFolder -Name "Upload" -Folder "${p.library}";Get-ChildItem "${escapePowerShellString(p.folderPath)}" -Recurse|%{Add-PnPFile -Path $_.FullName -Folder "${p.library}/Upload"};Write-Host "✓ Files uploaded" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-guest-expiration',title:'Set Guest Link Expiration',description:'Configure link expiry days',category:'Sharing',parameters:[{name:'days',label:'Expiration Days',type:'number',required:true,defaultValue:30}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOTenant -ExternalUserExpirationRequired $true -ExternalUserExpireInDays ${p.days};Write-Host "✓ Guest links expire in ${p.days} days" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-disable-download',title:'Disable File Downloads',description:'Block downloads for site',category:'Security',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{Set-SPOSite -Identity "${escapePowerShellString(p.url)}" -DisableFlows RelaxationEnabled;Write-Host "✓ Downloads disabled" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-export-files',title:'Export File Inventory',description:'List all files in site',category:'Storage',parameters:[{name:'url',label:'Site URL',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Get-PnPListItem -List "Documents" -PageSize 5000|Select @{N='Name';E={$_["FileLeafRef"]}},@{N='Size';E={$_["File_x0020_Size"]}},@{N='Modified';E={$_["Modified"]}}|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ File inventory exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-block-filetypes',title:'Block File Types',description:'Prevent upload of extensions',category:'Security',parameters:[{name:'extensions',label:'Extensions',type:'text',required:true,placeholder:'.exe,.bat,.cmd'}],scriptTemplate:p=>`Connect-SPOService -Url https://tenant-admin.sharepoint.com\ntry{$BlockedFileTypes="${escapePowerShellString(p.extensions)}";Set-SPOTenant -ExcludedFileExtensionsForSyncClient $BlockedFileTypes;Write-Host "✓ File types blocked: ${p.extensions}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'spo-clear-cache',title:'Clear Site Cache',description:'Force site cache refresh',category:'Site Management',parameters:[{name:'url',label:'Site URL',type:'text',required:true}],scriptTemplate:p=>`Connect-PnPOnline -Url "${escapePowerShellString(p.url)}" -Interactive\ntry{Clear-PnPMicrosoft365GroupFileVersionBatchDeleteJob;Write-Host "✓ Cache cleared" -ForegroundColor Green}catch{Write-Error $_}`}
];

export const sharePointOnlineCategories = [
  'Site Management',
  'Permissions',
  'Storage',
  'Security',
  'Sharing'
];
