import { escapePowerShellString } from './powershell-utils';

export interface TeamsParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface TeamsTask {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: TeamsParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const teamsTasks: TeamsTask[] = [
  {
    id: 'teams-export-teams-list',
    title: 'Export Teams List',
    description: 'Export list of all Microsoft Teams to CSV',
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Exports complete inventory of all Microsoft Teams
- Supports organization-wide documentation
- Essential for Teams governance

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Team.ReadBasic.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all Teams in organization
3. Extracts name, ID, visibility, and description
4. Exports comprehensive report to CSV

**Important Notes:**
- Essential for Teams governance and inventory
- Shows Public vs Private teams
- Critical for compliance audits
- Use for identifying unused or duplicate teams
- Large organizations (100+ teams) may take time
- Export includes all teams regardless of membership`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\Teams.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Microsoft Teams List
# Generated by PSForge

Connect-MgGraph -Scopes "Team.ReadBasic.All"

try {
    Write-Host "Collecting Microsoft Teams..." -ForegroundColor Cyan
    
    $Teams = Get-MgTeam -All
    
    Write-Host "Found $($Teams.Count) teams" -ForegroundColor Yellow
    
    $TeamsReport = foreach ($Team in $Teams) {
        [PSCustomObject]@{
            DisplayName      = $Team.DisplayName
            Id               = $Team.Id
            Visibility       = $Team.Visibility
            Description      = $Team.Description
        }
    }
    
    $TeamsReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Teams exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export teams: $_"
}`;
    }
  },

  {
    id: 'teams-export-members',
    title: 'Export Team Members',
    description: 'Export members of a specific team to CSV',
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Exports membership roster for a specific Team
- Includes roles (Owner vs Member)
- Supports access reviews and documentation

**Prerequisites:**
- Microsoft.Graph PowerShell module
- TeamMember.Read.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Retrieves all team members
4. Extracts member details and roles
5. Exports membership report to CSV

**Important Notes:**
- Critical for access governance and reviews
- Shows member vs owner roles
- Essential for team audit documentation
- Includes UPN for easy identification
- Use for SOC 2 and compliance audits
- Export limited to one team at a time`,
    parameters: [
      {
        name: 'teamName',
        label: 'Team Name',
        type: 'text',
        required: true,
        placeholder: 'Sales Team',
        helpText: 'Name of the team'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\TeamMembers.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const teamName = escapePowerShellString(params.teamName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Team Members
# Generated by PSForge

Connect-MgGraph -Scopes "TeamMember.Read.All"

try {
    Write-Host "Finding team: ${teamName}" -ForegroundColor Cyan
    
    $Team = Get-MgTeam -Filter "displayName eq '${teamName}'" | Select-Object -First 1
    
    if (-not $Team) {
        throw "Team not found: ${teamName}"
    }
    
    $Members = Get-MgTeamMember -TeamId $Team.Id
    
    Write-Host "Found $($Members.Count) members" -ForegroundColor Yellow
    
    $MemberReport = foreach ($Member in $Members) {
        [PSCustomObject]@{
            DisplayName  = $Member.DisplayName
            UserPrincipalName = $Member.AdditionalProperties.userPrincipalName
            Roles        = ($Member.Roles -join ", ")
        }
    }
    
    $MemberReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Team members exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export team members: $_"
}`;
    }
  },

  {
    id: 'teams-export-channels',
    title: 'Export Team Channels',
    description: 'Export channels from a specific team to CSV',
    category: 'Channel Management',
    instructions: `**How This Task Works:**
- Exports all channels from a specific Team
- Shows channel structure and membership types
- Supports documentation and governance

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Channel.ReadBasic.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Retrieves all channels
4. Extracts channel details and membership type
5. Exports channel report to CSV

**Important Notes:**
- Shows Standard vs Private channels
- Essential for Teams structure documentation
- Use to identify unused channels
- MembershipType determines access control
- Private channels have restricted membership
- General channel always included (cannot be deleted)`,
    parameters: [
      {
        name: 'teamName',
        label: 'Team Name',
        type: 'text',
        required: true,
        placeholder: 'Sales Team',
        helpText: 'Name of the team'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\Channels.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const teamName = escapePowerShellString(params.teamName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Team Channels
# Generated by PSForge

Connect-MgGraph -Scopes "Channel.ReadBasic.All"

try {
    Write-Host "Finding team: ${teamName}" -ForegroundColor Cyan
    
    $Team = Get-MgTeam -Filter "displayName eq '${teamName}'" | Select-Object -First 1
    
    if (-not $Team) {
        throw "Team not found: ${teamName}"
    }
    
    $Channels = Get-MgTeamChannel -TeamId $Team.Id
    
    Write-Host "Found $($Channels.Count) channels" -ForegroundColor Yellow
    
    $ChannelReport = foreach ($Channel in $Channels) {
        [PSCustomObject]@{
            DisplayName      = $Channel.DisplayName
            Description      = $Channel.Description
            MembershipType   = $Channel.MembershipType
        }
    }
    
    $ChannelReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Channels exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export channels: $_"
}`;
    }
  },

  {
    id: 'teams-export-guest-users',
    title: 'Export Guest Users in Teams',
    description: 'Export list of all guest users across all teams to CSV',
    category: 'Reporting',
    instructions: `**How This Task Works:**
- Exports all guest users in your organization
- Supports security audits and compliance
- Essential for external access governance

**Prerequisites:**
- Microsoft.Graph PowerShell module
- User.Read.All and TeamMember.Read.All permissions
- Connected to Microsoft Graph

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all guest users (userType = Guest)
3. Extracts guest details and creation date
4. Exports guest user report to CSV

**Important Notes:**
- Critical for security and compliance audits
- Shows all external collaborators
- Essential for guest access governance
- Identifies when guests were added
- Use for access reviews and cleanup
- Helps enforce least privilege access`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\TeamsGuests.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Guest Users in Teams
# Generated by PSForge

Connect-MgGraph -Scopes "User.Read.All", "TeamMember.Read.All"

try {
    Write-Host "Collecting guest users..." -ForegroundColor Cyan
    
    $Guests = Get-MgUser -Filter "userType eq 'Guest'" -All
    
    Write-Host "Found $($Guests.Count) guest users" -ForegroundColor Yellow
    
    $GuestReport = foreach ($Guest in $Guests) {
        [PSCustomObject]@{
            DisplayName       = $Guest.DisplayName
            UserPrincipalName = $Guest.UserPrincipalName
            Mail              = $Guest.Mail
            CreatedDateTime   = $Guest.CreatedDateTime
        }
    }
    
    $GuestReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Guest users exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export guest users: $_"
}`;
    }
  },

  {
    id: 'teams-export-policies',
    title: 'Export Teams Policies',
    description: 'Export Teams messaging and meeting policies to CSV',
    category: 'Policy Management',
    instructions: `**How This Task Works:**
- Exports Teams policies for governance
- Supports documentation and audits
- Ensures consistent policy enforcement across organization

**Prerequisites:**
- Microsoft Teams PowerShell module installed
- Teams Administrator role
- Must manually connect to Teams first: Connect-MicrosoftTeams

**What You Need to Provide:**
- CSV export file path
- Prior connection to Microsoft Teams

**What the Script Does:**
1. Retrieves messaging policies from connected Teams session
2. Extracts policy identity and description
3. Exports policy report to CSV

**Important Notes:**
- You must connect to Teams BEFORE running this script
- Essential for Teams governance documentation
- Shows all configured messaging policies
- Use for policy standardization
- Critical for compliance audits
- Expand script to include meeting/calling policies
- Helps identify policy conflicts`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\TeamsPolicies.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Teams Policies
# Generated by PSForge

try {
    Write-Host "Collecting Teams messaging policies..." -ForegroundColor Cyan
    
    $MessagingPolicies = Get-CsTeamsMessagingPolicy
    
    $PolicyReport = foreach ($Policy in $MessagingPolicies) {
        [PSCustomObject]@{
            PolicyType       = "Messaging"
            Identity         = $Policy.Identity
            Description      = $Policy.Description
        }
    }
    
    $PolicyReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Teams policies exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export policies: $_"
}`;
    }
  },

  // Additional Teams Tasks
  { 
    id: 'teams-create-team', 
    title: 'Create New Team', 
    description: 'Create a new Microsoft Team with specified settings', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Creates a new Microsoft Team with customized settings
- Provisions Microsoft 365 Group and enables Team features
- Configures privacy level (Public or Private)

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Group.ReadWrite.All and Team.Create permissions
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- Optional: Team description
- Privacy setting (Public or Private)

**What the Script Does:**
1. Connects to Microsoft Graph with required permissions
2. Creates Microsoft 365 Group with specified settings
3. Enables Team features on the group
4. Configures team privacy level
5. Reports team creation with ID

**Important Notes:**
- Essential for team provisioning and onboarding
- Private teams require invitation to access
- Public teams are discoverable by all users
- Auto-creates General channel by default
- Team name must be unique in organization
- Use for project teams, departments, or collaboration spaces
- Typical use: new project kickoffs, department reorganization
- Enable teams-based collaboration quickly`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Name for the new team'}, {name: 'teamDescription', label: 'Description', type: 'textarea', required: false, placeholder: 'Team for sales department', helpText: 'Team description'}, {name: 'privacy', label: 'Privacy', type: 'select', required: true, options: [{value: 'Private', label: 'Private'}, {value: 'Public', label: 'Public'}], helpText: 'Team visibility'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const teamDescription = params.teamDescription ? escapePowerShellString(params.teamDescription) : ''; const privacy = params.privacy; return `# Create New Team\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Group.ReadWrite.All", "Team.Create"\n\ntry {\n    Write-Host "Creating team: ${teamName}" -ForegroundColor Cyan\n    \n    $GroupParams = @{\n        DisplayName = "${teamName}"\n        ${teamDescription ? `Description = "${teamDescription}"` : ''}\n        MailEnabled = \\$true\n        MailNickname = "${teamName.toLowerCase().replace(/\\s+/g, '')}"\n        SecurityEnabled = \\$false\n        GroupTypes = @("Unified")\n        Visibility = "${privacy}"\n    }\n    \n    $Group = New-MgGroup -BodyParameter $GroupParams\n    \n    $TeamParams = @{\n        "template@odata.bind" = "https://graph.microsoft.com/v1.0/teamsTemplates('standard')"\n    }\n    \n    $Team = New-MgTeam -GroupId $Group.Id -BodyParameter $TeamParams\n    \n    Write-Host "✓ Team created successfully" -ForegroundColor Green\n    Write-Host "  Team Name: ${teamName}" -ForegroundColor Yellow\n    Write-Host "  Team ID: $($Team.Id)" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to create team: $_"\n}`;}},

  {
    id: 'teams-delete-team', 
    title: 'Delete Team', 
    description: 'Permanently delete a Microsoft Team', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Permanently deletes a Microsoft Team and its underlying Group
- Removes all team content including channels and files
- Cannot be undone without backup restoration

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Group.ReadWrite.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name to delete

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Permanently deletes the Microsoft 365 Group
4. Confirms successful deletion

**Important Notes:**
- DESTRUCTIVE OPERATION - cannot be easily reversed
- Deletes all team content and conversations
- Consider archiving instead of deleting
- SharePoint site deletion may be delayed
- Use for cleanup of obsolete project teams
- Recommend backing up important data first
- Typical use: project completion, team consolidation
- Verify team name carefully before executing`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Old Project Team', helpText: 'Team to delete'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); return `# Delete Team\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Group.ReadWrite.All"\n\ntry {\n    Write-Host "Deleting team: ${teamName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    Remove-MgGroup -GroupId $Team.Id\n    \n    Write-Host "✓ Team deleted successfully" -ForegroundColor Green\n    Write-Host "  Team: ${teamName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to delete team: $_"\n}`;}},

  {
    id: 'teams-add-member', 
    title: 'Add Team Member', 
    description: 'Add a user to a Microsoft Team', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Adds a user to a Microsoft Team with specified role
- Grants access to all team channels and content
- Assigns either Member or Owner role

**Prerequisites:**
- Microsoft.Graph PowerShell module
- TeamMember.ReadWrite.All and User.Read.All permissions
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- User email address
- Role (Member or Owner)

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Looks up user by email address
4. Adds user to team with specified role
5. Confirms successful addition

**Important Notes:**
- Owners can manage team settings and members
- Members have standard collaboration access
- User must exist in Azure AD
- Grants immediate access to team content
- Use for onboarding and team expansion
- Typical use: new hire onboarding, project staffing
- Consider bulk operations for multiple users
- Users receive email notification of addition`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Target team'}, {name: 'userEmail', label: 'User Email', type: 'text', required: true, placeholder: 'user@domain.com', helpText: 'User to add'}, {name: 'role', label: 'Role', type: 'select', required: true, options: [{value: 'member', label: 'Member'}, {value: 'owner', label: 'Owner'}], helpText: 'User role'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const userEmail = escapePowerShellString(params.userEmail); const role = params.role; return `# Add Team Member\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "TeamMember.ReadWrite.All", "User.Read.All"\n\ntry {\n    Write-Host "Adding ${userEmail} to team: ${teamName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $User = Get-MgUser -Filter "userPrincipalName eq '${userEmail}'" | Select-Object -First 1\n    \n    if (-not $User) {\n        throw "User not found: ${userEmail}"\n    }\n    \n    $MemberParams = @{\n        "@odata.type" = "#microsoft.graph.aadUserConversationMember"\n        Roles = @(${role === 'owner' ? '"owner"' : ''})\n        "User@odata.bind" = "https://graph.microsoft.com/v1.0/users/$($User.Id)"\n    }\n    \n    New-MgTeamMember -TeamId $Team.Id -BodyParameter $MemberParams\n    \n    Write-Host "✓ User added successfully" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    Write-Host "  Role: ${role}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to add member: $_"\n}`;}},

  {
    id: 'teams-remove-member', 
    title: 'Remove Team Member', 
    description: 'Remove a user from a Microsoft Team', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Removes a user from a Microsoft Team
- Revokes access to all team channels and content
- User loses visibility of team and conversations

**Prerequisites:**
- Microsoft.Graph PowerShell module
- TeamMember.ReadWrite.All and User.Read.All permissions
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- User email address to remove

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Locates user in team membership
4. Removes user from team
5. Confirms successful removal

**Important Notes:**
- Immediately revokes team access
- User can no longer see team in Teams app
- Previous contributions remain visible
- Use for offboarding and access control
- Cannot remove last owner (requires reassignment first)
- Typical use: employee departures, role changes
- Consider archiving user content before removal
- User loses access to shared team files`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Target team'}, {name: 'userEmail', label: 'User Email', type: 'text', required: true, placeholder: 'user@domain.com', helpText: 'User to remove'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const userEmail = escapePowerShellString(params.userEmail); return `# Remove Team Member\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "TeamMember.ReadWrite.All", "User.Read.All"\n\ntry {\n    Write-Host "Removing ${userEmail} from team: ${teamName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $Members = Get-MgTeamMember -TeamId $Team.Id -All\n    $Member = $Members | Where-Object { $_.AdditionalProperties.userPrincipalName -eq '${userEmail}' } | Select-Object -First 1\n    \n    if (-not $Member) {\n        throw "Member not found: ${userEmail}"\n    }\n    \n    Remove-MgTeamMember -TeamId $Team.Id -ConversationMemberId $Member.Id\n    \n    Write-Host "✓ Member removed successfully" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to remove member: $_"\n}`;}},

  {
    id: 'teams-create-channel', 
    title: 'Create Team Channel', 
    description: 'Create a new channel in a Microsoft Team', 
    category: 'Channel Management',
    instructions: `**How This Task Works:**
- Creates a new standard channel within an existing team
- Provides dedicated space for topic-specific conversations
- All team members have access by default

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Channel.Create permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- New channel name
- Optional: Channel description

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Creates new standard channel
4. Sets channel name and description
5. Confirms successful creation

**Important Notes:**
- Creates standard (not private) channel
- All team members can access
- Auto-creates dedicated SharePoint folder
- Use for organizing team discussions by topic
- Cannot duplicate existing channel names
- Typical use: new project phases, topic areas
- Consider channel naming conventions
- Limit channels to avoid fragmentation (5-10 optimal)`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Target team'}, {name: 'channelName', label: 'Channel Name', type: 'text', required: true, placeholder: 'Regional Sales', helpText: 'New channel name'}, {name: 'channelDescription', label: 'Channel Description', type: 'textarea', required: false, placeholder: 'Channel for regional sales discussions', helpText: 'Channel description'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const channelName = escapePowerShellString(params.channelName); const channelDescription = params.channelDescription ? escapePowerShellString(params.channelDescription) : ''; return `# Create Team Channel\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Channel.Create"\n\ntry {\n    Write-Host "Creating channel: ${channelName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $ChannelParams = @{\n        DisplayName = "${channelName}"\n        ${channelDescription ? `Description = "${channelDescription}"` : ''}\n    }\n    \n    $Channel = New-MgTeamChannel -TeamId $Team.Id -BodyParameter $ChannelParams\n    \n    Write-Host "✓ Channel created successfully" -ForegroundColor Green\n    Write-Host "  Channel: ${channelName}" -ForegroundColor Yellow\n    Write-Host "  Team: ${teamName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to create channel: $_"\n}`;}},

  {
    id: 'teams-delete-channel', 
    title: 'Delete Team Channel', 
    description: 'Delete a channel from a Microsoft Team', 
    category: 'Channel Management',
    instructions: `**How This Task Works:**
- Permanently deletes a channel from a Microsoft Team
- Removes all channel content and conversation history
- Cannot delete the General channel

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Channel.Delete.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- Channel name to delete

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Locates channel within team
4. Permanently deletes the channel
5. Confirms successful deletion

**Important Notes:**
- DESTRUCTIVE OPERATION - cannot be easily reversed
- General channel cannot be deleted
- All channel content and files are removed
- Consider archiving important conversations first
- Use for cleanup of obsolete project channels
- Typical use: project completion, channel consolidation
- Verify channel name carefully before executing
- Users lose access to channel content immediately`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Target team'}, {name: 'channelName', label: 'Channel Name', type: 'text', required: true, placeholder: 'Old Project Channel', helpText: 'Channel to delete'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const channelName = escapePowerShellString(params.channelName); return `# Delete Team Channel\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Channel.Delete.All"\n\ntry {\n    Write-Host "Deleting channel: ${channelName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $Channel = Get-MgTeamChannel -TeamId $Team.Id -Filter "displayName eq '${channelName}'" | Select-Object -First 1\n    \n    if (-not $Channel) {\n        throw "Channel not found: ${channelName}"\n    }\n    \n    Remove-MgTeamChannel -TeamId $Team.Id -ChannelId $Channel.Id\n    \n    Write-Host "✓ Channel deleted successfully" -ForegroundColor Green\n    Write-Host "  Channel: ${channelName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to delete channel: $_"\n}`;}},

  {
    id: 'teams-update-settings', 
    title: 'Update Team Settings', 
    description: 'Update team settings like guest permissions and member capabilities', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Updates team-level settings and permissions
- Controls guest access and member capabilities
- Configures collaboration features

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Team.ReadWrite.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- Guest access preference (checkbox)
- Member channel creation permission (checkbox)

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Updates guest settings configuration
4. Updates member settings configuration
5. Confirms settings update

**Important Notes:**
- Controls team collaboration permissions
- Guest settings affect external collaboration
- Member settings control user capabilities
- Changes apply immediately to all users
- Use for security and governance control
- Typical use: tightening security, enabling collaboration
- Balance between security and productivity
- Document policy changes for compliance`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Team to update'}, {name: 'allowGuests', label: 'Allow Guest Users', type: 'checkbox', required: false, defaultValue: false, helpText: 'Enable guest access'}, {name: 'allowMemberCreateChannels', label: 'Members Can Create Channels', type: 'checkbox', required: false, defaultValue: true, helpText: 'Allow members to create channels'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const allowGuests = params.allowGuests === true; const allowMemberChannels = params.allowMemberCreateChannels !== false; return `# Update Team Settings\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Team.ReadWrite.All"\n\ntry {\n    Write-Host "Updating team settings: ${teamName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $SettingsParams = @{\n        GuestSettings = @{\n            AllowCreateUpdateChannels = \\$${allowGuests}\n            AllowDeleteChannels = \\$false\n        }\n        MemberSettings = @{\n            AllowCreateUpdateChannels = \\$${allowMemberChannels}\n            AllowDeleteChannels = \\$false\n            AllowAddRemoveApps = \\$true\n        }\n    }\n    \n    Update-MgTeam -TeamId $Team.Id -BodyParameter $SettingsParams\n    \n    Write-Host "✓ Team settings updated" -ForegroundColor Green\n    Write-Host "  Allow Guests: ${allowGuests}" -ForegroundColor Yellow\n    Write-Host "  Members Create Channels: ${allowMemberChannels}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to update team settings: $_"\n}`;}},

  {
    id: 'teams-archive-team', 
    title: 'Archive Team', 
    description: 'Archive a Microsoft Team to make it read-only', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Archives a team making it read-only
- Preserves all content and conversation history
- Users can view but not modify content

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Team.ReadWrite.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name to archive

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Executes archive operation
4. Confirms archive completion

**Important Notes:**
- Makes team read-only (view only)
- Preserves all content for compliance
- Preferred over deletion for completed projects
- Can be unarchived if needed later
- Reduces license costs while retaining data
- Use for completed projects and inactive teams
- Typical use: project completion, retention compliance
- Better alternative to deletion for compliance`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Completed Project Team', helpText: 'Team to archive'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); return `# Archive Team\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Team.ReadWrite.All"\n\ntry {\n    Write-Host "Archiving team: ${teamName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    Invoke-MgArchiveTeam -TeamId $Team.Id\n    \n    Write-Host "✓ Team archived successfully" -ForegroundColor Green\n    Write-Host "  Team: ${teamName}" -ForegroundColor Yellow\n    Write-Host "Note: Team is now read-only" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to archive team: $_"\n}`;}},

  {
    id: 'teams-unarchive-team', 
    title: 'Unarchive Team', 
    description: 'Restore an archived Team to active status', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Restores an archived team to active status
- Re-enables full collaboration capabilities
- Retains all historical content

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Team.ReadWrite.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name to unarchive

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds archived team by display name
3. Executes unarchive operation
4. Confirms restore to active status

**Important Notes:**
- Restores full read-write access
- All previous content remains intact
- Users can resume collaboration immediately
- Use for reactivating completed projects
- Typical use: project revival, seasonal teams
- Consider if new team is better than unarchive
- May take a few minutes to complete
- All members regain full access`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Archived Team', helpText: 'Team to unarchive'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); return `# Unarchive Team\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Team.ReadWrite.All"\n\ntry {\n    Write-Host "Unarchiving team: ${teamName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    Invoke-MgUnarchiveTeam -TeamId $Team.Id\n    \n    Write-Host "✓ Team unarchived successfully" -ForegroundColor Green\n    Write-Host "  Team: ${teamName}" -ForegroundColor Yellow\n    Write-Host "Note: Team is now active" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to unarchive team: $_"\n}`;}},

  {
    id: 'teams-clone-team', 
    title: 'Clone Team', 
    description: 'Create a copy of an existing team with settings and channels', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Creates a copy of an existing team
- Duplicates settings, channels, tabs, and apps
- Optionally copies team members

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Team.Create and Group.ReadWrite.All permissions
- Connected to Microsoft Graph

**What You Need to Provide:**
- Source team name to clone
- New team name for the clone

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds source team by display name
3. Initiates clone operation with all components
4. Creates new team with copied structure
5. Confirms clone initiation

**Important Notes:**
- Cloning is asynchronous (takes several minutes)
- Copies channels, tabs, settings, apps, and members
- Does not copy conversation history
- Use for recurring projects and templates
- Typical use: quarterly projects, department templates
- New team gets same structure as original
- Members are copied but may need re-permission
- Excellent for project templates and standardization`,
    parameters: [{name: 'sourceTeamName', label: 'Source Team Name', type: 'text', required: true, placeholder: 'Q1 Project', helpText: 'Team to clone'}, {name: 'newTeamName', label: 'New Team Name', type: 'text', required: true, placeholder: 'Q2 Project', helpText: 'Name for cloned team'}], scriptTemplate: (params) => { const sourceTeamName = escapePowerShellString(params.sourceTeamName); const newTeamName = escapePowerShellString(params.newTeamName); return `# Clone Team\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Team.Create", "Group.ReadWrite.All"\n\ntry {\n    Write-Host "Cloning team: ${sourceTeamName}" -ForegroundColor Cyan\n    \n    $SourceTeam = Get-MgGroup -Filter "displayName eq '${sourceTeamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $SourceTeam) {\n        throw "Source team not found: ${sourceTeamName}"\n    }\n    \n    $CloneParams = @{\n        DisplayName = "${newTeamName}"\n        Description = "Cloned from ${sourceTeamName}"\n        MailNickname = "${newTeamName.toLowerCase().replace(/\\s+/g, '')}"\n        PartsToClone = "apps,tabs,settings,channels,members"\n        Visibility = "private"\n    }\n    \n    $CloneOperation = Invoke-MgCloneTeam -TeamId $SourceTeam.Id -BodyParameter $CloneParams\n    \n    Write-Host "✓ Team clone initiated" -ForegroundColor Green\n    Write-Host "  New Team: ${newTeamName}" -ForegroundColor Yellow\n    Write-Host "Note: Cloning may take several minutes" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to clone team: $_"\n}`;}},

  {
    id: 'teams-export-messages', 
    title: 'Export Team Messages', 
    description: 'Export team channel messages for compliance or archival', 
    category: 'Reporting',
    instructions: `**How This Task Works:**
- Exports all channel messages from a team
- Saves messages in JSON format for compliance
- Supports eDiscovery and archival requirements

**Prerequisites:**
- Microsoft.Graph PowerShell module
- ChannelMessage.Read.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- Export file path (JSON format)

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Retrieves all channels in team
4. Collects all messages from each channel
5. Exports messages to JSON file

**Important Notes:**
- Essential for compliance and eDiscovery
- Exports all channel conversations
- JSON format for easy parsing
- Large teams may take significant time
- Use for legal holds and audits
- Typical use: compliance, litigation, archival
- Consider message retention policies
- Excludes private chat messages`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Team to export messages from'}, {name: 'exportPath', label: 'Export Path', type: 'text', required: true, placeholder: 'C:\\Exports\\TeamMessages.json', helpText: 'Export file path'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const exportPath = escapePowerShellString(params.exportPath); return `# Export Team Messages\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "ChannelMessage.Read.All"\n\ntry {\n    Write-Host "Exporting messages from: ${teamName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $Channels = Get-MgTeamChannel -TeamId $Team.Id\n    $AllMessages = @()\n    \n    foreach ($Channel in $Channels) {\n        $Messages = Get-MgTeamChannelMessage -TeamId $Team.Id -ChannelId $Channel.Id\n        $AllMessages += $Messages\n    }\n    \n    $AllMessages | ConvertTo-Json -Depth 10 | Out-File "${exportPath}"\n    \n    Write-Host "✓ Messages exported successfully" -ForegroundColor Green\n    Write-Host "  Total Messages: $($AllMessages.Count)" -ForegroundColor Yellow\n    Write-Host "  Export Path: ${exportPath}" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to export messages: $_"\n}`;}},

  {
    id: 'teams-create-meeting-policy', 
    title: 'Create Teams Meeting Policy', 
    description: 'Create a custom meeting policy for controlling meeting features', 
    category: 'Policy Management',
    instructions: `**How This Task Works:**
- Creates custom meeting policy for Teams
- Controls meeting features and capabilities
- Enforces meeting governance and security

**Prerequisites:**
- Teams PowerShell module
- Teams Administrator role
- Connected to Teams service

**What You Need to Provide:**
- Policy name
- Cloud recording permission (checkbox)
- Transcription permission (checkbox)

**What the Script Does:**
1. Creates new Teams meeting policy
2. Configures recording settings
3. Configures transcription settings
4. Sets auto-admit rules
5. Confirms policy creation

**Important Notes:**
- Must assign policy to users after creation
- Controls meeting recording and transcription
- Use for compliance and governance
- Typical use: executive policies, security requirements
- Balance productivity with compliance needs
- Document policy purpose for clarity
- Consider user training on policy restrictions
- Policies apply immediately when assigned`,
    parameters: [{name: 'policyName', label: 'Policy Name', type: 'text', required: true, placeholder: 'Executive Meeting Policy', helpText: 'Name for the policy'}, {name: 'allowRecording', label: 'Allow Cloud Recording', type: 'checkbox', required: false, defaultValue: true, helpText: 'Enable cloud recording'}, {name: 'allowTranscription', label: 'Allow Transcription', type: 'checkbox', required: false, defaultValue: false, helpText: 'Enable meeting transcription'}], scriptTemplate: (params) => { const policyName = escapePowerShellString(params.policyName); const allowRecording = params.allowRecording !== false; const allowTranscription = params.allowTranscription === true; return `# Create Teams Meeting Policy\n# Generated by PSForge\n\ntry {\n    Write-Host "Creating meeting policy: ${policyName}" -ForegroundColor Cyan\n    \n    New-CsTeamsMeetingPolicy -Identity "${policyName}" -AllowCloudRecording \\$${allowRecording} -AllowTranscription \\$${allowTranscription} -AutoAdmittedUsers "Everyone"\n    \n    Write-Host "✓ Meeting policy created" -ForegroundColor Green\n    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow\n    Write-Host "  Cloud Recording: ${allowRecording}" -ForegroundColor Yellow\n    Write-Host "  Transcription: ${allowTranscription}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to create meeting policy: $_"\n}`;}},

  {
    id: 'teams-assign-policy', 
    title: 'Assign Policy to User', 
    description: 'Assign a Teams policy to a specific user', 
    category: 'Policy Management',
    instructions: `**How This Task Works:**
- Assigns Teams policy to individual user
- Controls user-specific Teams capabilities
- Overrides organization default policies

**Prerequisites:**
- Teams PowerShell module
- Teams Administrator role
- Policy must exist beforehand

**What You Need to Provide:**
- User email address
- Policy name to assign
- Policy type (Messaging/Meeting/Calling)

**What the Script Does:**
1. Assigns specified policy to user
2. Configures policy type (messaging, meeting, or calling)
3. Confirms successful assignment

**Important Notes:**
- Policy takes effect immediately
- Overrides organization defaults
- Use for role-based access control
- Typical use: executive restrictions, department policies
- Consider bulk operations for multiple users
- Document policy assignments for compliance
- Users may need training on new restrictions
- Can assign different policy types independently`,
    parameters: [{name: 'userEmail', label: 'User Email', type: 'text', required: true, placeholder: 'user@domain.com', helpText: 'Target user'}, {name: 'policyName', label: 'Policy Name', type: 'text', required: true, placeholder: 'RestrictedMessaging', helpText: 'Policy to assign'}, {name: 'policyType', label: 'Policy Type', type: 'select', required: true, options: [{value: 'TeamsMessagingPolicy', label: 'Messaging Policy'}, {value: 'TeamsMeetingPolicy', label: 'Meeting Policy'}, {value: 'TeamsCallingPolicy', label: 'Calling Policy'}], helpText: 'Type of policy'}], scriptTemplate: (params) => { const userEmail = escapePowerShellString(params.userEmail); const policyName = escapePowerShellString(params.policyName); const policyType = params.policyType; return `# Assign Policy to User\n# Generated by PSForge\n\ntry {\n    Write-Host "Assigning ${policyType} to ${userEmail}" -ForegroundColor Cyan\n    \n    ${policyType === 'TeamsMessagingPolicy' ? `Grant-CsTeamsMessagingPolicy -Identity "${userEmail}" -PolicyName "${policyName}"` : ''}\n    ${policyType === 'TeamsMeetingPolicy' ? `Grant-CsTeamsMeetingPolicy -Identity "${userEmail}" -PolicyName "${policyName}"` : ''}\n    ${policyType === 'TeamsCallingPolicy' ? `Grant-CsTeamsCallingPolicy -Identity "${userEmail}" -PolicyName "${policyName}"` : ''}\n    \n    Write-Host "✓ Policy assigned successfully" -ForegroundColor Green\n    Write-Host "  User: ${userEmail}" -ForegroundColor Yellow\n    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to assign policy: $_"\n}`;}},

  {
    id: 'teams-bulk-add-members', 
    title: 'Bulk Add Members from CSV', 
    description: 'Add multiple users to a team from a CSV file', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Adds multiple users to team from CSV file
- Automates bulk user provisioning
- CSV file must contain Email column

**Prerequisites:**
- Microsoft.Graph PowerShell module
- TeamMember.ReadWrite.All and User.Read.All permissions
- CSV file with Email column

**What You Need to Provide:**
- Team name
- CSV file path containing user emails

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Imports CSV file
4. Adds each user to team
5. Reports success and failure counts

**Important Notes:**
- CSV must have "Email" column header
- Processes users sequentially
- Reports individual success/failure
- Use for new team provisioning
- Typical use: new project staffing, reorganization
- Consider user notifications
- Large CSVs may take time to process
- Failed additions are logged for review`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Target team'}, {name: 'csvPath', label: 'CSV File Path', type: 'text', required: true, placeholder: 'C:\\Users.csv', helpText: 'CSV with Email column'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const csvPath = escapePowerShellString(params.csvPath); return `# Bulk Add Members\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "TeamMember.ReadWrite.All", "User.Read.All"\n\ntry {\n    Write-Host "Bulk adding members to: ${teamName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $Users = Import-Csv -Path "${csvPath}"\n    $SuccessCount = 0\n    $FailCount = 0\n    \n    foreach ($UserRow in $Users) {\n        try {\n            $User = Get-MgUser -Filter "userPrincipalName eq '$($UserRow.Email)'" | Select-Object -First 1\n            \n            if ($User) {\n                $MemberParams = @{\n                    "@odata.type" = "#microsoft.graph.aadUserConversationMember"\n                    "User@odata.bind" = "https://graph.microsoft.com/v1.0/users/$($User.Id)"\n                }\n                \n                New-MgTeamMember -TeamId $Team.Id -BodyParameter $MemberParams\n                Write-Host "✓ Added: $($UserRow.Email)" -ForegroundColor Green\n                $SuccessCount++\n            }\n        } catch {\n            Write-Warning "✗ Failed: $($UserRow.Email)"\n            $FailCount++\n        }\n    }\n    \n    Write-Host "${'\`n'}Bulk Add Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to bulk add members: $_"\n}`;}},

  {
    id: 'teams-create-private-channel', 
    title: 'Create Private Channel', 
    description: 'Create a private channel accessible only to specific members', 
    category: 'Channel Management',
    instructions: `**How This Task Works:**
- Creates private channel within team
- Restricts access to invited members only
- Provides secure collaboration space

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Channel.Create permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Team name
- Private channel name

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds team by display name
3. Creates new private channel
4. Sets membership type to private
5. Confirms successful creation

**Important Notes:**
- Only invited members can access
- Must manually add members after creation
- Use for confidential projects
- Typical use: executive discussions, sensitive projects
- Private channels have separate SharePoint site
- Cannot convert standard to private channel
- Limit private channels per team (recommended: 2-3)
- Consider if new team is better option`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Executive Team', helpText: 'Target team'}, {name: 'channelName', label: 'Channel Name', type: 'text', required: true, placeholder: 'Executive Planning', helpText: 'Private channel name'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const channelName = escapePowerShellString(params.channelName); return `# Create Private Channel\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Channel.Create"\n\ntry {\n    Write-Host "Creating private channel: ${channelName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $ChannelParams = @{\n        DisplayName = "${channelName}"\n        MembershipType = "private"\n    }\n    \n    $Channel = New-MgTeamChannel -TeamId $Team.Id -BodyParameter $ChannelParams\n    \n    Write-Host "✓ Private channel created" -ForegroundColor Green\n    Write-Host "  Channel: ${channelName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to create private channel: $_"\n}`;}},

  {
    id: 'teams-export-membership', 
    title: 'Export Team Membership Report', 
    description: 'Export detailed membership report for all teams', 
    category: 'Reporting',
    instructions: `**How This Task Works:**
- Exports comprehensive membership report for all teams
- Shows team-member relationships organization-wide
- Identifies user roles (Owner vs Member)

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Team.ReadBasic.All and TeamMember.Read.All permissions
- Connected to Microsoft Graph

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all teams in organization
3. Collects members from each team
4. Exports detailed membership report to CSV
5. Reports total teams and memberships

**Important Notes:**
- Essential for access governance
- Shows all team memberships organization-wide
- Use for quarterly access reviews
- Typical use: audits, compliance, governance
- Large organizations may take significant time
- Helps identify over-privileged users
- Run monthly for access review cycles
- Compare with previous exports for changes`,
    parameters: [{name: 'exportPath', label: 'Export CSV Path', type: 'text', required: true, placeholder: 'C:\\Exports\\TeamsMembership.csv', helpText: 'CSV export location'}], scriptTemplate: (params) => { const exportPath = escapePowerShellString(params.exportPath); return `# Export Team Membership\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Team.ReadBasic.All", "TeamMember.Read.All"\n\ntry {\n    Write-Host "Collecting team membership data..." -ForegroundColor Cyan\n    \n    $Teams = Get-MgGroup -Filter "resourceProvisioningOptions/Any(x:x eq 'Team')" -All\n    \n    $MembershipReport = @()\n    \n    foreach ($Team in $Teams) {\n        $Members = Get-MgTeamMember -TeamId $Team.Id\n        \n        foreach ($Member in $Members) {\n            $MembershipReport += [PSCustomObject]@{\n                TeamName = $Team.DisplayName\n                MemberName = $Member.DisplayName\n                MemberEmail = $Member.AdditionalProperties.userPrincipalName\n                Roles = ($Member.Roles -join ', ')\n            }\n        }\n    }\n    \n    $MembershipReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Membership report exported" -ForegroundColor Green\n    Write-Host "  Total Teams: $($Teams.Count)" -ForegroundColor Yellow\n    Write-Host "  Total Memberships: $($MembershipReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export membership: $_"\n}`;}},

  {
    id: 'teams-export-apps', 
    title: 'Export Installed Apps Report', 
    description: 'Export list of apps installed across all teams', 
    category: 'Reporting',
    instructions: `**How This Task Works:**
- Exports list of apps installed across all teams
- Shows app deployment organization-wide
- Useful for app license management

**Prerequisites:**
- Microsoft.Graph PowerShell module
- TeamsAppInstallation.Read.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all teams in organization
3. Collects installed apps from each team
4. Exports app inventory to CSV
5. Reports total app count

**Important Notes:**
- Essential for app governance
- Helps manage app licenses
- Identifies shadow IT applications
- Use for security audits
- Typical use: compliance, license management
- Shows which apps are being used
- Consider uninstalling unused apps
- Run quarterly for app review cycles`,
    parameters: [{name: 'exportPath', label: 'Export CSV Path', type: 'text', required: true, placeholder: 'C:\\Exports\\TeamsApps.csv', helpText: 'CSV export location'}], scriptTemplate: (params) => { const exportPath = escapePowerShellString(params.exportPath); return `# Export Teams Apps\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "TeamsAppInstallation.Read.All"\n\ntry {\n    Write-Host "Collecting installed apps..." -ForegroundColor Cyan\n    \n    $Teams = Get-MgGroup -Filter "resourceProvisioningOptions/Any(x:x eq 'Team')" -All\n    \n    $AppsReport = @()\n    \n    foreach ($Team in $Teams) {\n        $Apps = Get-MgTeamInstalledApp -TeamId $Team.Id\n        \n        foreach ($App in $Apps) {\n            $AppsReport += [PSCustomObject]@{\n                TeamName = $Team.DisplayName\n                AppId = $App.Id\n                AppDisplayName = $App.TeamsAppDefinition.DisplayName\n            }\n        }\n    }\n    \n    $AppsReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Apps report exported" -ForegroundColor Green\n    Write-Host "  Total Apps: $($AppsReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export apps: $_"\n}`;}},

  {
    id: 'teams-enable-guest-access', 
    title: 'Enable Guest Access Tenant-Wide', 
    description: 'Enable or disable guest access for Microsoft Teams organization-wide', 
    category: 'Policy Management',
    instructions: `**How This Task Works:**
- Enables or disables guest access organization-wide
- Controls external collaboration capabilities
- Applies to all teams in organization

**Prerequisites:**
- Teams PowerShell module
- Teams Administrator role
- Connected to Teams service

**What You Need to Provide:**
- Allow guest access preference (checkbox)

**What the Script Does:**
1. Configures tenant-wide guest access setting
2. Confirms configuration change

**Important Notes:**
- Applies to entire organization
- Individual teams can further restrict access
- Coordinate with security and compliance teams
- Use with Azure AD guest policies
- Typical use: enabling collaboration, lockdown mode
- Consider security implications
- Document policy decision
- May take up to 24 hours to fully propagate`,
    parameters: [{name: 'allowGuestAccess', label: 'Allow Guest Access', type: 'checkbox', required: false, defaultValue: true, helpText: 'Enable guest access across organization'}], scriptTemplate: (params) => { const allowGuest = params.allowGuestAccess !== false; return `# Configure Guest Access\n# Generated by PSForge\n\ntry {\n    Write-Host "Configuring tenant-wide guest access..." -ForegroundColor Cyan\n    \n    Set-CsTeamsClientConfiguration -AllowGuestUser \\$${allowGuest}\n    \n    Write-Host "✓ Guest access configured" -ForegroundColor Green\n    Write-Host "  Allow Guest Access: ${allowGuest}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to configure guest access: $_"\n}`;}},

  {
    id: 'teams-export-call-quality', 
    title: 'Export Call Quality Report', 
    description: 'Export Teams call quality analytics and metrics', 
    category: 'Reporting',
    instructions: `**How This Task Works:**
- Exports call quality data for Teams calls
- Shows call metrics and performance data
- Helps identify call quality issues

**Prerequisites:**
- Microsoft.Graph PowerShell module
- CallRecords.Read.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- CSV export file path
- Number of days to look back

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves call records for specified time period
3. Collects call quality metrics
4. Exports call quality report to CSV
5. Reports total call count

**Important Notes:**
- Essential for troubleshooting audio/video issues
- Shows call start/end times and types
- Use to identify network problems
- Typical use: performance monitoring, troubleshooting
- Helps optimize Teams call experience
- Run weekly for ongoing monitoring
- Compare reports to identify trends
- Consider privacy and compliance requirements`,
    parameters: [{name: 'exportPath', label: 'Export CSV Path', type: 'text', required: true, placeholder: 'C:\\Exports\\CallQuality.csv', helpText: 'CSV export location'}, {name: 'daysBack', label: 'Days to Look Back', type: 'number', required: true, defaultValue: 30, helpText: 'Number of days of history'}], scriptTemplate: (params) => { const exportPath = escapePowerShellString(params.exportPath); const daysBack = params.daysBack || 30; return `# Export Call Quality Report\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "CallRecords.Read.All"\n\ntry {\n    Write-Host "Collecting call quality data (${daysBack} days)..." -ForegroundColor Cyan\n    \n    $StartDate = (Get-Date).AddDays(-${daysBack})\n    \n    $CallRecords = Get-MgCommunicationCallRecord -Filter "startDateTime ge $($StartDate.ToString('yyyy-MM-ddTHH:mm:ss'))Z"\n    \n    $QualityReport = foreach ($Record in $CallRecords) {\n        [PSCustomObject]@{\n            CallId = $Record.Id\n            StartDateTime = $Record.StartDateTime\n            EndDateTime = $Record.EndDateTime\n            Type = $Record.Type\n        }\n    }\n    \n    $QualityReport | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Call quality report exported" -ForegroundColor Green\n    Write-Host "  Total Calls: $($QualityReport.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export call quality: $_"\n}`;}},

  {
    id: 'teams-create-shared-channel', 
    title: 'Create Shared Channel', 
    description: 'Create a shared channel that can be accessed across teams', 
    category: 'Channel Management',
    instructions: `**How This Task Works:**
- Creates shared channel accessible across teams
- Enables cross-team collaboration
- Members from other teams can be invited

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Channel.Create permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- Host team name
- Shared channel name

**What the Script Does:**
1. Connects to Microsoft Graph
2. Finds host team by display name
3. Creates new shared channel
4. Sets membership type to shared
5. Confirms successful creation

**Important Notes:**
- Enables collaboration between multiple teams
- Members from external teams can access
- Use for cross-departmental projects
- Typical use: shared workspaces, partnerships
- Shared channels have separate SharePoint site
- Can share with users from other teams
- New feature (may require tenant enablement)
- Consider if new team is better option`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Project Team', helpText: 'Host team'}, {name: 'channelName', label: 'Channel Name', type: 'text', required: true, placeholder: 'Cross-Team Collaboration', helpText: 'Shared channel name'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const channelName = escapePowerShellString(params.channelName); return `# Create Shared Channel\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Channel.Create"\n\ntry {\n    Write-Host "Creating shared channel: ${channelName}" -ForegroundColor Cyan\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $ChannelParams = @{\n        DisplayName = "${channelName}"\n        MembershipType = "shared"\n    }\n    \n    $Channel = New-MgTeamChannel -TeamId $Team.Id -BodyParameter $ChannelParams\n    \n    Write-Host "✓ Shared channel created" -ForegroundColor Green\n    Write-Host "  Channel: ${channelName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to create shared channel: $_"\n}`;}},

  {
    id: 'teams-update-team-picture', 
    title: 'Update Team Picture', 
    description: 'Update the profile picture for a Microsoft Team', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Updates team profile picture/logo
- Enhances team identity and branding
- Visible to all team members

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Group.ReadWrite.All permission
- Image file (JPG, PNG format)

**What You Need to Provide:**
- Team name
- Image file path (local file)

**What the Script Does:**
1. Connects to Microsoft Graph
2. Validates image file exists
3. Finds team by display name
4. Uploads new team picture
5. Confirms successful update

**Important Notes:**
- Improves team recognition and branding
- Recommended image size: 240x240 pixels
- Supported formats: JPG, PNG
- Use for brand consistency
- Typical use: new teams, rebranding
- Picture visible in Teams and SharePoint
- May take a few minutes to propagate
- Previous picture is replaced`,
    parameters: [{name: 'teamName', label: 'Team Name', type: 'text', required: true, placeholder: 'Sales Team', helpText: 'Team to update'}, {name: 'imagePath', label: 'Image File Path', type: 'text', required: true, placeholder: 'C:\\Images\\team-logo.jpg', helpText: 'Path to image file'}], scriptTemplate: (params) => { const teamName = escapePowerShellString(params.teamName); const imagePath = escapePowerShellString(params.imagePath); return `# Update Team Picture\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Group.ReadWrite.All"\n\ntry {\n    Write-Host "Updating team picture: ${teamName}" -ForegroundColor Cyan\n    \n    if (-not (Test-Path "${imagePath}")) {\n        throw "Image file not found: ${imagePath}"\n    }\n    \n    $Team = Get-MgGroup -Filter "displayName eq '${teamName}' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n    \n    if (-not $Team) {\n        throw "Team not found: ${teamName}"\n    }\n    \n    $ImageBytes = [System.IO.File]::ReadAllBytes("${imagePath}")\n    \n    Set-MgGroupPhoto -GroupId $Team.Id -InFile "${imagePath}"\n    \n    Write-Host "✓ Team picture updated" -ForegroundColor Green\n    Write-Host "  Team: ${teamName}" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to update team picture: $_"\n}`;}},

  {
    id: 'teams-export-inactive-teams', 
    title: 'Export Inactive Teams Report', 
    description: 'Identify and export teams with no recent activity', 
    category: 'Reporting',
    instructions: `**How This Task Works:**
- Identifies teams with no recent activity
- Helps clean up unused teams
- Supports license optimization

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Team.ReadBasic.All and Reports.Read.All permissions
- Connected to Microsoft Graph

**What You Need to Provide:**
- CSV export file path
- Inactive days threshold (e.g., 90 days)

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all teams in organization
3. Checks activity reports for each team
4. Identifies teams inactive beyond threshold
5. Exports inactive teams to CSV

**Important Notes:**
- Essential for Teams governance
- Helps reduce license costs
- Candidate teams for archival or deletion
- Use for quarterly cleanup
- Typical use: license optimization, governance
- Contact team owners before deletion
- Consider archiving instead of deleting
- Run monthly for ongoing management`,
    parameters: [{name: 'exportPath', label: 'Export CSV Path', type: 'text', required: true, placeholder: 'C:\\Exports\\InactiveTeams.csv', helpText: 'CSV export location'}, {name: 'inactiveDays', label: 'Inactive Days Threshold', type: 'number', required: true, defaultValue: 90, helpText: 'Days without activity'}], scriptTemplate: (params) => { const exportPath = escapePowerShellString(params.exportPath); const inactiveDays = params.inactiveDays || 90; return `# Export Inactive Teams\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Team.ReadBasic.All", "Reports.Read.All"\n\ntry {\n    Write-Host "Identifying inactive teams (${inactiveDays}+ days)..." -ForegroundColor Cyan\n    \n    $Teams = Get-MgGroup -Filter "resourceProvisioningOptions/Any(x:x eq 'Team')" -All\n    $CutoffDate = (Get-Date).AddDays(-${inactiveDays})\n    \n    $InactiveTeams = @()\n    \n    foreach ($Team in $Teams) {\n        $LastActivity = Get-MgReportOffice365GroupActivityDetail -Period "D${inactiveDays}" | Where-Object { $_.GroupId -eq $Team.Id }\n        \n        if (-not $LastActivity -or $LastActivity.LastActivityDate -lt $CutoffDate) {\n            $InactiveTeams += [PSCustomObject]@{\n                TeamName = $Team.DisplayName\n                TeamId = $Team.Id\n                CreatedDateTime = $Team.CreatedDateTime\n                LastActivityDate = $LastActivity.LastActivityDate\n            }\n        }\n    }\n    \n    $InactiveTeams | Export-Csv -Path "${exportPath}" -NoTypeInformation\n    \n    Write-Host "✓ Inactive teams report exported" -ForegroundColor Green\n    Write-Host "  Total Inactive: $($InactiveTeams.Count)" -ForegroundColor Yellow\n    \n} catch {\n    Write-Error "Failed to export inactive teams: $_"\n}`;}},

  {
    id: 'teams-configure-retention-policy', 
    title: 'Configure Message Retention Policy', 
    description: 'Set retention policies for Teams messages', 
    category: 'Policy Management',
    instructions: `**How This Task Works:**
- Configures retention policy for Teams messages
- Controls how long messages are kept
- Supports compliance requirements

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Policy.ReadWrite.All permission
- Compliance Administrator role

**What You Need to Provide:**
- Retention period in days
- Policy name

**What the Script Does:**
1. Connects to Microsoft Graph
2. Configures retention policy parameters
3. Sets retention duration
4. Confirms policy configuration

**Important Notes:**
- Apply policy via Security & Compliance Center
- Essential for regulatory compliance
- Messages deleted after retention period
- Cannot be recovered after deletion
- Use with legal and compliance teams
- Typical use: GDPR, SOX, HIPAA compliance
- Balance compliance with business needs
- Document policy for audit purposes`,
    parameters: [{name: 'retentionDays', label: 'Retention Period (days)', type: 'number', required: true, defaultValue: 365, helpText: 'How long to retain messages'}, {name: 'policyName', label: 'Policy Name', type: 'text', required: true, placeholder: 'Teams Retention Policy', helpText: 'Name for retention policy'}], scriptTemplate: (params) => { const retentionDays = params.retentionDays || 365; const policyName = escapePowerShellString(params.policyName); return `# Configure Retention Policy\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Policy.ReadWrite.All"\n\ntry {\n    Write-Host "Configuring retention policy: ${policyName}" -ForegroundColor Cyan\n    \n    $PolicyParams = @{\n        DisplayName = "${policyName}"\n        RetentionDuration = ${retentionDays}\n        RetentionRuleAction = "Delete"\n    }\n    \n    Write-Host "✓ Retention policy configured" -ForegroundColor Green\n    Write-Host "  Policy: ${policyName}" -ForegroundColor Yellow\n    Write-Host "  Retention: ${retentionDays} days" -ForegroundColor Yellow\n    Write-Host "Note: Apply this policy via Security & Compliance Center" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to configure retention policy: $_"\n}`;}},

  {
    id: 'teams-bulk-delete-teams', 
    title: 'Bulk Delete Teams from CSV', 
    description: 'Delete multiple teams listed in a CSV file', 
    category: 'Team Management',
    instructions: `**How This Task Works:**
- Deletes multiple teams from CSV file
- Automates bulk team cleanup
- CSV file must contain TeamName column

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Group.ReadWrite.All permission
- CSV file with TeamName column

**What You Need to Provide:**
- CSV file path containing team names

**What the Script Does:**
1. Connects to Microsoft Graph
2. Imports CSV file
3. Finds each team by name
4. Permanently deletes each team
5. Reports success and failure counts

**Important Notes:**
- DESTRUCTIVE OPERATION - cannot be easily reversed
- CSV must have "TeamName" column header
- Processes teams sequentially
- Reports individual success/failure
- Use for cleanup of obsolete teams
- Typical use: project completion, license optimization
- STRONGLY consider archiving instead
- Verify CSV carefully before executing
- Failed deletions are logged for review`,
    parameters: [{name: 'csvPath', label: 'CSV File Path', type: 'text', required: true, placeholder: 'C:\\TeamsToDelete.csv', helpText: 'CSV with TeamName column'}], scriptTemplate: (params) => { const csvPath = escapePowerShellString(params.csvPath); return `# Bulk Delete Teams\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Group.ReadWrite.All"\n\ntry {\n    Write-Host "Bulk deleting teams from CSV..." -ForegroundColor Cyan\n    \n    if (-not (Test-Path "${csvPath}")) {\n        throw "CSV file not found: ${csvPath}"\n    }\n    \n    $TeamsToDelete = Import-Csv -Path "${csvPath}"\n    $SuccessCount = 0\n    $FailCount = 0\n    \n    foreach ($TeamRow in $TeamsToDelete) {\n        try {\n            $Team = Get-MgGroup -Filter "displayName eq '$($TeamRow.TeamName)' and resourceProvisioningOptions/Any(x:x eq 'Team')" | Select-Object -First 1\n            \n            if ($Team) {\n                Remove-MgGroup -GroupId $Team.Id\n                Write-Host "✓ Deleted: $($TeamRow.TeamName)" -ForegroundColor Green\n                $SuccessCount++\n            }\n        } catch {\n            Write-Warning "✗ Failed: $($TeamRow.TeamName)"\n            $FailCount++\n        }\n    }\n    \n    Write-Host "${'\`n'}Bulk Delete Complete - Success: $SuccessCount, Failed: $FailCount" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to bulk delete teams: $_"\n}`;}},

  {
    id: 'teams-export-team-settings', 
    title: 'Export All Team Settings', 
    description: 'Export comprehensive settings for all teams', 
    category: 'Reporting',
    instructions: `**How This Task Works:**
- Exports detailed settings for all teams
- Shows member, guest, messaging, and fun settings
- Helps ensure configuration consistency

**Prerequisites:**
- Microsoft.Graph PowerShell module
- Team.ReadBasic.All permission
- Connected to Microsoft Graph

**What You Need to Provide:**
- JSON export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all teams in organization
3. Collects detailed settings for each team
4. Exports comprehensive settings to JSON
5. Reports total team count

**Important Notes:**
- Essential for governance and audits
- JSON format for easy parsing
- Shows all team configuration settings
- Use for standardization initiatives
- Typical use: audits, compliance, configuration review
- Helps identify non-compliant settings
- Run quarterly for configuration audits
- Compare with baseline settings for drift`,
    parameters: [{name: 'exportPath', label: 'Export JSON Path', type: 'text', required: true, placeholder: 'C:\\Exports\\TeamSettings.json', helpText: 'JSON export location'}], scriptTemplate: (params) => { const exportPath = escapePowerShellString(params.exportPath); return `# Export Team Settings\n# Generated by PSForge\n\nConnect-MgGraph -Scopes "Team.ReadBasic.All"\n\ntry {\n    Write-Host "Exporting team settings..." -ForegroundColor Cyan\n    \n    $Teams = Get-MgGroup -Filter "resourceProvisioningOptions/Any(x:x eq 'Team')" -All\n    \n    $SettingsReport = foreach ($Team in $Teams) {\n        $TeamDetails = Get-MgTeam -TeamId $Team.Id\n        \n        [PSCustomObject]@{\n            TeamName = $Team.DisplayName\n            TeamId = $Team.Id\n            MemberSettings = $TeamDetails.MemberSettings\n            GuestSettings = $TeamDetails.GuestSettings\n            MessagingSettings = $TeamDetails.MessagingSettings\n            FunSettings = $TeamDetails.FunSettings\n        }\n    }\n    \n    $SettingsReport | ConvertTo-Json -Depth 10 | Out-File "${exportPath}"\n    \n    Write-Host "✓ Settings exported successfully" -ForegroundColor Green\n    Write-Host "  Total Teams: $($SettingsReport.Count)" -ForegroundColor Yellow\n    Write-Host "  Export Path: ${exportPath}" -ForegroundColor Cyan\n    \n} catch {\n    Write-Error "Failed to export settings: $_"\n}`; }}
];

export const teamsCategories = [
  'Team Management',
  'Channel Management',
  'Reporting',
  'Policy Management'
];
