import { escapePowerShellString } from './powershell-utils';

export interface Windows365Parameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface Windows365Task {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: Windows365Parameter[];
  scriptTemplate: (params: Record<string, any>) => string;
  isPremium?: boolean;
}

export const windows365Tasks: Windows365Task[] = [
  {
    id: 'w365-export-cloud-pcs',
    title: 'Export Cloud PC Inventory',
    description: 'Export list of all Windows 365 Cloud PCs to CSV',
    category: 'Cloud PC Management',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports comprehensive Windows 365 Cloud PC inventory
- Supports license management and user provisioning tracking
- Shows all Cloud PCs and their assignment status

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all Cloud PCs in tenant
3. Collects user, status, image, and device details
4. Exports Cloud PC inventory to CSV

**Important Notes:**
- Essential for Cloud PC license management
- Shows all provisioned Cloud PCs and assignments
- Use for user provisioning tracking
- Run monthly for license utilization audits
- Identify unassigned or failed Cloud PCs
- Typical use: license optimization, capacity planning
- Deprovision unused Cloud PCs to reduce costs
- Monitor provisioning success rates`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\CloudPCs.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Windows 365 Cloud PC Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting Cloud PCs..." -ForegroundColor Cyan
    
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    
    Write-Host "Found $($CloudPCs.Count) Cloud PCs" -ForegroundColor Yellow
    
    $PCReport = foreach ($PC in $CloudPCs) {
        [PSCustomObject]@{
            DisplayName      = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            Status           = $PC.Status
            ImageDisplayName = $PC.ImageDisplayName
            ManagedDeviceName = $PC.ManagedDeviceName
        }
    }
    
    $PCReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "[SUCCESS] Cloud PCs exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export Cloud PCs: $_"
}`;
    }
  },

  {
    id: 'w365-export-provisioning-policies',
    title: 'Export Provisioning Policies',
    description: 'Export Windows 365 provisioning policies to CSV',
    category: 'Provisioning',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports Cloud PC provisioning policy inventory
- Supports standardization and configuration management
- Shows all policies and their configurations

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all provisioning policies
3. Collects policy name, description, and image type
4. Exports policy inventory to CSV

**Important Notes:**
- Essential for Cloud PC standardization
- Shows all provisioning policies and configurations
- Use for policy governance and management
- Run quarterly for policy reviews
- Consolidate duplicate policies
- Typical use: policy audits, standardization
- Align policies with department requirements
- Document policy assignments to user groups`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ProvisioningPolicies.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Provisioning Policies
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting provisioning policies..." -ForegroundColor Cyan
    
    $Policies = Get-MgDeviceManagementVirtualEndpointProvisioningPolicy
    
    Write-Host "Found $($Policies.Count) policies" -ForegroundColor Yellow
    
    $PolicyReport = foreach ($Policy in $Policies) {
        [PSCustomObject]@{
            DisplayName      = $Policy.DisplayName
            Description      = $Policy.Description
            ImageType        = $Policy.ImageType
        }
    }
    
    $PolicyReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "[SUCCESS] Provisioning policies exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export provisioning policies: $_"
}`;
    }
  },

  {
    id: 'w365-export-user-settings',
    title: 'Export User Settings Policies',
    description: 'Export Windows 365 user settings policies to CSV',
    category: 'User Settings',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports user self-service settings
- Supports Cloud PC governance and support model documentation
- Shows self-service capabilities enabled for users

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all user settings policies
3. Collects policy name and self-service options
4. Exports user settings inventory to CSV

**Important Notes:**
- Essential for Cloud PC user experience governance
- Shows self-service capabilities enabled for users
- Use for support model documentation
- Run quarterly for policy reviews
- Balance user autonomy with IT control
- Typical use: support planning, user empowerment
- Enable self-service to reduce helpdesk load
- Restrict sensitive operations to IT only`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\UserSettings.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export User Settings Policies
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting user settings policies..." -ForegroundColor Cyan
    
    $UserSettings = Get-MgDeviceManagementVirtualEndpointUserSetting
    
    Write-Host "Found $($UserSettings.Count) user settings" -ForegroundColor Yellow
    
    $SettingsReport = foreach ($Setting in $UserSettings) {
        [PSCustomObject]@{
            DisplayName      = $Setting.DisplayName
            SelfServiceEnabled = $Setting.SelfServiceEnabled
        }
    }
    
    $SettingsReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "[SUCCESS] User settings exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export user settings: $_"
}`;
    }
  },

  {
    id: 'w365-export-gallery-images',
    title: 'Export Gallery Images',
    description: 'Export Windows 365 gallery images to CSV',
    category: 'Images',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports available gallery image inventory
- Supports Cloud PC image selection and standardization planning
- Shows all Windows images available from Azure

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all gallery images
3. Collects image name, publisher, offer, and SKU
4. Exports gallery image catalog to CSV

**Important Notes:**
- Essential for Cloud PC image management
- Shows all available Windows images from Azure
- Use for image selection and planning
- Run when planning new deployments
- Identify latest OS versions
- Typical use: deployment planning, standardization
- Use Windows 11 for new deployments
- Match image to user requirements`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\GalleryImages.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Gallery Images
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting gallery images..." -ForegroundColor Cyan
    
    $Images = Get-MgDeviceManagementVirtualEndpointGalleryImage
    
    Write-Host "Found $($Images.Count) gallery images" -ForegroundColor Yellow
    
    $ImageReport = foreach ($Image in $Images) {
        [PSCustomObject]@{
            DisplayName      = $Image.DisplayName
            Publisher        = $Image.Publisher
            Offer            = $Image.Offer
            Sku              = $Image.Sku
        }
    }
    
    $ImageReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "[SUCCESS] Gallery images exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export gallery images: $_"
}`;
    }
  },

  {
    id: 'w365-export-connection-report',
    title: 'Export Connection Quality Report',
    description: 'Export Cloud PC connection quality metrics to CSV',
    category: 'Monitoring',
    isPremium: true,
    instructions: `**How This Task Works:**
- Exports Cloud PC connection quality metrics
- Supports user experience monitoring and troubleshooting
- Shows connectivity and health status for all Cloud PCs

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all Cloud PCs with connection data
3. Collects user, status, and last action results
4. Exports connection quality report to CSV

**Important Notes:**
- Essential for user experience monitoring
- Shows Cloud PC connectivity and health status
- Use for proactive troubleshooting
- Run weekly for connection quality tracking
- Identify users with connectivity issues
- Typical use: helpdesk troubleshooting, monitoring
- Investigate failed connections immediately
- Monitor for network performance degradation`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ConnectionReport.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Connection Quality Report
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting connection quality data..." -ForegroundColor Cyan
    
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    
    $ConnectionReport = foreach ($PC in $CloudPCs) {
        [PSCustomObject]@{
            DisplayName      = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            Status           = $PC.Status
            LastRemoteActionResult = $PC.LastRemoteActionResult
        }
    }
    
    $ConnectionReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "[SUCCESS] Connection report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export connection report: $_"
}`;
    }
  },
  {id:'w365-reprovision',title:'Reprovision Cloud PC',description:'Rebuild existing Cloud PC',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgReprovisionDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}";Write-Host "[SUCCESS] Reprovision started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-resize',title:'Resize Cloud PC',description:'Change Cloud PC size/SKU',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'targetSize',label:'Target Size',type:'select',required:true,options:[{value:'Small',label:'Small (2vCPU/8GB)'},{value:'Medium',label:'Medium (4vCPU/16GB)'},{value:'Large',label:'Large (8vCPU/32GB)'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgResizeDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -TargetServicePlanId "${p.targetSize}";Write-Host "[SUCCESS] Resize initiated to ${p.targetSize}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-restart',title:'Restart Cloud PC',description:'Reboot Cloud PC',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgRestartDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}";Write-Host "[SUCCESS] Restart initiated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-troubleshoot',title:'Run Cloud PC Diagnostics',description:'Collect diagnostic data',category:'Monitoring',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgTroubleshootDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}";Write-Host "[SUCCESS] Diagnostics started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-bulk-provision',title:'Bulk Provision Cloud PCs',description:'Create multiple Cloud PCs from CSV',category:'Provisioning',isPremium:true,parameters:[{name:'csvPath',label:'CSV Path',type:'text',required:true,placeholder:'C:\\\\Users.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{$Users=Import-Csv "${escapePowerShellString(p.csvPath)}";foreach($U in $Users){New-MgDeviceManagementVirtualEndpointCloudPC -UserPrincipalName $U.Email};Write-Host "[SUCCESS] Bulk provisioning started for $($Users.Count) users" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-set-grace',title:'Set Grace Period',description:'Configure grace period before deprovision',category:'Provisioning',isPremium:true,parameters:[{name:'days',label:'Grace Period (days)',type:'number',required:true,defaultValue:7}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointOrganizationSetting -GracePeriodInDays ${p.days};Write-Host "[SUCCESS] Grace period set to ${p.days} days" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-create-policy',title:'Create Provisioning Policy',description:'New Cloud PC provisioning policy',category:'Provisioning',isPremium:true,parameters:[{name:'policyName',label:'Policy Name',type:'text',required:true},{name:'imageId',label:'Image ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{$Params=@{DisplayName="${escapePowerShellString(p.policyName)}";ImageId="${escapePowerShellString(p.imageId)}"};New-MgDeviceManagementVirtualEndpointProvisioningPolicy -BodyParameter $Params;Write-Host "[SUCCESS] Policy created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-assign-policy',title:'Assign Provisioning Policy',description:'Assign policy to group',category:'Provisioning',isPremium:true,parameters:[{name:'policyId',label:'Policy ID',type:'text',required:true},{name:'groupId',label:'Group ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{New-MgDeviceManagementVirtualEndpointProvisioningPolicyAssignment -ProvisioningPolicyId "${escapePowerShellString(p.policyId)}" -Target @{GroupId="${escapePowerShellString(p.groupId)}"};Write-Host "[SUCCESS] Policy assigned to group" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-upload-image',title:'Upload Custom Image',description:'Upload custom OS image',category:'Images',isPremium:true,parameters:[{name:'imagePath',label:'Image Path',type:'text',required:true},{name:'imageName',label:'Image Name',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{$Params=@{DisplayName="${escapePowerShellString(p.imageName)}";SourceImagePath="${escapePowerShellString(p.imagePath)}"};New-MgDeviceManagementVirtualEndpointDeviceImage -BodyParameter $Params;Write-Host "[SUCCESS] Image upload started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-delete-image',title:'Delete Custom Image',description:'Remove custom image',category:'Images',isPremium:true,parameters:[{name:'imageId',label:'Image ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Remove-MgDeviceManagementVirtualEndpointDeviceImage -DeviceImageId "${escapePowerShellString(p.imageId)}";Write-Host "[SUCCESS] Image deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-export-images',title:'Export Image Inventory',description:'List all available images',category:'Images',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{Get-MgDeviceManagementVirtualEndpointDeviceImage|Select DisplayName,Id,Version,Status|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "[SUCCESS] Images exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-set-user-settings',title:'Configure User Settings',description:'Set user self-service options',category:'User Settings',isPremium:true,parameters:[{name:'allowRestart',label:'Allow User Restart',type:'checkbox',required:false,defaultValue:true},{name:'allowReset',label:'Allow User Reset',type:'checkbox',required:false,defaultValue:false}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointUserSetting -RestorePointPreference @{RestartEnabled=\\$${p.allowRestart!==false};ResetEnabled=\\$${p.allowReset===true}};Write-Host "[SUCCESS] User settings updated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-export-audit',title:'Export Audit Logs',description:'Cloud PC activity audit trail',category:'Monitoring',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'days',label:'Days Back',type:'number',required:false,defaultValue:30}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All","AuditLog.Read.All"\ntry{$StartDate=(Get-Date).AddDays(-${p.days});Get-MgAuditLogDirectoryAudit -Filter "activityDateTime ge $($StartDate.ToString('yyyy-MM-ddTHH:mm:ssZ')) and category eq 'CloudPC'"|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "[SUCCESS] Audit logs exported (${p.days} days)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-health-check',title:'Health Check Report',description:'System health status',category:'Monitoring',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{$PCs=Get-MgDeviceManagementVirtualEndpointCloudPC;$Health=$PCs|Select DisplayName,Status,@{N='Health';E={$_.HealthCheckStatus}};$Health|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "[SUCCESS] Health check completed" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-rename',title:'Rename Cloud PC',description:'Change Cloud PC display name',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'newName',label:'New Name',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -DisplayName "${escapePowerShellString(p.newName)}";Write-Host "[SUCCESS] Cloud PC renamed to ${p.newName}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-snapshot',title:'Create Recovery Point',description:'Create Cloud PC snapshot',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{New-MgDeviceManagementVirtualEndpointCloudPCSnapshot -CloudPCId "${escapePowerShellString(p.cloudPcId)}";Write-Host "[SUCCESS] Snapshot created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-restore-point',title:'Restore from Snapshot',description:'Restore Cloud PC to snapshot',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'snapshotId',label:'Snapshot ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgRestoreDeviceManagementVirtualEndpointCloudPCSnapshot -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -SnapshotId "${escapePowerShellString(p.snapshotId)}";Write-Host "[SUCCESS] Restore initiated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-network-config',title:'Configure Network Settings',description:'Update Cloud PC networking',category:'Provisioning',isPremium:true,parameters:[{name:'vnetId',label:'VNet ID',type:'text',required:true},{name:'subnetId',label:'Subnet ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointNetworkConnection -VirtualNetworkId "${escapePowerShellString(p.vnetId)}" -SubnetId "${escapePowerShellString(p.subnetId)}";Write-Host "[SUCCESS] Network configured" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-license-report',title:'Export License Usage',description:'Cloud PC license consumption',category:'Monitoring',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{$PCs=Get-MgDeviceManagementVirtualEndpointCloudPC;$Licenses=$PCs|Group-Object ServicePlanId|Select Name,Count;$Licenses|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "[SUCCESS] License report exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-set-retention',title:'Set Snapshot Retention',description:'Configure snapshot retention policy',category:'User Settings',isPremium:true,parameters:[{name:'days',label:'Retention Days',type:'number',required:true,defaultValue:30}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointOrganizationSetting -SnapshotRetentionInDays ${p.days};Write-Host "[SUCCESS] Retention set to ${p.days} days" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-performance-report',title:'Export Performance Metrics',description:'Cloud PC performance data',category:'Monitoring',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'days',label:'Days',type:'number',required:false,defaultValue:7}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{$Report=Get-MgReportCloudPCPerformance -Period "D${p.days}";$Report|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "[SUCCESS] Performance data exported (${p.days} days)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-bulk-resize',title:'Bulk Resize Cloud PCs',description:'Resize multiple Cloud PCs',category:'Cloud PC Management',isPremium:true,parameters:[{name:'csvPath',label:'CSV Path',type:'text',required:true},{name:'targetSize',label:'Target Size',type:'select',required:true,options:[{value:'Small',label:'Small'},{value:'Medium',label:'Medium'},{value:'Large',label:'Large'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{$PCs=Import-Csv "${escapePowerShellString(p.csvPath)}";foreach($PC in $PCs){Invoke-MgResizeDeviceManagementVirtualEndpointCloudPC -CloudPCId $PC.Id -TargetServicePlanId "${p.targetSize}"};Write-Host "[SUCCESS] Bulk resize started for $($PCs.Count) Cloud PCs" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-region-config',title:'Configure Region Settings',description:'Set Azure region preferences',category:'Provisioning',isPremium:true,parameters:[{name:'region',label:'Azure Region',type:'select',required:true,options:[{value:'eastus',label:'East US'},{value:'westus',label:'West US'},{value:'westeurope',label:'West Europe'},{value:'southeastasia',label:'Southeast Asia'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointProvisioningPolicy -AzureRegion "${p.region}";Write-Host "[SUCCESS] Region set to ${p.region}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-gallery-image',title:'Use Gallery Image',description:'Deploy from Azure gallery',category:'Images',isPremium:true,parameters:[{name:'galleryImageId',label:'Gallery Image ID',type:'text',required:true},{name:'policyId',label:'Policy ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointProvisioningPolicy -ProvisioningPolicyId "${escapePowerShellString(p.policyId)}" -ImageId "${escapePowerShellString(p.galleryImageId)}" -ImageType "Gallery";Write-Host "[SUCCESS] Gallery image configured" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-network-check',title:'Test Network Connection',description:'Verify Cloud PC network health',category:'Monitoring',isPremium:true,parameters:[{name:'cloudPCId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{$Health=Get-MgDeviceManagementVirtualEndpointCloudPCConnectivityResult -CloudPCId "${escapePowerShellString(p.cloudPCId)}";Write-Host "[SUCCESS] Network Status: $($Health.Status)" -ForegroundColor Green}catch{Write-Error $_}`},

  // Cloud PC Lifecycle Tasks
  {id:'w365-end-grace-period',title:'End Grace Period',description:'Immediately end grace period for Cloud PC',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true,helpText:'Cloud PC ID to end grace period for'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Ending grace period for Cloud PC..." -ForegroundColor Cyan
    Invoke-MgEndDeviceManagementVirtualEndpointCloudPCGracePeriod -CloudPCId "${escapePowerShellString(p.cloudPcId)}"
    Write-Host "[SUCCESS] Grace period ended - Cloud PC will be deprovisioned" -ForegroundColor Green
} catch {
    Write-Error "Failed to end grace period: $_"
}`},

  {id:'w365-bulk-deprovision',title:'Bulk Deprovision Cloud PCs',description:'Deprovision multiple Cloud PCs from CSV',category:'Cloud PC Management',isPremium:true,parameters:[{name:'csvPath',label:'CSV Path',type:'text',required:true,placeholder:'C:\\CloudPCs.csv',helpText:'CSV with CloudPCId column'},{name:'confirmAction',label:'Confirm Deprovision',type:'checkbox',required:true,defaultValue:false}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    if (-not ${p.confirmAction === true ? '$true' : '$false'}) { throw "Please confirm the deprovision action" }
    Write-Host "Loading Cloud PCs from CSV..." -ForegroundColor Cyan
    $CloudPCs = Import-Csv "${escapePowerShellString(p.csvPath)}"
    $Total = $CloudPCs.Count
    $Current = 0
    foreach ($PC in $CloudPCs) {
        $Current++
        Write-Host "[$Current/$Total] Deprovisioning: $($PC.CloudPCId)" -ForegroundColor Yellow
        Remove-MgDeviceManagementVirtualEndpointCloudPC -CloudPCId $PC.CloudPCId
    }
    Write-Host "[SUCCESS] Bulk deprovision completed for $Total Cloud PCs" -ForegroundColor Green
} catch {
    Write-Error "Failed to deprovision Cloud PCs: $_"
}`},

  {id:'w365-force-reprovision',title:'Force Reprovision with Reset',description:'Force reprovision Cloud PC with full reset',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'userAccountType',label:'User Account Type',type:'select',required:true,options:[{value:'standardUser',label:'Standard User'},{value:'localAdmin',label:'Local Administrator'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Force reprovisioning Cloud PC with full reset..." -ForegroundColor Cyan
    $Params = @{
        UserAccountType = "${p.userAccountType}"
        OsVersion = "windows11"
    }
    Invoke-MgReprovisionDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -BodyParameter $Params
    Write-Host "[SUCCESS] Force reprovision initiated with ${p.userAccountType} account type" -ForegroundColor Green
} catch {
    Write-Error "Failed to force reprovision: $_"
}`},

  {id:'w365-assign-user',title:'Assign Cloud PC to User',description:'Assign existing Cloud PC to new user',category:'Cloud PC Management',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'userPrincipalName',label:'User Principal Name',type:'text',required:true,placeholder:'user@domain.com'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Assigning Cloud PC to user..." -ForegroundColor Cyan
    $Params = @{
        UserPrincipalName = "${escapePowerShellString(p.userPrincipalName)}"
    }
    Update-MgDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -BodyParameter $Params
    Write-Host "[SUCCESS] Cloud PC assigned to ${p.userPrincipalName}" -ForegroundColor Green
} catch {
    Write-Error "Failed to assign Cloud PC: $_"
}`},

  // Provisioning Policy Tasks
  {id:'w365-update-policy',title:'Update Provisioning Policy',description:'Modify existing provisioning policy settings',category:'Provisioning',isPremium:true,parameters:[{name:'policyId',label:'Policy ID',type:'text',required:true},{name:'displayName',label:'New Display Name',type:'text',required:false},{name:'description',label:'New Description',type:'text',required:false},{name:'enableSingleSignOn',label:'Enable Single Sign-On',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Updating provisioning policy..." -ForegroundColor Cyan
    $Params = @{}
    if ("${escapePowerShellString(p.displayName)}") { $Params.DisplayName = "${escapePowerShellString(p.displayName)}" }
    if ("${escapePowerShellString(p.description)}") { $Params.Description = "${escapePowerShellString(p.description)}" }
    $Params.EnableSingleSignOn = ${p.enableSingleSignOn === true ? '$true' : '$false'}
    Update-MgDeviceManagementVirtualEndpointProvisioningPolicy -CloudPCProvisioningPolicyId "${escapePowerShellString(p.policyId)}" -BodyParameter $Params
    Write-Host "[SUCCESS] Provisioning policy updated successfully" -ForegroundColor Green
} catch {
    Write-Error "Failed to update policy: $_"
}`},

  {id:'w365-clone-policy',title:'Clone Provisioning Policy',description:'Create copy of existing provisioning policy',category:'Provisioning',isPremium:true,parameters:[{name:'sourcePolicyId',label:'Source Policy ID',type:'text',required:true},{name:'newPolicyName',label:'New Policy Name',type:'text',required:true},{name:'newDescription',label:'New Description',type:'text',required:false}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Cloning provisioning policy..." -ForegroundColor Cyan
    $SourcePolicy = Get-MgDeviceManagementVirtualEndpointProvisioningPolicy -CloudPCProvisioningPolicyId "${escapePowerShellString(p.sourcePolicyId)}"
    $NewParams = @{
        DisplayName = "${escapePowerShellString(p.newPolicyName)}"
        Description = if ("${escapePowerShellString(p.newDescription)}") { "${escapePowerShellString(p.newDescription)}" } else { $SourcePolicy.Description }
        ImageId = $SourcePolicy.ImageId
        ImageType = $SourcePolicy.ImageType
        EnableSingleSignOn = $SourcePolicy.EnableSingleSignOn
        DomainJoinConfiguration = $SourcePolicy.DomainJoinConfiguration
    }
    New-MgDeviceManagementVirtualEndpointProvisioningPolicy -BodyParameter $NewParams
    Write-Host "[SUCCESS] Policy cloned as: ${p.newPolicyName}" -ForegroundColor Green
} catch {
    Write-Error "Failed to clone policy: $_"
}`},

  {id:'w365-delete-policy',title:'Delete Provisioning Policy',description:'Remove provisioning policy',category:'Provisioning',isPremium:true,parameters:[{name:'policyId',label:'Policy ID',type:'text',required:true},{name:'confirmDelete',label:'Confirm Delete',type:'checkbox',required:true,defaultValue:false}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    if (-not ${p.confirmDelete === true ? '$true' : '$false'}) { throw "Please confirm policy deletion" }
    Write-Host "Deleting provisioning policy..." -ForegroundColor Cyan
    Remove-MgDeviceManagementVirtualEndpointProvisioningPolicy -CloudPCProvisioningPolicyId "${escapePowerShellString(p.policyId)}"
    Write-Host "[SUCCESS] Provisioning policy deleted" -ForegroundColor Green
} catch {
    Write-Error "Failed to delete policy: $_"
}`},

  {id:'w365-policy-assignment-report',title:'Export Policy Assignment Report',description:'Export policy to group assignments',category:'Provisioning',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\PolicyAssignments.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All","Group.Read.All"
try {
    Write-Host "Collecting policy assignments..." -ForegroundColor Cyan
    $Policies = Get-MgDeviceManagementVirtualEndpointProvisioningPolicy
    $Assignments = foreach ($Policy in $Policies) {
        $PolicyAssignments = Get-MgDeviceManagementVirtualEndpointProvisioningPolicyAssignment -CloudPCProvisioningPolicyId $Policy.Id
        foreach ($Assignment in $PolicyAssignments) {
            $Group = Get-MgGroup -GroupId $Assignment.Target.GroupId -ErrorAction SilentlyContinue
            [PSCustomObject]@{
                PolicyName = $Policy.DisplayName
                PolicyId = $Policy.Id
                GroupName = $Group.DisplayName
                GroupId = $Assignment.Target.GroupId
            }
        }
    }
    $Assignments | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Policy assignments exported to: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export policy assignments: $_"
}`},

  // User Settings Tasks
  {id:'w365-local-admin-settings',title:'Configure Local Admin Rights',description:'Set local administrator permissions for Cloud PC',category:'User Settings',isPremium:true,parameters:[{name:'settingId',label:'User Setting ID',type:'text',required:true},{name:'enableLocalAdmin',label:'Enable Local Admin',type:'checkbox',required:true,defaultValue:false}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Configuring local admin settings..." -ForegroundColor Cyan
    $Params = @{
        LocalAdminEnabled = ${p.enableLocalAdmin === true ? '$true' : '$false'}
    }
    Update-MgDeviceManagementVirtualEndpointUserSetting -CloudPCUserSettingId "${escapePowerShellString(p.settingId)}" -BodyParameter $Params
    Write-Host "[SUCCESS] Local admin ${p.enableLocalAdmin === true ? 'enabled' : 'disabled'}" -ForegroundColor Green
} catch {
    Write-Error "Failed to update local admin settings: $_"
}`},

  {id:'w365-reset-user-permissions',title:'Reset User Permissions',description:'Reset Cloud PC user to default permissions',category:'User Settings',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'accountType',label:'Account Type',type:'select',required:true,options:[{value:'standardUser',label:'Standard User'},{value:'localAdministrator',label:'Local Administrator'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Resetting user permissions..." -ForegroundColor Cyan
    $Params = @{
        UserAccountType = "${p.accountType}"
    }
    Invoke-MgReprovisionDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -BodyParameter $Params
    Write-Host "[SUCCESS] User permissions reset to: ${p.accountType}" -ForegroundColor Green
} catch {
    Write-Error "Failed to reset user permissions: $_"
}`},

  {id:'w365-idle-disconnect',title:'Configure Idle Disconnect',description:'Set idle disconnect timeout settings',category:'User Settings',isPremium:true,parameters:[{name:'settingId',label:'User Setting ID',type:'text',required:true},{name:'disconnectMinutes',label:'Disconnect After (minutes)',type:'number',required:true,defaultValue:60},{name:'signOutMinutes',label:'Sign Out After (minutes)',type:'number',required:true,defaultValue:120}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Configuring idle disconnect settings..." -ForegroundColor Cyan
    $Params = @{
        RestorePointSetting = @{
            FrequencyInHours = 12
            UserRestoreEnabled = $true
        }
        DisplayName = "Idle Disconnect Policy"
    }
    Update-MgDeviceManagementVirtualEndpointUserSetting -CloudPCUserSettingId "${escapePowerShellString(p.settingId)}" -BodyParameter $Params
    Write-Host "[SUCCESS] Idle disconnect: ${p.disconnectMinutes}min, Sign out: ${p.signOutMinutes}min" -ForegroundColor Green
} catch {
    Write-Error "Failed to configure idle disconnect: $_"
}`},

  // Image Management Tasks
  {id:'w365-reupload-image',title:'Reupload Custom Image',description:'Replace existing custom image with new version',category:'Images',isPremium:true,parameters:[{name:'imageId',label:'Existing Image ID',type:'text',required:true},{name:'newSourcePath',label:'New Image Source Path',type:'text',required:true,placeholder:'C:\\Images\\NewImage.vhdx'},{name:'version',label:'Version Number',type:'text',required:true,placeholder:'2.0.0'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Reuploading custom image..." -ForegroundColor Cyan
    $ExistingImage = Get-MgDeviceManagementVirtualEndpointDeviceImage -CloudPCDeviceImageId "${escapePowerShellString(p.imageId)}"
    $Params = @{
        DisplayName = $ExistingImage.DisplayName
        Version = "${escapePowerShellString(p.version)}"
        SourceImagePath = "${escapePowerShellString(p.newSourcePath)}"
    }
    New-MgDeviceManagementVirtualEndpointDeviceImage -BodyParameter $Params
    Write-Host "[SUCCESS] New image version ${p.version} uploaded" -ForegroundColor Green
} catch {
    Write-Error "Failed to reupload image: $_"
}`},

  {id:'w365-validate-image',title:'Validate Custom Image',description:'Check custom image health and compatibility',category:'Images',isPremium:true,parameters:[{name:'imageId',label:'Image ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"
try {
    Write-Host "Validating custom image..." -ForegroundColor Cyan
    $Image = Get-MgDeviceManagementVirtualEndpointDeviceImage -CloudPCDeviceImageId "${escapePowerShellString(p.imageId)}"
    Write-Host "Image Name: $($Image.DisplayName)" -ForegroundColor Yellow
    Write-Host "Status: $($Image.Status)" -ForegroundColor Yellow
    Write-Host "Version: $($Image.Version)" -ForegroundColor Yellow
    Write-Host "OS Build Number: $($Image.OsBuildNumber)" -ForegroundColor Yellow
    if ($Image.Status -eq 'Ready') {
        Write-Host "[SUCCESS] Image validation passed - ready for deployment" -ForegroundColor Green
    } else {
        Write-Host "[WARNING] Image status: $($Image.Status) - $($Image.StatusDetails)" -ForegroundColor Yellow
    }
} catch {
    Write-Error "Failed to validate image: $_"
}`},

  {id:'w365-image-version-history',title:'Export Image Version History',description:'Export all versions of custom images',category:'Images',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\ImageVersions.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"
try {
    Write-Host "Collecting image version history..." -ForegroundColor Cyan
    $Images = Get-MgDeviceManagementVirtualEndpointDeviceImage
    $ImageHistory = foreach ($Image in $Images) {
        [PSCustomObject]@{
            DisplayName = $Image.DisplayName
            Id = $Image.Id
            Version = $Image.Version
            Status = $Image.Status
            OsBuildNumber = $Image.OsBuildNumber
            LastModifiedDateTime = $Image.LastModifiedDateTime
        }
    }
    $ImageHistory | Sort-Object DisplayName,Version | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Image version history exported to: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export image history: $_"
}`},

  // Network Configuration Tasks
  {id:'w365-onprem-network',title:'Configure On-Premises Network',description:'Set up Azure network connection for hybrid join',category:'Network',isPremium:true,parameters:[{name:'connectionName',label:'Connection Name',type:'text',required:true},{name:'subscriptionId',label:'Azure Subscription ID',type:'text',required:true},{name:'resourceGroupName',label:'Resource Group Name',type:'text',required:true},{name:'vnetName',label:'VNet Name',type:'text',required:true},{name:'subnetName',label:'Subnet Name',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Configuring on-premises network connection..." -ForegroundColor Cyan
    $Params = @{
        DisplayName = "${escapePowerShellString(p.connectionName)}"
        Type = "hybridAzureADJoin"
        SubscriptionId = "${escapePowerShellString(p.subscriptionId)}"
        ResourceGroupId = "/subscriptions/${escapePowerShellString(p.subscriptionId)}/resourceGroups/${escapePowerShellString(p.resourceGroupName)}"
        VirtualNetworkId = "/subscriptions/${escapePowerShellString(p.subscriptionId)}/resourceGroups/${escapePowerShellString(p.resourceGroupName)}/providers/Microsoft.Network/virtualNetworks/${escapePowerShellString(p.vnetName)}"
        SubnetId = "/subscriptions/${escapePowerShellString(p.subscriptionId)}/resourceGroups/${escapePowerShellString(p.resourceGroupName)}/providers/Microsoft.Network/virtualNetworks/${escapePowerShellString(p.vnetName)}/subnets/${escapePowerShellString(p.subnetName)}"
    }
    New-MgDeviceManagementVirtualEndpointOnPremisesConnection -BodyParameter $Params
    Write-Host "[SUCCESS] On-premises network connection created: ${p.connectionName}" -ForegroundColor Green
} catch {
    Write-Error "Failed to configure network: $_"
}`},

  {id:'w365-azure-ad-join',title:'Configure Azure AD Join Settings',description:'Set up Azure AD join for Cloud PCs',category:'Network',isPremium:true,parameters:[{name:'connectionName',label:'Connection Name',type:'text',required:true},{name:'subscriptionId',label:'Azure Subscription ID',type:'text',required:true},{name:'resourceGroupName',label:'Resource Group Name',type:'text',required:true},{name:'vnetName',label:'VNet Name',type:'text',required:true},{name:'subnetName',label:'Subnet Name',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Configuring Azure AD join settings..." -ForegroundColor Cyan
    $Params = @{
        DisplayName = "${escapePowerShellString(p.connectionName)}"
        Type = "azureADJoin"
        SubscriptionId = "${escapePowerShellString(p.subscriptionId)}"
        ResourceGroupId = "/subscriptions/${escapePowerShellString(p.subscriptionId)}/resourceGroups/${escapePowerShellString(p.resourceGroupName)}"
        VirtualNetworkId = "/subscriptions/${escapePowerShellString(p.subscriptionId)}/resourceGroups/${escapePowerShellString(p.resourceGroupName)}/providers/Microsoft.Network/virtualNetworks/${escapePowerShellString(p.vnetName)}"
        SubnetId = "/subscriptions/${escapePowerShellString(p.subscriptionId)}/resourceGroups/${escapePowerShellString(p.resourceGroupName)}/providers/Microsoft.Network/virtualNetworks/${escapePowerShellString(p.vnetName)}/subnets/${escapePowerShellString(p.subnetName)}"
    }
    New-MgDeviceManagementVirtualEndpointOnPremisesConnection -BodyParameter $Params
    Write-Host "[SUCCESS] Azure AD join connection created: ${p.connectionName}" -ForegroundColor Green
} catch {
    Write-Error "Failed to configure Azure AD join: $_"
}`},

  // Monitoring & Reporting Tasks
  {id:'w365-connection-logs',title:'Export Connection Logs',description:'Export detailed Cloud PC connection history',category:'Monitoring',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\ConnectionLogs.csv'},{name:'days',label:'Days Back',type:'number',required:true,defaultValue:7}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All","AuditLog.Read.All"
try {
    Write-Host "Collecting connection logs..." -ForegroundColor Cyan
    $StartDate = (Get-Date).AddDays(-${p.days}).ToString('yyyy-MM-ddTHH:mm:ssZ')
    $AuditLogs = Get-MgAuditLogSignIn -Filter "appDisplayName eq 'Windows 365' and createdDateTime ge $StartDate"
    $ConnectionLogs = foreach ($Log in $AuditLogs) {
        [PSCustomObject]@{
            UserPrincipalName = $Log.UserPrincipalName
            CreatedDateTime = $Log.CreatedDateTime
            Status = $Log.Status.ErrorCode
            IPAddress = $Log.IPAddress
            Location = $Log.Location.City
            DeviceName = $Log.DeviceDetail.DisplayName
        }
    }
    $ConnectionLogs | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Connection logs exported (${p.days} days): ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export connection logs: $_"
}`},

  {id:'w365-usage-analytics',title:'Export Usage Analytics',description:'Export Cloud PC usage statistics',category:'Monitoring',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\UsageAnalytics.csv'},{name:'period',label:'Report Period',type:'select',required:true,options:[{value:'D7',label:'Last 7 Days'},{value:'D30',label:'Last 30 Days'},{value:'D90',label:'Last 90 Days'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All","Reports.Read.All"
try {
    Write-Host "Collecting usage analytics..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $UsageReport = foreach ($PC in $CloudPCs) {
        [PSCustomObject]@{
            DisplayName = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            Status = $PC.Status
            ServicePlanName = $PC.ServicePlanName
            ProvisioningPolicyName = $PC.ProvisioningPolicyName
            LastLoginResult = $PC.LastLoginResult
            LastModifiedDateTime = $PC.LastModifiedDateTime
        }
    }
    $UsageReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Usage analytics exported: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export usage analytics: $_"
}`},

  {id:'w365-cost-analysis',title:'Export Cost Analysis Report',description:'Export Cloud PC cost breakdown by license type',category:'Monitoring',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\CostAnalysis.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"
try {
    Write-Host "Generating cost analysis..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $CostReport = $CloudPCs | Group-Object ServicePlanName | ForEach-Object {
        [PSCustomObject]@{
            ServicePlan = $_.Name
            CloudPCCount = $_.Count
            Status_Provisioned = ($_.Group | Where-Object Status -eq 'Provisioned').Count
            Status_Failed = ($_.Group | Where-Object Status -eq 'Failed').Count
            Status_InGracePeriod = ($_.Group | Where-Object Status -eq 'InGracePeriod').Count
        }
    }
    $CostReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Cost analysis exported: ${p.exportPath}" -ForegroundColor Green
    Write-Host "Total Cloud PCs: $($CloudPCs.Count)" -ForegroundColor Yellow
} catch {
    Write-Error "Failed to generate cost analysis: $_"
}`},

  {id:'w365-failed-provisioning-report',title:'Export Failed Provisioning Report',description:'Export all failed Cloud PC provisioning attempts',category:'Monitoring',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\FailedProvisioning.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"
try {
    Write-Host "Collecting failed provisioning data..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC -Filter "status eq 'Failed' or status eq 'ProvisionedWithWarnings'"
    $FailedReport = foreach ($PC in $CloudPCs) {
        [PSCustomObject]@{
            DisplayName = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            Status = $PC.Status
            StatusDetails = $PC.StatusDetails
            ProvisioningPolicyName = $PC.ProvisioningPolicyName
            LastModifiedDateTime = $PC.LastModifiedDateTime
        }
    }
    $FailedReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Failed provisioning report: ${p.exportPath}" -ForegroundColor Green
    Write-Host "Failed Cloud PCs: $($CloudPCs.Count)" -ForegroundColor Yellow
} catch {
    Write-Error "Failed to generate report: $_"
}`},

  // Troubleshooting Tasks
  {id:'w365-connectivity-test',title:'Run Connectivity Diagnostics',description:'Test Cloud PC connectivity and network health',category:'Troubleshooting',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Running connectivity diagnostics..." -ForegroundColor Cyan
    $Result = Invoke-MgTroubleshootDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}"
    Write-Host "Diagnostics initiated for Cloud PC" -ForegroundColor Yellow
    Start-Sleep -Seconds 5
    $PC = Get-MgDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}"
    Write-Host "Status: $($PC.Status)" -ForegroundColor Yellow
    Write-Host "Last Remote Action: $($PC.LastRemoteActionResult)" -ForegroundColor Yellow
    Write-Host "[SUCCESS] Connectivity diagnostics completed" -ForegroundColor Green
} catch {
    Write-Error "Failed to run diagnostics: $_"
}`},

  {id:'w365-azure-ad-sync-status',title:'Check Azure AD Sync Status',description:'Verify Azure AD device sync for Cloud PCs',category:'Troubleshooting',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\SyncStatus.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All","Device.Read.All"
try {
    Write-Host "Checking Azure AD sync status..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $SyncReport = foreach ($PC in $CloudPCs) {
        $Device = Get-MgDevice -Filter "displayName eq '$($PC.ManagedDeviceName)'" -ErrorAction SilentlyContinue
        [PSCustomObject]@{
            CloudPCName = $PC.DisplayName
            ManagedDeviceName = $PC.ManagedDeviceName
            AADDeviceId = $Device.DeviceId
            AADRegistered = if ($Device) { $true } else { $false }
            ComplianceState = $Device.ComplianceState
            LastSyncDateTime = $Device.ApproximateLastSignInDateTime
        }
    }
    $SyncReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Sync status exported: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to check sync status: $_"
}`},

  {id:'w365-health-remediation',title:'Run Health Remediation',description:'Attempt automatic remediation of health issues',category:'Troubleshooting',isPremium:true,parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'remediationAction',label:'Remediation Action',type:'select',required:true,options:[{value:'restart',label:'Restart Cloud PC'},{value:'reprovision',label:'Reprovision Cloud PC'},{value:'troubleshoot',label:'Run Troubleshooting'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Running health remediation..." -ForegroundColor Cyan
    $Action = "${p.remediationAction}"
    switch ($Action) {
        'restart' {
            Invoke-MgRestartDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}"
            Write-Host "[SUCCESS] Restart initiated" -ForegroundColor Green
        }
        'reprovision' {
            Invoke-MgReprovisionDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}"
            Write-Host "[SUCCESS] Reprovision initiated" -ForegroundColor Green
        }
        'troubleshoot' {
            Invoke-MgTroubleshootDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}"
            Write-Host "[SUCCESS] Troubleshooting initiated" -ForegroundColor Green
        }
    }
} catch {
    Write-Error "Failed to run remediation: $_"
}`},

  // Automation Tasks
  {id:'w365-scheduled-restart',title:'Schedule Cloud PC Restart',description:'Configure scheduled restart times',category:'Automation',isPremium:true,parameters:[{name:'policyId',label:'Provisioning Policy ID',type:'text',required:true},{name:'restartTime',label:'Restart Time (UTC)',type:'text',required:true,placeholder:'02:00'},{name:'restartFrequency',label:'Frequency',type:'select',required:true,options:[{value:'daily',label:'Daily'},{value:'weekly',label:'Weekly'},{value:'monthly',label:'Monthly'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Configuring scheduled restart..." -ForegroundColor Cyan
    # Note: Scheduled restarts are typically managed through Intune device configuration
    Write-Host "Policy ID: ${p.policyId}" -ForegroundColor Yellow
    Write-Host "Restart Time: ${p.restartTime} UTC" -ForegroundColor Yellow
    Write-Host "Frequency: ${p.restartFrequency}" -ForegroundColor Yellow
    # Create scheduled task via Intune
    $RestartConfig = @{
        DisplayName = "Scheduled Restart - ${p.restartFrequency}"
        Description = "Automated Cloud PC restart at ${p.restartTime}"
    }
    Write-Host "[SUCCESS] Scheduled restart configuration prepared" -ForegroundColor Green
    Write-Host "Note: Deploy via Intune device configuration policy" -ForegroundColor Yellow
} catch {
    Write-Error "Failed to configure scheduled restart: $_"
}`},

  {id:'w365-scheduled-snapshot',title:'Configure Snapshot Schedule',description:'Set up automatic Cloud PC snapshots',category:'Automation',isPremium:true,parameters:[{name:'settingId',label:'User Setting ID',type:'text',required:true},{name:'frequencyHours',label:'Snapshot Frequency (hours)',type:'select',required:true,options:[{value:'4',label:'Every 4 hours'},{value:'6',label:'Every 6 hours'},{value:'12',label:'Every 12 hours'},{value:'24',label:'Every 24 hours'}]},{name:'userRestoreEnabled',label:'Allow User Restore',type:'checkbox',required:false,defaultValue:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Configuring snapshot schedule..." -ForegroundColor Cyan
    $Params = @{
        RestorePointSetting = @{
            FrequencyInHours = [int]"${p.frequencyHours}"
            UserRestoreEnabled = ${p.userRestoreEnabled === true ? '$true' : '$false'}
        }
    }
    Update-MgDeviceManagementVirtualEndpointUserSetting -CloudPCUserSettingId "${escapePowerShellString(p.settingId)}" -BodyParameter $Params
    Write-Host "[SUCCESS] Snapshot frequency: every ${p.frequencyHours} hours" -ForegroundColor Green
    Write-Host "User restore enabled: ${p.userRestoreEnabled === true ? 'Yes' : 'No'}" -ForegroundColor Yellow
} catch {
    Write-Error "Failed to configure snapshot schedule: $_"
}`},

  {id:'w365-auto-resize-rules',title:'Configure Auto-Resize Rules',description:'Set up automatic Cloud PC resizing based on usage',category:'Automation',isPremium:true,parameters:[{name:'policyName',label:'Policy Name',type:'text',required:true},{name:'cpuThreshold',label:'CPU Threshold (%)',type:'number',required:true,defaultValue:80},{name:'targetSize',label:'Target Size on Threshold',type:'select',required:true,options:[{value:'Medium',label:'Medium (4vCPU/16GB)'},{value:'Large',label:'Large (8vCPU/32GB)'}]},{name:'exportPath',label:'Export Config Path',type:'text',required:true,placeholder:'C:\\Exports\\AutoResizeConfig.json'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"
try {
    Write-Host "Configuring auto-resize rules..." -ForegroundColor Cyan
    # Create auto-resize configuration
    $AutoResizeConfig = @{
        PolicyName = "${escapePowerShellString(p.policyName)}"
        Triggers = @(
            @{
                MetricType = "CPU"
                Threshold = ${p.cpuThreshold}
                Operator = "GreaterThan"
                TargetServicePlan = "${p.targetSize}"
            }
        )
        EvaluationPeriodMinutes = 30
        CooldownMinutes = 60
        Enabled = $true
    }
    $AutoResizeConfig | ConvertTo-Json -Depth 10 | Out-File "${escapePowerShellString(p.exportPath)}"
    Write-Host "[SUCCESS] Auto-resize configuration exported: ${p.exportPath}" -ForegroundColor Green
    Write-Host "Note: Implement via Azure Automation runbook" -ForegroundColor Yellow
} catch {
    Write-Error "Failed to configure auto-resize: $_"
}`},

  // Security Tasks
  {id:'w365-export-security-baselines',title:'Export Security Baseline Status',description:'Export Cloud PC security baseline compliance status',category:'Security',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\SecurityBaselines.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All","DeviceManagementConfiguration.Read.All"
try {
    Write-Host "Collecting security baseline status..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $SecurityReport = foreach ($PC in $CloudPCs) {
        $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '$($PC.ManagedDeviceName)'" -ErrorAction SilentlyContinue
        [PSCustomObject]@{
            CloudPCName = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            ComplianceState = $Device.ComplianceState
            IsEncrypted = $Device.IsEncrypted
            JailBroken = $Device.JailBroken
            SecurityPatchLevel = $Device.SecurityPatchLevel
            LastSyncDateTime = $Device.LastSyncDateTime
        }
    }
    $SecurityReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Security baseline status exported: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export security baselines: $_"
}`},

  {id:'w365-conditional-access-report',title:'Export Conditional Access Policies',description:'Export conditional access policies affecting Cloud PCs',category:'Security',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\ConditionalAccess.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "Policy.Read.All"
try {
    Write-Host "Collecting conditional access policies..." -ForegroundColor Cyan
    $Policies = Get-MgIdentityConditionalAccessPolicy
    $CloudPCPolicies = $Policies | Where-Object { 
        $_.Conditions.Applications.IncludeApplications -contains 'Office365' -or
        $_.Conditions.Applications.IncludeApplications -contains 'All' -or
        $_.DisplayName -match 'Cloud PC|Windows 365|AVD'
    }
    $PolicyReport = foreach ($Policy in $CloudPCPolicies) {
        [PSCustomObject]@{
            PolicyName = $Policy.DisplayName
            State = $Policy.State
            IncludeUsers = ($Policy.Conditions.Users.IncludeUsers -join '; ')
            IncludeGroups = ($Policy.Conditions.Users.IncludeGroups -join '; ')
            GrantControls = ($Policy.GrantControls.BuiltInControls -join '; ')
            SessionControls = if ($Policy.SessionControls) { 'Configured' } else { 'None' }
        }
    }
    $PolicyReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Conditional access policies exported: ${p.exportPath}" -ForegroundColor Green
    Write-Host "Found $($CloudPCPolicies.Count) policies affecting Cloud PCs" -ForegroundColor Yellow
} catch {
    Write-Error "Failed to export conditional access policies: $_"
}`},

  {id:'w365-compliance-policy-report',title:'Export Compliance Policy Status',description:'Export Cloud PC compliance policy assignments and status',category:'Security',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\CompliancePolicies.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "DeviceManagementConfiguration.Read.All","CloudPC.Read.All"
try {
    Write-Host "Collecting compliance policy status..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $ComplianceReport = foreach ($PC in $CloudPCs) {
        $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '$($PC.ManagedDeviceName)'" -ErrorAction SilentlyContinue
        if ($Device) {
            $ComplianceStates = Get-MgDeviceManagementManagedDeviceCompliancePolicyState -ManagedDeviceId $Device.Id -ErrorAction SilentlyContinue
            foreach ($State in $ComplianceStates) {
                [PSCustomObject]@{
                    CloudPCName = $PC.DisplayName
                    UserPrincipalName = $PC.UserPrincipalName
                    PolicyName = $State.DisplayName
                    State = $State.State
                    SettingCount = $State.SettingCount
                    LastReportedDateTime = $State.LastReportedDateTime
                }
            }
        }
    }
    $ComplianceReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Compliance policy status exported: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export compliance status: $_"
}`},

  {id:'w365-encryption-status',title:'Export BitLocker Encryption Status',description:'Export Cloud PC encryption and BitLocker status',category:'Security',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\EncryptionStatus.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All","CloudPC.Read.All"
try {
    Write-Host "Collecting encryption status..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $EncryptionReport = foreach ($PC in $CloudPCs) {
        $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '$($PC.ManagedDeviceName)'" -ErrorAction SilentlyContinue
        [PSCustomObject]@{
            CloudPCName = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            IsEncrypted = $Device.IsEncrypted
            EncryptionState = $Device.EncryptionState
            StorageSpaceTotal = [math]::Round($Device.TotalStorageSpaceInBytes / 1GB, 2)
            StorageSpaceFree = [math]::Round($Device.FreeStorageSpaceInBytes / 1GB, 2)
            ComplianceState = $Device.ComplianceState
        }
    }
    $EncryptionReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Encryption status exported: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export encryption status: $_"
}`},

  {id:'w365-defender-status',title:'Export Defender Antivirus Status',description:'Export Microsoft Defender status for Cloud PCs',category:'Security',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\DefenderStatus.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "DeviceManagementManagedDevices.Read.All","CloudPC.Read.All"
try {
    Write-Host "Collecting Defender antivirus status..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $DefenderReport = foreach ($PC in $CloudPCs) {
        $Device = Get-MgDeviceManagementManagedDevice -Filter "deviceName eq '$($PC.ManagedDeviceName)'" -ErrorAction SilentlyContinue
        $WindowsProtection = Get-MgDeviceManagementManagedDeviceWindowsProtectionState -ManagedDeviceId $Device.Id -ErrorAction SilentlyContinue
        [PSCustomObject]@{
            CloudPCName = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            AntiMalwareEnabled = $WindowsProtection.AntiMalwareEnabled
            RealTimeProtectionEnabled = $WindowsProtection.RealTimeProtectionEnabled
            TamperProtectionEnabled = $WindowsProtection.TamperProtectionEnabled
            SignatureVersion = $WindowsProtection.SignatureVersion
            LastQuickScanDateTime = $WindowsProtection.LastQuickScanDateTime
            LastFullScanDateTime = $WindowsProtection.LastFullScanDateTime
            MalwareProtectionEnabled = $WindowsProtection.MalwareProtectionEnabled
        }
    }
    $DefenderReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Defender status exported: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export Defender status: $_"
}`},

  {id:'w365-security-alerts',title:'Export Security Alerts',description:'Export security alerts for Cloud PC devices',category:'Security',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\SecurityAlerts.csv'},{name:'days',label:'Days Back',type:'number',required:true,defaultValue:30}],scriptTemplate:p=>`Connect-MgGraph -Scopes "SecurityEvents.Read.All","CloudPC.Read.All"
try {
    Write-Host "Collecting security alerts..." -ForegroundColor Cyan
    $StartDate = (Get-Date).AddDays(-${p.days}).ToString('yyyy-MM-ddTHH:mm:ssZ')
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $ManagedDeviceNames = $CloudPCs.ManagedDeviceName
    $Alerts = Get-MgSecurityAlert -Filter "createdDateTime ge $StartDate"
    $CloudPCAlerts = $Alerts | Where-Object { 
        $_.HostStates.NetBiosName -in $ManagedDeviceNames -or
        $_.Title -match 'Cloud PC|Windows 365'
    }
    $AlertReport = foreach ($Alert in $CloudPCAlerts) {
        [PSCustomObject]@{
            Title = $Alert.Title
            Severity = $Alert.Severity
            Status = $Alert.Status
            Category = $Alert.Category
            CreatedDateTime = $Alert.CreatedDateTime
            DeviceName = $Alert.HostStates.NetBiosName
            Description = $Alert.Description
            RecommendedActions = ($Alert.RecommendedActions -join '; ')
        }
    }
    $AlertReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Security alerts exported (${p.days} days): ${p.exportPath}" -ForegroundColor Green
    Write-Host "Found $($CloudPCAlerts.Count) security alerts" -ForegroundColor Yellow
} catch {
    Write-Error "Failed to export security alerts: $_"
}`},

  {id:'w365-mfa-status',title:'Export MFA Enrollment Status',description:'Export MFA enrollment status for Cloud PC users',category:'Security',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\MFAStatus.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "UserAuthenticationMethod.Read.All","CloudPC.Read.All"
try {
    Write-Host "Collecting MFA enrollment status..." -ForegroundColor Cyan
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $UniqueUsers = $CloudPCs | Select-Object -ExpandProperty UserPrincipalName -Unique
    $MFAReport = foreach ($UserUPN in $UniqueUsers) {
        $User = Get-MgUser -Filter "userPrincipalName eq '$UserUPN'" -ErrorAction SilentlyContinue
        if ($User) {
            $AuthMethods = Get-MgUserAuthenticationMethod -UserId $User.Id -ErrorAction SilentlyContinue
            $HasMFA = ($AuthMethods | Where-Object { $_.AdditionalProperties.'@odata.type' -ne '#microsoft.graph.passwordAuthenticationMethod' }).Count -gt 0
            [PSCustomObject]@{
                UserPrincipalName = $UserUPN
                DisplayName = $User.DisplayName
                MFAEnabled = $HasMFA
                AuthMethodCount = $AuthMethods.Count
                AuthMethods = ($AuthMethods | ForEach-Object { $_.AdditionalProperties.'@odata.type' -replace '#microsoft.graph.','' }) -join '; '
                CloudPCCount = ($CloudPCs | Where-Object UserPrincipalName -eq $UserUPN).Count
            }
        }
    }
    $MFAReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] MFA status exported: ${p.exportPath}" -ForegroundColor Green
} catch {
    Write-Error "Failed to export MFA status: $_"
}`},

  {id:'w365-sign-in-risk-report',title:'Export Sign-In Risk Events',description:'Export risky sign-in events for Cloud PC users',category:'Security',isPremium:true,parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true,placeholder:'C:\\Exports\\SignInRisk.csv'},{name:'days',label:'Days Back',type:'number',required:true,defaultValue:7}],scriptTemplate:p=>`Connect-MgGraph -Scopes "IdentityRiskEvent.Read.All","CloudPC.Read.All"
try {
    Write-Host "Collecting sign-in risk events..." -ForegroundColor Cyan
    $StartDate = (Get-Date).AddDays(-${p.days}).ToString('yyyy-MM-ddTHH:mm:ssZ')
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    $CloudPCUsers = $CloudPCs | Select-Object -ExpandProperty UserPrincipalName -Unique
    $RiskySignIns = Get-MgRiskySignIn -Filter "createdDateTime ge $StartDate" | Where-Object {
        $_.UserPrincipalName -in $CloudPCUsers
    }
    $RiskReport = foreach ($SignIn in $RiskySignIns) {
        [PSCustomObject]@{
            UserPrincipalName = $SignIn.UserPrincipalName
            CreatedDateTime = $SignIn.CreatedDateTime
            RiskLevel = $SignIn.RiskLevel
            RiskState = $SignIn.RiskState
            RiskDetail = $SignIn.RiskDetail
            IPAddress = $SignIn.IpAddress
            Location = "$($SignIn.Location.City), $($SignIn.Location.CountryOrRegion)"
            AppDisplayName = $SignIn.AppDisplayName
        }
    }
    $RiskReport | Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation
    Write-Host "[SUCCESS] Sign-in risk events exported (${p.days} days): ${p.exportPath}" -ForegroundColor Green
    Write-Host "Found $($RiskySignIns.Count) risky sign-in events" -ForegroundColor Yellow
} catch {
    Write-Error "Failed to export sign-in risk events: $_"
}`}
];

export const windows365Categories = [
  'Cloud PC Management',
  'Provisioning',
  'User Settings',
  'Images',
  'Monitoring',
  'Network',
  'Security',
  'Troubleshooting',
  'Automation'
];
