import { escapePowerShellString } from './powershell-utils';

export interface WindowsServerParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface WindowsServerTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: WindowsServerParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const windowsServerTasks: WindowsServerTask[] = [
  {
    id: 'ws-export-server-inventory',
    title: 'Export Server Inventory',
    description: 'Export comprehensive server inventory from multiple servers to CSV',
    category: 'Server Management',
    parameters: [
      {
        name: 'serverNames',
        label: 'Server Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'SERVER01\nSERVER02',
        helpText: 'List of server names'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ServerInventory.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverNamesInput = params.serverNames.trim();
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Server Inventory
# Generated by PSForge

$Servers = @(
${serverNamesInput.split('\n').filter((line: string) => line.trim()).map((name: string) => `    "${escapePowerShellString(name.trim())}"`).join('\n')}
)

try {
    Write-Host "Collecting server inventory..." -ForegroundColor Cyan
    
    $Inventory = foreach ($Server in $Servers) {
        try {
            $OS = Get-WmiObject -Class Win32_OperatingSystem -ComputerName $Server
            $CS = Get-WmiObject -Class Win32_ComputerSystem -ComputerName $Server
            
            [PSCustomObject]@{
                ServerName       = $Server
                OperatingSystem  = $OS.Caption
                OSVersion        = $OS.Version
                Manufacturer     = $CS.Manufacturer
                Model            = $CS.Model
                TotalMemoryGB    = [math]::Round($CS.TotalPhysicalMemory / 1GB, 2)
                Domain           = $CS.Domain
            }
        } catch {
            Write-Warning "Failed to collect data from: $Server"
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Server inventory exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export server inventory: $_"
}`;
    }
  },

  {
    id: 'ws-export-installed-roles',
    title: 'Export Installed Roles and Features',
    description: 'Export installed Windows Server roles and features to CSV',
    category: 'Roles & Features',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'SERVER01',
        helpText: 'Name of the server'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\InstalledRoles.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Installed Roles and Features
# Generated by PSForge

try {
    Write-Host "Collecting installed roles and features from: ${serverName}" -ForegroundColor Cyan
    
    $Features = Get-WindowsFeature -ComputerName "${serverName}" | Where-Object { $_.Installed -eq $true }
    
    Write-Host "Found $($Features.Count) installed features" -ForegroundColor Yellow
    
    $FeatureReport = foreach ($Feature in $Features) {
        [PSCustomObject]@{
            DisplayName      = $Feature.DisplayName
            Name             = $Feature.Name
            FeatureType      = $Feature.FeatureType
            InstallState     = $Feature.InstallState
        }
    }
    
    $FeatureReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Roles and features exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export roles and features: $_"
}`;
    }
  },

  {
    id: 'ws-export-event-logs',
    title: 'Export Event Logs',
    description: 'Export recent event logs from a Windows Server to CSV',
    category: 'Event Logs',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'SERVER01',
        helpText: 'Name of the server'
      },
      {
        name: 'logName',
        label: 'Log Name',
        type: 'select',
        required: true,
        options: [
          { value: 'System', label: 'System' },
          { value: 'Application', label: 'Application' },
          { value: 'Security', label: 'Security' }
        ],
        defaultValue: 'System',
        helpText: 'Event log to export'
      },
      {
        name: 'hours',
        label: 'Last Hours',
        type: 'number',
        required: true,
        defaultValue: 24,
        helpText: 'Export events from the last N hours'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\EventLogs.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const logName = params.logName;
      const hours = params.hours || 24;
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Event Logs
# Generated by PSForge

try {
    Write-Host "Collecting ${logName} event logs from: ${serverName}" -ForegroundColor Cyan
    
    $StartTime = (Get-Date).AddHours(-${hours})
    
    $Events = Get-WinEvent -ComputerName "${serverName}" -FilterHashtable @{
        LogName = "${logName}"
        StartTime = $StartTime
    } -MaxEvents 1000 -ErrorAction Stop
    
    Write-Host "Found $($Events.Count) events" -ForegroundColor Yellow
    
    $EventReport = foreach ($Event in $Events) {
        [PSCustomObject]@{
            TimeCreated      = $Event.TimeCreated
            Level            = $Event.LevelDisplayName
            Source           = $Event.ProviderName
            EventID          = $Event.Id
            Message          = $Event.Message
        }
    }
    
    $EventReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Event logs exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export event logs: $_"
}`;
    }
  },

  {
    id: 'ws-export-services',
    title: 'Export Services Status',
    description: 'Export Windows services status from a server to CSV',
    category: 'Services',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'SERVER01',
        helpText: 'Name of the server'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\Services.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Services Status
# Generated by PSForge

try {
    Write-Host "Collecting services from: ${serverName}" -ForegroundColor Cyan
    
    $Services = Get-Service -ComputerName "${serverName}"
    
    Write-Host "Found $($Services.Count) services" -ForegroundColor Yellow
    
    $ServiceReport = foreach ($Service in $Services) {
        [PSCustomObject]@{
            ServiceName      = $Service.Name
            DisplayName      = $Service.DisplayName
            Status           = $Service.Status
            StartType        = $Service.StartType
        }
    }
    
    $ServiceReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Services exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export services: $_"
}`;
    }
  },

  {
    id: 'ws-export-disk-usage',
    title: 'Export Disk Usage',
    description: 'Export disk usage information from a server to CSV',
    category: 'Storage',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'SERVER01',
        helpText: 'Name of the server'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\DiskUsage.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Disk Usage
# Generated by PSForge

try {
    Write-Host "Collecting disk usage from: ${serverName}" -ForegroundColor Cyan
    
    $Disks = Get-WmiObject -Class Win32_LogicalDisk -ComputerName "${serverName}" -Filter "DriveType=3"
    
    $DiskReport = foreach ($Disk in $Disks) {
        $PercentFree = if ($Disk.Size -gt 0) {
            [math]::Round(($Disk.FreeSpace / $Disk.Size) * 100, 2)
        } else { 0 }
        
        [PSCustomObject]@{
            DriveLetter      = $Disk.DeviceID
            VolumeName       = $Disk.VolumeName
            SizeGB           = [math]::Round($Disk.Size / 1GB, 2)
            FreeSpaceGB      = [math]::Round($Disk.FreeSpace / 1GB, 2)
            PercentFree      = $PercentFree
        }
    }
    
    $DiskReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Disk usage exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export disk usage: $_"
}`;
    }
  }
];

export const windowsServerCategories = [
  'Server Management',
  'Roles & Features',
  'Event Logs',
  'Services',
  'Storage'
];
