import { escapePowerShellString } from './powershell-utils';

export interface Windows365Parameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface Windows365Task {
  id: string;
  title: string;
  description: string;
  category: string;
  instructions?: string;
  parameters: Windows365Parameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const windows365Tasks: Windows365Task[] = [
  {
    id: 'w365-export-cloud-pcs',
    title: 'Export Cloud PC Inventory',
    description: 'Export list of all Windows 365 Cloud PCs to CSV',
    category: 'Cloud PC Management',
    instructions: `**How This Task Works:**
- Exports comprehensive Windows 365 Cloud PC inventory
- Supports license management and user provisioning tracking
- Shows all Cloud PCs and their assignment status

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all Cloud PCs in tenant
3. Collects user, status, image, and device details
4. Exports Cloud PC inventory to CSV

**Important Notes:**
- Essential for Cloud PC license management
- Shows all provisioned Cloud PCs and assignments
- Use for user provisioning tracking
- Run monthly for license utilization audits
- Identify unassigned or failed Cloud PCs
- Typical use: license optimization, capacity planning
- Deprovision unused Cloud PCs to reduce costs
- Monitor provisioning success rates`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\CloudPCs.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Windows 365 Cloud PC Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting Cloud PCs..." -ForegroundColor Cyan
    
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    
    Write-Host "Found $($CloudPCs.Count) Cloud PCs" -ForegroundColor Yellow
    
    $PCReport = foreach ($PC in $CloudPCs) {
        [PSCustomObject]@{
            DisplayName      = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            Status           = $PC.Status
            ImageDisplayName = $PC.ImageDisplayName
            ManagedDeviceName = $PC.ManagedDeviceName
        }
    }
    
    $PCReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Cloud PCs exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export Cloud PCs: $_"
}`;
    }
  },

  {
    id: 'w365-export-provisioning-policies',
    title: 'Export Provisioning Policies',
    description: 'Export Windows 365 provisioning policies to CSV',
    category: 'Provisioning',
    instructions: `**How This Task Works:**
- Exports Cloud PC provisioning policy inventory
- Supports standardization and configuration management
- Shows all policies and their configurations

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all provisioning policies
3. Collects policy name, description, and image type
4. Exports policy inventory to CSV

**Important Notes:**
- Essential for Cloud PC standardization
- Shows all provisioning policies and configurations
- Use for policy governance and management
- Run quarterly for policy reviews
- Consolidate duplicate policies
- Typical use: policy audits, standardization
- Align policies with department requirements
- Document policy assignments to user groups`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ProvisioningPolicies.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Provisioning Policies
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting provisioning policies..." -ForegroundColor Cyan
    
    $Policies = Get-MgDeviceManagementVirtualEndpointProvisioningPolicy
    
    Write-Host "Found $($Policies.Count) policies" -ForegroundColor Yellow
    
    $PolicyReport = foreach ($Policy in $Policies) {
        [PSCustomObject]@{
            DisplayName      = $Policy.DisplayName
            Description      = $Policy.Description
            ImageType        = $Policy.ImageType
        }
    }
    
    $PolicyReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Provisioning policies exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export provisioning policies: $_"
}`;
    }
  },

  {
    id: 'w365-export-user-settings',
    title: 'Export User Settings Policies',
    description: 'Export Windows 365 user settings policies to CSV',
    category: 'User Settings',
    instructions: `**How This Task Works:**
- Exports user self-service settings
- Supports Cloud PC governance and support model documentation
- Shows self-service capabilities enabled for users

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all user settings policies
3. Collects policy name and self-service options
4. Exports user settings inventory to CSV

**Important Notes:**
- Essential for Cloud PC user experience governance
- Shows self-service capabilities enabled for users
- Use for support model documentation
- Run quarterly for policy reviews
- Balance user autonomy with IT control
- Typical use: support planning, user empowerment
- Enable self-service to reduce helpdesk load
- Restrict sensitive operations to IT only`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\UserSettings.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export User Settings Policies
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting user settings policies..." -ForegroundColor Cyan
    
    $UserSettings = Get-MgDeviceManagementVirtualEndpointUserSetting
    
    Write-Host "Found $($UserSettings.Count) user settings" -ForegroundColor Yellow
    
    $SettingsReport = foreach ($Setting in $UserSettings) {
        [PSCustomObject]@{
            DisplayName      = $Setting.DisplayName
            SelfServiceEnabled = $Setting.SelfServiceEnabled
        }
    }
    
    $SettingsReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ User settings exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export user settings: $_"
}`;
    }
  },

  {
    id: 'w365-export-gallery-images',
    title: 'Export Gallery Images',
    description: 'Export Windows 365 gallery images to CSV',
    category: 'Images',
    instructions: `**How This Task Works:**
- Exports available gallery image inventory
- Supports Cloud PC image selection and standardization planning
- Shows all Windows images available from Azure

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all gallery images
3. Collects image name, publisher, offer, and SKU
4. Exports gallery image catalog to CSV

**Important Notes:**
- Essential for Cloud PC image management
- Shows all available Windows images from Azure
- Use for image selection and planning
- Run when planning new deployments
- Identify latest OS versions
- Typical use: deployment planning, standardization
- Use Windows 11 for new deployments
- Match image to user requirements`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\GalleryImages.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Gallery Images
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting gallery images..." -ForegroundColor Cyan
    
    $Images = Get-MgDeviceManagementVirtualEndpointGalleryImage
    
    Write-Host "Found $($Images.Count) gallery images" -ForegroundColor Yellow
    
    $ImageReport = foreach ($Image in $Images) {
        [PSCustomObject]@{
            DisplayName      = $Image.DisplayName
            Publisher        = $Image.Publisher
            Offer            = $Image.Offer
            Sku              = $Image.Sku
        }
    }
    
    $ImageReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Gallery images exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export gallery images: $_"
}`;
    }
  },

  {
    id: 'w365-export-connection-report',
    title: 'Export Connection Quality Report',
    description: 'Export Cloud PC connection quality metrics to CSV',
    category: 'Monitoring',
    instructions: `**How This Task Works:**
- Exports Cloud PC connection quality metrics
- Supports user experience monitoring and troubleshooting
- Shows connectivity and health status for all Cloud PCs

**Prerequisites:**
- Microsoft Graph PowerShell module installed
- CloudPC.Read.All permission
- Windows 365 Administrator or Global Administrator role

**What You Need to Provide:**
- CSV export file path

**What the Script Does:**
1. Connects to Microsoft Graph
2. Retrieves all Cloud PCs with connection data
3. Collects user, status, and last action results
4. Exports connection quality report to CSV

**Important Notes:**
- Essential for user experience monitoring
- Shows Cloud PC connectivity and health status
- Use for proactive troubleshooting
- Run weekly for connection quality tracking
- Identify users with connectivity issues
- Typical use: helpdesk troubleshooting, monitoring
- Investigate failed connections immediately
- Monitor for network performance degradation`,
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ConnectionReport.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Connection Quality Report
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting connection quality data..." -ForegroundColor Cyan
    
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    
    $ConnectionReport = foreach ($PC in $CloudPCs) {
        [PSCustomObject]@{
            DisplayName      = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            Status           = $PC.Status
            LastRemoteActionResult = $PC.LastRemoteActionResult
        }
    }
    
    $ConnectionReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Connection report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export connection report: $_"
}`;
    }
  },
  {id:'w365-reprovision',title:'Reprovision Cloud PC',description:'Rebuild existing Cloud PC',category:'Cloud PC Management',parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgReprovisionDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}";Write-Host "✓ Reprovision started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-resize',title:'Resize Cloud PC',description:'Change Cloud PC size/SKU',category:'Cloud PC Management',parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'targetSize',label:'Target Size',type:'select',required:true,options:[{value:'Small',label:'Small (2vCPU/8GB)'},{value:'Medium',label:'Medium (4vCPU/16GB)'},{value:'Large',label:'Large (8vCPU/32GB)'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgResizeDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -TargetServicePlanId "${p.targetSize}";Write-Host "✓ Resize initiated to ${p.targetSize}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-restart',title:'Restart Cloud PC',description:'Reboot Cloud PC',category:'Cloud PC Management',parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgRestartDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}";Write-Host "✓ Restart initiated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-troubleshoot',title:'Run Cloud PC Diagnostics',description:'Collect diagnostic data',category:'Monitoring',parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgTroubleshootDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}";Write-Host "✓ Diagnostics started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-bulk-provision',title:'Bulk Provision Cloud PCs',description:'Create multiple Cloud PCs from CSV',category:'Provisioning',parameters:[{name:'csvPath',label:'CSV Path',type:'text',required:true,placeholder:'C:\\\\Users.csv'}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{$Users=Import-Csv "${escapePowerShellString(p.csvPath)}";foreach($U in $Users){New-MgDeviceManagementVirtualEndpointCloudPC -UserPrincipalName $U.Email};Write-Host "✓ Bulk provisioning started for $($Users.Count) users" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-set-grace',title:'Set Grace Period',description:'Configure grace period before deprovision',category:'Provisioning',parameters:[{name:'days',label:'Grace Period (days)',type:'number',required:true,defaultValue:7}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointOrganizationSetting -GracePeriodInDays ${p.days};Write-Host "✓ Grace period set to ${p.days} days" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-create-policy',title:'Create Provisioning Policy',description:'New Cloud PC provisioning policy',category:'Provisioning',parameters:[{name:'policyName',label:'Policy Name',type:'text',required:true},{name:'imageId',label:'Image ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{$Params=@{DisplayName="${escapePowerShellString(p.policyName)}";ImageId="${escapePowerShellString(p.imageId)}"};New-MgDeviceManagementVirtualEndpointProvisioningPolicy -BodyParameter $Params;Write-Host "✓ Policy created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-assign-policy',title:'Assign Provisioning Policy',description:'Assign policy to group',category:'Provisioning',parameters:[{name:'policyId',label:'Policy ID',type:'text',required:true},{name:'groupId',label:'Group ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{New-MgDeviceManagementVirtualEndpointProvisioningPolicyAssignment -ProvisioningPolicyId "${escapePowerShellString(p.policyId)}" -Target @{GroupId="${escapePowerShellString(p.groupId)}"};Write-Host "✓ Policy assigned to group" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-upload-image',title:'Upload Custom Image',description:'Upload custom OS image',category:'Images',parameters:[{name:'imagePath',label:'Image Path',type:'text',required:true},{name:'imageName',label:'Image Name',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{$Params=@{DisplayName="${escapePowerShellString(p.imageName)}";SourceImagePath="${escapePowerShellString(p.imagePath)}"};New-MgDeviceManagementVirtualEndpointDeviceImage -BodyParameter $Params;Write-Host "✓ Image upload started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-delete-image',title:'Delete Custom Image',description:'Remove custom image',category:'Images',parameters:[{name:'imageId',label:'Image ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Remove-MgDeviceManagementVirtualEndpointDeviceImage -DeviceImageId "${escapePowerShellString(p.imageId)}";Write-Host "✓ Image deleted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-export-images',title:'Export Image Inventory',description:'List all available images',category:'Images',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{Get-MgDeviceManagementVirtualEndpointDeviceImage|Select DisplayName,Id,Version,Status|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Images exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-set-user-settings',title:'Configure User Settings',description:'Set user self-service options',category:'User Settings',parameters:[{name:'allowRestart',label:'Allow User Restart',type:'checkbox',required:false,defaultValue:true},{name:'allowReset',label:'Allow User Reset',type:'checkbox',required:false,defaultValue:false}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointUserSetting -RestorePointPreference @{RestartEnabled=\\$${p.allowRestart!==false};ResetEnabled=\\$${p.allowReset===true}};Write-Host "✓ User settings updated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-export-audit',title:'Export Audit Logs',description:'Cloud PC activity audit trail',category:'Monitoring',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'days',label:'Days Back',type:'number',required:false,defaultValue:30}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All","AuditLog.Read.All"\ntry{$StartDate=(Get-Date).AddDays(-${p.days});Get-MgAuditLogDirectoryAudit -Filter "activityDateTime ge $($StartDate.ToString('yyyy-MM-ddTHH:mm:ssZ')) and category eq 'CloudPC'"|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Audit logs exported (${p.days} days)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-health-check',title:'Health Check Report',description:'System health status',category:'Monitoring',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{$PCs=Get-MgDeviceManagementVirtualEndpointCloudPC;$Health=$PCs|Select DisplayName,Status,@{N='Health';E={$_.HealthCheckStatus}};$Health|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Health check completed" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-rename',title:'Rename Cloud PC',description:'Change Cloud PC display name',category:'Cloud PC Management',parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'newName',label:'New Name',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointCloudPC -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -DisplayName "${escapePowerShellString(p.newName)}";Write-Host "✓ Cloud PC renamed to ${p.newName}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-snapshot',title:'Create Recovery Point',description:'Create Cloud PC snapshot',category:'Cloud PC Management',parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{New-MgDeviceManagementVirtualEndpointCloudPCSnapshot -CloudPCId "${escapePowerShellString(p.cloudPcId)}";Write-Host "✓ Snapshot created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-restore-point',title:'Restore from Snapshot',description:'Restore Cloud PC to snapshot',category:'Cloud PC Management',parameters:[{name:'cloudPcId',label:'Cloud PC ID',type:'text',required:true},{name:'snapshotId',label:'Snapshot ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Invoke-MgRestoreDeviceManagementVirtualEndpointCloudPCSnapshot -CloudPCId "${escapePowerShellString(p.cloudPcId)}" -SnapshotId "${escapePowerShellString(p.snapshotId)}";Write-Host "✓ Restore initiated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-network-config',title:'Configure Network Settings',description:'Update Cloud PC networking',category:'Provisioning',parameters:[{name:'vnetId',label:'VNet ID',type:'text',required:true},{name:'subnetId',label:'Subnet ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointNetworkConnection -VirtualNetworkId "${escapePowerShellString(p.vnetId)}" -SubnetId "${escapePowerShellString(p.subnetId)}";Write-Host "✓ Network configured" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-license-report',title:'Export License Usage',description:'Cloud PC license consumption',category:'Monitoring',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{$PCs=Get-MgDeviceManagementVirtualEndpointCloudPC;$Licenses=$PCs|Group-Object ServicePlanId|Select Name,Count;$Licenses|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ License report exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-set-retention',title:'Set Snapshot Retention',description:'Configure snapshot retention policy',category:'User Settings',parameters:[{name:'days',label:'Retention Days',type:'number',required:true,defaultValue:30}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointOrganizationSetting -SnapshotRetentionInDays ${p.days};Write-Host "✓ Retention set to ${p.days} days" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-performance-report',title:'Export Performance Metrics',description:'Cloud PC performance data',category:'Monitoring',parameters:[{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'days',label:'Days',type:'number',required:false,defaultValue:7}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{$Report=Get-MgReportCloudPCPerformance -Period "D${p.days}";$Report|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Performance data exported (${p.days} days)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-bulk-resize',title:'Bulk Resize Cloud PCs',description:'Resize multiple Cloud PCs',category:'Cloud PC Management',parameters:[{name:'csvPath',label:'CSV Path',type:'text',required:true},{name:'targetSize',label:'Target Size',type:'select',required:true,options:[{value:'Small',label:'Small'},{value:'Medium',label:'Medium'},{value:'Large',label:'Large'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{$PCs=Import-Csv "${escapePowerShellString(p.csvPath)}";foreach($PC in $PCs){Invoke-MgResizeDeviceManagementVirtualEndpointCloudPC -CloudPCId $PC.Id -TargetServicePlanId "${p.targetSize}"};Write-Host "✓ Bulk resize started for $($PCs.Count) Cloud PCs" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-region-config',title:'Configure Region Settings',description:'Set Azure region preferences',category:'Provisioning',parameters:[{name:'region',label:'Azure Region',type:'select',required:true,options:[{value:'eastus',label:'East US'},{value:'westus',label:'West US'},{value:'westeurope',label:'West Europe'},{value:'southeastasia',label:'Southeast Asia'}]}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointProvisioningPolicy -AzureRegion "${p.region}";Write-Host "✓ Region set to ${p.region}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-gallery-image',title:'Use Gallery Image',description:'Deploy from Azure gallery',category:'Images',parameters:[{name:'galleryImageId',label:'Gallery Image ID',type:'text',required:true},{name:'policyId',label:'Policy ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.ReadWrite.All"\ntry{Update-MgDeviceManagementVirtualEndpointProvisioningPolicy -ProvisioningPolicyId "${escapePowerShellString(p.policyId)}" -ImageId "${escapePowerShellString(p.galleryImageId)}" -ImageType "Gallery";Write-Host "✓ Gallery image configured" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'w365-network-check',title:'Test Network Connection',description:'Verify Cloud PC network health',category:'Monitoring',parameters:[{name:'cloudPCId',label:'Cloud PC ID',type:'text',required:true}],scriptTemplate:p=>`Connect-MgGraph -Scopes "CloudPC.Read.All"\ntry{$Health=Get-MgDeviceManagementVirtualEndpointCloudPCConnectivityResult -CloudPCId "${escapePowerShellString(p.cloudPCId)}";Write-Host "✓ Network Status: $($Health.Status)" -ForegroundColor Green}catch{Write-Error $_}`}
];

export const windows365Categories = [
  'Cloud PC Management',
  'Provisioning',
  'User Settings',
  'Images',
  'Monitoring'
];
