import { escapePowerShellString } from './powershell-utils';

export interface Windows365Parameter {
  title: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface Windows365Task {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: Windows365Parameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const windows365Tasks: Windows365Task[] = [
  {
    id: 'w365-export-cloud-pcs',
    title: 'Export Cloud PC Inventory',
    description: 'Export list of all Windows 365 Cloud PCs to CSV',
    category: 'Cloud PC Management',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\CloudPCs.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Windows 365 Cloud PC Inventory
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting Cloud PCs..." -ForegroundColor Cyan
    
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    
    Write-Host "Found $($CloudPCs.Count) Cloud PCs" -ForegroundColor Yellow
    
    $PCReport = foreach ($PC in $CloudPCs) {
        [PSCustomObject]@{
            DisplayName      = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            Status           = $PC.Status
            ImageDisplayName = $PC.ImageDisplayName
            ManagedDeviceName = $PC.ManagedDeviceName
        }
    }
    
    $PCReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Cloud PCs exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export Cloud PCs: $_"
}`;
    }
  },

  {
    id: 'w365-export-provisioning-policies',
    title: 'Export Provisioning Policies',
    description: 'Export Windows 365 provisioning policies to CSV',
    category: 'Provisioning',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ProvisioningPolicies.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Provisioning Policies
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting provisioning policies..." -ForegroundColor Cyan
    
    $Policies = Get-MgDeviceManagementVirtualEndpointProvisioningPolicy
    
    Write-Host "Found $($Policies.Count) policies" -ForegroundColor Yellow
    
    $PolicyReport = foreach ($Policy in $Policies) {
        [PSCustomObject]@{
            DisplayName      = $Policy.DisplayName
            Description      = $Policy.Description
            ImageType        = $Policy.ImageType
        }
    }
    
    $PolicyReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Provisioning policies exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export provisioning policies: $_"
}`;
    }
  },

  {
    id: 'w365-export-user-settings',
    title: 'Export User Settings Policies',
    description: 'Export Windows 365 user settings policies to CSV',
    category: 'User Settings',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\UserSettings.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export User Settings Policies
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting user settings policies..." -ForegroundColor Cyan
    
    $UserSettings = Get-MgDeviceManagementVirtualEndpointUserSetting
    
    Write-Host "Found $($UserSettings.Count) user settings" -ForegroundColor Yellow
    
    $SettingsReport = foreach ($Setting in $UserSettings) {
        [PSCustomObject]@{
            DisplayName      = $Setting.DisplayName
            SelfServiceEnabled = $Setting.SelfServiceEnabled
        }
    }
    
    $SettingsReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ User settings exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export user settings: $_"
}`;
    }
  },

  {
    id: 'w365-export-gallery-images',
    title: 'Export Gallery Images',
    description: 'Export Windows 365 gallery images to CSV',
    category: 'Images',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\GalleryImages.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Gallery Images
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting gallery images..." -ForegroundColor Cyan
    
    $Images = Get-MgDeviceManagementVirtualEndpointGalleryImage
    
    Write-Host "Found $($Images.Count) gallery images" -ForegroundColor Yellow
    
    $ImageReport = foreach ($Image in $Images) {
        [PSCustomObject]@{
            DisplayName      = $Image.DisplayName
            Publisher        = $Image.Publisher
            Offer            = $Image.Offer
            Sku              = $Image.Sku
        }
    }
    
    $ImageReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Gallery images exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export gallery images: $_"
}`;
    }
  },

  {
    id: 'w365-export-connection-report',
    title: 'Export Connection Quality Report',
    description: 'Export Cloud PC connection quality metrics to CSV',
    category: 'Monitoring',
    parameters: [
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ConnectionReport.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Connection Quality Report
# Generated by PSForge

Connect-MgGraph -Scopes "CloudPC.Read.All"

try {
    Write-Host "Collecting connection quality data..." -ForegroundColor Cyan
    
    $CloudPCs = Get-MgDeviceManagementVirtualEndpointCloudPC
    
    $ConnectionReport = foreach ($PC in $CloudPCs) {
        [PSCustomObject]@{
            DisplayName      = $PC.DisplayName
            UserPrincipalName = $PC.UserPrincipalName
            Status           = $PC.Status
            LastRemoteActionResult = $PC.LastRemoteActionResult
        }
    }
    
    $ConnectionReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Connection report exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export connection report: $_"
}`;
    }
  }
];

export const windows365Categories = [
  'Cloud PC Management',
  'Provisioning',
  'User Settings',
  'Images',
  'Monitoring'
];
