import { escapePowerShellString } from './powershell-utils';

export interface WindowsServerParameter {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'checkbox' | 'textarea';
  required: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
  defaultValue?: string | number | boolean;
  helpText?: string;
}

export interface WindowsServerTask {
  id: string;
  title: string;
  description: string;
  category: string;
  parameters: WindowsServerParameter[];
  scriptTemplate: (params: Record<string, any>) => string;
}

export const windowsServerTasks: WindowsServerTask[] = [
  {
    id: 'ws-export-server-inventory',
    title: 'Export Server Inventory',
    description: 'Export comprehensive server inventory from multiple servers to CSV',
    category: 'Server Management',
    parameters: [
      {
        name: 'serverNames',
        label: 'Server Names (one per line)',
        type: 'textarea',
        required: true,
        placeholder: 'SERVER01\nSERVER02',
        helpText: 'List of server names'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\ServerInventory.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverNamesInput = params.serverNames.trim();
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Server Inventory
# Generated by PSForge

$Servers = @(
${serverNamesInput.split('\n').filter((line: string) => line.trim()).map((name: string) => `    "${escapePowerShellString(name.trim())}"`).join('\n')}
)

try {
    Write-Host "Collecting server inventory..." -ForegroundColor Cyan
    
    $Inventory = foreach ($Server in $Servers) {
        try {
            $OS = Get-WmiObject -Class Win32_OperatingSystem -ComputerName $Server
            $CS = Get-WmiObject -Class Win32_ComputerSystem -ComputerName $Server
            
            [PSCustomObject]@{
                ServerName       = $Server
                OperatingSystem  = $OS.Caption
                OSVersion        = $OS.Version
                Manufacturer     = $CS.Manufacturer
                Model            = $CS.Model
                TotalMemoryGB    = [math]::Round($CS.TotalPhysicalMemory / 1GB, 2)
                Domain           = $CS.Domain
            }
        } catch {
            Write-Warning "Failed to collect data from: $Server"
        }
    }
    
    $Inventory | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Server inventory exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export server inventory: $_"
}`;
    }
  },

  {
    id: 'ws-export-installed-roles',
    title: 'Export Installed Roles and Features',
    description: 'Export installed Windows Server roles and features to CSV',
    category: 'Roles & Features',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'SERVER01',
        helpText: 'Name of the server'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\InstalledRoles.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Installed Roles and Features
# Generated by PSForge

try {
    Write-Host "Collecting installed roles and features from: ${serverName}" -ForegroundColor Cyan
    
    $Features = Get-WindowsFeature -ComputerName "${serverName}" | Where-Object { $_.Installed -eq $true }
    
    Write-Host "Found $($Features.Count) installed features" -ForegroundColor Yellow
    
    $FeatureReport = foreach ($Feature in $Features) {
        [PSCustomObject]@{
            DisplayName      = $Feature.DisplayName
            Name             = $Feature.Name
            FeatureType      = $Feature.FeatureType
            InstallState     = $Feature.InstallState
        }
    }
    
    $FeatureReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Roles and features exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export roles and features: $_"
}`;
    }
  },

  {
    id: 'ws-export-event-logs',
    title: 'Export Event Logs',
    description: 'Export recent event logs from a Windows Server to CSV',
    category: 'Event Logs',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'SERVER01',
        helpText: 'Name of the server'
      },
      {
        name: 'logName',
        label: 'Log Name',
        type: 'select',
        required: true,
        options: [
          { value: 'System', label: 'System' },
          { value: 'Application', label: 'Application' },
          { value: 'Security', label: 'Security' }
        ],
        defaultValue: 'System',
        helpText: 'Event log to export'
      },
      {
        name: 'hours',
        label: 'Last Hours',
        type: 'number',
        required: true,
        defaultValue: 24,
        helpText: 'Export events from the last N hours'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\EventLogs.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const logName = params.logName;
      const hours = params.hours || 24;
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Event Logs
# Generated by PSForge

try {
    Write-Host "Collecting ${logName} event logs from: ${serverName}" -ForegroundColor Cyan
    
    $StartTime = (Get-Date).AddHours(-${hours})
    
    $Events = Get-WinEvent -ComputerName "${serverName}" -FilterHashtable @{
        LogName = "${logName}"
        StartTime = $StartTime
    } -MaxEvents 1000 -ErrorAction Stop
    
    Write-Host "Found $($Events.Count) events" -ForegroundColor Yellow
    
    $EventReport = foreach ($Event in $Events) {
        [PSCustomObject]@{
            TimeCreated      = $Event.TimeCreated
            Level            = $Event.LevelDisplayName
            Source           = $Event.ProviderName
            EventID          = $Event.Id
            Message          = $Event.Message
        }
    }
    
    $EventReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Event logs exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export event logs: $_"
}`;
    }
  },

  {
    id: 'ws-export-services',
    title: 'Export Services Status',
    description: 'Export Windows services status from a server to CSV',
    category: 'Services',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'SERVER01',
        helpText: 'Name of the server'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\Services.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Services Status
# Generated by PSForge

try {
    Write-Host "Collecting services from: ${serverName}" -ForegroundColor Cyan
    
    $Services = Get-Service -ComputerName "${serverName}"
    
    Write-Host "Found $($Services.Count) services" -ForegroundColor Yellow
    
    $ServiceReport = foreach ($Service in $Services) {
        [PSCustomObject]@{
            ServiceName      = $Service.Name
            DisplayName      = $Service.DisplayName
            Status           = $Service.Status
            StartType        = $Service.StartType
        }
    }
    
    $ServiceReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Services exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export services: $_"
}`;
    }
  },

  {
    id: 'ws-export-disk-usage',
    title: 'Export Disk Usage',
    description: 'Export disk usage information from a server to CSV',
    category: 'Storage',
    parameters: [
      {
        name: 'serverName',
        label: 'Server Name',
        type: 'text',
        required: true,
        placeholder: 'SERVER01',
        helpText: 'Name of the server'
      },
      {
        name: 'exportPath',
        label: 'Export CSV Path',
        type: 'text',
        required: true,
        placeholder: 'C:\\Exports\\DiskUsage.csv',
        helpText: 'Path where the CSV file will be saved'
      }
    ],
    scriptTemplate: (params) => {
      const serverName = escapePowerShellString(params.serverName);
      const exportPath = escapePowerShellString(params.exportPath);

      return `# Export Disk Usage
# Generated by PSForge

try {
    Write-Host "Collecting disk usage from: ${serverName}" -ForegroundColor Cyan
    
    $Disks = Get-WmiObject -Class Win32_LogicalDisk -ComputerName "${serverName}" -Filter "DriveType=3"
    
    $DiskReport = foreach ($Disk in $Disks) {
        $PercentFree = if ($Disk.Size -gt 0) {
            [math]::Round(($Disk.FreeSpace / $Disk.Size) * 100, 2)
        } else { 0 }
        
        [PSCustomObject]@{
            DriveLetter      = $Disk.DeviceID
            VolumeName       = $Disk.VolumeName
            SizeGB           = [math]::Round($Disk.Size / 1GB, 2)
            FreeSpaceGB      = [math]::Round($Disk.FreeSpace / 1GB, 2)
            PercentFree      = $PercentFree
        }
    }
    
    $DiskReport | Export-Csv -Path "${exportPath}" -NoTypeInformation
    
    Write-Host "✓ Disk usage exported to: ${exportPath}" -ForegroundColor Green
    
} catch {
    Write-Error "Failed to export disk usage: $_"
}`;
    }
  },
  {id:'ws-install-role',title:'Install Server Role',description:'Install Windows Server role',category:'Roles & Features',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'role',label:'Role Name',type:'select',required:true,options:[{value:'AD-Domain-Services',label:'Active Directory'},{value:'DHCP',label:'DHCP'},{value:'DNS',label:'DNS'},{value:'Web-Server',label:'IIS'},{value:'File-Services',label:'File Services'}]}],scriptTemplate:p=>`try{Install-WindowsFeature -Name ${p.role} -ComputerName "${escapePowerShellString(p.serverName)}" -IncludeManagementTools;Write-Host "✓ Role ${p.role} installed" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-remove-role',title:'Remove Server Role',description:'Uninstall Windows Server role',category:'Roles & Features',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'role',label:'Role Name',type:'text',required:true}],scriptTemplate:p=>`try{Uninstall-WindowsFeature -Name "${escapePowerShellString(p.role)}" -ComputerName "${escapePowerShellString(p.serverName)}" -Remove;Write-Host "✓ Role removed" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-export-features',title:'Export Installed Features',description:'List all installed roles and features',category:'Roles & Features',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`try{Get-WindowsFeature -ComputerName "${escapePowerShellString(p.serverName)}"|Where Installed|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Features exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-restart-server',title:'Restart Server',description:'Reboot Windows Server',category:'Server Management',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'force',label:'Force Restart',type:'checkbox',required:false,defaultValue:false}],scriptTemplate:p=>`try{Restart-Computer -ComputerName "${escapePowerShellString(p.serverName)}" -Force:$(if(${p.force===true}){"\\$true"}else{"\\$false"});Write-Host "✓ Restart initiated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-shutdown-server',title:'Shutdown Server',description:'Power off Windows Server',category:'Server Management',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true}],scriptTemplate:p=>`try{Stop-Computer -ComputerName "${escapePowerShellString(p.serverName)}" -Force;Write-Host "✓ Shutdown initiated" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-rename-server',title:'Rename Server',description:'Change computer name',category:'Server Management',parameters:[{name:'serverName',label:'Current Name',type:'text',required:true},{name:'newName',label:'New Name',type:'text',required:true}],scriptTemplate:p=>`try{Rename-Computer -ComputerName "${escapePowerShellString(p.serverName)}" -NewName "${escapePowerShellString(p.newName)}" -Force -Restart;Write-Host "✓ Server renamed to ${p.newName} (restart required)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-list-services',title:'Export Services List',description:'Export all Windows services',category:'Services',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`try{Get-Service -ComputerName "${escapePowerShellString(p.serverName)}"|Select Name,DisplayName,Status,StartType|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Services exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-start-service',title:'Start Windows Service',description:'Start a Windows service',category:'Services',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'serviceName',label:'Service Name',type:'text',required:true}],scriptTemplate:p=>`try{Start-Service -Name "${escapePowerShellString(p.serviceName)}" -ComputerName "${escapePowerShellString(p.serverName)}";Write-Host "✓ Service ${p.serviceName} started" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-stop-service',title:'Stop Windows Service',description:'Stop a Windows service',category:'Services',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'serviceName',label:'Service Name',type:'text',required:true}],scriptTemplate:p=>`try{Stop-Service -Name "${escapePowerShellString(p.serviceName)}" -ComputerName "${escapePowerShellString(p.serverName)}" -Force;Write-Host "✓ Service ${p.serviceName} stopped" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-restart-service',title:'Restart Windows Service',description:'Restart a Windows service',category:'Services',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'serviceName',label:'Service Name',type:'text',required:true}],scriptTemplate:p=>`try{Restart-Service -Name "${escapePowerShellString(p.serviceName)}" -ComputerName "${escapePowerShellString(p.serverName)}" -Force;Write-Host "✓ Service ${p.serviceName} restarted" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-set-service-startup',title:'Set Service Startup Type',description:'Configure service startup behavior',category:'Services',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'serviceName',label:'Service Name',type:'text',required:true},{name:'startupType',label:'Startup Type',type:'select',required:true,options:[{value:'Automatic',label:'Automatic'},{value:'Manual',label:'Manual'},{value:'Disabled',label:'Disabled'}]}],scriptTemplate:p=>`try{Set-Service -Name "${escapePowerShellString(p.serviceName)}" -ComputerName "${escapePowerShellString(p.serverName)}" -StartupType ${p.startupType};Write-Host "✓ Service startup set to ${p.startupType}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-export-eventlog',title:'Export Event Log',description:'Export Windows event logs',category:'Event Logs',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'logName',label:'Log Name',type:'select',required:true,options:[{value:'Application',label:'Application'},{value:'System',label:'System'},{value:'Security',label:'Security'}]},{name:'exportPath',label:'Export Path',type:'text',required:true},{name:'maxEvents',label:'Max Events',type:'number',required:false,defaultValue:1000}],scriptTemplate:p=>`try{Get-WinEvent -LogName ${p.logName} -ComputerName "${escapePowerShellString(p.serverName)}" -MaxEvents ${p.maxEvents}|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Event log exported (${p.maxEvents} events)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-clear-eventlog',title:'Clear Event Log',description:'Clear Windows event log',category:'Event Logs',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'logName',label:'Log Name',type:'select',required:true,options:[{value:'Application',label:'Application'},{value:'System',label:'System'}]}],scriptTemplate:p=>`try{Clear-EventLog -LogName ${p.logName} -ComputerName "${escapePowerShellString(p.serverName)}";Write-Host "✓ Event log ${p.logName} cleared" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-search-eventlog',title:'Search Event Log',description:'Search for specific events',category:'Event Logs',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'logName',label:'Log Name',type:'text',required:true},{name:'eventId',label:'Event ID',type:'number',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`try{Get-WinEvent -FilterHashtable @{LogName='${escapePowerShellString(p.logName)}';Id=${p.eventId}} -ComputerName "${escapePowerShellString(p.serverName)}"|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Events exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-create-share',title:'Create Network Share',description:'Create SMB file share',category:'Storage',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'shareName',label:'Share Name',type:'text',required:true},{name:'path',label:'Folder Path',type:'text',required:true,placeholder:'C:\\\\Share'}],scriptTemplate:p=>`try{Invoke-Command -ComputerName "${escapePowerShellString(p.serverName)}" -ScriptBlock{New-SmbShare -Name "${escapePowerShellString(p.shareName)}" -Path "${escapePowerShellString(p.path)}" -FullAccess Everyone};Write-Host "✓ Share ${p.shareName} created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-remove-share',title:'Remove Network Share',description:'Delete SMB file share',category:'Storage',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'shareName',label:'Share Name',type:'text',required:true}],scriptTemplate:p=>`try{Invoke-Command -ComputerName "${escapePowerShellString(p.serverName)}" -ScriptBlock{Remove-SmbShare -Name "${escapePowerShellString(p.shareName)}" -Force};Write-Host "✓ Share removed" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-export-shares',title:'Export Network Shares',description:'List all SMB shares',category:'Storage',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`try{Get-SmbShare -CimSession "${escapePowerShellString(p.serverName)}"|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Shares exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-set-timezone',title:'Set Server Timezone',description:'Configure timezone settings',category:'Server Management',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'timezone',label:'Timezone',type:'select',required:true,options:[{value:'Pacific Standard Time',label:'Pacific'},{value:'Eastern Standard Time',label:'Eastern'},{value:'Central Standard Time',label:'Central'},{value:'GMT Standard Time',label:'GMT'}]}],scriptTemplate:p=>`try{Set-TimeZone -Id "${p.timezone}" -ComputerName "${escapePowerShellString(p.serverName)}";Write-Host "✓ Timezone set to ${p.timezone}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-configure-firewall',title:'Configure Firewall Rule',description:'Add Windows Firewall rule',category:'Server Management',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'ruleName',label:'Rule Name',type:'text',required:true},{name:'port',label:'Port',type:'number',required:true},{name:'protocol',label:'Protocol',type:'select',required:true,options:[{value:'TCP',label:'TCP'},{value:'UDP',label:'UDP'}]}],scriptTemplate:p=>`try{Invoke-Command -ComputerName "${escapePowerShellString(p.serverName)}" -ScriptBlock{New-NetFirewallRule -DisplayName "${escapePowerShellString(p.ruleName)}" -Direction Inbound -LocalPort ${p.port} -Protocol ${p.protocol} -Action Allow};Write-Host "✓ Firewall rule created" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-export-firewall',title:'Export Firewall Rules',description:'Export all firewall rules',category:'Server Management',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'exportPath',label:'Export Path',type:'text',required:true}],scriptTemplate:p=>`try{Get-NetFirewallRule -CimSession "${escapePowerShellString(p.serverName)}"|Select DisplayName,Direction,Action,Enabled|Export-Csv "${escapePowerShellString(p.exportPath)}" -NoTypeInformation;Write-Host "✓ Firewall rules exported" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-defrag-disk',title:'Defragment Disk',description:'Optimize disk fragmentation',category:'Storage',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'driveLetter',label:'Drive Letter',type:'text',required:true,placeholder:'C:'}],scriptTemplate:p=>`try{Invoke-Command -ComputerName "${escapePowerShellString(p.serverName)}" -ScriptBlock{Optimize-Volume -DriveLetter "${escapePowerShellString(p.driveLetter).replace(':','')}" -Defrag};Write-Host "✓ Defragmentation started for ${p.driveLetter}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-check-disk',title:'Check Disk Health',description:'Run CHKDSK utility',category:'Storage',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'driveLetter',label:'Drive Letter',type:'text',required:true,placeholder:'C:'}],scriptTemplate:p=>`try{Invoke-Command -ComputerName "${escapePowerShellString(p.serverName)}" -ScriptBlock{Repair-Volume -DriveLetter "${escapePowerShellString(p.driveLetter).replace(':','')}" -Scan};Write-Host "✓ Disk check completed for ${p.driveLetter}" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-extend-volume',title:'Extend Disk Volume',description:'Increase disk partition size',category:'Storage',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'driveLetter',label:'Drive Letter',type:'text',required:true},{name:'sizeGB',label:'Add Size (GB)',type:'number',required:true}],scriptTemplate:p=>`try{Invoke-Command -ComputerName "${escapePowerShellString(p.serverName)}" -ScriptBlock{$MaxSize=(Get-PartitionSupportedSize -DriveLetter "${escapePowerShellString(p.driveLetter).replace(':','')}").SizeMax;Resize-Partition -DriveLetter "${escapePowerShellString(p.driveLetter).replace(':','')}" -Size $MaxSize};Write-Host "✓ Volume extended" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-join-domain',title:'Join Domain',description:'Join server to Active Directory domain',category:'Server Management',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true},{name:'domainName',label:'Domain Name',type:'text',required:true,placeholder:'contoso.com'}],scriptTemplate:p=>`try{$Cred=Get-Credential;Add-Computer -ComputerName "${escapePowerShellString(p.serverName)}" -DomainName "${escapePowerShellString(p.domainName)}" -Credential $Cred -Restart;Write-Host "✓ Domain join initiated (restart required)" -ForegroundColor Green}catch{Write-Error $_}`},
  {id:'ws-leave-domain',title:'Leave Domain',description:'Remove server from domain',category:'Server Management',parameters:[{name:'serverName',label:'Server Name',type:'text',required:true}],scriptTemplate:p=>`try{$Cred=Get-Credential;Remove-Computer -ComputerName "${escapePowerShellString(p.serverName)}" -UnjoinDomainCredential $Cred -WorkgroupName "WORKGROUP" -Restart;Write-Host "✓ Domain leave initiated (restart required)" -ForegroundColor Green}catch{Write-Error $_}`}
];

export const windowsServerCategories = [
  'Server Management',
  'Roles & Features',
  'Event Logs',
  'Services',
  'Storage'
];
